[
    {
      nor: 'en bil',
      eng: 'a car',
      pl: 'samochód',
      ar: 'سيارة',
      ger: 'ein Auto',
      lt: 'automobilis',
      key: '0',
      norEgz: 'Han kjører en bil.',
      soundLink: '',
      wordId: 0
    },
    {
      nor: 'stor',
      eng: 'big',
      pl: 'duży',
      ar: 'كبير',
      ger: 'groß',
      lt: 'didelis',
      key: '1',
      norEgz: 'Det er en stor hund.',
      soundLink: '',
      wordId: 1
    },
    {
      nor: 'lang',
      eng: 'long',
      pl: 'długi',
      ar: 'طويل',
      ger: 'lang',
      lt: 'ilgas',
      key: '2',
      norEgz: 'Broen er lang.',
      soundLink: '',
      wordId: 2
    },
    {
      nor: 'høy',
      eng: 'tall',
      pl: 'wysoki',
      ar: 'طويل القامة',
      ger: 'groß',
      lt: 'aukštas',
      key: '3',
      norEgz: 'Han er høy.',
      soundLink: '',
      wordId: 3
    },
    {
      nor: 'lav',
      eng: 'low',
      pl: 'niski',
      ar: 'منخفض',
      ger: 'niedrig',
      lt: 'žemas',
      key: '4',
      norEgz: 'Taket er lavt.',
      soundLink: '',
      wordId: 4
    },
    {
      nor: 'å bo',
      eng: 'to live',
      pl: 'mieszkać',
      ar: 'أن يعيش',
      ger: 'wohnen',
      lt: 'gyventi',
      key: '5',
      norEgz: 'Vi bor i Norge.',
      soundLink: '',
      wordId: 5
    },
    {
      nor: 'å stå',
      eng: 'to stand',
      pl: 'stać',
      ar: 'يقف',
      ger: 'stehen',
      lt: 'stovėti',
      key: '6',
      norEgz: 'Han står ved døren.',
      soundLink: '',
      wordId: 6
    },
    {
      nor: 'å sitte',
      eng: 'to sit',
      pl: 'siedzieć',
      ar: 'جلس',
      ger: 'sitzen',
      lt: 'sėdėti',
      key: '7',
      norEgz: 'Hun sitter på stolen.',
      soundLink: '',
      wordId: 7
    },
    {
      nor: 'tung',
      eng: 'heavy',
      pl: 'ciężki',
      ar: 'ثقيل',
      ger: 'schwer',
      lt: 'sunkus',
      key: '8',
      norEgz: 'Denne boken er tung.',
      soundLink: '',
      wordId: 8
    },
    {
        nor: 'et fjell',
        eng: 'a mountain',
        pl: 'góra',
        ar: 'جبل',
        ger: 'ein Berg',
        lt: 'kalnas',
        key: '9',
        norEgz: 'Det er et fjell i nærheten.',
        soundLink: '',
        wordId: 9
      },
      {
        nor: 'en sofa',
        eng: 'a sofa',
        pl: 'sofa',
        ar: 'أريكة',
        ger: 'ein Sofa',
        lt: 'sofa',
        key: '10',
        norEgz: 'Vi har en ny sofa.',
        soundLink: '',
        wordId: 10
      },
      {
        nor: 'en seng',
        eng: 'a bed',
        pl: 'łóżko',
        ar: 'سرير',
        ger: 'ein Bett',
        lt: 'lova',
        key: '11',
        norEgz: 'Sengen er myk.',
        soundLink: '',
        wordId: 11
      },
      {
        nor: 'liten',
        eng: 'small',
        pl: 'mały',
        ar: 'صغير',
        ger: 'klein',
        lt: 'mažas',
        key: '12',
        norEgz: 'Det er en liten katt.',
        soundLink: '',
        wordId: 12
      },
      {
        nor: 'et tre',
        eng: 'a tree',
        pl: 'drzewo',
        ar: 'شجرة',
        ger: 'ein Baum',
        lt: 'medis',
        key: '13',
        norEgz: 'Det er et tre i hagen.',
        soundLink: '',
        wordId: 13
      },
      {
        nor: 'en blomst',
        eng: 'a flower',
        pl: 'kwiat',
        ar: 'زهرة',
        ger: 'eine Blume',
        lt: 'gėlė',
        key: '14',
        norEgz: 'Han ga henne en blomst.',
        soundLink: '',
        wordId: 14
      },
      {
        nor: 'kjølig',
        eng: 'cool',
        pl: 'chłodny',
        ar: 'بارد',
        ger: 'kühl',
        lt: 'vėsus',
        key: '15',
        norEgz: 'Været er kjølig i dag.',
        soundLink: '',
        wordId: 15
      },
      {
        nor: 'tørr',
        eng: 'dry',
        pl: 'suchy',
        ar: 'جاف',
        ger: 'trocken',
        lt: 'sausas',
        key: '16',
        norEgz: 'Klærne er tørre nå.',
        soundLink: '',
        wordId: 16
      },
      {
        nor: 'våt',
        eng: 'wet',
        pl: 'mokry',
        ar: 'مبلل',
        ger: 'nass',
        lt: 'šlapias',
        key: '17',
        norEgz: 'Gulvet er vått.',
        soundLink: '',
        wordId: 17
      },{
        nor: 'sterk',
        eng: 'strong',
        pl: 'mocny',
        ar: 'قوي',
        ger: 'stark',
        lt: 'stiprus',
        key: '18',
        norEgz: 'Han er en sterk mann.',
        soundLink: '',
        wordId: 18
      },
      {
        nor: 'svak',
        eng: 'weak',
        pl: 'słaby',
        ar: 'ضعيف',
        ger: 'schwach',
        lt: 'silpnas',
        key: '19',
        norEgz: 'Signalet er svakt her.',
        soundLink: '',
        wordId: 19
      },
      {
        nor: 'rask',
        eng: 'fast',
        pl: 'szybki',
        ar: 'سريع',
        ger: 'schnell',
        lt: 'greitas',
        key: '20',
        norEgz: 'Han løper veldig raskt.',
        soundLink: '',
        wordId: 20
      },
      {
        nor: 'en kake',
        eng: 'a cake',
        pl: 'ciasto',
        ar: 'كعكة',
        ger: 'ein Kuchen',
        lt: 'tortas',
        key: '21',
        norEgz: 'Hun laget en kake til festen.',
        soundLink: '',
        wordId: 21
      },
      {
        nor: 'en sykkel',
        eng: 'a bicycle',
        pl: 'rower',
        ar: 'دراجة',
        ger: 'ein Fahrrad',
        lt: 'dviratis',
        key: '22',
        norEgz: 'Han sykler til jobben.',
        soundLink: '',
        wordId: 22
      },
      {
        nor: 'en båt',
        eng: 'a boat',
        pl: 'łódź',
        ar: 'قارب',
        ger: 'ein Boot',
        lt: 'valtis',
        key: '23',
        norEgz: 'De reiste med en båt.',
        soundLink: '',
        wordId: 23
      },
      {
        nor: 'treg',
        eng: 'slow',
        pl: 'wolny',
        ar: 'بطيء',
        ger: 'langsam',
        lt: 'lėtas',
        key: '24',
        norEgz: 'Datamaskinen min er veldig treg.',
        soundLink: '',
        wordId: 24
      },
      {
        nor: 'pen',
        eng: 'pretty',
        pl: 'ładny',
        ar: 'جميلة',
        ger: 'hübsch',
        lt: 'gražus',
        key: '25',
        norEgz: 'Hun er en pen jente.',
        soundLink: '',
        wordId: 25
      },
      {
        nor: 'en telefon',
        eng: 'a telephone',
        pl: 'telefon',
        ar: 'هاتف',
        ger: 'ein Telefon',
        lt: 'telefonas',
        key: '26',
        norEgz: 'Han ringte meg på telefonen.',
        soundLink: '',
        wordId: 26
      },
      {
        nor: 'en avis',
        eng: 'a newspaper',
        pl: 'gazeta',
        ar: 'جريدة',
        ger: 'eine Zeitung',
        lt: 'laikraštis',
        key: '27',
        norEgz: 'Jeg leser avisen hver morgen.',
        soundLink: '',
        wordId: 27
      },
      {
        nor: 'et speil',
        eng: 'a mirror',
        pl: 'lustro',
        ar: 'مرآة',
        ger: 'ein Spiegel',
        lt: 'veidrodis',
        key: '28',
        norEgz: 'Hun så seg selv i speilet.',
        soundLink: '',
        wordId: 28
      },
      {
        nor: 'kort',
        eng: 'short',
        pl: 'krótki',
        ar: 'قصير',
        ger: 'kurz',
        lt: 'trumpas',
        key: '29',
        norEgz: 'Filmen var kort, men god.',
        soundLink: '',
        wordId: 29
      },
      {
        nor: 'en venn',
        eng: 'a friend',
        pl: 'przyjaciel',
        ar: 'صديق',
        ger: 'ein Freund',
        lt: 'draugas',
        key: '30',
        norEgz: 'Han er en god venn av meg.',
        soundLink: '',
        wordId: 30
      },
      {
        nor: 'en jente',
        eng: 'a girl',
        pl: 'dziewczyna',
        ar: 'فتاة',
        ger: 'ein Mädchen',
        lt: 'mergaitė',
        key: '31',
        norEgz: 'Det er en jente i parken.',
        soundLink: '',
        wordId: 31
      },
      {
        nor: 'en gutt',
        eng: 'a boy',
        pl: 'chłopiec',
        ar: 'ولد',
        ger: 'ein Junge',
        lt: 'berniukas',
        key: '32',
        norEgz: 'Han er en snill gutt.',
        soundLink: '',
        wordId: 32
      },
      {
        nor: 'å få',
        eng: 'to get',
        pl: 'dostać',
        ar: 'الحصول على',
        ger: 'bekommen',
        lt: 'gauti',
        key: '33',
        norEgz: 'Jeg fikk en gave fra henne.',
        soundLink: '',
        wordId: 33
      },
      {
        nor: 'å ville',
        eng: 'to want',
        pl: 'chcieć',
        ar: 'يريد',
        ger: 'wollen',
        lt: 'norėti',
        key: '34',
        norEgz: 'Han ville gå på kino.',
        soundLink: '',
        wordId: 34
      },
      {
        nor: 'å kunne',
        eng: 'to be able',
        pl: 'móc',
        ar: 'يستطيع',
        ger: 'können',
        lt: 'galėti',
        key: '35',
        norEgz: 'Hun kunne ikke finne nøklene sine.',
        soundLink: '',
        wordId: 35
      },
      {
        nor: 'å måtte',
        eng: 'to have to',
        pl: 'musieć',
        ar: 'يجب أن',
        ger: 'müssen',
        lt: 'turėti',
        key: '36',
        norEgz: 'Vi måtte vente i en time.',
        soundLink: '',
        wordId: 36
      },
      {
        nor: 'et barn',
        eng: 'a child',
        pl: 'dziecko',
        ar: 'طفل',
        ger: 'ein Kind',
        lt: 'vaikas',
        key: '37',
        norEgz: 'Det er et søtt barn.',
        soundLink: '',
        wordId: 37
      },
      {
        nor: 'en familie',
        eng: 'a family',
        pl: 'rodzina',
        ar: 'عائلة',
        ger: 'eine Familie',
        lt: 'šeima',
        key: '38',
        norEgz: 'Familien vår bor i Norge.',
        soundLink: '',
        wordId: 38
      },
      {
        nor: 'et hus',
        eng: 'a house',
        pl: 'dom',
        ar: 'بيت',
        ger: 'ein Haus',
        lt: 'namas',
        key: '39',
        norEgz: 'Vi kjøpte et nytt hus.',
        soundLink: '',
        wordId: 39
      },
      {
        nor: 'en bok',
        eng: 'a book',
        pl: 'książka',
        ar: 'كتاب',
        ger: 'ein Buch',
        lt: 'knyga',
        key: '40',
        norEgz: 'Jeg leser en interessant bok.',
        soundLink: '',
        wordId: 40
      },
      {
        nor: 'å reise',
        eng: 'to travel',
        pl: 'podróżować',
        ar: 'السفر',
        ger: 'reisen',
        lt: 'keliauti',
        key: '41',
        norEgz: 'De liker å reise rundt i verden.',
        soundLink: '',
        wordId: 41
    },
    {
        nor: 'å lytte',
        eng: 'to listen',
        pl: 'słuchać',
        ar: 'يستمع',
        ger: 'zuhören',
        lt: 'klausytis',
        key: '42',
        norEgz: 'Hun lytter nøye til musikken.',
        soundLink: '',
        wordId: 42
    },
    {
        nor: 'å lære',
        eng: 'to learn',
        pl: 'uczyć się',
        ar: 'تعلم',
        ger: 'lernen',
        lt: 'mokytis',
        key: '43',
        norEgz: 'Jeg vil lære å snakke norsk.',
        soundLink: '',
        wordId: 43
    },
    {
        nor: 'en stol',
        eng: 'a chair',
        pl: 'krzesło',
        ar: 'كرسي',
        ger: 'ein Stuhl',
        lt: 'kėdė',
        key: '44',
        norEgz: 'Sett deg ned på stolen.',
        soundLink: '',
        wordId: 44
    },
    {
        nor: 'et bord',
        eng: 'a table',
        pl: 'stół',
        ar: 'طاولة',
        ger: 'ein Tisch',
        lt: 'stalas',
        key: '45',
        norEgz: 'Vi spiste middag ved bordet.',
        soundLink: '',
        wordId: 45
    },
    {
        nor: 'en skole',
        eng: 'a school',
        pl: 'szkoła',
        ar: 'مدرسة',
        ger: 'eine Schule',
        lt: 'mokykla',
        key: '46',
        norEgz: 'Barna går på skolen hver dag.',
        soundLink: '',
        wordId: 46
    },
    {
        nor: 'å se',
        eng: 'to see',
        pl: 'zobaczyć',
        ar: 'أنظر',
        ger: 'sehen',
        lt: 'matyti',
        key: '47',
        norEgz: 'Kan du se månen i kveld?',
        soundLink: '',
        wordId: 47
    },
    {
        nor: 'å spise',
        eng: 'to eat',
        pl: 'jeść',
        ar: 'يأكل',
        ger: 'essen',
        lt: 'valgyti',
        key: '48',
        norEgz: 'Vi spiser middag klokka seks.',
        soundLink: '',
        wordId: 48
    },
    {
        nor: 'en lærer',
        eng: 'a teacher',
        pl: 'nauczyciel',
        ar: 'معلم',
        ger: 'ein Lehrer',
        lt: 'mokytojas',
        key: '49',
        norEgz: 'Læreren underviser i klasserommet.',
        soundLink: '',
        wordId: 49
    },
    {
        nor: 'et eple',
        eng: 'an apple',
        pl: 'jabłko',
        ar: 'تفاحة',
        ger: 'ein Apfel',
        lt: 'obuolys',
        key: '50',
        norEgz: 'Hun spiser et eple til lunsj.',
        soundLink: '',
        wordId: 50
  },
  {
    nor: 'en dør',
    eng: 'a door',
    pl: 'drzwi',
    ar: 'باب',
    ger: 'eine Tür',
    lt: 'durys',
    key: '51',
    norEgz: 'Åpne døren, vær så snill.',
    soundLink: '',
    wordId: 51
  },
  {
    nor: 'et vindu',
    eng: 'a window',
    pl: 'okno',
    ar: 'نافذة',
    ger: 'ein Fenster',
    lt: 'langas',
    key: '52',
    norEgz: 'Han åpnet vinduet for å få frisk luft.',
    soundLink: '',
    wordId: 52
  },
  {
    nor: 'en katt',
    eng: 'a cat',
    pl: 'kot',
    ar: 'قطة',
    ger: 'eine Katze',
    lt: 'katė',
    key: '53',
    norEgz: 'Katten vår heter Luna.',
    soundLink: '',
    wordId: 53
  },
  {
    nor: 'en hund',
    eng: 'a dog',
    pl: 'pies',
    ar: 'كلب',
    ger: 'ein Hund',
    lt: 'šuo',
    key: '54',
    norEgz: 'Hunden min elsker å gå tur.',
    soundLink: '',
    wordId: 54
  },
  {
    nor: 'en kopp',
    eng: 'a cup',
    pl: 'filiżanka',
    ar: 'كوب',
    ger: 'eine Tasse',
    lt: 'puodelis',
    key: '55',
    norEgz: 'Jeg drikker kaffe fra koppen.',
    soundLink: '',
    wordId: 55
  },
  {
    nor: 'et glass',
    eng: 'a glass',
    pl: 'szklanka',
    ar: 'كأس',
    ger: 'ein Glas',
    lt: 'stiklinė',
    key: '56',
    norEgz: 'Han fylte et glass med vann.',
    soundLink: '',
    wordId: 56
  },
  {
    nor: 'en by',
    eng: 'a city',
    pl: 'miasto',
    ar: 'مدينة',
    ger: 'eine Stadt',
    lt: 'miestas',
    key: '57',
    norEgz: 'Oslo er hovedstaden i Norge.',
    soundLink: '',
    wordId: 57
  },
  {
    nor: 'å legge',
    eng: 'to put',
    pl: 'kłaść',
    ar: 'وضع',
    ger: 'legen',
    lt: 'dėti',
    key: '58',
    norEgz: 'Hun legger boken på bordet.',
    soundLink: '',
    wordId: 58
  },
  {
    nor: 'å arbeide',
    eng: 'to work',
    pl: 'pracować',
    ar: 'العمل',
    ger: 'arbeiten',
    lt: 'dirbti',
    key: '59',
    norEgz: 'Han arbeider på et kontor.',
    soundLink: '',
    wordId: 59
  },
  {
    nor: 'å studere',
    eng: 'to study',
    pl: 'studiować',
    ar: 'يدرس',
    ger: 'studieren',
    lt: 'mokytis',
    key: '60',
    norEgz: 'Hun studerer medisin på universitetet.',
    soundLink: '',
    wordId: 60
  },
  {
    nor: 'å le',
    eng: 'to laugh',
    pl: 'śmiać się',
    ar: 'يضحك',
    ger: 'lachen',
    lt: 'juoktis',
    key: '61',
    norEgz: 'Barna ler når de ser klovnen.',
    soundLink: '',
    wordId: 61
  },
  {
    nor: 'å gråte',
    eng: 'to cry',
    pl: 'płakać',
    ar: 'يبكي',
    ger: 'weinen',
    lt: 'verkti',
    key: '62',
    norEgz: 'Babyen gråter når den er sulten.',
    soundLink: '',
    wordId: 62
  },
  {
    nor: 'en koffert',
    eng: 'a suitcase',
    pl: 'walizka',
    ar: 'حقيبة',
    ger: 'ein Koffer',
    lt: 'lagaminas',
    key: '63',
    norEgz: 'Han pakker kofferten før reisen.',
    soundLink: '',
    wordId: 63
  },
  {
    nor: 'et skjerf',
    eng: 'a scarf',
    pl: 'szalik',
    ar: 'وشاح',
    ger: 'ein Schal',
    lt: 'šalikas',
    key: '64',
    norEgz: 'Hun har på seg et skjerf for å holde seg varm.',
    soundLink: '',
    wordId: 64
  },
  {
    nor: 'en jakke',
    eng: 'a jacket',
    pl: 'kurtka',
    ar: 'سترة',
    ger: 'eine Jacke',
    lt: 'striukė',
    key: '65',
    norEgz: 'Han kjøpte en ny jakke i butikken.',
    soundLink: '',
    wordId: 65
  },
  {
    nor: 'å komme',
    eng: 'to come',
    pl: 'przychodzić',
    ar: 'يأتي',
    ger: 'kommen',
    lt: 'ateiti',
    key: '66',
    norEgz: 'Han kommer til festen senere.',
    soundLink: '',
    wordId: 66
  },
  {
    nor: 'å tenke',
    eng: 'to think',
    pl: 'myśleć',
    ar: 'يفكر',
    ger: 'denken',
    lt: 'galvoti',
    key: '67',
    norEgz: 'Jeg tenker på hva jeg skal gjøre i morgen.',
    soundLink: '',
    wordId: 67
  },
  {
    nor: 'å kjøpe',
    eng: 'to buy',
    pl: 'kupować',
    ar: 'يشترى',
    ger: 'kaufen',
    lt: 'pirkti',
    key: '68',
    norEgz: 'Hun kjøper en billett til konserten.',
    soundLink: '',
    wordId: 68
  },
  {
    nor: 'å kjøre',
    eng: 'to drive',
    pl: 'prowadzić',
    ar: 'يقود',
    ger: 'fahren',
    lt: 'vairuoti',
    key: '69',
    norEgz: 'Han kjører bilen til jobben.',
    soundLink: '',
    wordId: 69
  },
  {
    nor: 'et slips',
    eng: 'a tie',
    pl: 'krawat',
    ar: 'ربطة عنق',
    ger: 'eine Krawatte',
    lt: 'kaklaraištis',
    key: '70',
    norEgz: 'Han har på seg et slips til bryllupet.',
    soundLink: '',
    wordId: 70
  },
  {
    nor: 'en paraply',
    eng: 'an umbrella',
    pl: 'parasolka',
    ar: 'مظلة',
    ger: 'ein Regenschirm',
    lt: 'skėtis',
    key: '71',
    norEgz: 'Hun tar med seg en paraply i tilfelle det regner.',
    soundLink: '',
    wordId: 71
  },
  {
    nor: 'en stjerne',
    eng: 'a star',
    pl: 'gwiazda',
    ar: 'نجمة',
    ger: 'ein Stern',
    lt: 'žvaigždė',
    key: '72',
    norEgz: 'Vi ser stjernene på nattehimmelen.',
    soundLink: '',
    wordId: 72
  },
  {
    nor: 'en måne',
    eng: 'a moon',
    pl: 'księżyc',
    ar: 'قمر',
    ger: 'ein Mond',
    lt: 'mėnulis',
    key: '73',
    norEgz: 'Månen lyser opp natten.',
    soundLink: '',
    wordId: 73
  },
  {
    nor: 'å løpe',
    eng: 'to run',
    pl: 'biegać',
    ar: 'يركض',
    ger: 'laufen',
    lt: 'bėgti',
    key: '74',
    norEgz: 'Hun løper hver morgen for å holde seg i form.',
    soundLink: '',
    wordId: 74
  },
  {
    nor: 'å hoppe',
    eng: 'to jump',
    pl: 'skakać',
    ar: 'يقفز',
    ger: 'springen',
    lt: 'šokti',
    key: '75',
    norEgz: 'Barnet hopper på trampolinen.',
    soundLink: '',
    wordId: 75
  },
  {
    nor: 'å svømme',
    eng: 'to swim',
    pl: 'pływać',
    ar: 'يسبح',
    ger: 'schwimmen',
    lt: 'plaukti',
    key: '76',
    norEgz: 'Han liker å svømme i innsjøen om sommeren.',
    soundLink: '',
    wordId: 76
  },
  {
    nor: 'å danse',
    eng: 'to dance',
    pl: 'tańczyć',
    ar: 'يرقص',
    ger: 'tanzen',
    lt: 'šokti',
    key: '77',
    norEgz: 'De danser hele natten på festen.',
    soundLink: '',
    wordId: 77
  },
  {
    nor: 'å synge',
    eng: 'to sing',
    pl: 'śpiewać',
    ar: 'يغني',
    ger: 'singen',
    lt: 'dainuoti',
    key: '78',
    norEgz: 'Hun synger i koret på skolen.',
    soundLink: '',
    wordId: 78
  },
  {
    nor: 'en sol',
    eng: 'a sun',
    pl: 'słońce',
    ar: 'شمس',
    ger: 'eine Sonne',
    lt: 'saulė',
    key: '79',
    norEgz: 'Solen skinner på en klar dag.',
    soundLink: '',
    wordId: 79
  },
  {
    nor: 'et hotell',
    eng: 'a hotel',
    pl: 'hotel',
    ar: 'فندق',
    ger: 'ein Hotel',
    lt: 'viešbutis',
    key: '80',
    norEgz: 'Vi bor på et hotell i ferien.',
    soundLink: '',
    wordId: 80
  },
  {
    nor: 'et tårn',
    eng: 'a tower',
    pl: 'wieża',
    ar: 'برج',
    ger: 'ein Turm',
    lt: 'bokštas',
    key: '81',
    norEgz: 'Det gamle slottet har et høyt tårn.',
    soundLink: '',
    wordId: 81
  },
  {
    nor: 'en gate',
    eng: 'a street',
    pl: 'ulica',
    ar: 'شارع',
    ger: 'eine Straße',
    lt: 'gatvė',
    key: '82',
    norEgz: 'Huset ligger ved en travel gate.',
    soundLink: '',
    wordId: 82
  },
  {
    nor: 'en bro',
    eng: 'a bridge',
    pl: 'most',
    ar: 'جسر',
    ger: 'eine Brücke',
    lt: 'tiltas',
    key: '83',
    norEgz: 'Vi krysser broen for å komme til parken.',
    soundLink: '',
    wordId: 83
  },
  {
    nor: 'et slott',
    eng: 'a castle',
    pl: 'zamek',
    ar: 'قلعة',
    ger: 'ein Schloss',
    lt: 'pilis',
    key: '84',
    norEgz: 'Turister besøker det historiske slottet.',
    soundLink: '',
    wordId: 84
  },
  {
    nor: 'en fontene',
    eng: 'a fountain',
    pl: 'fontanna',
    ar: 'نافورة',
    ger: 'ein Springbrunnen',
    lt: 'fontanas',
    key: '85',
    norEgz: 'Fontenen i parken er veldig vakker.',
    soundLink: '',
    wordId: 85
  },
  {
    nor: 'lett',
    eng: 'easy',
    pl: 'łatwy',
    ar: 'سهل',
    ger: 'leicht',
    lt: 'lengvas',
    key: '86',
    norEgz: 'Denne oppgaven er lett for meg.',
    soundLink: '',
    wordId: 86
  },
  {
    nor: 'å selge',
    eng: 'to sell',
    pl: 'sprzedawać',
    ar: 'يبيع',
    ger: 'verkaufen',
    lt: 'parduoti',
    key: '87',
    norEgz: 'Han selger frukt på markedet.',
    soundLink: '',
    wordId: 87
  },
  {
    nor: 'å møte',
    eng: 'to meet',
    pl: 'spotykać',
    ar: 'يلتقي',
    ger: 'treffen',
    lt: 'susitikti',
    key: '88',
    norEgz: 'Vi møtes på kafeen klokka to.',
    soundLink: '',
    wordId: 88
  },
  {
    nor: 'å besøke',
    eng: 'to visit',
    pl: 'odwiedzać',
    ar: 'يزور',
    ger: 'besuchen',
    lt: 'aplankyti',
    key: '89',
    norEgz: 'De besøker besteforeldrene sine i helgen.',
    soundLink: '',
    wordId: 89
  },
  {
    nor: 'gammel',
    eng: 'old',
    pl: 'stary',
    ar: 'قديم',
    ger: 'alt',
    lt: 'senas',
    key: '90',
    norEgz: 'Det gamle huset trenger reparasjon.',
    soundLink: '',
    wordId: 90
  },
  {
    nor: 'ung',
    eng: 'young',
    pl: 'młody',
    ar: 'شاب',
    ger: 'jung',
    lt: 'jaunas',
    key: '91',
    norEgz: 'Han er en ung og talentfull musiker.',
    soundLink: '',
    wordId: 91
  },
  {
    nor: 'ny',
    eng: 'new',
    pl: 'nowy',
    ar: 'جديد',
    ger: 'neu',
    lt: 'naujas',
    key: '92',
    norEgz: 'De har kjøpt en ny bil.',
    soundLink: '',
    wordId: 92
  },
  {
    nor: 'varm',
    eng: 'warm',
    pl: 'ciepły',
    ar: 'دافئ',
    ger: 'warm',
    lt: 'šiltas',
    key: '93',
    norEgz: 'Det er en varm sommerdag.',
    soundLink: '',
    wordId: 93
  },
  {
    nor: 'kald',
    eng: 'cold',
    pl: 'zimny',
    ar: 'بارد',
    ger: 'kalt',
    lt: 'šaltas',
    key: '94',
    norEgz: 'Vinteren i Norge er veldig kald.',
    soundLink: '',
    wordId: 94
  },
  {
    nor: 'en hatt',
    eng: 'a hat',
    pl: 'kapelusz',
    ar: 'قبعة',
    ger: 'ein Hut',
    lt: 'šešėlis',
    key: '95',
    norEgz: 'Hun kjøpte en hatt for å beskytte seg mot solen.',
    soundLink: '',
    wordId: 95
  },
  {
    nor: 'en lommebok',
    eng: 'a wallet',
    pl: 'portfel',
    ar: 'محفظة',
    ger: 'eine Brieftasche',
    lt: 'piniginė',
    key: '96',
    norEgz: 'Han mistet lommeboken sin i går.',
    soundLink: '',
    wordId: 96
  },
  {
    nor: 'et belte',
    eng: 'a belt',
    pl: 'pasek',
    ar: 'حزام',
    ger: 'ein Gürtel',
    lt: 'diržas',
    key: '97',
    norEgz: 'Hun kjøpte et nytt belte for å matche skoene.',
    soundLink: '',
    wordId: 97
  },
  {
    nor: 'en nøkkel',
    eng: 'a key',
    pl: 'klucz',
    ar: 'مفتاح',
    ger: 'ein Schlüssel',
    lt: 'raktas',
    key: '98',
    norEgz: 'Han mistet nøkkelen sin og kunne ikke komme inn.',
    soundLink: '',
    wordId: 98
  },
  {
    nor: 'et bilde',
    eng: 'a picture',
    pl: 'obraz',
    ar: 'صورة',
    ger: 'ein Bild',
    lt: 'nuotrauka',
    key: '99',
    norEgz: 'Hun tok et vakkert bilde av solnedgangen.',
    soundLink: '',
    wordId: 99
  },
  {
    nor: 'en klokke',
    eng: 'a watch',
    pl: 'zegarek',
    ar: 'ساعة',
    ger: 'eine Uhr',
    lt: 'laikrodis',
    key: '100',
    norEgz: 'Han sjekket klokken for å se hvor mye tid som var igjen.',
    soundLink: '',
    wordId: 100
  },
  {
    nor: 'et armbånd',
    eng: 'a bracelet',
    pl: 'bransoletka',
    ar: 'سوار',
    ger: 'ein Armband',
    lt: 'apyrankė',
    key: '101',
    norEgz: 'Hun fikk et vakkert armbånd i bursdagsgave.',
    soundLink: '',
    wordId: 101
  },
  {
    nor: 'stygg',
    eng: 'ugly',
    pl: 'brzydki',
    ar: 'قبيح',
    ger: 'hässlich',
    lt: 'bjaurus',
    key: '102',
    norEgz: 'Han synes den gamle bygningen er stygg.',
    soundLink: '',
    wordId: 102
  },
  {
    nor: 'ren',
    eng: 'clean',
    pl: 'czysty',
    ar: 'نظيف',
    ger: 'sauber',
    lt: 'švarus',
    key: '103',
    norEgz: 'Hun liker å holde huset sitt rent og ryddig.',
    soundLink: '',
    wordId: 103
  },
  {
    nor: 'skitten',
    eng: 'dirty',
    pl: 'brudny',
    ar: 'متسخ',
    ger: 'schmutzig',
    lt: 'nešvarus',
    key: '104',
    norEgz: 'Gulvet var skittent etter festen.',
    soundLink: '',
    wordId: 104
  },
  {
    nor: 'tom',
    eng: 'empty',
    pl: 'pusty',
    ar: 'فارغ',
    ger: 'leer',
    lt: 'tuščias',
    key: '105',
    norEgz: 'Kjøleskapet er tomt, vi må kjøpe mat.',
    soundLink: '',
    wordId: 105
  },
  {
    nor: 'full',
    eng: 'full',
    pl: 'pełny',
    ar: 'ممتلئ',
    ger: 'voll',
    lt: 'pilnas',
    key: '106',
    norEgz: 'Bensintanken er full, vi kan kjøre langt.',
    soundLink: '',
    wordId: 106
  },
  {
    nor: 'en fisk',
    eng: 'a fish',
    pl: 'ryba',
    ar: 'سمكة',
    ger: 'ein Fisch',
    lt: 'žuvis',
    key: '107',
    norEgz: 'Han fanget en stor fisk i elven.',
    soundLink: '',
    wordId: 107
  },
  {
    nor: 'en fugl',
    eng: 'a bird',
    pl: 'ptak',
    ar: 'طائر',
    ger: 'ein Vogel',
    lt: 'paukštis',
    key: '108',
    norEgz: 'Fuglen satt på en gren og sang.',
    soundLink: '',
    wordId: 108
  },
  {
    nor: 'en park',
    eng: 'a park',
    pl: 'park',
    ar: 'حديقة',
    ger: 'ein Park',
    lt: 'parkas',
    key: '109',
    norEgz: 'Barna lekte i parken hele ettermiddagen.',
    soundLink: '',
    wordId: 109
  },
  {
    nor: 'en sko',
    eng: 'a shoe',
    pl: 'but',
    ar: 'حذاء',
    ger: 'ein Schuh',
    lt: 'batai',
    key: '110',
    norEgz: 'Hun kjøpte et par nye sko i butikken.',
    soundLink: '',
    wordId: 110
  },
  {
    nor: 'bred',
    eng: 'wide',
    pl: 'szeroki',
    ar: 'عريض',
    ger: 'breit',
    lt: 'platus',
    key: '111',
    norEgz: 'Den brede elven strømmet rolig forbi.',
    soundLink: '',
    wordId: 111
  },
  {
    nor: 'god',
    eng: 'good',
    pl: 'dobry',
    ar: 'جيد',
    ger: 'gut',
    lt: 'geras',
    key: '112',
    norEgz: 'Hun er en god venn av meg.',
    soundLink: '',
    wordId: 112
  },
  {
    nor: 'dårlig',
    eng: 'bad',
    pl: 'zły',
    ar: 'سيء',
    ger: 'schlecht',
    lt: 'blogas',
    key: '113',
    norEgz: 'Været var dårlig i dag.',
    soundLink: '',
    wordId: 113
  },
  {
    nor: 'et tog',
    eng: 'a train',
    pl: 'pociąg',
    ar: 'قطار',
    ger: 'ein Zug',
    lt: 'traukinys',
    key: '114',
    norEgz: 'Vi tok toget til byen.',
    soundLink: '',
    wordId: 114
  },
  {
    nor: 'et fly',
    eng: 'a plane',
    pl: 'samolot',
    ar: 'طائرة',
    ger: 'ein Flugzeug',
    lt: 'lėktuvas',
    key: '115',
    norEgz: 'Hun reiste med fly til London.',
    soundLink: '',
    wordId: 115
  },
  {
    nor: 'hard',
    eng: 'hard',
    pl: 'twardy',
    ar: 'صعب',
    ger: 'hart',
    lt: 'kietas',
    key: '116',
    norEgz: 'Gulvet var hardt og kaldt.',
    soundLink: '',
    wordId: 116
  },
  {
    nor: 'myk',
    eng: 'soft',
    pl: 'miękki',
    ar: 'ناعم',
    ger: 'weich',
    lt: 'minkštas',
    key: '117',
    norEgz: 'Putene var myke og behagelige.',
    soundLink: '',
    wordId: 117
  },
  {
    nor: 'lys',
    eng: 'light',
    pl: 'jasny',
    ar: 'خفيف',
    ger: 'hell',
    lt: 'šviesus',
    key: '118',
    norEgz: 'Rommene var lyse og luftige.',
    soundLink: '',
    wordId: 118
  },
  {
    nor: 'mørk',
    eng: 'dark',
    pl: 'ciemny',
    ar: 'مظلم',
    ger: 'dunkel',
    lt: 'tamsus',
    key: '119',
    norEgz: 'Det blir mørkt tidlig om vinteren.',
    soundLink: '',
    wordId: 119
  },
  {
    nor: 'en mobiltelefon',
    eng: 'a mobile phone',
    pl: 'telefon komórkowy',
    ar: 'هاتف محمول',
    ger: 'ein Mobiltelefon',
    lt: 'mobilusis telefonas',
    key: '120',
    norEgz: 'Han mistet mobiltelefonen sin i går',
    soundLink: '',
    wordId: 120
  },
  {
    nor: 'et nettbrett',
    eng: 'a tablet',
    pl: 'tablet',
    ar: 'جهاز لوحي',
    ger: 'ein Tablet',
    lt: 'planšetė',
    key: '121',
    norEgz: 'Hun bruker nettbrettet til å lese e-bøker.',
    soundLink: '',
    wordId: 121
  },
  {
    nor: 'en øyeblikk',
    eng: 'a moment',
    pl: 'chwila',
    ar: 'لحظة',
    ger: 'ein Moment',
    lt: 'akimirka',
    key: '122',
    norEgz: 'Vent et øyeblikk, vær så snill.',
    soundLink: '',
    wordId: 122
  },
  {
    nor: 'en film',
    eng: 'a movie',
    pl: 'film',
    ar: 'فيلم',
    ger: 'ein Film',
    lt: 'filmas',
    key: '123',
    norEgz: 'Vi så en spennende film i går kveld.',
    soundLink: '',
    wordId: 123
  },
  {
    nor: 'bitter',
    eng: 'bitter',
    pl: 'gorzki',
    ar: 'مُر',
    ger: 'bitter',
    lt: 'kartus',
    key: '124',
    norEgz: 'Grapefrukt kan smake litt bittert.',
    soundLink: '',
    wordId: 124
  },
  {
    nor: 'skarp',
    eng: 'sharp',
    pl: 'ostry',
    ar: 'حاد',
    ger: 'scharf',
    lt: 'aštrus',
    key: '125',
    norEgz: 'Kniven var skarp og kuttet lett gjennom papiret.',
    soundLink: '',
    wordId: 125
  },
  {
    nor: 'å være',
    eng: 'to be',
    pl: 'być',
    ar: 'كان',
    ger: 'sein',
    lt: 'būti',
    key: '126',
    norEgz: 'Det er viktig å være tålmodig.',
    soundLink: '',
    wordId: 126
  },
  {
    nor: 'å ha',
    eng: 'to have',
    pl: 'mieć',
    ar: 'يملك',
    ger: 'haben',
    lt: 'turėti',
    key: '127',
    norEgz: 'Hun har en ny bil.',
    soundLink: '',
    wordId: 127
  },
  {
    nor: 'sint',
    eng: 'angry',
    pl: 'zły',
    ar: 'غاضب',
    ger: 'wütend',
    lt: 'piktas',
    key: '128',
    norEgz: 'Han ble sint da han mistet nøklene sine.',
    soundLink: '',
    wordId: 128
  },
  {
    nor: 'rolig',
    eng: 'calm',
    pl: 'spokojny',
    ar: 'هادئ',
    ger: 'ruhig',
    lt: 'ramus',
    key: '129',
    norEgz: 'Han er rolig',
    soundLink: '',
    wordId: 129
  },
  {
    nor: 'billig',
    eng: 'cheap',
    pl: 'tani',
    ar: 'رخيص',
    ger: 'billig',
    lt: 'pigus',
    key: '130',
    norEgz: 'Denne skjorten var veldig billig.',
    soundLink: '',
    wordId: 130
  },
  {
    nor: 'å jobbe',
    eng: 'to work',
    pl: 'pracować',
    ar: 'يعمل',
    ger: 'arbeiten',
    lt: 'dirbti',
    key: '131',
    norEgz: 'Hun jobber som lærer.',
    soundLink: '',
    wordId: 131
  },
  {
    nor: 'å snakke',
    eng: 'to talk',
    pl: 'rozmawiać',
    ar: 'يتحدث',
    ger: 'sprechen',
    lt: 'kalbėti',
    key: '132',
    norEgz: 'Vi snakket sammen i flere timer.',
    soundLink: '',
    wordId: 132
  },
  {
    nor: 'en øy',
    eng: 'an island',
    pl: 'wyspa',
    ar: 'جزيرة',
    ger: 'eine Insel',
    lt: 'sala',
    key: '133',
    norEgz: 'De tilbrakte ferien på en liten øy.',
    soundLink: '',
    wordId: 133
  },
  {
    nor: 'en elv',
    eng: 'a river',
    pl: 'rzeka',
    ar: 'نهر',
    ger: 'ein Fluss',
    lt: 'upė',
    key: '134',
    norEgz: 'De padlet nedover elven i kano.',
    soundLink: '',
    wordId: 134
  },
  {
    nor: 'et hav',
    eng: 'a sea',
    pl: 'morze',
    ar: 'بحر',
    ger: 'ein Meer',
    lt: 'jūra',
    key: '135',
    norEgz: 'Havet var rolig og vakkert.',
    soundLink: '',
    wordId: 135
  },
  {
    nor: 'trist',
    eng: 'sad',
    pl: 'smutny',
    ar: 'حزين',
    ger: 'traurig',
    lt: 'liūdnas',
    key: '136',
    norEgz: 'Han følte seg trist etter å ha sagt farvel.',
    soundLink: '',
    wordId: 136
  },
  {
    nor: 'en innsjø',
    eng: 'a lake',
    pl: 'jezioro',
    ar: 'بحيرة',
    ger: 'ein See',
    lt: 'ežeras',
    key: '137',
    norEgz: 'De hadde en piknik ved innsjøen.',
    soundLink: '',
    wordId: 137
  },
  {
    nor: 'en skog',
    eng: 'a forest',
    pl: 'las',
    ar: 'غابة',
    ger: 'ein Wald',
    lt: 'miškas',
    key: '138',
    norEgz: 'De gikk på tur i skogen.',
    soundLink: '',
    wordId: 138
  },
  {
    nor: 'å gjøre',
    eng: 'to do',
    pl: 'robić',
    ar: 'يفعل',
    ger: 'tun',
    lt: 'daryti',
    key: '139',
    norEgz: 'Hva skal vi gjøre i helgen?',
    soundLink: '',
    wordId: 139
  },
  {
    nor: 'å si',
    eng: 'to say',
    pl: 'mówić',
    ar: 'يقول',
    ger: 'sagen',
    lt: 'sakyti',
    key: '140',
    norEgz: 'Hun sa at hun ville komme.',
    soundLink: '',
    wordId: 140
  },
  {
    nor: 'å gå',
    eng: 'to go',
    pl: 'iść',
    ar: 'يذهب',
    ger: 'gehen',
    lt: 'eiti',
    key: '141',
    norEgz: 'Han gikk til butikken.',
    soundLink: '',
    wordId: 141
  },
  {
    nor: 'en dal',
    eng: 'a valley',
    pl: 'dolina',
    ar: 'وادي',
    ger: 'ein Tal',
    lt: 'slėnis',
    key: '142',
    norEgz: 'De vandret gjennom dalen.',
    soundLink: '',
    wordId: 142
  },
  {
    nor: 'en butikk',
    eng: 'a store',
    pl: 'sklep',
    ar: 'متجر',
    ger: 'ein Geschäft',
    lt: 'parduotuvė',
    key: '143',
    norEgz: 'Han kjøpte klær i butikken.',
    soundLink: '',
    wordId: 143
  },
  {
    nor: 'en restaurant',
    eng: 'a restaurant',
    pl: 'restauracja',
    ar: 'مطعم',
    ger: 'ein Restaurant',
    lt: 'restoranas',
    key: '144',
    norEgz: 'De spiste middag på en restaurant.',
    soundLink: '',
    wordId: 144
  },
  {
    nor: 'et sykehus',
    eng: 'a hospital',
    pl: 'szpital',
    ar: 'مستشفى',
    ger: 'ein Krankenhaus',
    lt: 'ligoninė',
    key: '145',
    norEgz: 'Han ble kjørt til sykehuset etter ulykken.',
    soundLink: '',
    wordId: 145
  },
  {
    nor: 'å drikke',
    eng: 'to drink',
    pl: 'pić',
    ar: 'يشرب',
    ger: 'trinken',
    lt: 'gerti',
    key: '146',
    norEgz: 'Han drakk et glass vann.',
    soundLink: '',
    wordId: 146
  },
  {
    nor: 'en brannstasjon',
    eng: 'a fire station',
    pl: 'straż pożarna',
    ar: 'محطة الإطفاء',
    ger: 'eine Feuerwache',
    lt: 'gaisrinė',
    key: '147',
    norEgz: 'Brannstasjonen ligger i nærheten av parken.',
    soundLink: '',
    wordId: 147
  },
  {
    nor: 'en politistasjon',
    eng: 'a police station',
    pl: 'komisariat policji',
    ar: 'مركز شرطة',
    ger: 'eine Polizeistation',
    lt: 'policijos nuovada',
    key: '148',
    norEgz: 'Politistasjonen ligger ved siden av rådhuset.',
    soundLink: '',
    wordId: 148
  },
  {
    nor: 'et bibliotek',
    eng: 'a library',
    pl: 'biblioteka',
    ar: 'مكتبة',
    ger: 'eine Bibliothek',
    lt: 'biblioteka',
    key: '149',
    norEgz: 'Han lånte en bok fra biblioteket.',
    soundLink: '',
    wordId: 149
  },
  {
    nor: 'en bank',
    eng: 'a bank',
    pl: 'bank',
    ar: 'بنك',
    ger: 'eine Bank',
    lt: 'bankas',
    key: '150',
    norEgz: 'Hun gikk til banken for å ta ut penger.',
    soundLink: '',
    wordId: 150
  },
  {
    nor: 'en kirke',
    eng: 'a church',
    pl: 'kościół',
    ar: 'كنيسة',
    ger: 'eine Kirche',
    lt: 'bažnyčia',
    key: '151',
    norEgz: 'Familien gikk til kirken hver søndag.',
    soundLink: '',
    wordId: 151
  },
  {
    nor: 'å lese',
    eng: 'to read',
    pl: 'czytać',
    ar: 'يقرأ',
    ger: 'lesen',
    lt: 'skaityti',
    key: '152',
    norEgz: 'Hun liker å lese bøker om historie.',
    soundLink: '',
    wordId: 152
  },
  {
    nor: 'å skrive',
    eng: 'to write',
    pl: 'pisać',
    ar: 'يكتب',
    ger: 'schreiben',
    lt: 'rašyti',
    key: '153',
    norEgz: 'Han skriver en e-post til sin venn.',
    soundLink: '',
    wordId: 153
  },
  {
    nor: 'å sove',
    eng: 'to sleep',
    pl: 'spać',
    ar: 'ينام',
    ger: 'schlafen',
    lt: 'miegoti',
    key: '154',
    norEgz: 'Han pleier å sove tidlig om natten.',
    soundLink: '',
    wordId: 154
  },
  {
    nor: 'en blyant',
    eng: 'a pencil',
    pl: 'ołówek',
    ar: 'قلم رصاص',
    ger: 'ein Bleistift',
    lt: 'pieštukas',
    key: '155',
    norEgz: 'Hun tegner med en blyant.',
    soundLink: '',
    wordId: 155
  },
  {
    nor: 'et viskelær',
    eng: 'an eraser',
    pl: 'gumka do ścierania',
    ar: 'ممحاة',
    ger: 'ein Radiergummi',
    lt: 'trintukas',
    key: '156',
    norEgz: 'Han brukte et viskelær for å fjerne feilen.',
    soundLink: '',
    wordId: 156
  },
  {
    nor: 'en penn',
    eng: 'a pen',
    pl: 'długopis',
    ar: 'قلم',
    ger: 'ein Stift',
    lt: 'rašiklis',
    key: '157',
    norEgz: 'Hun skrev et brev med en penn.',
    soundLink: '',
    wordId: 157
  },
  {
    nor: 'en notatbok',
    eng: 'a notebook',
    pl: 'notes',
    ar: 'دفتر الملاحظات',
    ger: 'ein Notizbuch',
    lt: 'užrašų knyga',
    key: '158',
    norEgz: 'Hun skriver i en notatbok hver dag.',
    soundLink: '',
    wordId: 158
  },
  {
    nor: 'glad',
    eng: 'happy',
    pl: 'szczęśliwy',
    ar: 'سعيد',
    ger: 'glücklich',
    lt: 'laimingas',
    key: '159',
    norEgz: 'Han er veldig glad i dag.',
    soundLink: '',
    wordId: 159
  },
  {
    nor: 'dyr',
    eng: 'expensive',
    pl: 'drogi',
    ar: 'غالي',
    ger: 'teuer',
    lt: 'brangus',
    key: '160',
    norEgz: 'Denne bilen er veldig dyr.',
    soundLink: '',
    wordId: 160
  },
  {
    nor: 'søt',
    eng: 'cute',
    pl: 'słodki',
    ar: 'جميل',
    ger: 'niedlich',
    lt: 'mielas',
    key: '161',
    norEgz: 'Hun har en søt liten hund.',
    soundLink: '',
    wordId: 161
  },
  {
    nor: 'sur',
    eng: 'sour',
    pl: 'kwaśny',
    ar: 'حامض',
    ger: 'sauer',
    lt: 'rūgštus',
    key: '162',
    norEgz: 'Sitroner er sure.',
    soundLink: '',
    wordId: 162
  },
  {
    nor: 'salt',
    eng: 'salty',
    pl: 'słony',
    ar: 'مالح',
    ger: 'salzig',
    lt: 'sūrus',
    key: '163',
    norEgz: 'Potetgull er salt.',
    soundLink: '',
    wordId: 163
  },
  {
    nor: 'en ryggsekk',
    eng: 'a backpack',
    pl: 'plecak',
    ar: 'حقيبة ظهر',
    ger: 'ein Rucksack',
    lt: 'kuprinė',
    key: '164',
    norEgz: 'Han har en tung ryggsekk.',
    soundLink: '',
    wordId: 164
  },
  {
    nor: 'en plate',
    eng: 'a plate',
    pl: 'talerz',
    ar: 'صحن',
    ger: 'ein Teller',
    lt: 'lėkštė',
    key: '165',
    norEgz: 'Hun serverte maten på en plate.',
    soundLink: '',
    wordId: 165
  },
  {
    nor: 'et kamera',
    eng: 'a camera',
    pl: 'aparat fotograficzny',
    ar: 'كاميرا',
    ger: 'eine Kamera',
    lt: 'fotoaparatas',
    key: '166',
    norEgz: 'Han tar bilde med kamera.',
    soundLink: '',
    wordId: 166
  },
  {
    nor: 'en datamaskin',
    eng: 'a computer',
    pl: 'komputer',
    ar: 'كمبيوتر',
    ger: 'ein Computer',
    lt: 'kompiuteris',
    key: '167',
    norEgz: 'Han kjøpte en ny datamaskin.',
    soundLink: '',
    wordId: 167
  },
  {
    nor: 'en mus',
    eng: 'a mouse',
    pl: 'mysz',
    ar: 'فأر',
    ger: 'eine Maus',
    lt: 'pelė',
    key: '168',
    norEgz: 'Han bruker en trådløs mus.',
    soundLink: '',
    wordId: 168
  },
  {
    nor: 'en skjerm',
    eng: 'a monitor',
    pl: 'monitor',
    ar: 'شاشة',
    ger: 'ein Monitor',
    lt: 'monitorius',
    key: '169',
    norEgz: 'Hun har en stor skjerm på kontoret.',
    soundLink: '',
    wordId: 169
  },
  {
    nor: 'å spille',
    eng: 'to play',
    pl: 'grać',
    ar: 'يلعب',
    ger: 'spielen',
    lt: 'žaisti',
    key: '170',
    norEgz: 'Barna liker å spille fotball.',
    soundLink: '',
    wordId: 170
  },
  {
    nor: 'en skriver',
    eng: 'a printer',
    pl: 'drukarka',
    ar: 'طابعة',
    ger: 'ein Drucker',
    lt: 'spausdintuvas',
    key: '171',
    norEgz: 'Hun trenger en ny skriver.',
    soundLink: '',
    wordId: 171
  },
  {
    nor: 'et tastatur',
    eng: 'a keyboard',
    pl: 'klawiatura',
    ar: 'لوحة المفاتيح',
    ger: 'eine Tastatur',
    lt: 'klaviatūra',
    key: '172',
    norEgz: 'Han kjøpte et mekanisk tastatur.',
    soundLink: '',
    wordId: 172
  },
  {
    nor: 'smal',
    eng: 'narrow',
    pl: 'wąski',
    ar: 'ضيق',
    ger: 'schmal',
    lt: 'siauras',
    key: '173',
    norEgz: 'Veien er veldig smal.',
    soundLink: '',
    wordId: 173
  }
]
     






