[
    {
      nor: 'en bil',
      eng: 'a car',
      pl: 'samochód',
      ar: 'سيارة',
      ger: 'ein Auto',
      lt: 'automobilis',
      ua: 'автомобіль', 
      sp: 'un coche',
      key: '0',
      norEgz: 'Han kjører en bil.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbil.mp3?alt=media&token=994e0f46-bc52-411f-8614-ed11bea959c8',
      wordId: 0
    },
    {
      nor: 'stor',
      eng: 'big',
      pl: 'duży',
      ar: 'كبير',
      ger: 'groß',
      lt: 'didelis',
      ua: 'великий', 
      sp: 'grande',
      key: '1',
      norEgz: 'Det er en stor hund.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstor.mp3?alt=media&token=cd01dbdf-b602-4e93-9ffe-b32599565abb',
      wordId: 1
    },
    {
      nor: 'lang',
      eng: 'long',
      pl: 'długi',
      ar: 'طويل',
      ger: 'lang',
      lt: 'ilgas',
      ua: 'довгий', 
      sp: 'largo',
      key: '2',
      norEgz: 'Broen er lang.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flang.mp3?alt=media&token=968d6e30-3a78-40a6-b254-d89fb4e9a749',
      wordId: 2
    },
    {
      nor: 'høy',
      eng: 'tall',
      pl: 'wysoki',
      ar: 'طويل القامة',
      ger: 'groß',
      lt: 'aukštas',
      ua: 'високий', 
      sp: 'alto',
      key: '3',
      norEgz: 'Han er høy.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhooy.mp3?alt=media&token=dc477bb9-2921-4b1d-84d3-1f53fe0cfd63',
      wordId: 3
    },
    {
      nor: 'lav',
      eng: 'low',
      pl: 'niski',
      ar: 'منخفض',
      ger: 'niedrig',
      lt: 'žemas',
      ua: 'низький', 
      sp: 'bajo',
      key: '4',
      norEgz: 'Taket er lavt.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flav.mp3?alt=media&token=7031e79f-3ac1-48e5-857f-709b493277c3',
      wordId: 4
    },
    {
      nor: 'å bo',
      eng: 'to live',
      pl: 'mieszkać',
      ar: 'أن يعيش',
      ger: 'wohnen',
      lt: 'gyventi',
      ua: 'жити', 
      sp: 'vivir',
      key: '5',
      norEgz: 'Vi bor i Norge.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbo.mp3?alt=media&token=d06c822d-5c69-4dae-aa35-82a2477c2e7c',
      wordId: 5
    },
    {
      nor: 'å stå',
      eng: 'to stand',
      pl: 'stać',
      ar: 'يقف',
      ger: 'stehen',
      lt: 'stovėti',
      ua: 'стояти', 
      sp: 'estar de pie',
      key: '6',
      norEgz: 'Han står ved døren.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstaa.mp3?alt=media&token=3f7552fe-a9b0-43ab-9269-577674275a2c',
      wordId: 6
    },
    {
      nor: 'å sitte',
      eng: 'to sit',
      pl: 'siedzieć',
      ar: 'جلس',
      ger: 'sitzen',
      lt: 'sėdėti',
      ua: 'сидіти', 
      sp: 'sentarse',
      key: '7',
      norEgz: 'Hun sitter på stolen.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsitte.mp3?alt=media&token=0f05cab9-248b-4a5b-9626-b538c71d31af',
      wordId: 7
    },
    {
      nor: 'tung',
      eng: 'heavy',
      pl: 'ciężki',
      ar: 'ثقيل',
      ger: 'schwer',
      lt: 'sunkus',
      ua: 'важкий', 
      sp: 'pesado',
      key: '8',
      norEgz: 'Denne boken er tung.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftung.mp3?alt=media&token=9a3892b8-d173-4b1c-ae87-a3d15b9e8f65',
      wordId: 8
    },
    {
        nor: 'et fjell',
        eng: 'a mountain',
        pl: 'góra',
        ar: 'جبل',
        ger: 'ein Berg',
        lt: 'kalnas',
        ua: 'гора', 
        sp: 'una montaña',
        key: '9',
        norEgz: 'Det er et fjell i nærheten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffjell.mp3?alt=media&token=ee408a00-a0e7-4d2f-8173-9b20bdefacb0',
        wordId: 9
      },
      {
        nor: 'en sofa',
        eng: 'a sofa',
        pl: 'sofa',
        ar: 'أريكة',
        ger: 'ein Sofa',
        lt: 'sofa',
        ua: 'диван', 
        sp: 'un sofá',
        key: '10',
        norEgz: 'Vi har en ny sofa.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsofa.mp3?alt=media&token=8799ff44-f022-47d4-b7e8-9719589eb592',
        wordId: 10
      },
      {
        nor: 'en seng',
        eng: 'a bed',
        pl: 'łóżko',
        ar: 'سرير',
        ger: 'ein Bett',
        lt: 'lova',
        ua: 'ліжко', 
        sp: 'una cama',
        key: '11',
        norEgz: 'Sengen er myk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fseng.mp3?alt=media&token=fd1d2f96-fdc8-4f56-bf02-c385776ba4b9',
        wordId: 11
      },
      {
        nor: 'liten',
        eng: 'small',
        pl: 'mały',
        ar: 'صغير',
        ger: 'klein',
        lt: 'mažas',
        ua: 'маленький', 
        sp: 'pequeño',
        key: '12',
        norEgz: 'Det er en liten katt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fliten.mp3?alt=media&token=e8608887-2e76-42e1-b138-d02968a92dc6',
        wordId: 12
      },
      {
        nor: 'et tre',
        eng: 'a tree',
        pl: 'drzewo',
        ar: 'شجرة',
        ger: 'ein Baum',
        lt: 'medis',
        ua: 'дерево', 
        sp: 'un árbol',
        key: '13',
        norEgz: 'Det er et tre i hagen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftre.mp3?alt=media&token=d213ef92-6bd5-49cd-8496-acda9ad2a8e3',
        wordId: 13
      },
      {
        nor: 'en blomst',
        eng: 'a flower',
        pl: 'kwiat',
        ar: 'زهرة',
        ger: 'eine Blume',
        lt: 'gėlė',
        ua: 'квітка', 
        sp: 'una flor',
        key: '14',
        norEgz: 'Han ga henne en blomst.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblomst.mp3?alt=media&token=cc895940-29b4-41c1-8ac8-24b8c5face40',
        wordId: 14
      },
      {
        nor: 'kjølig',
        eng: 'cool',
        pl: 'chłodny',
        ar: 'بارد',
        ger: 'kühl',
        lt: 'vėsus',
        ua: 'прохолодний', 
        sp: 'fresco',
        key: '15',
        norEgz: 'Været er kjølig i dag.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjoolig.mp3?alt=media&token=2456b08f-503b-4608-9471-f8088297faa6',
        wordId: 15
      },
      {
        nor: 'tørr',
        eng: 'dry',
        pl: 'suchy',
        ar: 'جاف',
        ger: 'trocken',
        lt: 'sausas',
        ua: 'сухий', 
        sp: 'seco',
        key: '16',
        norEgz: 'Klærne er tørre nå.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorr.mp3?alt=media&token=4258ffd1-910d-46d4-970a-0e5e71a0fd46',
        wordId: 16
      },
      {
        nor: 'våt',
        eng: 'wet',
        pl: 'mokry',
        ar: 'مبلل',
        ger: 'nass',
        lt: 'šlapias',
        ua: 'мокрий', 
        sp: 'mojado',
        key: '17',
        norEgz: 'Gulvet er vått.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaat.mp3?alt=media&token=a92a350c-8793-4f10-a6db-34ee69d4c7b7',
        wordId: 17
      },{
        nor: 'sterk',
        eng: 'strong',
        pl: 'mocny',
        ar: 'قوي',
        ger: 'stark',
        lt: 'stiprus',
        ua: 'сильний', 
        sp: 'fuerte',
        key: '18',
        norEgz: 'Han er en sterk mann.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsterk.mp3?alt=media&token=c24a7702-26c6-41d7-b25a-7a82a2a39f1e',
        wordId: 18
      },
      {
        nor: 'svak',
        eng: 'weak',
        pl: 'słaby',
        ar: 'ضعيف',
        ger: 'schwach',
        lt: 'silpnas',
        ua: 'слабкий', 
        sp: 'débil',
        key: '19',
        norEgz: 'Signalet er svakt her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvak.mp3?alt=media&token=60d34454-1dd4-455f-b2e6-c2cbfcb6b4fd',
        wordId: 19
      },
      {
        nor: 'rask',
        eng: 'fast',
        pl: 'szybki',
        ar: 'سريع',
        ger: 'schnell',
        lt: 'greitas',
        ua: 'швидкий', 
        sp: 'rápido',
        key: '20',
        norEgz: 'Han løper veldig raskt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frask.mp3?alt=media&token=a67eeb87-1360-4d0f-9de8-0a8551157068',
        wordId: 20
      },
      {
        nor: 'en kake',
        eng: 'a cake',
        pl: 'ciasto',
        ar: 'كعكة',
        ger: 'ein Kuchen',
        lt: 'tortas',
        ua: 'торт', 
        sp: 'un pastel',
        key: '21',
        norEgz: 'Hun laget en kake til festen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkake.mp3?alt=media&token=e9ccf858-92cd-44e9-acae-042826d58374',
        wordId: 21
      },
      {
        nor: 'en sykkel',
        eng: 'a bicycle',
        pl: 'rower',
        ar: 'دراجة',
        ger: 'ein Fahrrad',
        lt: 'dviratis',
        ua: 'велосипед', 
        sp: 'una bicicleta',
        key: '22',
        norEgz: 'Han sykler til jobben.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykkel.mp3?alt=media&token=618c4200-13cb-4745-80f3-12691892cb5f',
        wordId: 22
      },
      {
        nor: 'en båt',
        eng: 'a boat',
        pl: 'łódź',
        ar: 'قارب',
        ger: 'ein Boot',
        lt: 'valtis',
        ua: 'човен', 
        sp: 'un barco',
        key: '23',
        norEgz: 'De reiste med en båt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbaat.mp3?alt=media&token=6a8777b3-e15c-4b5a-a9c4-6dc26f062284',
        wordId: 23
      },
      {
        nor: 'treg',
        eng: 'slow',
        pl: 'wolny',
        ar: 'بطيء',
        ger: 'langsam',
        lt: 'lėtas',
        ua: 'повільний', 
        sp: 'lento',
        key: '24',
        norEgz: 'Datamaskinen min er veldig treg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftreg.mp3?alt=media&token=6acd7120-530a-46dc-823b-988ba0a2ec49',
        wordId: 24
      },
      {
        nor: 'pen',
        eng: 'pretty',
        pl: 'ładny',
        ar: 'جميلة',
        ger: 'hübsch',
        lt: 'gražus',
        ua: 'гарний', 
        sp: 'bonito',
        key: '25',
        norEgz: 'Hun er en pen jente.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpen.mp3?alt=media&token=5481b467-0dca-4539-9647-df6c9b28c122',
        wordId: 25
      },
      {
        nor: 'en telefon',
        eng: 'a telephone',
        pl: 'telefon',
        ar: 'هاتف',
        ger: 'ein Telefon',
        lt: 'telefonas',
        ua: 'телефон', 
        sp: 'un teléfono',
        key: '26',
        norEgz: 'Han ringte meg på telefonen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftelefon.mp3?alt=media&token=4c5dcbeb-a30e-439c-829f-77191c8fb202',
        wordId: 26
      },
      {
        nor: 'en avis',
        eng: 'a newspaper',
        pl: 'gazeta',
        ar: 'جريدة',
        ger: 'eine Zeitung',
        lt: 'laikraštis',
        ua: 'газета', 
        sp: 'un periódico',
        key: '27',
        norEgz: 'Jeg leser avisen hver morgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Favis.mp3?alt=media&token=a99c9bca-c128-4f30-ba97-fd90698ae65a',
        wordId: 27
      },
      {
        nor: 'et speil',
        eng: 'a mirror',
        pl: 'lustro',
        ar: 'مرآة',
        ger: 'ein Spiegel',
        lt: 'veidrodis',
        ua: 'дзеркало', 
        sp: 'un espejo',
        key: '28',
        norEgz: 'Hun så seg selv i speilet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspeil.mp3?alt=media&token=860c19b1-9c72-44d9-8fc8-83076af5d7a5',
        wordId: 28
      },
      {
        nor: 'kort',
        eng: 'short',
        pl: 'krótki',
        ar: 'قصير',
        ger: 'kurz',
        lt: 'trumpas',
        ua: 'короткий', 
        sp: 'corto',
        key: '29',
        norEgz: 'Filmen var kort, men god.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkort.mp3?alt=media&token=b6f354a3-8ef9-40e6-8cc5-e39f123d2caa',
        wordId: 29
      },
      {
        nor: 'en venn',
        eng: 'a friend',
        pl: 'przyjaciel',
        ar: 'صديق',
        ger: 'ein Freund',
        lt: 'draugas',
        ua: 'друг', 
        sp: 'un amigo',
        key: '30',
        norEgz: 'Han er en god venn av meg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvenn.mp3?alt=media&token=177a17bc-3293-495a-b53f-e50e6a072f77',
        wordId: 30
      },
      {
        nor: 'en jente',
        eng: 'a girl',
        pl: 'dziewczyna',
        ar: 'فتاة',
        ger: 'ein Mädchen',
        lt: 'mergaitė',
        ua: 'дівчина', 
        sp: 'una chica',
        key: '31',
        norEgz: 'Det er en jente i parken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjente.mp3?alt=media&token=2f35c7b7-c3dc-4210-b3fb-071e77f467c0',
        wordId: 31
      },
      {
        nor: 'en gutt',
        eng: 'a boy',
        pl: 'chłopiec',
        ar: 'ولد',
        ger: 'ein Junge',
        lt: 'berniukas',
        ua: 'хлопець', 
        sp: 'un chico',
        key: '32',
        norEgz: 'Han er en snill gutt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgutt.mp3?alt=media&token=afc817af-2488-4810-adc9-ff8a0db1b2e0',
        wordId: 32
      },
      {
        nor: 'å få',
        eng: 'to get',
        pl: 'dostać',
        ar: 'الحصول على',
        ger: 'bekommen',
        lt: 'gauti',
        ua: 'отримати',
        sp: 'obtener',
        key: '33',
        norEgz: 'Jeg fikk en gave fra henne.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffaa.mp3?alt=media&token=e975bbf1-d4ff-43d8-bb89-5218805b69b5',
        wordId: 33
      },
      {
        nor: 'å ville',
        eng: 'to want',
        pl: 'chcieć',
        ar: 'يريد',
        ger: 'wollen',
        lt: 'norėti',
        ua: 'хотіти',
        sp: 'querer',
        key: '34',
        norEgz: 'Han ville gå på kino.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fville.mp3?alt=media&token=68914219-53ff-45ac-a103-b7b5c01a1ad2',
        wordId: 34
      },
      {
        nor: 'å kunne',
        eng: 'to be able',
        pl: 'móc',
        ar: 'يستطيع',
        ger: 'können',
        lt: 'galėti',
        ua: 'могти',
        sp: 'poder',
        key: '35',
        norEgz: 'Hun kunne ikke finne nøklene sine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkunne.mp3?alt=media&token=cbc28c39-0a78-46a2-b1ca-072b363a4e9f',
        wordId: 35
      },
      {
        nor: 'å måtte',
        eng: 'to have to',
        pl: 'musieć',
        ar: 'يجب أن',
        ger: 'müssen',
        lt: 'turėti',
        ua: 'мати',
        sp: 'tener que',
        key: '36',
        norEgz: 'Vi måtte vente i en time.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaatte.mp3?alt=media&token=02f2a784-2710-44ff-9eeb-46c1b851df58',
        wordId: 36
      },
      {
        nor: 'et barn',
        eng: 'a child',
        pl: 'dziecko',
        ar: 'طفل',
        ger: 'ein Kind',
        lt: 'vaikas',
        ua: 'дитина',
        sp: 'un niño',
        key: '37',
        norEgz: 'Det er et søtt barn.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbarn.mp3?alt=media&token=75e9e474-3305-4699-b276-8aa25abbbdc1',
        wordId: 37
      },
      {
        nor: 'en familie',
        eng: 'a family',
        pl: 'rodzina',
        ar: 'عائلة',
        ger: 'eine Familie',
        lt: 'šeima',
        ua: 'сім’я',
        sp: 'una familia',
        key: '38',
        norEgz: 'Familien vår bor i Norge.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffamilie.mp3?alt=media&token=456ee8d5-78fe-4967-a73f-f78165b03c68',
        wordId: 38
      },
      {
        nor: 'et hus',
        eng: 'a house',
        pl: 'dom',
        ar: 'بيت',
        ger: 'ein Haus',
        lt: 'namas',
        ua: 'будинок',
        sp: 'una casa',
        key: '39',
        norEgz: 'Vi kjøpte et nytt hus.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhus.mp3?alt=media&token=f42d6cc4-2585-4498-90c9-00393910ee09',
        wordId: 39
      },
      {
        nor: 'en bok',
        eng: 'a book',
        pl: 'książka',
        ar: 'كتاب',
        ger: 'ein Buch',
        lt: 'knyga',
        ua: 'книга',
        sp: 'un libro',
        key: '40',
        norEgz: 'Jeg leser en interessant bok.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbok.mp3?alt=media&token=b72147af-c18b-4504-b421-9ae701b02c55',
        wordId: 40
      },
      {
        nor: 'å reise',
        eng: 'to travel',
        pl: 'podróżować',
        ar: 'السفر',
        ger: 'reisen',
        lt: 'keliauti',
        ua: 'подорожувати',
        sp: 'viajar',
        key: '41',
        norEgz: 'De liker å reise rundt i verden.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freise.mp3?alt=media&token=c2a0e50a-1e12-44af-853d-54eb9943f575',
        wordId: 41
    },
    {
        nor: 'å lytte',
        eng: 'to listen',
        pl: 'słuchać',
        ar: 'يستمع',
        ger: 'zuhören',
        lt: 'klausytis',
        ua: 'слухати',
        sp: 'escuchar',
        key: '42',
        norEgz: 'Hun lytter nøye til musikken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flytte.mp3?alt=media&token=be3d123d-ddd5-4013-9f6b-d70d5178ac64',
        wordId: 42
    },
    {
        nor: 'å lære',
        eng: 'to learn',
        pl: 'uczyć się',
        ar: 'تعلم',
        ger: 'lernen',
        lt: 'mokytis',
        ua: 'вчитися',
        sp: 'aprender',
        key: '43',
        norEgz: 'Jeg vil lære å snakke norsk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleere.mp3?alt=media&token=febdecc0-e9d4-440c-8f48-ea54f8942dbb',
        wordId: 43
    },
    {
        nor: 'en stol',
        eng: 'a chair',
        pl: 'krzesło',
        ar: 'كرسي',
        ger: 'ein Stuhl',
        lt: 'kėdė',
        ua: 'стілець',
        sp: 'una silla',
        key: '44',
        norEgz: 'Sett deg ned på stolen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstol.mp3?alt=media&token=d689b1b0-d210-4106-924f-b3fbebd8ca6f',
        wordId: 44
    },
    {
        nor: 'et bord',
        eng: 'a table',
        pl: 'stół',
        ar: 'طاولة',
        ger: 'ein Tisch',
        lt: 'stalas',
        ua: 'стіл',
        sp: 'una mesa',
        key: '45',
        norEgz: 'Vi spiste middag ved bordet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbord.mp3?alt=media&token=dc049ce7-478b-4910-bd8d-09ea9badabaf',
        wordId: 45
    },
    {
        nor: 'en skole',
        eng: 'a school',
        pl: 'szkoła',
        ar: 'مدرسة',
        ger: 'eine Schule',
        lt: 'mokykla',
        ua: 'школа',
        sp: 'una escuela',
        key: '46',
        norEgz: 'Barna går på skolen hver dag.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskole.mp3?alt=media&token=26087d43-8fb9-465b-b615-b6c8ae9ad63f',
        wordId: 46
    },
    {
        nor: 'å se',
        eng: 'to see',
        pl: 'zobaczyć',
        ar: 'أنظر',
        ger: 'sehen',
        lt: 'matyti',
        ua: 'дивитися',
        sp: 'ver',
        key: '47',
        norEgz: 'Kan du se månen i kveld?',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fse.mp3?alt=media&token=8b1dfd13-b9df-4854-9deb-bed4f03872c9',
        wordId: 47
    },
    {
        nor: 'å spise',
        eng: 'to eat',
        pl: 'jeść',
        ar: 'يأكل',
        ger: 'essen',
        lt: 'valgyti',
        ua: 'їсти',
        sp: 'comer',
        key: '48',
        norEgz: 'Vi spiser middag klokka seks.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspise.mp3?alt=media&token=94f0d894-ea58-461c-a006-acde95933f20',
        wordId: 48
    },
    {
        nor: 'en lærer',
        eng: 'a teacher',
        pl: 'nauczyciel',
        ar: 'معلم',
        ger: 'ein Lehrer',
        lt: 'mokytojas',
        ua: 'вчитель',
        sp: 'un profesor',
        key: '49',
        norEgz: 'Læreren underviser i klasserommet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleerer.mp3?alt=media&token=2669dfa8-b1b0-49b6-9857-bb4baf3a8b21',
        wordId: 49
    },
    {
        nor: 'et eple',
        eng: 'an apple',
        pl: 'jabłko',
        ar: 'تفاحة',
        ger: 'ein Apfel',
        lt: 'obuolys',
        ua: 'яблуко',
        sp: 'una manzana',
        key: '50',
        norEgz: 'Hun spiser et eple til lunsj.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feple.mp3?alt=media&token=27062beb-9a12-44e1-9654-3d9ad143701e',
        wordId: 50
  },
  {
    nor: 'en dør',
    eng: 'a door',
    pl: 'drzwi',
    ar: 'باب',
    ger: 'eine Tür',
    lt: 'durys',
    ua: 'двері',
    sp: 'una puerta',
    key: '51',
    norEgz: 'Åpne døren, vær så snill.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdoor.mp3?alt=media&token=36df259e-d77b-4fbf-b54a-dc52f33b4109',
    wordId: 51
  },
  {
    nor: 'et vindu',
    eng: 'a window',
    pl: 'okno',
    ar: 'نافذة',
    ger: 'ein Fenster',
    lt: 'langas',
    ua: 'вікно',
    sp: 'una ventana',
    key: '52',
    norEgz: 'Han åpnet vinduet for å få frisk luft.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvindu.mp3?alt=media&token=612490f2-e675-4a57-af64-66a44182d0ca',
    wordId: 52
  },
  {
    nor: 'en katt',
    eng: 'a cat',
    pl: 'kot',
    ar: 'قطة',
    ger: 'eine Katze',
    lt: 'katė',
    ua: 'кіт',
    sp: 'un gato',
    key: '53',
    norEgz: 'Katten vår heter Luna.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkatt.mp3?alt=media&token=3193bfa2-904d-4dd8-bcbc-0b9988a5a92f',
    wordId: 53
  },
  {
    nor: 'en hund',
    eng: 'a dog',
    pl: 'pies',
    ar: 'كلب',
    ger: 'ein Hund',
    lt: 'šuo',
    ua: 'собака',
    sp: 'un perro',
    key: '54',
    norEgz: 'Hunden min elsker å gå tur.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhund.mp3?alt=media&token=6f48901c-fab9-42ba-9c9b-a03a7f38d4dc',
    wordId: 54
  },
  {
    nor: 'en kopp',
    eng: 'a cup',
    pl: 'filiżanka',
    ar: 'كوب',
    ger: 'eine Tasse',
    lt: 'puodelis',
    ua: 'чашка',
    sp: 'una taza',
    key: '55',
    norEgz: 'Jeg drikker kaffe fra koppen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkopp.mp3?alt=media&token=2ec52834-17f7-4190-9bc9-582a46032be8',
    wordId: 55
  },
  {
    nor: 'et glass',
    eng: 'a glass',
    pl: 'szklanka',
    ar: 'كأس',
    ger: 'ein Glas',
    lt: 'stiklinė',
    ua: 'склянка',
    sp: 'un vaso',
    key: '56',
    norEgz: 'Han fylte et glass med vann.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fglass.mp3?alt=media&token=de4523b9-8065-4297-bfc1-0b220373f696',
    wordId: 56
  },
  {
    nor: 'en by',
    eng: 'a city',
    pl: 'miasto',
    ar: 'مدينة',
    ger: 'eine Stadt',
    lt: 'miestas',
    ua: 'місто',
    sp: 'una ciudad',
    key: '57',
    norEgz: 'Oslo er hovedstaden i Norge.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fby.mp3?alt=media&token=cb1c1625-6a96-49f7-9e7f-a382907b668a',
    wordId: 57
  },
  {
    nor: 'å legge',
    eng: 'to put',
    pl: 'kłaść',
    ar: 'وضع',
    ger: 'legen',
    lt: 'dėti',
    ua: 'класти',
    sp: 'poner',
    key: '58',
    norEgz: 'Hun legger boken på bordet.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flegge.mp3?alt=media&token=269e98ed-6417-453f-aefe-1c5c7af0c617',
    wordId: 58
  },
  {
    nor: 'å arbeide',
    eng: 'to work',
    pl: 'pracować',
    ar: 'العمل',
    ger: 'arbeiten',
    lt: 'dirbti',
    ua: 'працювати',
    sp: 'trabajar',
    key: '59',
    norEgz: 'Han arbeider på et kontor.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Farbeide.mp3?alt=media&token=8392cbe4-a500-4810-a39e-bec82adb3d58',
    wordId: 59
  },
  {
    nor: 'å studere',
    eng: 'to study',
    pl: 'studiować',
    ar: 'يدرس',
    ger: 'studieren',
    lt: 'mokytis',
    ua: 'вчитися',
    sp: 'estudiar',
    key: '60',
    norEgz: 'Hun studerer medisin på universitetet.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstudere.mp3?alt=media&token=7a3ed484-3cfa-4f51-b425-a391dd8bfeb7',
    wordId: 60
  },
  {
    nor: 'å le',
    eng: 'to laugh',
    pl: 'śmiać się',
    ar: 'يضحك',
    ger: 'lachen',
    lt: 'juoktis',
    ua: 'сміятися',
    sp: 'reír',
    key: '61',
    norEgz: 'Barna ler når de ser klovnen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fle.mp3?alt=media&token=921151a7-0b0d-49f1-9b59-42e62020b141',
    wordId: 61
  },
  {
    nor: 'å gråte',
    eng: 'to cry',
    pl: 'płakać',
    ar: 'يبكي',
    ger: 'weinen',
    lt: 'verkti',
    ua: 'плакати',
    sp: 'llorar',
    key: '62',
    norEgz: 'Babyen gråter når den er sulten.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgraate.mp3?alt=media&token=05035171-780d-4f38-a58f-c2d3193e58cc',
    wordId: 62
  },
  {
    nor: 'en koffert',
    eng: 'a suitcase',
    pl: 'walizka',
    ar: 'حقيبة',
    ger: 'ein Koffer',
    lt: 'lagaminas',
    ua: 'валіза',
    sp: 'una maleta',
    key: '63',
    norEgz: 'Han pakker kofferten før reisen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkoffert.mp3?alt=media&token=6fd79fb5-3a69-42ae-8cd3-f09d175dbadb',
    wordId: 63
  },
  {
    nor: 'et skjerf',
    eng: 'a scarf',
    pl: 'szalik',
    ar: 'وشاح',
    ger: 'ein Schal',
    lt: 'šalikas',
    key: '64',
    norEgz: 'Hun har på seg et skjerf for å holde seg varm.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjerf.mp3?alt=media&token=d39e3ed2-ca48-4c3e-af0e-f04d78257884',
    wordId: 64
  },
  {
    nor: 'en jakke',
    eng: 'a jacket',
    pl: 'kurtka',
    ar: 'سترة',
    ger: 'eine Jacke',
    lt: 'striukė',
    key: '65',
    norEgz: 'Han kjøpte en ny jakke i butikken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjakke.mp3?alt=media&token=c036d7d1-dca5-4679-b925-7e263a098a3a',
    wordId: 65
  },
  {
    nor: 'å komme',
    eng: 'to come',
    pl: 'przychodzić',
    ar: 'يأتي',
    ger: 'kommen',
    lt: 'ateiti',
    key: '66',
    norEgz: 'Han kommer til festen senere.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkomme.mp3?alt=media&token=f8dc22a8-84a8-43bd-9d35-5687491a5250',
    wordId: 66
  },
  {
    nor: 'å tenke',
    eng: 'to think',
    pl: 'myśleć',
    ar: 'يفكر',
    ger: 'denken',
    lt: 'galvoti',
    key: '67',
    norEgz: 'Jeg tenker på hva jeg skal gjøre i morgen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftenke.mp3?alt=media&token=c212e447-1309-4079-8427-3e764d4cfc84',
    wordId: 67
  },
  {
    nor: 'å kjøpe',
    eng: 'to buy',
    pl: 'kupować',
    ar: 'يشترى',
    ger: 'kaufen',
    lt: 'pirkti',
    key: '68',
    norEgz: 'Hun kjøper en billett til konserten.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjoope.mp3?alt=media&token=f3344d5b-7cff-41e2-81ef-85048f014e97',
    wordId: 68
  },
  {
    nor: 'å kjøre',
    eng: 'to drive',
    pl: 'prowadzić',
    ar: 'يقود',
    ger: 'fahren',
    lt: 'vairuoti',
    key: '69',
    norEgz: 'Han kjører bilen til jobben.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjoore.mp3?alt=media&token=5cf53e21-e03e-4298-97c4-ad1ca1bae3d8',
    wordId: 69
  },
  {
    nor: 'et slips',
    eng: 'a tie',
    pl: 'krawat',
    ar: 'ربطة عنق',
    ger: 'eine Krawatte',
    lt: 'kaklaraištis',
    key: '70',
    norEgz: 'Han har på seg et slips til bryllupet.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fslips.mp3?alt=media&token=f9278413-be68-4945-8839-9c49788d30cf',
    wordId: 70
  },
  {
    nor: 'en paraply',
    eng: 'an umbrella',
    pl: 'parasolka',
    ar: 'مظلة',
    ger: 'ein Regenschirm',
    lt: 'skėtis',
    key: '71',
    norEgz: 'Hun tar med seg en paraply i tilfelle det regner.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fparaply.mp3?alt=media&token=4db699c6-4d18-4330-b318-31b57bb862b0',
    wordId: 71
  },
  {
    nor: 'en stjerne',
    eng: 'a star',
    pl: 'gwiazda',
    ar: 'نجمة',
    ger: 'ein Stern',
    lt: 'žvaigždė',
    key: '72',
    norEgz: 'Vi ser stjernene på nattehimmelen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstjerne.mp3?alt=media&token=658afd58-c05a-46e6-a299-a39bc021286a',
    wordId: 72
  },
  {
    nor: 'en måne',
    eng: 'a moon',
    pl: 'księżyc',
    ar: 'قمر',
    ger: 'ein Mond',
    lt: 'mėnulis',
    key: '73',
    norEgz: 'Månen lyser opp natten.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaane.mp3?alt=media&token=74bec971-f5c8-4874-b4d9-1b59be842758',
    wordId: 73
  },
  {
    nor: 'å løpe',
    eng: 'to run',
    pl: 'biegać',
    ar: 'يركض',
    ger: 'laufen',
    lt: 'bėgti',
    key: '74',
    norEgz: 'Hun løper hver morgen for å holde seg i form.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Floope.mp3?alt=media&token=7c6f40c4-347c-49e4-8bf2-644c3833e752',
    wordId: 74
  },
  {
    nor: 'å hoppe',
    eng: 'to jump',
    pl: 'skakać',
    ar: 'يقفز',
    ger: 'springen',
    lt: 'šokti',
    key: '75',
    norEgz: 'Barnet hopper på trampolinen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhoppe.mp3?alt=media&token=3ce26483-25a6-4ccb-b59d-44d45ee36060',
    wordId: 75
  },
  {
    nor: 'å svømme',
    eng: 'to swim',
    pl: 'pływać',
    ar: 'يسبح',
    ger: 'schwimmen',
    lt: 'plaukti',
    key: '76',
    norEgz: 'Han liker å svømme i innsjøen om sommeren.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvoomme.mp3?alt=media&token=05b4f451-9219-4d7a-92ff-bb4a5c98a7d4',
    wordId: 76
  },
  {
    nor: 'å danse',
    eng: 'to dance',
    pl: 'tańczyć',
    ar: 'يرقص',
    ger: 'tanzen',
    lt: 'šokti',
    key: '77',
    norEgz: 'De danser hele natten på festen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdanse.mp3?alt=media&token=6201b96c-bf31-4b45-bb8d-81f84525074e',
    wordId: 77
  },
  {
    nor: 'å synge',
    eng: 'to sing',
    pl: 'śpiewać',
    ar: 'يغني',
    ger: 'singen',
    lt: 'dainuoti',
    key: '78',
    norEgz: 'Hun synger i koret på skolen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsynge.mp3?alt=media&token=84f330d1-1057-4980-8682-729d62f29455',
    wordId: 78
  },
  {
    nor: 'en sol',
    eng: 'a sun',
    pl: 'słońce',
    ar: 'شمس',
    ger: 'eine Sonne',
    lt: 'saulė',
    key: '79',
    norEgz: 'Solen skinner på en klar dag.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsol.mp3?alt=media&token=7e481b41-b506-48f1-9237-329f137065b0',
    wordId: 79
  },
  {
    nor: 'et hotell',
    eng: 'a hotel',
    pl: 'hotel',
    ar: 'فندق',
    ger: 'ein Hotel',
    lt: 'viešbutis',
    key: '80',
    norEgz: 'Vi bor på et hotell i ferien.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhotell.mp3?alt=media&token=baa36880-edd4-447b-bf08-6e52d90d0917',
    wordId: 80
  },
  {
    nor: 'et tårn',
    eng: 'a tower',
    pl: 'wieża',
    ar: 'برج',
    ger: 'ein Turm',
    lt: 'bokštas',
    key: '81',
    norEgz: 'Det gamle slottet har et høyt tårn.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftaarn.mp3?alt=media&token=646012dd-7373-47b6-ac34-1eedfe9fa077',
    wordId: 81
  },
  {
    nor: 'en gate',
    eng: 'a street',
    pl: 'ulica',
    ar: 'شارع',
    ger: 'eine Straße',
    lt: 'gatvė',
    key: '82',
    norEgz: 'Huset ligger ved en travel gate.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgate.mp3?alt=media&token=56414b0c-b540-4edc-bd11-e4870a89787d',
    wordId: 82
  },
  {
    nor: 'en bro',
    eng: 'a bridge',
    pl: 'most',
    ar: 'جسر',
    ger: 'eine Brücke',
    lt: 'tiltas',
    key: '83',
    norEgz: 'Vi krysser broen for å komme til parken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbro.mp3?alt=media&token=125c8f61-8e4e-43c6-b042-eb6fe562fe00',
    wordId: 83
  },
  {
    nor: 'et slott',
    eng: 'a castle',
    pl: 'zamek',
    ar: 'قلعة',
    ger: 'ein Schloss',
    lt: 'pilis',
    key: '84',
    norEgz: 'Turister besøker det historiske slottet.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fslott.mp3?alt=media&token=419064cb-a84b-4352-8cd7-5b047b9dbd0b',
    wordId: 84
  },
  {
    nor: 'en fontene',
    eng: 'a fountain',
    pl: 'fontanna',
    ar: 'نافورة',
    ger: 'ein Springbrunnen',
    lt: 'fontanas',
    key: '85',
    norEgz: 'Fontenen i parken er veldig vakker.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffontene.mp3?alt=media&token=24440f64-41d2-4986-94f1-245581547cd8',
    wordId: 85
  },
  {
    nor: 'lett',
    eng: 'easy',
    pl: 'łatwy',
    ar: 'سهل',
    ger: 'leicht',
    lt: 'lengvas',
    key: '86',
    norEgz: 'Denne oppgaven er lett for meg.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flett.mp3?alt=media&token=a62d5afa-d642-4577-bafa-7b7cb61eface',
    wordId: 86
  },
  {
    nor: 'å selge',
    eng: 'to sell',
    pl: 'sprzedawać',
    ar: 'يبيع',
    ger: 'verkaufen',
    lt: 'parduoti',
    key: '87',
    norEgz: 'Han selger frukt på markedet.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fselge.mp3?alt=media&token=fa8254cc-1a1e-4b3d-b4d1-8e3fbd9d85fb',
    wordId: 87
  },
  {
    nor: 'å møte',
    eng: 'to meet',
    pl: 'spotykać',
    ar: 'يلتقي',
    ger: 'treffen',
    lt: 'susitikti',
    key: '88',
    norEgz: 'Vi møtes på kafeen klokka to.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmoote.mp3?alt=media&token=8a46d9c3-a836-493d-9860-5c5e387ed988',
    wordId: 88
  },
  {
    nor: 'å besøke',
    eng: 'to visit',
    pl: 'odwiedzać',
    ar: 'يزور',
    ger: 'besuchen',
    lt: 'aplankyti',
    key: '89',
    norEgz: 'De besøker besteforeldrene sine i helgen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbesooke.mp3?alt=media&token=57db6c29-53b0-4b90-b37c-f5b8a7ea1dd7',
    wordId: 89
  },
  {
    nor: 'gammel',
    eng: 'old',
    pl: 'stary',
    ar: 'قديم',
    ger: 'alt',
    lt: 'senas',
    key: '90',
    norEgz: 'Det gamle huset trenger reparasjon.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgammel.mp3?alt=media&token=56161850-987b-4d95-bd85-0e126a4675b2',
    wordId: 90
  },
  {
    nor: 'ung',
    eng: 'young',
    pl: 'młody',
    ar: 'شاب',
    ger: 'jung',
    lt: 'jaunas',
    key: '91',
    norEgz: 'Han er en ung og talentfull musiker.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fung.mp3?alt=media&token=8acda1b8-60ea-488d-950f-94d958734b96',
    wordId: 91
  },
  {
    nor: 'ny',
    eng: 'new',
    pl: 'nowy',
    ar: 'جديد',
    ger: 'neu',
    lt: 'naujas',
    key: '92',
    norEgz: 'De har kjøpt en ny bil.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fny.mp3?alt=media&token=9c0b09a9-b6d1-48d5-8ce4-55bc5268fd7a',
    wordId: 92
  },
  {
    nor: 'varm',
    eng: 'warm',
    pl: 'ciepły',
    ar: 'دافئ',
    ger: 'warm',
    lt: 'šiltas',
    key: '93',
    norEgz: 'Det er en varm sommerdag.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvarm.mp3?alt=media&token=4a9c8a2d-377c-4597-b6e6-3d8079f4bc44',
    wordId: 93
  },
  {
    nor: 'kald',
    eng: 'cold',
    pl: 'zimny',
    ar: 'بارد',
    ger: 'kalt',
    lt: 'šaltas',
    key: '94',
    norEgz: 'Vinteren i Norge er veldig kald.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkald.mp3?alt=media&token=58d8fc3c-73d5-4559-ba90-feddf71a7c99',
    wordId: 94
  },
  {
    nor: 'en hatt',
    eng: 'a hat',
    pl: 'kapelusz',
    ar: 'قبعة',
    ger: 'ein Hut',
    lt: 'šešėlis',
    key: '95',
    norEgz: 'Hun kjøpte en hatt for å beskytte seg mot solen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhatt.mp3?alt=media&token=d64f2373-7f43-4de4-be5a-e548ac089742',
    wordId: 95
  },
  {
    nor: 'en lommebok',
    eng: 'a wallet',
    pl: 'portfel',
    ar: 'محفظة',
    ger: 'eine Brieftasche',
    lt: 'piniginė',
    key: '96',
    norEgz: 'Han mistet lommeboken sin i går.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flommebok.mp3?alt=media&token=b9ce92b1-57b9-4190-b2bb-6c1d5a36efb6',
    wordId: 96
  },
  {
    nor: 'et belte',
    eng: 'a belt',
    pl: 'pasek',
    ar: 'حزام',
    ger: 'ein Gürtel',
    lt: 'diržas',
    key: '97',
    norEgz: 'Hun kjøpte et nytt belte for å matche skoene.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbelte.mp3?alt=media&token=d8460c4a-2e10-450b-8d76-3f3a1a56296f',
    wordId: 97
  },
  {
    nor: 'en nøkkel',
    eng: 'a key',
    pl: 'klucz',
    ar: 'مفتاح',
    ger: 'ein Schlüssel',
    lt: 'raktas',
    key: '98',
    norEgz: 'Han mistet nøkkelen sin og kunne ikke komme inn.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnookkel.mp3?alt=media&token=423ba0f5-35b7-4ac5-b6d6-ab0c3b1fb206',
    wordId: 98
  },
  {
    nor: 'et bilde',
    eng: 'a picture',
    pl: 'obraz',
    ar: 'صورة',
    ger: 'ein Bild',
    lt: 'nuotrauka',
    key: '99',
    norEgz: 'Hun tok et vakkert bilde av solnedgangen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbilde.mp3?alt=media&token=ae5ba1d4-3036-4118-9b8a-45f01795bc95',
    wordId: 99
  },
  {
    nor: 'en klokke',
    eng: 'a watch',
    pl: 'zegarek',
    ar: 'ساعة',
    ger: 'eine Uhr',
    lt: 'laikrodis',
    key: '100',
    norEgz: 'Han sjekket klokken for å se hvor mye tid som var igjen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklokke.mp3?alt=media&token=67bbfa12-b0c8-49a2-995f-aff52101dbde',
    wordId: 100
  },
  {
    nor: 'et armbånd',
    eng: 'a bracelet',
    pl: 'bransoletka',
    ar: 'سوار',
    ger: 'ein Armband',
    lt: 'apyrankė',
    key: '101',
    norEgz: 'Hun fikk et vakkert armbånd i bursdagsgave.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Farmbaand.mp3?alt=media&token=1849789b-0965-4dd1-8867-727904578216',
    wordId: 101
  },
  {
    nor: 'stygg',
    eng: 'ugly',
    pl: 'brzydki',
    ar: 'قبيح',
    ger: 'hässlich',
    lt: 'bjaurus',
    key: '102',
    norEgz: 'Han synes den gamle bygningen er stygg.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstygg.mp3?alt=media&token=fb0d5b21-2b3d-4864-ae6c-4b570dc23063',
    wordId: 102
  },
  {
    nor: 'ren',
    eng: 'clean',
    pl: 'czysty',
    ar: 'نظيف',
    ger: 'sauber',
    lt: 'švarus',
    key: '103',
    norEgz: 'Hun liker å holde huset sitt rent og ryddig.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fren.mp3?alt=media&token=729d4172-1077-470a-8910-a7b939c08c1c',
    wordId: 103
  },
  {
    nor: 'skitten',
    eng: 'dirty',
    pl: 'brudny',
    ar: 'متسخ',
    ger: 'schmutzig',
    lt: 'nešvarus',
    key: '104',
    norEgz: 'Gulvet var skittent etter festen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskitten.mp3?alt=media&token=f72b81af-bff3-4b6d-bbcf-43ad089a17af',
    wordId: 104
  },
  {
    nor: 'tom',
    eng: 'empty',
    pl: 'pusty',
    ar: 'فارغ',
    ger: 'leer',
    lt: 'tuščias',
    key: '105',
    norEgz: 'Kjøleskapet er tomt, vi må kjøpe mat.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftom.mp3?alt=media&token=d7994027-ab74-46bf-8236-1a03bf19c6e5',
    wordId: 105
  },
  {
    nor: 'full',
    eng: 'full',
    pl: 'pełny',
    ar: 'ممتلئ',
    ger: 'voll',
    lt: 'pilnas',
    key: '106',
    norEgz: 'Bensintanken er full, vi kan kjøre langt.',
    soundLink: '',
    wordId: 106
  },
  {
    nor: 'en fisk',
    eng: 'a fish',
    pl: 'ryba',
    ar: 'سمكة',
    ger: 'ein Fisch',
    lt: 'žuvis',
    key: '107',
    norEgz: 'Han fanget en stor fisk i elven.',
    soundLink: '',
    wordId: 107
  },
  {
    nor: 'en fugl',
    eng: 'a bird',
    pl: 'ptak',
    ar: 'طائر',
    ger: 'ein Vogel',
    lt: 'paukštis',
    key: '108',
    norEgz: 'Fuglen satt på en gren og sang.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffull.mp3?alt=media&token=857adffc-1615-43c2-8250-80ef4aaeb2bc',
    wordId: 108
  },
  {
    nor: 'en park',
    eng: 'a park',
    pl: 'park',
    ar: 'حديقة',
    ger: 'ein Park',
    lt: 'parkas',
    key: '109',
    norEgz: 'Barna lekte i parken hele ettermiddagen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpark.mp3?alt=media&token=5bff62ee-6eca-402c-8169-297973de32c8',
    wordId: 109
  },
  {
    nor: 'en sko',
    eng: 'a shoe',
    pl: 'but',
    ar: 'حذاء',
    ger: 'ein Schuh',
    lt: 'batai',
    key: '110',
    norEgz: 'Hun kjøpte et par nye sko i butikken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsko.mp3?alt=media&token=f0e60576-07a0-4b09-aa69-dd3ed55c6c68',
    wordId: 110
  },
  {
    nor: 'bred',
    eng: 'wide',
    pl: 'szeroki',
    ar: 'عريض',
    ger: 'breit',
    lt: 'platus',
    key: '111',
    norEgz: 'Den brede elven strømmet rolig forbi.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbred.mp3?alt=media&token=2808b841-5b26-4c4c-a900-d0260c6aec0c',
    wordId: 111
  },
  {
    nor: 'god',
    eng: 'good',
    pl: 'dobry',
    ar: 'جيد',
    ger: 'gut',
    lt: 'geras',
    key: '112',
    norEgz: 'Hun er en god venn av meg.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgod.mp3?alt=media&token=d3e2963b-c7e2-4bf0-8c98-aaf6c70f7f7c',
    wordId: 112
  },
  {
    nor: 'dårlig',
    eng: 'bad',
    pl: 'zły',
    ar: 'سيء',
    ger: 'schlecht',
    lt: 'blogas',
    key: '113',
    norEgz: 'Været var dårlig i dag.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdaarlig.mp3?alt=media&token=6384f043-1fd0-4823-91ab-485fe7590879',
    wordId: 113
  },
  {
    nor: 'et tog',
    eng: 'a train',
    pl: 'pociąg',
    ar: 'قطار',
    ger: 'ein Zug',
    lt: 'traukinys',
    key: '114',
    norEgz: 'Vi tok toget til byen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftog.mp3?alt=media&token=c5c2a835-5bda-41f2-b538-ff9b9e81863a',
    wordId: 114
  },
  {
    nor: 'et fly',
    eng: 'a plane',
    pl: 'samolot',
    ar: 'طائرة',
    ger: 'ein Flugzeug',
    lt: 'lėktuvas',
    key: '115',
    norEgz: 'Hun reiste med fly til London.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffly.mp3?alt=media&token=cf5367d8-d071-46d2-9bbd-589b44327020',
    wordId: 115
  },
  {
    nor: 'hard',
    eng: 'hard',
    pl: 'twardy',
    ar: 'صعب',
    ger: 'hart',
    lt: 'kietas',
    key: '116',
    norEgz: 'Gulvet var hardt og kaldt.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhard.mp3?alt=media&token=e43007fe-4a67-4843-8739-4e7c69909399',
    wordId: 116
  },
  {
    nor: 'myk',
    eng: 'soft',
    pl: 'miękki',
    ar: 'ناعم',
    ger: 'weich',
    lt: 'minkštas',
    key: '117',
    norEgz: 'Putene var myke og behagelige.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmyk.mp3?alt=media&token=3da3970c-2146-45c1-8bf4-8d884dd0c972',
    wordId: 117
  },
  {
    nor: 'lys',
    eng: 'light',
    pl: 'jasny',
    ar: 'خفيف',
    ger: 'hell',
    lt: 'šviesus',
    key: '118',
    norEgz: 'Rommene var lyse og luftige.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flys.mp3?alt=media&token=2c8cb979-e7ed-41ed-a6fb-d2d27ee7765a',
    wordId: 118
  },
  {
    nor: 'mørk',
    eng: 'dark',
    pl: 'ciemny',
    ar: 'مظلم',
    ger: 'dunkel',
    lt: 'tamsus',
    key: '119',
    norEgz: 'Det blir mørkt tidlig om vinteren.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmoork.mp3?alt=media&token=f6b757a9-e8c6-412d-90dd-d09a53574b7d',
    wordId: 119
  },
  {
    nor: 'en mobiltelefon',
    eng: 'a mobile phone',
    pl: 'telefon komórkowy',
    ar: 'هاتف محمول',
    ger: 'ein Mobiltelefon',
    lt: 'mobilusis telefonas',
    key: '120',
    norEgz: 'Han mistet mobiltelefonen sin i går',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmobiltelefon.mp3?alt=media&token=0801578c-dc8a-48aa-9afe-aaf6343423f2',
    wordId: 120
  },
  {
    nor: 'et nettbrett',
    eng: 'a tablet',
    pl: 'tablet',
    ar: 'جهاز لوحي',
    ger: 'ein Tablet',
    lt: 'planšetė',
    key: '121',
    norEgz: 'Hun bruker nettbrettet til å lese e-bøker.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnettbrett.mp3?alt=media&token=a311c65c-9b6b-4843-a72d-6fcc7dc86d05',
    wordId: 121
  },
  {
    nor: 'en øyeblikk',
    eng: 'a moment',
    pl: 'chwila',
    ar: 'لحظة',
    ger: 'ein Moment',
    lt: 'akimirka',
    key: '122',
    norEgz: 'Vent et øyeblikk, vær så snill.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fooyeblikk.mp3?alt=media&token=447599d6-9758-441f-b50b-c596873b9e4f',
    wordId: 122
  },
  {
    nor: 'en film',
    eng: 'a movie',
    pl: 'film',
    ar: 'فيلم',
    ger: 'ein Film',
    lt: 'filmas',
    key: '123',
    norEgz: 'Vi så en spennende film i går kveld.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffilm.mp3?alt=media&token=4fe25c9f-25fc-4710-aca5-b780587d83aa',
    wordId: 123
  },
  {
    nor: 'bitter',
    eng: 'bitter',
    pl: 'gorzki',
    ar: 'مُر',
    ger: 'bitter',
    lt: 'kartus',
    key: '124',
    norEgz: 'Grapefrukt kan smake litt bittert.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbitter.mp3?alt=media&token=61295c76-0933-447c-a6f5-f62f676fa92b',
    wordId: 124
  },
  {
    nor: 'skarp',
    eng: 'sharp',
    pl: 'ostry',
    ar: 'حاد',
    ger: 'scharf',
    lt: 'aštrus',
    key: '125',
    norEgz: 'Kniven var skarp og kuttet lett gjennom papiret.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskarp.mp3?alt=media&token=0a5fffae-eecc-4e7c-bea6-0d830d80853a',
    wordId: 125
  },
  {
    nor: 'å være',
    eng: 'to be',
    pl: 'być',
    ar: 'كان',
    ger: 'sein',
    lt: 'būti',
    key: '126',
    norEgz: 'Det er viktig å være tålmodig.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fveere.mp3?alt=media&token=4ad4cd0a-4321-40e3-a422-76f2e2b7efb4',
    wordId: 126
  },
  {
    nor: 'å ha',
    eng: 'to have',
    pl: 'mieć',
    ar: 'يملك',
    ger: 'haben',
    lt: 'turėti',
    key: '127',
    norEgz: 'Hun har en ny bil.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fha.mp3?alt=media&token=6fe73f1e-6074-4c0c-ad9b-655a3c8fac70',
    wordId: 127
  },
  {
    nor: 'sint',
    eng: 'angry',
    pl: 'zły',
    ar: 'غاضب',
    ger: 'wütend',
    lt: 'piktas',
    key: '128',
    norEgz: 'Han ble sint da han mistet nøklene sine.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsint.mp3?alt=media&token=6847d24a-292b-4ecd-8f9f-f995aa0c1ac6',
    wordId: 128
  },
  {
    nor: 'rolig',
    eng: 'calm',
    pl: 'spokojny',
    ar: 'هادئ',
    ger: 'ruhig',
    lt: 'ramus',
    key: '129',
    norEgz: 'Han er rolig',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frolig.mp3?alt=media&token=a14a1b95-98f2-406d-83df-cf795bca8a1c',
    wordId: 129
  },
  {
    nor: 'billig',
    eng: 'cheap',
    pl: 'tani',
    ar: 'رخيص',
    ger: 'billig',
    lt: 'pigus',
    key: '130',
    norEgz: 'Denne skjorten var veldig billig.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbillig.mp3?alt=media&token=4f8384fd-6ed1-4b8b-98fb-b564fc990993',
    wordId: 130
  },
  {
    nor: 'å jobbe',
    eng: 'to work',
    pl: 'pracować',
    ar: 'يعمل',
    ger: 'arbeiten',
    lt: 'dirbti',
    key: '131',
    norEgz: 'Hun jobber som lærer.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjobbe.mp3?alt=media&token=ab2880a4-698c-4e45-a2ba-a3177a5a52a0',
    wordId: 131
  },
  {
    nor: 'å snakke',
    eng: 'to talk',
    pl: 'rozmawiać',
    ar: 'يتحدث',
    ger: 'sprechen',
    lt: 'kalbėti',
    key: '132',
    norEgz: 'Vi snakket sammen i flere timer.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsnakke.mp3?alt=media&token=f782e4b1-e87c-47a6-a3bc-574315421a2a',
    wordId: 132
  },
  {
    nor: 'en øy',
    eng: 'an island',
    pl: 'wyspa',
    ar: 'جزيرة',
    ger: 'eine Insel',
    lt: 'sala',
    key: '133',
    norEgz: 'De tilbrakte ferien på en liten øy.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fooy.mp3?alt=media&token=f5529a4c-31bf-4265-ba5c-e9eff5f538b8',
    wordId: 133
  },
  {
    nor: 'en elv',
    eng: 'a river',
    pl: 'rzeka',
    ar: 'نهر',
    ger: 'ein Fluss',
    lt: 'upė',
    key: '134',
    norEgz: 'De padlet nedover elven i kano.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felv.mp3?alt=media&token=addbfe5e-741d-4ce3-8254-c0d249a63e94',
    wordId: 134
  },
  {
    nor: 'et hav',
    eng: 'a sea',
    pl: 'morze',
    ar: 'بحر',
    ger: 'ein Meer',
    lt: 'jūra',
    key: '135',
    norEgz: 'Havet var rolig og vakkert.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhav.mp3?alt=media&token=97566159-0e84-4a68-8cd8-b650a5b2e3c7',
    wordId: 135
  },
  {
    nor: 'trist',
    eng: 'sad',
    pl: 'smutny',
    ar: 'حزين',
    ger: 'traurig',
    lt: 'liūdnas',
    key: '136',
    norEgz: 'Han følte seg trist etter å ha sagt farvel.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftrist.mp3?alt=media&token=5a6bfb0b-a7c7-42f6-8af5-456475c8dec0',
    wordId: 136
  },
  {
    nor: 'en innsjø',
    eng: 'a lake',
    pl: 'jezioro',
    ar: 'بحيرة',
    ger: 'ein See',
    lt: 'ežeras',
    key: '137',
    norEgz: 'De hadde en piknik ved innsjøen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finnsjoo.mp3?alt=media&token=afef4c5a-b44e-4fa4-8d49-04228e514a06',
    wordId: 137
  },
  {
    nor: 'en skog',
    eng: 'a forest',
    pl: 'las',
    ar: 'غابة',
    ger: 'ein Wald',
    lt: 'miškas',
    key: '138',
    norEgz: 'De gikk på tur i skogen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskog.mp3?alt=media&token=de379fd4-4115-4afc-9367-2d2dacc1cf83',
    wordId: 138
  },
  {
    nor: 'å gjøre',
    eng: 'to do',
    pl: 'robić',
    ar: 'يفعل',
    ger: 'tun',
    lt: 'daryti',
    key: '139',
    norEgz: 'Hva skal vi gjøre i helgen?',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgjoore.mp3?alt=media&token=2f6950bb-a431-4afe-9f84-2958da541b43',
    wordId: 139
  },
  {
    nor: 'å si',
    eng: 'to say',
    pl: 'mówić',
    ar: 'يقول',
    ger: 'sagen',
    lt: 'sakyti',
    key: '140',
    norEgz: 'Hun sa at hun ville komme.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsi.mp3?alt=media&token=54d7c707-7615-47e3-ba3f-5ddab6daf7f8',
    wordId: 140
  },
  {
    nor: 'å gå',
    eng: 'to go',
    pl: 'iść',
    ar: 'يذهب',
    ger: 'gehen',
    lt: 'eiti',
    key: '141',
    norEgz: 'Han gikk til butikken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgaa.mp3?alt=media&token=fba1a90c-60ac-4d0e-a729-97db3c7a1f3b',
    wordId: 141
  },
  {
    nor: 'en dal',
    eng: 'a valley',
    pl: 'dolina',
    ar: 'وادي',
    ger: 'ein Tal',
    lt: 'slėnis',
    key: '142',
    norEgz: 'De vandret gjennom dalen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdal.mp3?alt=media&token=06d4fab4-101f-4a20-b71d-21a8cef54379',
    wordId: 142
  },
  {
    nor: 'en butikk',
    eng: 'a store',
    pl: 'sklep',
    ar: 'متجر',
    ger: 'ein Geschäft',
    lt: 'parduotuvė',
    key: '143',
    norEgz: 'Han kjøpte klær i butikken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbutikk.mp3?alt=media&token=876e75f1-f5a2-40c2-a7f0-c6325f4c2d05',
    wordId: 143
  },
  {
    nor: 'en restaurant',
    eng: 'a restaurant',
    pl: 'restauracja',
    ar: 'مطعم',
    ger: 'ein Restaurant',
    lt: 'restoranas',
    key: '144',
    norEgz: 'De spiste middag på en restaurant.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frestaurant.mp3?alt=media&token=24010f8a-8f63-4344-948f-a3d9b5d582a4',
    wordId: 144
  },
  {
    nor: 'et sykehus',
    eng: 'a hospital',
    pl: 'szpital',
    ar: 'مستشفى',
    ger: 'ein Krankenhaus',
    lt: 'ligoninė',
    key: '145',
    norEgz: 'Han ble kjørt til sykehuset etter ulykken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykehus.mp3?alt=media&token=dcbf2629-08e6-4181-ad13-9e3a3b2e3086',
    wordId: 145
  },
  {
    nor: 'å drikke',
    eng: 'to drink',
    pl: 'pić',
    ar: 'يشرب',
    ger: 'trinken',
    lt: 'gerti',
    key: '146',
    norEgz: 'Han drakk et glass vann.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdrikke.mp3?alt=media&token=63e8e0d2-c805-48e3-95ff-bb4b58d67d2b',
    wordId: 146
  },
  {
    nor: 'en brannstasjon',
    eng: 'a fire station',
    pl: 'straż pożarna',
    ar: 'محطة الإطفاء',
    ger: 'eine Feuerwache',
    lt: 'gaisrinė',
    key: '147',
    norEgz: 'Brannstasjonen ligger i nærheten av parken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbrannstasjon.mp3?alt=media&token=b744063e-2dde-4a7e-b217-1542389248d6',
    wordId: 147
  },
  {
    nor: 'en politistasjon',
    eng: 'a police station',
    pl: 'komisariat policji',
    ar: 'مركز شرطة',
    ger: 'eine Polizeistation',
    lt: 'policijos nuovada',
    key: '148',
    norEgz: 'Politistasjonen ligger ved siden av rådhuset.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpolitistasjon.mp3?alt=media&token=02f571c3-0401-45fc-a01f-9dd43f0cfe7f',
    wordId: 148
  },
  {
    nor: 'et bibliotek',
    eng: 'a library',
    pl: 'biblioteka',
    ar: 'مكتبة',
    ger: 'eine Bibliothek',
    lt: 'biblioteka',
    key: '149',
    norEgz: 'Han lånte en bok fra biblioteket.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbibliotek.mp3?alt=media&token=d49d6028-fd94-49c9-8b51-b9f522ef7076',
    wordId: 149
  },
  {
    nor: 'en bank',
    eng: 'a bank',
    pl: 'bank',
    ar: 'بنك',
    ger: 'eine Bank',
    lt: 'bankas',
    key: '150',
    norEgz: 'Hun gikk til banken for å ta ut penger.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbank.mp3?alt=media&token=1abca584-a8a4-40d1-90a7-b7743e3b2a30',
    wordId: 150
  },
  {
    nor: 'en kirke',
    eng: 'a church',
    pl: 'kościół',
    ar: 'كنيسة',
    ger: 'eine Kirche',
    lt: 'bažnyčia',
    key: '151',
    norEgz: 'Familien gikk til kirken hver søndag.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkirke.mp3?alt=media&token=eaae606f-9a2c-4e42-bf8a-78101c452a2d',
    wordId: 151
  },
  {
    nor: 'å lese',
    eng: 'to read',
    pl: 'czytać',
    ar: 'يقرأ',
    ger: 'lesen',
    lt: 'skaityti',
    key: '152',
    norEgz: 'Hun liker å lese bøker om historie.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flese.mp3?alt=media&token=dfd0822b-364a-45c6-aa78-7e4ec2dd6546',
    wordId: 152
  },
  {
    nor: 'å skrive',
    eng: 'to write',
    pl: 'pisać',
    ar: 'يكتب',
    ger: 'schreiben',
    lt: 'rašyti',
    key: '153',
    norEgz: 'Han skriver en e-post til sin venn.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskrive.mp3?alt=media&token=086fbd16-cfa1-4e37-ace8-e5f9ae263f4e',
    wordId: 153
  },
  {
    nor: 'å sove',
    eng: 'to sleep',
    pl: 'spać',
    ar: 'ينام',
    ger: 'schlafen',
    lt: 'miegoti',
    key: '154',
    norEgz: 'Han pleier å sove tidlig om natten.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsove.mp3?alt=media&token=820919d1-9a40-4cd7-b0b3-98cd5120c75f',
    wordId: 154
  },
  {
    nor: 'en blyant',
    eng: 'a pencil',
    pl: 'ołówek',
    ar: 'قلم رصاص',
    ger: 'ein Bleistift',
    lt: 'pieštukas',
    key: '155',
    norEgz: 'Hun tegner med en blyant.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblyant.mp3?alt=media&token=9c4e80df-737e-40f3-bdcb-f0ea438c87a1',
    wordId: 155
  },
  {
    nor: 'et viskelær',
    eng: 'an eraser',
    pl: 'gumka do ścierania',
    ar: 'ممحاة',
    ger: 'ein Radiergummi',
    lt: 'trintukas',
    key: '156',
    norEgz: 'Han brukte et viskelær for å fjerne feilen.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fviskeleer.mp3?alt=media&token=e37a25a4-9061-4363-8073-2cd2aaaf7168',
    wordId: 156
  },
  {
    nor: 'en penn',
    eng: 'a pen',
    pl: 'długopis',
    ar: 'قلم',
    ger: 'ein Stift',
    lt: 'rašiklis',
    key: '157',
    norEgz: 'Hun skrev et brev med en penn.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpenn.mp3?alt=media&token=f24e9bc5-e4b9-411b-b0cd-22fabc97b267',
    wordId: 157
  },
  {
    nor: 'en notatbok',
    eng: 'a notebook',
    pl: 'notes',
    ar: 'دفتر الملاحظات',
    ger: 'ein Notizbuch',
    lt: 'užrašų knyga',
    key: '158',
    norEgz: 'Hun skriver i en notatbok hver dag.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnotatbok.mp3?alt=media&token=aba446aa-3845-4db4-949b-213994d42a2f',
    wordId: 158
  },
  {
    nor: 'glad',
    eng: 'happy',
    pl: 'szczęśliwy',
    ar: 'سعيد',
    ger: 'glücklich',
    lt: 'laimingas',
    key: '159',
    norEgz: 'Han er veldig glad i dag.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fglad.mp3?alt=media&token=21b38b88-e818-49a6-ba0b-d67b4c5323d9',
    wordId: 159
  },
  {
    nor: 'dyr',
    eng: 'expensive',
    pl: 'drogi',
    ar: 'غالي',
    ger: 'teuer',
    lt: 'brangus',
    key: '160',
    norEgz: 'Denne bilen er veldig dyr.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdyr.mp3?alt=media&token=9c301d17-5154-4bab-b30d-bbdae0bff368',
    wordId: 160
  },
  {
    nor: 'søt',
    eng: 'cute',
    pl: 'słodki',
    ar: 'جميل',
    ger: 'niedlich',
    lt: 'mielas',
    key: '161',
    norEgz: 'Hun har en søt liten hund.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsoot.mp3?alt=media&token=67e889bf-cd89-47a8-ad22-9aa7c1fd82ba',
    wordId: 161
  },
  {
    nor: 'sur',
    eng: 'sour',
    pl: 'kwaśny',
    ar: 'حامض',
    ger: 'sauer',
    lt: 'rūgštus',
    key: '162',
    norEgz: 'Sitroner er sure.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsur.mp3?alt=media&token=1940bece-a88c-4047-b5bb-ae35fbbaf633',
    wordId: 162
  },
  {
    nor: 'salt',
    eng: 'salty',
    pl: 'słony',
    ar: 'مالح',
    ger: 'salzig',
    lt: 'sūrus',
    key: '163',
    norEgz: 'Potetgull er salt.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsalt.mp3?alt=media&token=2fb9021e-5320-4193-a5f8-de0e972d904e',
    wordId: 163
  },
  {
    nor: 'en ryggsekk',
    eng: 'a backpack',
    pl: 'plecak',
    ar: 'حقيبة ظهر',
    ger: 'ein Rucksack',
    lt: 'kuprinė',
    key: '164',
    norEgz: 'Han har en tung ryggsekk.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fryggsekk.mp3?alt=media&token=121fc373-5874-4079-84a6-8c04f1ae981e',
    wordId: 164
  },
  {
    nor: 'en plate',
    eng: 'a plate',
    pl: 'talerz',
    ar: 'صحن',
    ger: 'ein Teller',
    lt: 'lėkštė',
    key: '165',
    norEgz: 'Hun serverte maten på en plate.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fplate.mp3?alt=media&token=cc29c5cc-5d78-4488-b469-16166b87df87',
    wordId: 165
  },
  {
    nor: 'et kamera',
    eng: 'a camera',
    pl: 'aparat fotograficzny',
    ar: 'كاميرا',
    ger: 'eine Kamera',
    lt: 'fotoaparatas',
    key: '166',
    norEgz: 'Han tar bilde med kamera.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkamera.mp3?alt=media&token=2a185902-7054-4c38-a65c-b4d759a16114',
    wordId: 166
  },
  {
    nor: 'en datamaskin',
    eng: 'a computer',
    pl: 'komputer',
    ar: 'كمبيوتر',
    ger: 'ein Computer',
    lt: 'kompiuteris',
    key: '167',
    norEgz: 'Han kjøpte en ny datamaskin.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdatamaskin.mp3?alt=media&token=7d82bfe6-4c71-4ea3-8c09-9b248dadcae0',
    wordId: 167
  },
  {
    nor: 'en mus',
    eng: 'a mouse',
    pl: 'mysz',
    ar: 'فأر',
    ger: 'eine Maus',
    lt: 'pelė',
    key: '168',
    norEgz: 'Han bruker en trådløs mus.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmus.mp3?alt=media&token=54c7751d-e3ea-4bfe-9bd6-418424172cf0',
    wordId: 168
  },
  {
    nor: 'en skjerm',
    eng: 'a monitor',
    pl: 'monitor',
    ar: 'شاشة',
    ger: 'ein Monitor',
    lt: 'monitorius',
    key: '169',
    norEgz: 'Hun har en stor skjerm på kontoret.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjerm.mp3?alt=media&token=b5be5282-a051-43c8-8cbb-04d577086cc8',
    wordId: 169
  },
  {
    nor: 'å spille',
    eng: 'to play',
    pl: 'grać',
    ar: 'يلعب',
    ger: 'spielen',
    lt: 'žaisti',
    key: '170',
    norEgz: 'Barna liker å spille fotball.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspille.mp3?alt=media&token=c8412b2d-36d5-49e5-bfac-507e9bf923b3',
    wordId: 170
  },
  {
    nor: 'en skriver',
    eng: 'a printer',
    pl: 'drukarka',
    ar: 'طابعة',
    ger: 'ein Drucker',
    lt: 'spausdintuvas',
    key: '171',
    norEgz: 'Hun trenger en ny skriver.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskriver.mp3?alt=media&token=a55f6d91-50ab-4d39-82f6-0a70c2b2a33d',
    wordId: 171
  },
  {
    nor: 'et tastatur',
    eng: 'a keyboard',
    pl: 'klawiatura',
    ar: 'لوحة المفاتيح',
    ger: 'eine Tastatur',
    lt: 'klaviatūra',
    key: '172',
    norEgz: 'Han kjøpte et mekanisk tastatur.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftastatur.mp3?alt=media&token=1f3a0524-0107-49c0-94b8-330b61d8e773',
    wordId: 172
  },
  {
    nor: 'smal',
    eng: 'narrow',
    pl: 'wąski',
    ar: 'ضيق',
    ger: 'schmal',
    lt: 'siauras',
    key: '173',
    norEgz: 'Veien er veldig smal.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmal.mp3?alt=media&token=1b09749e-5d4a-4971-8c1f-a00746c637e1',
    wordId: 173
  }
]
     





// add betale
