[
    {
      nor: 'å spørre',
      eng: 'to ask',
      pl: 'pytać',
      ar: 'يسأل',
      ger: 'fragen',
      lt: 'klausti',
      key: '0',
      norEgz: 'Han spurte hvor bussen går.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspoorre.mp3?alt=media&token=9425af20-3a4e-4a9c-97a3-8307a4477aa3',
      wordId: 0
    },
    {
      nor: 'å svare',
      eng: 'to answer',
      pl: 'odpowiadać',
      ar: 'يجيب',
      ger: 'antworten',
      lt: 'atsakyti',
      key: '1',
      norEgz: 'Hun svarte raskt på spørsmålet.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvare.mp3?alt=media&token=4f2c7adc-3be2-4efa-afd8-ded0149a5a7a',
      wordId: 1
    },
    {
      nor: 'å åpne',
      eng: 'to open',
      pl: 'otwierać',
      ar: 'يفتح',
      ger: 'öffnen',
      lt: 'atidaryti',
      key: '2',
      norEgz: 'Kan du åpne vinduet?',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faapne.mp3?alt=media&token=e4c7c91d-1e98-4d7a-9dbc-39de78fb11e5',
      wordId: 2
    },
    {
      nor: 'en tegning',
      eng: 'a drawing',
      pl: 'rysunek',
      ar: 'رسم',
      ger: 'eine Zeichnung',
      lt: 'piešinys',
      key: '3',
      norEgz: 'Hun laget en flott tegning.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftegning.mp3?alt=media&token=6189a861-b4d4-4da4-a613-5999ef5151f0',
      wordId: 3
    },
    {
      nor: 'en maling',
      eng: 'a painting',
      pl: 'obraz',
      ar: 'لوحة',
      ger: 'ein Gemälde',
      lt: 'tapyba',
      key: '4',
      norEgz: 'Dette er en vakker maling.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaling.mp3?alt=media&token=f8c690be-a208-4a00-889e-287c2ad808ad',
      wordId: 4
    },
    {
      nor: 'en matlaging',
      eng: 'cooking',
      pl: 'gotowanie',
      ar: 'طبخ',
      ger: 'Kochen',
      lt: 'virtuvė',
      key: '5',
      norEgz: 'Hun liker matlaging etter jobb.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmatlaging.mp3?alt=media&token=ac8f0968-c5c5-415f-a607-6d33d89bcb8e',
      wordId: 5
    },
    {
      nor: 'å lukke',
      eng: 'to close',
      pl: 'zamykać',
      ar: 'يغلق',
      ger: 'schließen',
      lt: 'uždaryti',
      key: '6',
      norEgz: 'Husk å lukke døren.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flukke.mp3?alt=media&token=ed1851f9-8f52-4342-a6aa-ee5bfe6cdc25',
      wordId: 6
    },
    {
      nor: 'å gi',
      eng: 'to give',
      pl: 'dawać',
      ar: 'يعطي',
      ger: 'geben',
      lt: 'duoti',
      key: '7',
      norEgz: 'Han ga henne en gave.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgi.mp3?alt=media&token=11c6e157-1ddc-4e96-b3a0-b4328154a84f',
      wordId: 7
    },
    {
      nor: 'å ta',
      eng: 'to take',
      pl: 'brać',
      ar: 'يأخذ',
      ger: 'nehmen',
      lt: 'imti',
      key: '8',
      norEgz: 'Han tar bok fra hylla.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fta.mp3?alt=media&token=7bbe88a2-8c70-43a6-b709-b60e25556b57',
      wordId: 8
    },
    {
        nor: 'interessant',
        eng: 'interesting',
        pl: 'interesujący',
        ar: 'مثير للاهتمام',
        ger: 'interessant',
        lt: 'įdomus',
        key: '9',
        norEgz: 'Det var en interessant bok.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finteressant.mp3?alt=media&token=afe4910d-3530-402e-ab77-df7e3d7d6cc6',
        wordId: 9
      },
      {
        nor: 'kjedelig',
        eng: 'boring',
        pl: 'nudny',
        ar: 'ممل',
        ger: 'langweilig',
        lt: 'nuobodus',
        key: '10',
        norEgz: 'Denne filmen er kjedelig.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjedelig.mp3?alt=media&token=b04f6436-d011-47b5-9962-449fdb0276e8',
        wordId: 10
      },
      {
        nor: 'å forstå',
        eng: 'to understand',
        pl: 'rozumieć',
        ar: 'يفهم',
        ger: 'verstehen',
        lt: 'suprasti',
        key: '11',
        norEgz: 'Jeg forstår ikke hva du sier.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforstaa.mp3?alt=media&token=df6f43cc-ad2d-41b5-96f4-ec448dd367cd',
        wordId: 11
      },
      {
        nor: 'å øve',
        eng: 'to practice',
        pl: 'ćwiczyć',
        ar: 'يمارس',
        ger: 'üben',
        lt: 'praktikuotis',
        key: '12',
        norEgz: 'Vi må øve før konserten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foove.mp3?alt=media&token=33df2ade-a7b6-42d0-97c1-81bb5d7c1b15',
        wordId: 12
      },
      {
        nor: 'internasjonal',
        eng: 'international',
        pl: 'międzynarodowy',
        ar: 'دولي',
        ger: 'international',
        lt: 'tarptautinis',
        key: '13',
        norEgz: 'Dette er en internasjonal konferanse.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finternasjonal.mp3?alt=media&token=ef8ef7b5-030a-4e91-8338-5f18d4ef3853',
        wordId: 13
      },
      {
        nor: 'komfortabel',
        eng: 'comfortable',
        pl: 'wygodny',
        ar: 'مريح',
        ger: 'bequem',
        lt: 'patogus',
        key: '14',
        norEgz: 'Denne stolen er komfortabel.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkomfortabel.mp3?alt=media&token=9a81ef80-e8fe-485b-9b27-b3534aeaa46a',
        wordId: 14
      },
      {
        nor: 'kjapp',
        eng: 'quick',
        pl: 'szybki',
        ar: 'سريع',
        ger: 'schnell',
        lt: 'greitas',
        key: '15',
        norEgz: 'Han er kjapp til å løse problemer.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjapp.mp3?alt=media&token=f7ffa9e8-9f48-4f77-ac6f-d62401df4ba0',
        wordId: 15
      },
      {
        nor: 'en vinter',
        eng: 'a winter',
        pl: 'zima',
        ar: 'شتاء',
        ger: 'ein Winter',
        lt: 'žiema',
        key: '16',
        norEgz: 'Det snør om vinteren.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvinter.mp3?alt=media&token=b50b1f6e-6fe8-4948-962b-5bdb3ebce6de',
        wordId: 16
      },
      {
        nor: 'en vår',
        eng: 'a spring',
        pl: 'wiosna',
        ar: 'ربيع',
        ger: 'ein Frühling',
        lt: 'pavasaris',
        key: '17',
        norEgz: 'Våren er min favoritt årstid.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaar.mp3?alt=media&token=7ebdbddf-eac2-4ca8-b83a-c969224d8f0b',
        wordId: 17
      },
      {
        nor: 'en sommer',
        eng: 'a summer',
        pl: 'lato',
        ar: 'صيف',
        ger: 'ein Sommer',
        lt: 'vasara',
        key: '18',
        norEgz: 'Sommerværet er varmt og solrikt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsommer.mp3?alt=media&token=7bfe5ef7-1580-49b0-afd7-11495c61adb3',
        wordId: 18
      },
      {
        nor: 'å planlegge',
        eng: 'to plan',
        pl: 'planować',
        ar: 'يخطط',
        ger: 'planen',
        lt: 'planuoti',
        key: '19',
        norEgz: 'Vi må planlegge ferien vår.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fplanlegge.mp3?alt=media&token=3d4d3dc9-576c-4705-b76e-757ac23fb50c',
        wordId: 19
      },
      {
        nor: 'å hilse',
        eng: 'to greet',
        pl: 'witać',
        ar: 'يحيي',
        ger: 'grüßen',
        lt: 'sveikintis',
        key: '20',
        norEgz: 'Hun hilste på naboene sine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhilse.mp3?alt=media&token=ab43a3af-a1e3-4b4c-9af7-c16b23affe2a',
        wordId: 20
      },
      {
        nor: 'en utdanning',
        eng: 'an education',
        pl: 'edukacja',
        ar: 'تعليم',
        ger: 'eine Bildung',
        lt: 'švietimas',
        key: '21',
        norEgz: 'Utdanning er viktig for fremtiden.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futdanning.mp3?alt=media&token=f09fd3fb-0fff-47d9-9cae-53332ed0297d',
        wordId: 21
      },
      {
        nor: 'en karakter',
        eng: 'a character',
        pl: 'postać',
        ar: 'شخصية',
        ger: 'eine Figur',
        lt: 'personažas',
        key: '22',
        norEgz: 'Han er en interessant karakter i boken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkarakter.mp3?alt=media&token=b9d2b16b-9d96-4015-abed-bc64b11f6ed9',
        wordId: 22
      },
      {
        nor: 'en elg',
        eng: 'a moose',
        pl: 'łoś',
        ar: 'موظ',
        ger: 'ein Elch',
        lt: 'briedis',
        key: '23',
        norEgz: 'Vi så en elg i skogen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felg.mp3?alt=media&token=0a9e420c-07b2-420a-8d8e-bc58fbffecad',
        wordId: 23
      },
      {
        nor: 'et brev',
        eng: 'a letter',
        pl: 'list',
        ar: 'خطاب',
        ger: 'ein Brief',
        lt: 'laiškas',
        key: '24',
        norEgz: 'Jeg fikk et brev i posten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbrev.mp3?alt=media&token=00cf842f-99ad-4383-a0e2-6a3ee46e7eb3',
        wordId: 24
      },
      {
        nor: 'enkel',
        eng: 'simple',
        pl: 'prosty',
        ar: 'بسيط',
        ger: 'einfach',
        lt: 'paprastas',
        key: '25',
        norEgz: 'Dette er en enkel oppgave.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fenkel.mp3?alt=media&token=6f3fe33e-415a-4e50-8c79-ef283889ba45',
        wordId: 25
      },
      {
        nor: 'komplisert',
        eng: 'complicated',
        pl: 'skomplikowany',
        ar: 'معقد',
        ger: 'kompliziert',
        lt: 'sudėtingas',
        key: '26',
        norEgz: 'Matematikk er komplisert.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkomplisert.mp3?alt=media&token=e0ef4856-a90f-41e8-8023-db5b0170d640',
        wordId: 26
      },
      {
        nor: 'viktig',
        eng: 'important',
        pl: 'ważny',
        ar: 'مهم',
        ger: 'wichtig',
        lt: 'svarbus',
        key: '27',
        norEgz: 'Det er viktig å spise sunt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fviktig.mp3?alt=media&token=73cfed23-93d6-4a11-a890-d039021206ef',
        wordId: 27
      },
      {
        nor: 'å legge seg',
        eng: 'to go to bed',
        pl: 'kłaść się spać',
        ar: 'الذهاب إلى الفراش',
        ger: 'ins Bett gehen',
        lt: 'eiti miegoti',
        key: '28',
        norEgz: 'Hun legger seg tidlig hver kveld.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleggeseg.mp3?alt=media&token=3a4e6e34-4347-4a63-9954-2b197cd9832d',
        wordId: 28
      },
      {
        nor: 'å prøve',
        eng: 'to try',
        pl: 'próbować',
        ar: 'يجرب',
        ger: 'versuchen',
        lt: 'bandyti',
        key: '29',
        norEgz: 'Jeg vil prøve denne kaken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fproove.mp3?alt=media&token=f80d8d1f-c43c-4a7e-a32f-0d03f33e0829',
        wordId: 29
      },
      {
        nor: 'tynn',
        eng: 'thin',
        pl: 'chudy',
        ar: 'رفيع',
        ger: 'dünn',
        lt: 'plonas',
        key: '30',
        norEgz: 'Dette teppet er veldig tynn.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftynn.mp3?alt=media&token=edb31027-f943-47b5-8205-333b210ed58f',
        wordId: 30
      },
      {
        nor: 'høflig',
        eng: 'polite',
        pl: 'uprzejmy',
        ar: 'مهذب',
        ger: 'höflich',
        lt: 'mandagus',
        key: '31',
        norEgz: 'Han er alltid høflig mot andre.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhooflig.mp3?alt=media&token=899d0953-da67-4c48-ad7b-22c951bd6b94',
        wordId: 31
      },
      {
        nor: 'uhøflig',
        eng: 'rude',
        pl: 'niegrzeczny',
        ar: 'غير مهذب',
        ger: 'unhöflich',
        lt: 'nemandagus',
        key: '32',
        norEgz: 'Det er uhøflig å avbryte andre.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fuhooflig.mp3?alt=media&token=84b53e9b-5843-4c6e-9e32-f45b9763eb60',
        wordId: 32
      },
      {
        nor: 'effektiv',
        eng: 'efficient',
        pl: 'wydajny',
        ar: 'فعّال',
        ger: 'effizient',
        lt: 'efektyvus',
        key: '33',
        norEgz: 'Denne metoden er veldig effektiv.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feffektiv.mp3?alt=media&token=8effd340-13ca-4640-8041-bf9d495839e8',
        wordId: 33
      },
      {
        nor: 'en krukke',
        eng: 'a jar',
        pl: 'słoik',
        ar: 'جرة',
        ger: 'ein Glas',
        lt: 'indelis',
        key: '34',
        norEgz: 'Hun oppbevarer honning i en krukke.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkrukke.mp3?alt=media&token=14482db3-ad89-462f-b637-fc009d0f4fcf',
        wordId: 34
      },
      {
        nor: 'en bensinstasjon',
        eng: 'a gas station',
        pl: 'stacja benzynowa',
        ar: 'محطة وقود',
        ger: 'eine Tankstelle',
        lt: 'degalinė',
        key: '35',
        norEgz: 'Vi må stoppe ved en bensinstasjon.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbensinstasjon.mp3?alt=media&token=4b129f39-f17d-42f4-8efc-3f00119b885c',
        wordId: 35
      },
      {
        nor: 'en fabrikk',
        eng: 'a factory',
        pl: 'fabryka',
        ar: 'مصنع',
        ger: 'eine Fabrik',
        lt: 'fabrikas',
        key: '36',
        norEgz: 'Han jobber i en fabrikk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffabrikk.mp3?alt=media&token=e0d536f4-ba0c-4e57-911b-54544a063446',
        wordId: 36
      },
      {
        nor: 'et bakeri',
        eng: 'a bakery',
        pl: 'piekarnia',
        ar: 'مخبز',
        ger: 'eine Bäckerei',
        lt: 'kepykla',
        key: '37',
        norEgz: 'De kjøper brød fra et bakeri.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbakeri.mp3?alt=media&token=f298c058-5b84-44d8-b8cc-2a0403b2cd78',
        wordId: 37
      },
      {
        nor: 'en frisør',
        eng: 'a hairdresser',
        pl: 'fryzjer',
        ar: 'مصفف شعر',
        ger: 'ein Friseur',
        lt: 'kirpėjas',
        key: '38',
        norEgz: 'Jeg har time hos en frisør i morgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrisoor.mp3?alt=media&token=7e9c74e7-b260-4941-b7c6-645c957d1860',
        wordId: 38
      },
      {
        nor: 'å huske',
        eng: 'to remember',
        pl: 'pamiętać',
        ar: 'تذكر',
        ger: 'sich erinnern',
        lt: 'atsiminti',
        key: '39',
        norEgz: 'Jeg prøver å huske navnet hans.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhuske.mp3?alt=media&token=56dcc196-4d87-4d74-a5c2-b87410285c93',
        wordId: 39
      },
      {
        nor: 'å glemme',
        eng: 'to forget',
        pl: 'zapominać',
        ar: 'ينسى',
        ger: 'vergessen',
        lt: 'pamiršti',
        key: '40',
        norEgz: 'Han pleier å glemme nøklene sine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fglemme.mp3?alt=media&token=14c10b03-7f5e-49f9-8e6c-d13837d3da88',
        wordId: 40
      },
      {
        nor: 'en maler',
        eng: 'a painter',
        pl: 'malarz',
        ar: 'رسام',
        ger: 'ein Maler',
        lt: 'dažytojas',
        key: '41',
        norEgz: 'Hun er en talentfull maler.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaler.mp3?alt=media&token=8a7b2453-c831-46a7-9eed-6b83d9d3bea6',
        wordId: 41
      },
      {
        nor: 'en elektriker',
        eng: 'an electrician',
        pl: 'elektryk',
        ar: 'كهربائي',
        ger: 'ein Elektriker',
        lt: 'elektrikas',
        key: '42',
        norEgz: 'Vi trenger en elektriker for å fikse ledningene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felektriker.mp3?alt=media&token=c3ee37fd-f06c-4b18-8846-2960e10ba3c8',
        wordId: 42
      },
      {
        nor: 'en tunnel',
        eng: 'a tunnel',
        pl: 'tunel',
        ar: 'نفق',
        ger: 'ein Tunnel',
        lt: 'tunelis',
        key: '43',
        norEgz: 'Bilen kjører gjennom en tunnel.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftunnel.mp3?alt=media&token=b249e6f8-0ddf-4e9f-82b1-529482433c06',
        wordId: 43
      },
      {
        nor: 'en frukt',
        eng: 'a fruit',
        pl: 'owoc',
        ar: 'فاكهة',
        ger: 'eine Frucht',
        lt: 'vaisius',
        key: '44',
        norEgz: 'Eplet er en frukt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrukt.mp3?alt=media&token=a005d771-67f5-438b-a05b-d96404e5b07e',
        wordId: 44
      },
      {
        nor: 'en grønnsak',
        eng: 'a vegetable',
        pl: 'warzywo',
        ar: 'خضروات',
        ger: 'ein Gemüse',
        lt: 'daržovė',
        key: '45',
        norEgz: 'Gulroten er en grønnsak.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgroonnsak.mp3?alt=media&token=6cfbe3dd-4ca8-4808-b478-817d318f1792',
        wordId: 45
      },
      {
        nor: 'ineffektiv',
        eng: 'inefficient',
        pl: 'nieefektywny',
        ar: 'غير فعال',
        ger: 'ineffizient',
        lt: 'neefektyvus',
        key: '46',
        norEgz: 'Den gamle metoden er ineffektiv.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fineffektiv.mp3?alt=media&token=dedd74f5-5f5a-4612-8295-25d644bda391',
        wordId: 46
      },
      {
        nor: 'trygg',
        eng: 'safe',
        pl: 'bezpieczny',
        ar: 'آمن',
        ger: 'sicher',
        lt: 'saugus',
        key: '47',
        norEgz: 'Dette området er trygt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftrygg.mp3?alt=media&token=3b357fe5-2120-4749-9c94-48afd06b8a5f',
        wordId: 47
      },
      {
        nor: 'farlig',
        eng: 'dangerous',
        pl: 'niebezpieczny',
        ar: 'خطر',
        ger: 'gefährlich',
        lt: 'pavojingas',
        key: '48',
        norEgz: 'Kjør forsiktig, veien er farlig.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffarlig.mp3?alt=media&token=da25b174-1588-4b31-a43d-b7a32a400f9d',
        wordId: 48
      },
      {
        nor: 'høylytt',
        eng: 'loud',
        pl: 'głośny',
        ar: 'عالي الصوت',
        ger: 'laut',
        lt: 'garsus',
        key: '49',
        norEgz: 'Musikken er veldig høylytt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhooylytt.mp3?alt=media&token=87c47721-0202-4795-93c5-96f358da92dd',
        wordId: 49
      },
      {
        nor: 'en passasjer',
        eng: 'a passenger',
        pl: 'pasażer',
        ar: 'راكب',
        ger: 'ein Fahrgast',
        lt: 'keleivis',
        key: '50',
        norEgz: 'En passasjer venter på toget.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpassasjer.mp3?alt=media&token=fcda55de-12e8-4caf-832f-40ed1bd28e08',
        wordId: 50
      },
      {
        nor: 'en sjåfør',
        eng: 'a driver',
        pl: 'kierowca',
        ar: 'سائق',
        ger: 'ein Fahrer',
        lt: 'vairuotojas',
        key: '51',
        norEgz: 'Sjåføren kjører bussen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsjaafoor.mp3?alt=media&token=1e4540cd-5d3b-4ae4-b2d8-006619f3a165',
        wordId: 51
      },
      {
        nor: 'en servitør',
        eng: 'a waiter',
        pl: 'kelner',
        ar: 'نادل',
        ger: 'ein Kellner',
        lt: 'padavėjas',
        key: '52',
        norEgz: 'Servitøren tar bestillingen vår.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fservitoor.mp3?alt=media&token=3b27f8fb-c168-4f56-9c61-0824649626fb',
        wordId: 52
      },
      {
        nor: 'en selger',
        eng: 'a seller',
        pl: 'sprzedawca',
        ar: 'بائع',
        ger: 'ein Verkäufer',
        lt: 'pardavėjas',
        key: '53',
        norEgz: 'En selger hjelper kunden med å velge en vare.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fselger.mp3?alt=media&token=d706ad63-6c30-4021-b0b2-00aa779ced54',
        wordId: 53
      },
      {
        nor: 'å lukte',
        eng: 'to smell',
        pl: 'pachnieć',
        ar: 'يشم',
        ger: 'riechen',
        lt: 'uostyti',
        key: '54',
        norEgz: 'Blomstene lukter godt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flukte.mp3?alt=media&token=03349ab9-8528-4fff-8122-9c8e19a5eabe',
        wordId: 54
      },
      {
        nor: 'å finne',
        eng: 'to find',
        pl: 'znaleźć',
        ar: 'يجد',
        ger: 'finden',
        lt: 'rasti',
        key: '55',
        norEgz: 'Jeg prøver å finne nøklene mine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffinne.mp3?alt=media&token=891f0c90-18e1-4bf6-ad17-bae365f553e2',
        wordId: 55
      },
      {
        nor: 'en direktør',
        eng: 'a director',
        pl: 'dyrektor',
        ar: 'مدير',
        ger: 'ein Direktor',
        lt: 'direktorius',
        key: '56',
        norEgz: 'Direktøren styrer selskapet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdirektoor.mp3?alt=media&token=f0851cc3-7e44-4461-8ec7-57260db61d56',
        wordId: 56
      },
      {
        nor: 'et skilt',
        eng: 'a sign',
        pl: 'znak',
        ar: 'إشارة',
        ger: 'ein Schild',
        lt: 'ženklas',
        key: '57',
        norEgz: 'Følg skiltene til flyplassen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskilt.mp3?alt=media&token=7d609bdb-dfe5-41aa-940f-ad21f6faf5b5',
        wordId: 57
      },
      {
        nor: 'en billett',
        eng: 'a ticket',
        pl: 'bilet',
        ar: 'تذكرة',
        ger: 'ein Ticket',
        lt: 'bilietas',
        key: '58',
        norEgz: 'Jeg har billett til et tog.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbillett.mp3?alt=media&token=cd6f947a-decc-4fa7-9df6-d390d88040ff',
        wordId: 58
      },
      {
        nor: 'en lege',
        eng: 'a doctor',
        pl: 'lekarz',
        ar: 'طبيب',
        ger: 'ein Arzt',
        lt: 'gydytojas',
        key: '59',
        norEgz: 'Hun må gå til en lege for å få råd.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flege.mp3?alt=media&token=03abe9fd-661c-425d-9901-b631e2913596',
        wordId: 59
      },
      {
        nor: 'en heis',
        eng: 'an elevator',
        pl: 'winda',
        ar: 'مصعد',
        ger: 'ein Aufzug',
        lt: 'liftas',
        key: '60',
        norEgz: 'Vi tok heisen opp til femte etasje.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fheis.mp3?alt=media&token=d64fd778-3e97-4738-8445-f8b6285ac8d3',
        wordId: 60
      },
      {
        nor: 'en trapp',
        eng: 'a staircase',
        pl: 'schody',
        ar: 'درج',
        ger: 'eine Treppe',
        lt: 'laiptai',
        key: '61',
        norEgz: 'Hun gikk opp trappen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftrapp.mp3?alt=media&token=809c78f2-8a85-46e8-b608-f1a77d14c913',
        wordId: 61
      },
      {
        nor: 'å smake',
        eng: 'to taste',
        pl: 'smakować',
        ar: 'يتذوق',
        ger: 'schmecken',
        lt: 'ragauti',
        key: '62',
        norEgz: 'Hun smakte på suppen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmake.mp3?alt=media&token=f7748a02-9b25-46bf-bb34-e7433776cb08',
        wordId: 62
      },
      {
        nor: 'å tro',
        eng: 'to believe',
        pl: 'wierzyć',
        ar: 'يعتقد',
        ger: 'glauben',
        lt: 'tikėti',
        key: '63',
        norEgz: 'Jeg tror det kommer til å regne i morgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftro.mp3?alt=media&token=968c1501-c08b-4800-9c13-2de5e6413020',
        wordId: 63
      },
      {
        nor: 'sunn',
        eng: 'healthy',
        pl: 'zdrowy',
        ar: 'صحي',
        ger: 'gesund',
        lt: 'sveikas',
        key: '64',
        norEgz: 'Grønnsaker er sunne.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsunn.mp3?alt=media&token=727462be-b82e-4c5d-9c1e-181ab875906e',
        wordId: 64
      },
      {
        nor: 'usunn',
        eng: 'unhealthy',
        pl: 'niezdrowy',
        ar: 'غير صحي',
        ger: 'ungesund',
        lt: 'nesveikas',
        key: '65',
        norEgz: 'For mye sukker er usunt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fusunn.mp3?alt=media&token=2606d12a-6d69-477d-9586-34a1315e6535',
        wordId: 65
      },
      {
        nor: 'tykk',
        eng: 'thick',
        pl: 'gruby',
        ar: 'سميك',
        ger: 'dick',
        lt: 'storas',
        key: '66',
        norEgz: 'Denne boken er veldig tykk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftykk.mp3?alt=media&token=0f1230b2-2e99-4c80-b10e-4b79330c97d7',
        wordId: 66
      },
      {
        nor: 'en musiker',
        eng: 'a musician',
        pl: 'muzyk',
        ar: 'موسيقي',
        ger: 'ein Musiker',
        lt: 'muzikantas',
        key: '67',
        norEgz: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmusiker.mp3?alt=media&token=f8909e66-25c4-4e33-bf09-c3a03f978254',
        soundLink: 'Han er en stor musiker.',
        wordId: 67
      },
      {
        nor: 'en danser',
        eng: 'a dancer',
        pl: 'tancerz',
        ar: 'راقص',
        ger: 'ein Tänzer',
        lt: 'šokėjas',
        key: '68',
        norEgz: 'Hun er en talentfull danser.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdanser.mp3?alt=media&token=29a1d8fd-bdf5-4133-9e6c-9c76fcd97e4c',
        wordId: 68
      },
      {
        nor: 'en kunstner',
        eng: 'an artist',
        pl: 'artysta',
        ar: 'فنان',
        ger: 'ein Künstler',
        lt: 'menininkas',
        key: '69',
        norEgz: 'Han er en berømt kunstner.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkunstner.mp3?alt=media&token=b0eeba0f-5924-4cfc-ade0-36c66d0b5eef',
        wordId: 69
      },
      {
        nor: 'en reporter',
        eng: 'a reporter',
        pl: 'reporter',
        ar: 'مراسل',
        ger: 'ein Reporter',
        lt: 'reporteris',
        key: '70',
        norEgz: 'Reporteren intervjuet politikeren.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freporter.mp3?alt=media&token=3094ba5f-006b-4879-a7dd-1f98ceecc11b',
        wordId: 70
      },
      {
        nor: 'jevn',
        eng: 'smooth',
        pl: 'gładki',
        ar: 'ناعم',
        ger: 'glatt',
        lt: 'lygus',
        key: '71',
        norEgz: 'Overflaten er jevn og fin.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjevn.mp3?alt=media&token=c4de4561-e3a8-4a8c-a7bf-122bb803798b',
        wordId: 71
      },
      {
        nor: 'å frykte',
        eng: 'to fear',
        pl: 'bać się',
        ar: 'خوف',
        ger: 'fürchten',
        lt: 'bijoti',
        key: '72',
        norEgz: 'Han frykter høyder.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrykte.mp3?alt=media&token=b961a07c-0576-4050-9831-a4a5717a1e3f',
        wordId: 72
      },
      {
        nor: 'å håpe',
        eng: 'to hope',
        pl: 'mieć nadzieję',
        ar: 'أمل',
        ger: 'hoffen',
        lt: 'tikėtis',
        key: '73',
        norEgz: 'Vi håper på godt vær i morgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhaape.mp3?alt=media&token=fa0f2597-ee2a-4603-aed5-eb5753d375c8',
        wordId: 73
      },
      {
        nor: 'en advokat',
        eng: 'a lawyer',
        pl: 'adwokat',
        ar: 'محام',
        ger: 'ein Anwalt',
        lt: 'advokatas',
        key: '74',
        norEgz: 'Hun er en dyktig advokat.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fadvokat.mp3?alt=media&token=b1e73101-34ae-4068-8f5c-e505a6ad6f35',
        wordId: 74
      },
      {
        nor: 'en kokk',
        eng: 'a cook',
        pl: 'kucharz',
        ar: 'طباخ',
        ger: 'ein Koch',
        lt: 'virtuvės šefas',
        key: '75',
        norEgz: 'Han er en talentfull kokk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkokk.mp3?alt=media&token=9e756327-cf7c-49ac-9465-293bebad212b',
        wordId: 75
      },
      {
        nor: 'et instrument',
        eng: 'an instrument',
        pl: 'instrument',
        ar: 'آلة موسيقية',
        ger: 'ein Instrument',
        lt: 'instrumentas',
        key: '76',
        norEgz: 'Hun spiller et musikkinstrument.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finstrument.mp3?alt=media&token=1c296120-c51a-4045-ab2f-3244b0530f74',
        wordId: 76
      },
      {
        nor: 'en tromme',
        eng: 'a drum',
        pl: 'bęben',
        ar: 'طبل',
        ger: 'eine Trommel',
        lt: 'būgnas',
        key: '77',
        norEgz: 'Han spiller på en tromme.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftromme.mp3?alt=media&token=d18193dd-3a54-42d6-a9e4-eea5f4f00d86',
        wordId: 77
      },
      {
        nor: 'en gitar',
        eng: 'a guitar',
        pl: 'gitara',
        ar: 'جيتار',
        ger: 'eine Gitarre',
        lt: 'gitara',
        key: '78',
        norEgz: 'Hun spiller gitar i et band.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgitar.mp3?alt=media&token=afd0d9fd-e025-4217-96ad-8bc062f1cda5',
        wordId: 78
      },
      {
        nor: 'å elske',
        eng: 'to love',
        pl: 'kochać',
        ar: 'يحب',
        ger: 'lieben',
        lt: 'mylėti',
        key: '79',
        norEgz: 'Jeg elsker deg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felske.mp3?alt=media&token=18925ad8-60ba-4711-b780-76cf98bc92a1',
        wordId: 79
      },
      {
        nor: 'å hate',
        eng: 'to hate',
        pl: 'nienawidzić',
        ar: 'يكره',
        ger: 'hassen',
        lt: 'nekęsti',
        key: '80',
        norEgz: 'Hun hater å vente.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhate.mp3?alt=media&token=4d9508b9-66cb-4763-861e-044798d9e8c3',
        wordId: 80
      },
      {
        nor: 'å bære',
        eng: 'to carry',
        pl: 'nosić',
        ar: 'يحمل',
        ger: 'tragen',
        lt: 'nešti',
        key: '81',
        norEgz: 'Han bærer en tung ryggsekk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbeere.mp3?alt=media&token=7a97ec24-6e28-4614-b963-a2d75c96b082',
        wordId: 81
      },
      {
        nor: 'å ringe',
        eng: 'to call',
        pl: 'dzwonić',
        ar: 'يتصل',
        ger: 'anrufen',
        lt: 'skambinti',
        key: '82',
        norEgz: 'Jeg ringer deg i kveld.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fringe.mp3?alt=media&token=76f5cf71-69e3-408f-8794-feb5215feb64',
        wordId: 82
      },
      {
        nor: 'en reservasjon',
        eng: 'a reservation',
        pl: 'rezerwacja',
        ar: 'حجز',
        ger: 'eine Reservierung',
        lt: 'rezervacija',
        key: '83',
        norEgz: 'Vi har en reservasjon for to personer.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freservasjon.mp3?alt=media&token=ec06718d-e2ce-4049-aa09-cf622e40589d',
        wordId: 83
      },
      {
        nor: 'en planet',
        eng: 'a planet',
        pl: 'planeta',
        ar: 'كوكب',
        ger: 'ein Planet',
        lt: 'planeta',
        key: '84',
        norEgz: 'Jorden er en planet i solsystemet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fplanet.mp3?alt=media&token=eedc4bf5-1839-4782-aa2c-bbfdbd30bb73',
        wordId: 84
      },
      {
        nor: 'et høst',
        eng: 'an autumn',
        pl: 'jesień',
        ar: 'خريف',
        ger: 'ein Herbst',
        lt: 'ruduo',
        key: '85',
        norEgz: 'Høst er en vakker årstid med fargerike blader.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhoost.mp3?alt=media&token=7570c172-c17b-4ef9-9023-a8c7dd32f95d',
        wordId: 85
      },
      {
        nor: 'uviktig',
        eng: 'unimportant',
        pl: 'nieistotny',
        ar: 'غير مهم',
        ger: 'unwichtig',
        lt: 'nesvarbu',
        key: '86',
        norEgz: 'Det er uviktig hvilken farge du velger.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fuviktig.mp3?alt=media&token=39ac4c66-5be6-4997-81da-fe59f1e931b8',
        wordId: 86
      },
      {
        nor: 'sulten',
        eng: 'hungry',
        pl: 'głodny',
        ar: 'جائع',
        ger: 'hungrig',
        lt: 'alčiai',
        key: '87',
        norEgz: 'Jeg er veldig sulten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsulten.mp3?alt=media&token=4317c383-5738-4340-b5e6-a4070edf3885',
        wordId: 87
      },
      {
        nor: 'mett',
        eng: 'full',
        pl: 'pełny',
        ar: 'شبعان',
        ger: 'satt',
        lt: 'pilnas',
        key: '88',
        norEgz: 'Jeg er mett etter den store middagen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmett.mp3?alt=media&token=fa1e95da-4828-4901-a6b1-2a607e117cec',
        wordId: 88
      },
      {
        nor: 'en eksamen',
        eng: 'an exam',
        pl: 'egzamin',
        ar: 'امتحان',
        ger: 'eine Prüfung',
        lt: 'egzaminas',
        key: '89',
        norEgz: 'Jeg har en viktig eksamen i morgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feksamen.mp3?alt=media&token=b3cbae3c-d66a-4ba9-b3d7-ac33a422033a',
        wordId: 89
      },
      {
        nor: 'et emne',
        eng: 'a subject',
        pl: 'przedmiot',
        ar: 'موضوع',
        ger: 'ein Fach',
        lt: 'tema',
        key: '90',
        norEgz: 'Matematikk er et utfordrende emne.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Femne.mp3?alt=media&token=68cb6b57-62fd-428e-bf94-0e199d21f6fe',
        wordId: 90
      },
      {
        nor: 'en timeplan',
        eng: 'a schedule',
        pl: 'plan',
        ar: 'جدول',
        ger: 'ein Zeitplan',
        lt: 'tvarkaraštis',
        key: '91',
        norEgz: 'Jeg må sjekke timeplanen min for neste uke.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftimeplan.mp3?alt=media&token=32ed01a5-aebc-4d7b-8eb3-3c947ed2e346',
        wordId: 91
      },
      {
        nor: 'en pause',
        eng: 'a break',
        pl: 'przerwa',
        ar: 'استراحة',
        ger: 'eine Pause',
        lt: 'pertrauka',
        key: '92',
        norEgz: 'Vi tar en pause etter denne økten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpause.mp3?alt=media&token=28485d18-c103-4eeb-b72a-9da5c9e7c732',
        wordId: 92
      },
      {
        nor: 'å bruke',
        eng: 'to use',
        pl: 'używać',
        ar: 'استعمل',
        ger: 'benutzen',
        lt: 'naudoti',
        key: '93',
        norEgz: 'Jeg bruker en blyant for å tegne.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbruke.mp3?alt=media&token=df8ecc00-cc2b-4444-95f5-5061abe7f073',
        wordId: 93
      },
      {
        nor: 'å skjære',
        eng: 'to cut',
        pl: 'kroić',
        ar: 'قطع',
        ger: 'schneiden',
        lt: 'pjaustyti',
        key: '94',
        norEgz: 'Kan du skjære brødet for meg?',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjeere.mp3?alt=media&token=619cdf08-1e84-4bbd-b931-413691dad984',
        wordId: 94
      },
      {
        nor: 'å føle',
        eng: 'to feel',
        pl: 'czuć',
        ar: 'يشعر',
        ger: 'fühlen',
        lt: 'jausti',
        key: '95',
        norEgz: 'Jeg føler meg trøtt i dag.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffoole.mp3?alt=media&token=3de49428-1c0e-466e-9605-2e13e307ddb8',
        wordId: 95
      },
      {
        nor: 'et hjørne',
        eng: 'a corner',
        pl: 'róg',
        ar: 'زاوية',
        ger: 'eine Ecke',
        lt: 'kampas',
        key: '96',
        norEgz: 'Møt meg ved hjørnet av gaten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhjoorne.mp3?alt=media&token=4c171ebb-c8c7-4037-844b-8be0a84c1a76',
        wordId: 96
      },
      {
        nor: 'en vegg',
        eng: 'a wall',
        pl: 'ściana',
        ar: 'جدار',
        ger: 'eine Wand',
        lt: 'siena',
        key: '97',
        norEgz: 'Han hang bildet på veggen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvegg.mp3?alt=media&token=ecc41604-29fe-464c-8c19-f9d0d894ad07',
        wordId: 97
      },
      {
        nor: 'en grense',
        eng: 'a border',
        pl: 'granica',
        ar: 'حدود',
        ger: 'eine Grenze',
        lt: 'siena',
        key: '98',
        norEgz: 'Vi krysset grensen til Sverige.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrense.mp3?alt=media&token=6c72d17d-4101-44e7-910c-f701e278f837',
        wordId: 98
      },
      {
        nor: 'en inngang',
        eng: 'an entrance',
        pl: 'wejście',
        ar: 'مدخل',
        ger: 'ein Eingang',
        lt: 'įėjimas',
        key: '99',
        norEgz: 'Inngangen til bygningen er på baksiden.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finngang.mp3?alt=media&token=7a4688c7-d1aa-4ed1-b9fa-d0f1480f8419',
        wordId: 99
      },
      {
        nor: 'en utgang',
        eng: 'an exit',
        pl: 'wyjście',
        ar: 'مخرج',
        ger: 'ein Ausgang',
        lt: 'išėjimas',
        key: '100',
        norEgz: 'Finn nærmeste utgang i tilfelle nødsituasjon.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futgang.mp3?alt=media&token=18cf54ef-e4c3-4171-9c3d-31f6453cacd9',
        wordId: 100
      },
      {
        nor: 'tørst',
        eng: 'thirsty',
        pl: 'spragniony',
        ar: 'عطشان',
        ger: 'durstig',
        lt: 'ištroškęs',
        key: '101',
        norEgz: 'Jeg er tørst og trenger vann.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorst.mp3?alt=media&token=27ceefc0-7ad6-471f-b250-3b5bed2c7bef',
        wordId: 101
      },
      {
        nor: 'rik',
        eng: 'rich',
        pl: 'bogaty',
        ar: 'غني',
        ger: 'reich',
        lt: 'turtingas',
        key: '102',
        norEgz: 'Han er en rik forretningsmann.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frik.mp3?alt=media&token=7331b335-0fb4-4090-91ba-76f4cb6382d4',
        wordId: 102
      },
      {
        nor: 'et marked',
        eng: 'a market',
        pl: 'rynek',
        ar: 'سوق',
        ger: 'ein Markt',
        lt: 'turgus',
        key: '103',
        norEgz: 'Vi skal besøke det lokale markedet i morgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmarked.mp3?alt=media&token=f4f010cb-c29d-491a-a299-341c08c39f95',
        wordId: 103
      },
      {
        nor: 'en dyrehage',
        eng: 'a zoo',
        pl: 'ogród zoologiczny',
        ar: 'حديقة حيوان',
        ger: 'ein Zoo',
        lt: 'zoologijos sodas',
        key: '104',
        norEgz: 'Vi tok barna med til dyrehagen i helgen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdyrehage.mp3?alt=media&token=967e011a-17e7-489b-917b-d6ae112ae3e4',
        wordId: 104
      },
      {
        nor: 'en hage',
        eng: 'a garden',
        pl: 'ogród',
        ar: 'حديقة',
        ger: 'ein Garten',
        lt: 'sodas',
        key: '105',
        norEgz: 'Hun har en vakker hage bak huset sitt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhage.mp3?alt=media&token=eed1b8ec-d204-4c98-88c1-f87bf5ebb776',
        wordId: 105
      },
      {
        nor: 'en strand',
        eng: 'a beach',
        pl: 'plaża',
        ar: 'شاطئ',
        ger: 'ein Strand',
        lt: 'paplūdimys',
        key: '106',
        norEgz: 'Vi tilbrakte dagen på stranden.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstrand.mp3?alt=media&token=1c27bc04-b6d1-4504-8540-8ccefae0f350',
        wordId: 106
      },
      {
        nor: 'å holde',
        eng: 'to hold',
        pl: 'trzymać',
        ar: 'يمسك',
        ger: 'halten',
        lt: 'laikyti',
        key: '107',
        norEgz: 'Kan du holde vesken min et øyeblikk?',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fholde.mp3?alt=media&token=2e9a3043-9079-41cd-a002-c9f0e7fa3181',
        wordId: 107
      },
      {
        nor: 'å skrike',
        eng: 'to scream',
        pl: 'krzyczeć',
        ar: 'يصرخ',
        ger: 'schreien',
        lt: 'šaukti',
        key: '108',
        norEgz: 'Hun skrek av smerte da hun falt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskrike.mp3?alt=media&token=80f33a9d-bcc2-427e-b868-b8804c82a68f',
        wordId: 108
      },
      {
        nor: 'å rope',
        eng: 'to shout',
        pl: 'wołać',
        ar: 'يصيح',
        ger: 'rufen',
        lt: 'šaukti',
        key: '109',
        norEgz: 'Han ropte navnet mitt fra den andre siden av gaten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frope.mp3?alt=media&token=e7d78f3d-4534-4620-a551-7ed9679f6a7a',
        wordId: 109
      },
      {
        nor: 'en tallerken',
        eng: 'a plate',
        pl: 'talerz',
        ar: 'طبق',
        ger: 'ein Teller',
        lt: 'lėkštė',
        key: '110',
        norEgz: 'Kan du sende meg den blå tallerkenen?',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftallerken.mp3?alt=media&token=a26013e6-7e97-4c50-8888-00f628ff828c',
        wordId: 110
      },
      {
        nor: 'en skje',
        eng: 'a spoon',
        pl: 'łyżka',
        ar: 'ملعقة',
        ger: 'ein Löffel',
        lt: 'šaukštas',
        key: '111',
        norEgz: 'Jeg trenger en skje for å røre i suppen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskje.mp3?alt=media&token=c920d99e-f2cc-4b3c-a2c7-57c5c8a9baba',
        wordId: 111
      },
      {
        nor: 'praktisk',
        eng: 'practical',
        pl: 'praktyczny',
        ar: 'عملي',
        ger: 'praktisch',
        lt: 'praktiškas',
        key: '112',
        norEgz: 'Å ha en bil er veldig praktisk i denne byen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpraktisk.mp3?alt=media&token=23d3da81-9e16-4e98-b699-f3d732e71166',
        wordId: 112
      },
      {
        nor: 'upraktisk',
        eng: 'impractical',
        pl: 'niepraktyczny',
        ar: 'غير عملي',
        ger: 'unpraktisch',
        lt: 'nepraktiškas',
        key: '113',
        norEgz: 'Denne vesken er upraktisk for reiser.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fupraktisk.mp3?alt=media&token=83a2ed84-9fc1-4d95-9db3-4a612cda2ac7',
        wordId: 113
      },
      {
        nor: 'morsom',
        eng: 'fun',
        pl: 'zabawny',
        ar: 'ممتع',
        ger: 'lustig',
        lt: 'linksmas',
        key: '114',
        norEgz: 'Vi hadde en morsom dag på fornøyelsesparken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmorsom.mp3?alt=media&token=c72b635d-fbd8-4e58-8882-c0715b186daa',
        wordId: 114
      },
      {
        nor: 'en gaffel',
        eng: 'a fork',
        pl: 'widelec',
        ar: 'شوكة',
        ger: 'eine Gabel',
        lt: 'šakutė',
        key: '115',
        norEgz: 'Kan du gi meg en gaffel, vær så snill?',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgaffel.mp3?alt=media&token=29fb93cc-265a-432a-87d0-f58f4c04ff63',
        wordId: 115
      },
      {
        nor: 'en kniv',
        eng: 'a knife',
        pl: 'nóż',
        ar: 'سكين',
        ger: 'ein Messer',
        lt: 'peilis',
        key: '116',
        norEgz: 'Pass på at du håndterer kniven forsiktig.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkniv.mp3?alt=media&token=453abbc5-75bc-46ae-9c84-27f5da6f7f0c',
        wordId: 116
      },
      {
        nor: 'en blyant',
        eng: 'a pencil',
        pl: 'ołówek',
        ar: 'قلم رصاص',
        ger: 'ein Bleistift',
        lt: 'pieštukas',
        key: '117',
        norEgz: 'Hun tegnet et vakkert bilde med en blyant.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblyant.mp3?alt=media&token=9c4e80df-737e-40f3-bdcb-f0ea438c87a1',
        wordId: 117
      },
      {
        nor: 'å kysse',
        eng: 'to kiss',
        pl: 'całować',
        ar: 'يُقبِّل',
        ger: 'küssen',
        lt: 'bučiuoti',
        key: '118',
        norEgz: 'De kysset hverandre under mistelteinen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkysse.mp3?alt=media&token=a7319234-7906-483a-a73c-7278236d4332',
        wordId: 118
      },
      {
        nor: 'å sykle',
        eng: 'to cycle',
        pl: 'jeździć na rowerze',
        ar: 'يَركَب الدَرّاجَة',
        ger: 'Rad fahren',
        lt: 'važiuoti dviračiu',
        key: '119',
        norEgz: 'Vi liker å sykle sammen i parken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykle.mp3?alt=media&token=9167762b-65ef-4e3a-b7be-ac7a777cc4c3',
        wordId: 119
      },
      {
        nor: 'å varsel',
        eng: 'to warn',
        pl: 'ostrzegać',
        ar: 'يحذر',
        ger: 'warnen',
        lt: 'įspėti',
        key: '120',
        norEgz: 'Han varslet oss om den kommende stormen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvarsel.mp3?alt=media&token=ccc0edf3-60ee-4032-a765-37ce7a33973a',
        wordId: 120
      },
      {
        nor: 'fattig',
        eng: 'poor',
        pl: 'biedny',
        ar: 'فقير',
        ger: 'arm',
        lt: 'varžtas',
        key: '121',
        norEgz: 'Han vokste opp i en fattig familie.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffattig.mp3?alt=media&token=f5e70d99-b341-4e6d-9a87-84ee7746d07e',
        wordId: 121
      },
      {
        nor: 'en regnbue',
        eng: 'a rainbow',
        pl: 'tęcza',
        ar: 'قوس قزح',
        ger: 'ein Regenbogen',
        lt: 'vaivorykštė',
        key: '122',
        norEgz: 'Vi så en vakker regnbue etter regnet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fregnbue.mp3?alt=media&token=c790d356-9481-43f4-a9ce-b094c7647fbe',
        wordId: 122
      },
      {
        nor: 'et kart',
        eng: 'a map',
        pl: 'mapa',
        ar: 'خريطة',
        ger: 'eine Karte',
        lt: 'žemėlapis',
        key: '123',
        norEgz: 'Hun studerte kartet før hun begynte å kjøre.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkart.mp3?alt=media&token=352316f8-b198-4201-9aeb-0430f70f0b9e',
        wordId: 123
      },
      {
        nor: 'trøtt',
        eng: 'tired',
        pl: 'zmęczony',
        ar: 'متعب',
        ger: 'müde',
        lt: 'pavargęs',
        key: '124',
        norEgz: 'Han er trøtt etter jobb.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftroott.mp3?alt=media&token=a6e32f2c-4b23-41aa-b971-c994666a7549',
        wordId: 124
      },
      {
        nor: 'våken',
        eng: 'awake',
        pl: 'obudzony',
        ar: 'مستيقظ',
        ger: 'wach',
        lt: 'pabudęs',
        key: '125',
        norEgz: 'Hun var våken hele natten.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaaken.mp3?alt=media&token=2a1d8748-08aa-40e0-b619-6fc0182cb81d',
        wordId: 125
      },
      {
        nor: 'ærlig',
        eng: 'honest',
        pl: 'szczery',
        ar: 'صادق',
        ger: 'ehrlich',
        lt: 'nuoširdus',
        key: '126',
        norEgz: 'Han er en ærlig person.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feerlig.mp3?alt=media&token=e7b98c65-2e7a-4299-8ad6-0abd5d727688',
        wordId: 126
      },
      {
        nor: 'uærlig',
        eng: 'dishonest',
        pl: 'nieuczciwy',
        ar: 'غير أمين',
        ger: 'unehrlich',
        lt: 'nepasitikintis',
        key: '127',
        norEgz: 'Uærlige mennesker er vanskelig å stole på.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fueerlig.mp3?alt=media&token=422a7051-7c09-492d-a0bf-030a2e498a60',
        wordId: 127
      },
      {
        nor: 'å skjule',
        eng: 'to hide',
        pl: 'ukrywać',
        ar: 'يختبئ',
        ger: 'verstecken',
        lt: 'paslėpti',
        key: '128',
        norEgz: 'Han prøver å skjule hemmeligheter.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjule.mp3?alt=media&token=1d8654f1-b294-4621-95e0-606a85df61fb',
        wordId: 128
      },
      {
        nor: 'å puste',
        eng: 'to breathe',
        pl: 'oddychać',
        ar: 'يتنفس',
        ger: 'atmen',
        lt: 'kvėpuoti',
        key: '129',
        norEgz: 'Hun lærte å puste dypt under yoga-timene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpuste.mp3?alt=media&token=c72a3eb3-a016-4585-90b3-b3727a4643c4',
        wordId: 129
      },
      {
        nor: 'en festival',
        eng: 'a festival',
        pl: 'festiwal',
        ar: 'مهرجان',
        ger: 'ein Festival',
        lt: 'festivalis',
        key: '130',
        norEgz: 'Vi gleder oss til å delta på musikkfestivalen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffestival.mp3?alt=media&token=8ca9ad9d-ff2b-484f-927a-b56093df00eb',
        wordId: 130
      },
      {
        nor: 'en bonde',
        eng: 'a farmer',
        pl: 'rolnik',
        ar: 'مزارع',
        ger: 'ein Bauer',
        lt: 'ūkininkas',
        key: '131',
        norEgz: 'Bonden jobber hardt for å dyrke avlingene sine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbonde.mp3?alt=media&token=4275da58-ef16-4dbe-bf71-f90603eb524d',
        wordId: 131
      },
      {
        nor: 'mulig',
        eng: 'possible',
        pl: 'możliwy',
        ar: 'ممكن',
        ger: 'möglich',
        lt: 'galima',
        key: '132',
        norEgz: 'Det er mulig å reise til månen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmulig.mp3?alt=media&token=ac2cb6ba-2c65-41e1-847e-249debbcdd1b',
        wordId: 132
      }, 
      {
        nor: 'umulig',
        eng: 'impossible',
        pl: 'niemożliwe',
        ar: 'مستحيل',
        ger: 'unmöglich',
        lt: 'neįmanoma',
        key: '133',
        norEgz: 'Det virker umulig å fullføre oppgaven.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fumulig.mp3?alt=media&token=95c62f06-b3a1-47e1-8020-b2c708f2ec6c',
        wordId: 133
      },
      {
        nor: 'nødvendig',
        eng: 'necessary',
        pl: 'konieczny',
        ar: 'ضروري',
        ger: 'notwendig',
        lt: 'būtina',
        key: '134',
        norEgz: 'Det er nødvendig å forberede seg før eksamen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnoodvendig.mp3?alt=media&token=5b8fa988-ed7b-4cd0-ab73-a1b1186cf8a7',
        wordId: 134
      },
      {
        nor: 'en ferie',
        eng: 'a holiday',
        pl: 'wakacje',
        ar: 'عطلة',
        ger: 'ein Urlaub',
        lt: 'atostogos',
        key: '135',
        norEgz: 'Vi planlegger en ferie til Spania neste sommer.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fferie.mp3?alt=media&token=d52a232c-ab4a-4384-893e-872f9261c321',
        wordId: 135
      },
      {
        nor: 'en håndball',
        eng: 'a handball',
        pl: 'piłka ręczna',
        ar: 'كرة اليد',
        ger: 'ein Handball',
        lt: 'rankinis',
        key: '136',
        norEgz: 'Hun spiller håndball for skolelaget.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhaandball.mp3?alt=media&token=039aa2c9-f4b8-4802-a898-4bce896ada33',
        wordId: 136
      },
      {
        nor: 'å smitte',
        eng: 'to infect',
        pl: 'zarażać',
        ar: 'يعدي',
        ger: 'anstecken',
        lt: 'užkrėsti',
        key: '137',
        norEgz: 'Influensaviruset kan smitte andre mennesker raskt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmitte.mp3?alt=media&token=6aec707f-8a31-47a6-873b-570c883a4cde',
        wordId: 137
      },
      {
        nor: 'å leve',
        eng: 'to live',
        pl: 'żyć',
        ar: 'يعيش',
        ger: 'leben',
        lt: 'gyventi',
        key: '138',
        norEgz: 'Vi må lære å leve i harmoni med naturen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleve.mp3?alt=media&token=c039671d-0012-4080-899c-602d27ea4777',
        wordId: 138
      },
      {
        nor: 'å beskytte',
        eng: 'to protect',
        pl: 'chronić',
        ar: 'يحمي',
        ger: 'schützen',
        lt: 'apsaugoti',
        key: '139',
        norEgz: 'Vi må beskytte miljøet for kommende generasjoner.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbeskytte.mp3?alt=media&token=c67c79fa-b979-498c-8b7c-4fd2a1cd6026',
        wordId: 139
      },
      {
        nor: 'en svømming',
        eng: 'a swimming',
        pl: 'pływanie',
        ar: 'سباحة',
        ger: 'ein Schwimmen',
        lt: 'plaukimas',
        key: '140',
        norEgz: 'Han deltar i en svømming konkurranse neste uke.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvoomming.mp3?alt=media&token=708e5ff2-4cd8-419b-9294-9f24c20f9c71',
        wordId: 140
      },
      {
        nor: 'en ski',
        eng: 'a ski',
        pl: 'narta',
        ar: 'تزلج',
        ger: 'ein Ski',
        lt: 'slidinė',
        key: '141',
        norEgz: 'Han kjøpte en ny ski for vinteren.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fski.mp3?alt=media&token=ff5ed6c4-ce75-4934-ab40-423fa2fbad6a',
        wordId: 141
      },
      {
        nor: 'å dekke',
        eng: 'to cover',
        pl: 'pokrywać',
        ar: 'يغطي',
        ger: 'abdecken',
        lt: 'dengti',
        key: '142',
        norEgz: 'Vi må dekke bordet før gjestene kommer.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdekke.mp3?alt=media&token=1046b9ad-57bd-46f5-92ba-82ac86a73508',
        wordId: 142
      },
      {
        nor: 'å grave',
        eng: 'to dig',
        pl: 'kopać',
        ar: 'يحفر',
        ger: 'graben',
        lt: 'kasti',
        key: '143',
        norEgz: 'Han begynte å grave et hull i hagen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrave.mp3?alt=media&token=c4c3fa74-9799-4e06-b6c3-337a7ac2ccad',
        wordId: 143
      },
      {
        nor: 'å fly',
        eng: 'to fly',
        pl: 'lecieć',
        ar: 'يطير',
        ger: 'fliegen',
        lt: 'skristi',
        key: '144',
        norEgz: 'Fuglene begynte å fly sørover for vinteren.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffly.mp3?alt=media&token=cf5367d8-d071-46d2-9bbd-589b44327020',
        wordId: 144
      },
      {
        nor: 'en ishockey',
        eng: 'ice hockey',
        pl: 'hokej na lodzie',
        ar: 'هوكي الجليد',
        ger: 'Eishockey',
        lt: 'ledoritulys',
        key: '145',
        norEgz: 'Han er en stor fan av ishockey.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fishockey.mp3?alt=media&token=7a62965d-effe-4533-b99a-b132ac08425e',
        wordId: 145
      },
      {
        nor: 'en basket',
        eng: 'basketball',
        pl: 'koszykówka',
        ar: 'كرة السلة',
        ger: 'Basketball',
        lt: 'krepšinis',
        key: '146',
        norEgz: 'De spiller basket etter skolen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbasket.mp3?alt=media&token=145defea-cf6e-4a9e-9738-9d0bc06c2c69',
        wordId: 146
      },
      {
        nor: 'en volleyball',
        eng: 'volleyball',
        pl: 'siatkówka',
        ar: 'كرة الطائرة',
        ger: 'Volleyball',
        lt: 'tinklinis',
        key: '147',
        norEgz: 'De deltar i en volleyball turnering.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvolleyball.mp3?alt=media&token=a5949333-1755-44bc-9e1a-6e50370581a6',
        wordId: 147
      },
      {
        nor: 'unødvendig',
        eng: 'unnecessary',
        pl: 'niepotrzebny',
        ar: 'غير ضروري',
        ger: 'unnötig',
        lt: 'nereikalingas',
        key: '148',
        norEgz: 'Det er unødvendig å bekymre seg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Funoodvendig.mp3?alt=media&token=ae116600-1f50-4389-8596-5028be33f21f',
        wordId: 148
      },
      {
        nor: 'frisk',
        eng: 'fresh',
        pl: 'świeży',
        ar: 'طازج',
        ger: 'frisch',
        lt: 'šviežias',
        key: '149',
        norEgz: 'Luften er frisk her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrisk.mp3?alt=media&token=ffa59af5-0ef3-44f7-b4c4-d3e10755e4a3',
        wordId: 149
      },
      {
        nor: 'stille',
        eng: 'quiet',
        pl: 'cichy',
        ar: 'هادئ',
        ger: 'ruhig',
        lt: 'tylus',
        key: '150',
        norEgz: 'Det er så stille her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstille.mp3?alt=media&token=089460e2-31ff-4986-b742-3d80efc716bf',
        wordId: 150
      },
      {
        nor: 'en fiolin',
        eng: 'a violin',
        pl: 'skrzypce',
        ar: 'كمان',
        ger: 'eine Violine',
        lt: 'smuikas',
        key: '151',
        norEgz: 'Han spiller på en fiolin.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffiolin.mp3?alt=media&token=73001e51-049c-4289-8f78-91a0c2b193d8',
        wordId: 151
      },
      {
        nor: 'et medlem',
        eng: 'a member',
        pl: 'członek',
        ar: 'عضو',
        ger: 'ein Mitglied',
        lt: 'narys',
        key: '152',
        norEgz: 'Han er et medlem av klubben.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmedlem.mp3?alt=media&token=3672ff38-9c4e-49ef-bdee-a057911ab053',
        wordId: 152
      },
      {
        nor: 'å bade',
        eng: 'to bathe',
        pl: 'kąpać się',
        ar: 'الاستحمام',
        ger: 'baden',
        lt: 'maudytis',
        key: '153',
        norEgz: 'Vi liker å bade i sjøen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbade.mp3?alt=media&token=53bdc581-7da3-4d9b-9e6e-295980120faf',
        wordId: 153
      },
      {
        nor: 'å vaske',
        eng: 'to wash',
        pl: 'myć',
        ar: 'غسل',
        ger: 'waschen',
        lt: 'plauti',
        key: '154',
        norEgz: 'Jeg må vaske klærne mine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaske.mp3?alt=media&token=b363426e-2cae-4833-b80b-862602903ab0',
        wordId: 154
      },
      {
        nor: 'å tørke',
        eng: 'to dry',
        pl: 'suszyć',
        ar: 'يجف',
        ger: 'trocknen',
        lt: 'džiovinti',
        key: '155',
        norEgz: 'Jeg må tørke klærne mine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorke.mp3?alt=media&token=892da2c3-16bb-4db1-bfbb-92712b11d023',
        wordId: 155
        },
        {
        nor: 'en besøkende',
        eng: 'a visitor',
        pl: 'zwiedzający',
        ar: 'زائر',
        ger: 'ein Besucher',
        lt: 'lankytojas',
        key: '156',
        norEgz: 'Vi har en besøkende fra Tyskland.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbesookende.mp3?alt=media&token=c979fa2e-9ee7-44ad-bac2-c311536e5b83',
        wordId: 156
        },
        {
        nor: 'en turist',
        eng: 'a tourist',
        pl: 'turysta',
        ar: 'سائح',
        ger: 'ein Tourist',
        lt: 'turistas',
        key: '157',
        norEgz: 'Turisten tok bilder av severdighetene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fturist.mp3?alt=media&token=e71b62a7-d0d9-47b5-b1e8-96a92f32032f',
        wordId: 157
        },
        {
        nor: 'ujevn',
        eng: 'uneven',
        pl: 'nierówny',
        ar: 'غير مستو',
        ger: 'unregelmäßig',
        lt: 'nelygus',
        key: '158',
        norEgz: 'Gulvet er ujevnt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fujevn.mp3?alt=media&token=a6c8189e-1d9b-46c2-af68-2246206bb5e8',
        wordId: 158
        },
        {
        nor: 'lokal',
        eng: 'local',
        pl: 'lokalny',
        ar: 'محلي',
        ger: 'lokal',
        lt: 'vietinis',
        key: '159',
        norEgz: 'Den lokale butikken har gode priser.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flokal.mp3?alt=media&token=82cc4296-806c-4faa-9996-98467fd03d04',
        wordId: 159
        },
        {
        nor: 'en konsert',
        eng: 'a concert',
        pl: 'koncert',
        ar: 'حفلة موسيقية',
        ger: 'ein Konzert',
        lt: 'koncertas',
        key: '160',
        norEgz: 'Jeg gleder meg til konserten i kveld.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkonsert.mp3?alt=media&token=cbd03b88-1637-44aa-a3a8-a3ceebdd33b3',
        wordId: 160
        },
        {
        nor: 'en skuff',
        eng: 'a drawer',
        pl: 'szuflada',
        ar: 'درج',
        ger: 'eine Schublade',
        lt: 'stalčius',
        key: '161',
        norEgz: 'Jeg åpnet en skuff for å finne en skje.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskuff.mp3?alt=media&token=66848a16-5daa-428f-a3fe-c8504989b4ff',
        wordId: 161
        },
        {
        nor: 'å krympe',
        eng: 'to shrink',
        pl: 'kurczyć się',
        ar: 'تقلص',
        ger: 'schrumpfen',
        lt: 'traukti',
        key: '162',
        norEgz: 'Denne genseren krymper hvis du vasker den på høy temperatur.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkrympe.mp3?alt=media&token=3ec5eba9-7749-443d-ae6d-b86672c351db',
        wordId: 162
        },
        {
        nor: 'å bli kvitt',
        eng: 'to get rid of',
        pl: 'pozbyć się',
        ar: 'التخلص من',
        ger: 'loswerden',
        lt: 'atbristi',
        key: '163',
        norEgz: 'Vi må bli kvitt dette gamle skapet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblikvitt.mp3?alt=media&token=d9cc0af5-b2d7-4d31-bcbf-c9e0fe8e4601',
        wordId: 163
        },
        {
        nor: 'å blande',
        eng: 'to mix',
        pl: 'mieszać',
        ar: 'خلط',
        ger: 'mischen',
        lt: 'maišyti',
        key: '164',
        norEgz: 'Hun blandet ingrediensene sammen i en bolle.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblande.mp3?alt=media&token=e73249ee-b2b1-4e9d-95bd-6ac7070ecfcf',
        wordId: 164
        },
        {
        nor: 'et skap',
        eng: 'a cabinet',
        pl: 'szafka',
        ar: 'خزانة',
        ger: 'ein Schrank',
        lt: 'spintelė',
        key: '165',
        norEgz: 'Hun hentet tallerkener fra skapet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskap.mp3?alt=media&token=4639e7c8-bb7e-4316-9a3f-a4cab9162346',
        wordId: 165
        },
        {
        nor: 'en leilighet',
        eng: 'an apartment',
        pl: 'mieszkanie',
        ar: 'شقة',
        ger: 'eine Wohnung',
        lt: 'butas',
        key: '166',
        norEgz: 'Hun bor i en liten leilighet i byen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleilighet.mp3?alt=media&token=623cea77-8155-4c2b-97d4-d3c1aa9b3021',
        wordId: 166
        },
        {
        nor: 'å riste',
        eng: 'to shake',
        pl: 'potrząsać',
        ar: 'هز',
        ger: 'schütteln',
        lt: 'kratyti',
        key: '167',
        norEgz: 'Hun ristet på hodet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Friste.mp3?alt=media&token=9dc82054-15bb-4225-8a45-4af4a8007cb2',
        wordId: 167
        },
        {
        nor: 'å bekymre',
        eng: 'to worry',
        pl: 'martwić się',
        ar: 'القلق',
        ger: 'sich sorgen',
        lt: 'nerimauti',
        key: '168',
        norEgz: 'Du trenger ikke å bekymre deg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbekymre.mp3?alt=media&token=85b922c6-450d-4287-8f3e-7e4a7b23ec44',
        wordId: 168
        },
        {
        nor: 'å forlate',
        eng: 'to leave',
        pl: 'opuścić',
        ar: 'ترك',
        ger: 'verlassen',
        lt: 'palikti',
        key: '169',
        norEgz: 'Han forlot rommet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforlate.mp3?alt=media&token=14a6707a-ac19-475f-bc12-87ced5721a36',
        wordId: 169
        },
        {
        nor: 'å sukke',
        eng: 'to sigh',
        pl: 'wzdychać',
        ar: 'تنهد',
        ger: 'seufzen',
        lt: 'atsidegti',
        key: '170',
        norEgz: 'Hun sukket dypt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsukke.mp3?alt=media&token=fc5cbfa7-8085-44d3-b5f5-d9b8d7ee1465',
        wordId: 170
        },
        {
        nor: 'intelligent',
        eng: 'intelligent',
        pl: 'inteligentny',
        ar: 'ذكي',
        ger: 'intelligent',
        lt: 'intelektualus',
        key: '171',
        norEgz: 'Han er en intelligent person.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fintelligent.mp3?alt=media&token=4b59f9ab-9a2b-44a8-bf4b-255387594f67',
        wordId: 171
        },
        {
        nor: 'dum',
        eng: 'stupid',
        pl: 'głupi',
        ar: 'غبي',
        ger: 'dumm',
        lt: 'kvailas',
        key: '172',
        norEgz: 'Det var en dum feil.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdum.mp3?alt=media&token=87d6235e-3a3d-4a93-aa38-9451ca3b6420',
        wordId: 172
        },
        {
        nor: 'å tørste',
        eng: 'to thirst',
        pl: 'pragnąć',
        ar: 'يعطش',
        ger: 'durstig sein',
        lt: 'trokšti',
        key: '173',
        norEgz: 'Etter en lang tur, begynte han å tørste.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorste.mp3?alt=media&token=77edd996-8638-4117-b4da-a4751f67392c',
        wordId: 173
        }
    
]


// høylyt does not have sound link!! delete plate cause there is tallarken