[
    {
      nor: 'å spørre',
      eng: 'to ask',
      pl: 'pytać',
      ar: 'يسأل',
      ger: 'fragen',
      lt: 'klausti',
      key: '0',
      norEgz: 'Han spurte hvor bussen går.',
      soundLink: '',
      wordId: 0
    },
    {
      nor: 'å svare',
      eng: 'to answer',
      pl: 'odpowiadać',
      ar: 'يجيب',
      ger: 'antworten',
      lt: 'atsakyti',
      key: '1',
      norEgz: 'Hun svarte raskt på spørsmålet.',
      soundLink: '',
      wordId: 1
    },
    {
      nor: 'å åpne',
      eng: 'to open',
      pl: 'otwierać',
      ar: 'يفتح',
      ger: 'öffnen',
      lt: 'atidaryti',
      key: '2',
      norEgz: 'Kan du åpne vinduet?',
      soundLink: '',
      wordId: 2
    },
    {
      nor: 'en tegning',
      eng: 'a drawing',
      pl: 'rysunek',
      ar: 'رسم',
      ger: 'eine Zeichnung',
      lt: 'piešinys',
      key: '3',
      norEgz: 'Hun laget en flott tegning.',
      soundLink: '',
      wordId: 3
    },
    {
      nor: 'en maling',
      eng: 'a painting',
      pl: 'obraz',
      ar: 'لوحة',
      ger: 'ein Gemälde',
      lt: 'tapyba',
      key: '4',
      norEgz: 'Dette er en vakker maling.',
      soundLink: '',
      wordId: 4
    },
    {
      nor: 'en matlaging',
      eng: 'cooking',
      pl: 'gotowanie',
      ar: 'طبخ',
      ger: 'Kochen',
      lt: 'virtuvė',
      key: '5',
      norEgz: 'Hun liker matlaging etter jobb.',
      soundLink: '',
      wordId: 5
    },
    {
      nor: 'å lukke',
      eng: 'to close',
      pl: 'zamykać',
      ar: 'يغلق',
      ger: 'schließen',
      lt: 'uždaryti',
      key: '6',
      norEgz: 'Husk å lukke døren.',
      soundLink: '',
      wordId: 6
    },
    {
      nor: 'å gi',
      eng: 'to give',
      pl: 'dawać',
      ar: 'يعطي',
      ger: 'geben',
      lt: 'duoti',
      key: '7',
      norEgz: 'Han ga henne en gave.',
      soundLink: '',
      wordId: 7
    },
    {
      nor: 'å ta',
      eng: 'to take',
      pl: 'brać',
      ar: 'يأخذ',
      ger: 'nehmen',
      lt: 'imti',
      key: '8',
      norEgz: 'Han tar bok fra hylla.',
      soundLink: '',
      wordId: 8
    },
    {
        nor: 'interessant',
        eng: 'interesting',
        pl: 'interesujący',
        ar: 'مثير للاهتمام',
        ger: 'interessant',
        lt: 'įdomus',
        key: '9',
        norEgz: 'Det var en interessant bok.',
        soundLink: '',
        wordId: 9
      },
      {
        nor: 'kjedelig',
        eng: 'boring',
        pl: 'nudny',
        ar: 'ممل',
        ger: 'langweilig',
        lt: 'nuobodus',
        key: '10',
        norEgz: 'Denne filmen er kjedelig.',
        soundLink: '',
        wordId: 10
      },
      {
        nor: 'å forstå',
        eng: 'to understand',
        pl: 'rozumieć',
        ar: 'يفهم',
        ger: 'verstehen',
        lt: 'suprasti',
        key: '11',
        norEgz: 'Jeg forstår ikke hva du sier.',
        soundLink: '',
        wordId: 11
      },
      {
        nor: 'å øve',
        eng: 'to practice',
        pl: 'ćwiczyć',
        ar: 'يمارس',
        ger: 'üben',
        lt: 'praktikuotis',
        key: '12',
        norEgz: 'Vi må øve før konserten.',
        soundLink: '',
        wordId: 12
      },
      {
        nor: 'internasjonal',
        eng: 'international',
        pl: 'międzynarodowy',
        ar: 'دولي',
        ger: 'international',
        lt: 'tarptautinis',
        key: '13',
        norEgz: 'Dette er en internasjonal konferanse.',
        soundLink: '',
        wordId: 13
      },
      {
        nor: 'komfortabel',
        eng: 'comfortable',
        pl: 'wygodny',
        ar: 'مريح',
        ger: 'bequem',
        lt: 'patogus',
        key: '14',
        norEgz: 'Denne stolen er komfortabel.',
        soundLink: '',
        wordId: 14
      },
      {
        nor: 'kjapp',
        eng: 'quick',
        pl: 'szybki',
        ar: 'سريع',
        ger: 'schnell',
        lt: 'greitas',
        key: '15',
        norEgz: 'Han er kjapp til å løse problemer.',
        soundLink: '',
        wordId: 15
      },
      {
        nor: 'en vinter',
        eng: 'a winter',
        pl: 'zima',
        ar: 'شتاء',
        ger: 'ein Winter',
        lt: 'žiema',
        key: '16',
        norEgz: 'Det snør om vinteren.',
        soundLink: '',
        wordId: 16
      },
      {
        nor: 'en vår',
        eng: 'a spring',
        pl: 'wiosna',
        ar: 'ربيع',
        ger: 'ein Frühling',
        lt: 'pavasaris',
        key: '17',
        norEgz: 'Våren er min favoritt årstid.',
        soundLink: '',
        wordId: 17
      },
      {
        nor: 'en sommer',
        eng: 'a summer',
        pl: 'lato',
        ar: 'صيف',
        ger: 'ein Sommer',
        lt: 'vasara',
        key: '18',
        norEgz: 'Sommerværet er varmt og solrikt.',
        soundLink: '',
        wordId: 18
      },
      {
        nor: 'å planlegge',
        eng: 'to plan',
        pl: 'planować',
        ar: 'يخطط',
        ger: 'planen',
        lt: 'planuoti',
        key: '19',
        norEgz: 'Vi må planlegge ferien vår.',
        soundLink: '',
        wordId: 19
      },
      {
        nor: 'å hilse',
        eng: 'to greet',
        pl: 'witać',
        ar: 'يحيي',
        ger: 'grüßen',
        lt: 'sveikintis',
        key: '20',
        norEgz: 'Hun hilste på naboene sine.',
        soundLink: '',
        wordId: 20
      },
      {
        nor: 'en utdanning',
        eng: 'an education',
        pl: 'edukacja',
        ar: 'تعليم',
        ger: 'eine Bildung',
        lt: 'švietimas',
        key: '21',
        norEgz: 'Utdanning er viktig for fremtiden.',
        soundLink: '',
        wordId: 21
      },
      {
        nor: 'en karakter',
        eng: 'a character',
        pl: 'postać',
        ar: 'شخصية',
        ger: 'eine Figur',
        lt: 'personažas',
        key: '22',
        norEgz: 'Han er en interessant karakter i boken.',
        soundLink: '',
        wordId: 22
      },
      {
        nor: 'en elg',
        eng: 'a moose',
        pl: 'łoś',
        ar: 'موظ',
        ger: 'ein Elch',
        lt: 'briedis',
        key: '23',
        norEgz: 'Vi så en elg i skogen.',
        soundLink: '',
        wordId: 23
      },
      {
        nor: 'et brev',
        eng: 'a letter',
        pl: 'list',
        ar: 'خطاب',
        ger: 'ein Brief',
        lt: 'laiškas',
        key: '24',
        norEgz: 'Jeg fikk et brev i posten.',
        soundLink: '',
        wordId: 24
      },
      {
        nor: 'enkel',
        eng: 'simple',
        pl: 'prosty',
        ar: 'بسيط',
        ger: 'einfach',
        lt: 'paprastas',
        key: '25',
        norEgz: 'Dette er en enkel oppgave.',
        soundLink: '',
        wordId: 25
      },
      {
        nor: 'komplisert',
        eng: 'complicated',
        pl: 'skomplikowany',
        ar: 'معقد',
        ger: 'kompliziert',
        lt: 'sudėtingas',
        key: '26',
        norEgz: 'Matematikk er komplisert.',
        soundLink: '',
        wordId: 26
      },
      {
        nor: 'viktig',
        eng: 'important',
        pl: 'ważny',
        ar: 'مهم',
        ger: 'wichtig',
        lt: 'svarbus',
        key: '27',
        norEgz: 'Det er viktig å spise sunt.',
        soundLink: '',
        wordId: 27
      },
      {
        nor: 'å legge seg',
        eng: 'to go to bed',
        pl: 'kłaść się spać',
        ar: 'الذهاب إلى الفراش',
        ger: 'ins Bett gehen',
        lt: 'eiti miegoti',
        key: '28',
        norEgz: 'Hun legger seg tidlig hver kveld.',
        soundLink: '',
        wordId: 28
      },
      {
        nor: 'å prøve',
        eng: 'to try',
        pl: 'próbować',
        ar: 'يجرب',
        ger: 'versuchen',
        lt: 'bandyti',
        key: '29',
        norEgz: 'Jeg vil prøve denne kaken.',
        soundLink: '',
        wordId: 29
      },
      {
        nor: 'tynn',
        eng: 'thin',
        pl: 'chudy',
        ar: 'رفيع',
        ger: 'dünn',
        lt: 'plonas',
        key: '30',
        norEgz: 'Dette teppet er veldig tynn.',
        soundLink: '',
        wordId: 30
      },
      {
        nor: 'høflig',
        eng: 'polite',
        pl: 'uprzejmy',
        ar: 'مهذب',
        ger: 'höflich',
        lt: 'mandagus',
        key: '31',
        norEgz: 'Han er alltid høflig mot andre.',
        soundLink: '',
        wordId: 31
      },
      {
        nor: 'uhøflig',
        eng: 'rude',
        pl: 'niegrzeczny',
        ar: 'غير مهذب',
        ger: 'unhöflich',
        lt: 'nemandagus',
        key: '32',
        norEgz: 'Det er uhøflig å avbryte andre.',
        soundLink: '',
        wordId: 32
      },
      {
        nor: 'effektiv',
        eng: 'efficient',
        pl: 'wydajny',
        ar: 'فعّال',
        ger: 'effizient',
        lt: 'efektyvus',
        key: '33',
        norEgz: 'Denne metoden er veldig effektiv.',
        soundLink: '',
        wordId: 33
      },
      {
        nor: 'en krukke',
        eng: 'a jar',
        pl: 'słoik',
        ar: 'جرة',
        ger: 'ein Glas',
        lt: 'indelis',
        key: '34',
        norEgz: 'Hun oppbevarer honning i en krukke.',
        soundLink: '',
        wordId: 34
      },
      {
        nor: 'en bensinstasjon',
        eng: 'a gas station',
        pl: 'stacja benzynowa',
        ar: 'محطة وقود',
        ger: 'eine Tankstelle',
        lt: 'degalinė',
        key: '35',
        norEgz: 'Vi må stoppe ved en bensinstasjon.',
        soundLink: '',
        wordId: 35
      },
      {
        nor: 'en fabrikk',
        eng: 'a factory',
        pl: 'fabryka',
        ar: 'مصنع',
        ger: 'eine Fabrik',
        lt: 'fabrikas',
        key: '36',
        norEgz: 'Han jobber i en fabrikk.',
        soundLink: '',
        wordId: 36
      },
      {
        nor: 'et bakeri',
        eng: 'a bakery',
        pl: 'piekarnia',
        ar: 'مخبز',
        ger: 'eine Bäckerei',
        lt: 'kepykla',
        key: '37',
        norEgz: 'De kjøper brød fra et bakeri.',
        soundLink: '',
        wordId: 37
      },
      {
        nor: 'en frisør',
        eng: 'a hairdresser',
        pl: 'fryzjer',
        ar: 'مصفف شعر',
        ger: 'ein Friseur',
        lt: 'kirpėjas',
        key: '38',
        norEgz: 'Jeg har time hos en frisør i morgen.',
        soundLink: '',
        wordId: 38
      },
      {
        nor: 'å huske',
        eng: 'to remember',
        pl: 'pamiętać',
        ar: 'تذكر',
        ger: 'sich erinnern',
        lt: 'atsiminti',
        key: '39',
        norEgz: 'Jeg prøver å huske navnet hans.',
        soundLink: '',
        wordId: 39
      },
      {
        nor: 'å glemme',
        eng: 'to forget',
        pl: 'zapominać',
        ar: 'ينسى',
        ger: 'vergessen',
        lt: 'pamiršti',
        key: '40',
        norEgz: 'Han pleier å glemme nøklene sine.',
        soundLink: '',
        wordId: 40
      },
      {
        nor: 'en maler',
        eng: 'a painter',
        pl: 'malarz',
        ar: 'رسام',
        ger: 'ein Maler',
        lt: 'dažytojas',
        key: '41',
        norEgz: 'Hun er en talentfull maler.',
        soundLink: '',
        wordId: 41
      },
      {
        nor: 'en elektriker',
        eng: 'an electrician',
        pl: 'elektryk',
        ar: 'كهربائي',
        ger: 'ein Elektriker',
        lt: 'elektrikas',
        key: '42',
        norEgz: 'Vi trenger en elektriker for å fikse ledningene.',
        soundLink: '',
        wordId: 42
      },
      {
        nor: 'en tunnel',
        eng: 'a tunnel',
        pl: 'tunel',
        ar: 'نفق',
        ger: 'ein Tunnel',
        lt: 'tunelis',
        key: '43',
        norEgz: 'Bilen kjører gjennom en tunnel.',
        soundLink: '',
        wordId: 43
      },
      {
        nor: 'en frukt',
        eng: 'a fruit',
        pl: 'owoc',
        ar: 'فاكهة',
        ger: 'eine Frucht',
        lt: 'vaisius',
        key: '44',
        norEgz: 'Eplet er en frukt.',
        soundLink: '',
        wordId: 44
      },
      {
        nor: 'en grønnsak',
        eng: 'a vegetable',
        pl: 'warzywo',
        ar: 'خضروات',
        ger: 'ein Gemüse',
        lt: 'daržovė',
        key: '45',
        norEgz: 'Gulroten er en grønnsak.',
        soundLink: '',
        wordId: 45
      },
      {
        nor: 'ineffektiv',
        eng: 'inefficient',
        pl: 'nieefektywny',
        ar: 'غير فعال',
        ger: 'ineffizient',
        lt: 'neefektyvus',
        key: '46',
        norEgz: 'Den gamle metoden er ineffektiv.',
        soundLink: '',
        wordId: 46
      },
      {
        nor: 'trygg',
        eng: 'safe',
        pl: 'bezpieczny',
        ar: 'آمن',
        ger: 'sicher',
        lt: 'saugus',
        key: '47',
        norEgz: 'Dette området er trygt.',
        soundLink: '',
        wordId: 47
      },
      {
        nor: 'farlig',
        eng: 'dangerous',
        pl: 'niebezpieczny',
        ar: 'خطر',
        ger: 'gefährlich',
        lt: 'pavojingas',
        key: '48',
        norEgz: 'Kjør forsiktig, veien er farlig.',
        soundLink: '',
        wordId: 48
      },
      {
        nor: 'høylytt',
        eng: 'loud',
        pl: 'głośny',
        ar: 'عالي الصوت',
        ger: 'laut',
        lt: 'garsus',
        key: '49',
        norEgz: 'Musikken er veldig høylytt.',
        soundLink: '',
        wordId: 49
      },
      {
        nor: 'en passasjer',
        eng: 'a passenger',
        pl: 'pasażer',
        ar: 'راكب',
        ger: 'ein Fahrgast',
        lt: 'keleivis',
        key: '50',
        norEgz: 'En passasjer venter på toget.',
        soundLink: '',
        wordId: 50
      },
      {
        nor: 'en sjåfør',
        eng: 'a driver',
        pl: 'kierowca',
        ar: 'سائق',
        ger: 'ein Fahrer',
        lt: 'vairuotojas',
        key: '51',
        norEgz: 'Sjåføren kjører bussen.',
        soundLink: '',
        wordId: 51
      },
      {
        nor: 'en servitør',
        eng: 'a waiter',
        pl: 'kelner',
        ar: 'نادل',
        ger: 'ein Kellner',
        lt: 'padavėjas',
        key: '52',
        norEgz: 'Servitøren tar bestillingen vår.',
        soundLink: '',
        wordId: 52
      },
      {
        nor: 'en selger',
        eng: 'a seller',
        pl: 'sprzedawca',
        ar: 'بائع',
        ger: 'ein Verkäufer',
        lt: 'pardavėjas',
        key: '53',
        norEgz: 'En selger hjelper kunden med å velge en vare.',
        soundLink: '',
        wordId: 53
      },
      {
        nor: 'å lukte',
        eng: 'to smell',
        pl: 'pachnieć',
        ar: 'يشم',
        ger: 'riechen',
        lt: 'uostyti',
        key: '54',
        norEgz: 'Blomstene lukter godt.',
        soundLink: '',
        wordId: 54
      },
      {
        nor: 'å finne',
        eng: 'to find',
        pl: 'znaleźć',
        ar: 'يجد',
        ger: 'finden',
        lt: 'rasti',
        key: '55',
        norEgz: 'Jeg prøver å finne nøklene mine.',
        soundLink: '',
        wordId: 55
      },
      {
        nor: 'en direktør',
        eng: 'a director',
        pl: 'dyrektor',
        ar: 'مدير',
        ger: 'ein Direktor',
        lt: 'direktorius',
        key: '56',
        norEgz: 'Direktøren styrer selskapet.',
        soundLink: '',
        wordId: 56
      },
      {
        nor: 'et skilt',
        eng: 'a sign',
        pl: 'znak',
        ar: 'إشارة',
        ger: 'ein Schild',
        lt: 'ženklas',
        key: '57',
        norEgz: 'Følg skiltene til flyplassen.',
        soundLink: '',
        wordId: 57
      },
      {
        nor: 'en billett',
        eng: 'a ticket',
        pl: 'bilet',
        ar: 'تذكرة',
        ger: 'ein Ticket',
        lt: 'bilietas',
        key: '58',
        norEgz: 'Jeg har billett til et tog.',
        soundLink: '',
        wordId: 58
      },
      {
        nor: 'en lege',
        eng: 'a doctor',
        pl: 'lekarz',
        ar: 'طبيب',
        ger: 'ein Arzt',
        lt: 'gydytojas',
        key: '59',
        norEgz: 'Hun må gå til en lege for å få råd.',
        soundLink: '',
        wordId: 59
      },
      {
        nor: 'en heis',
        eng: 'an elevator',
        pl: 'winda',
        ar: 'مصعد',
        ger: 'ein Aufzug',
        lt: 'liftas',
        key: '60',
        norEgz: 'Vi tok heisen opp til femte etasje.',
        soundLink: '',
        wordId: 60
      },
      {
        nor: 'en trapp',
        eng: 'a staircase',
        pl: 'schody',
        ar: 'درج',
        ger: 'eine Treppe',
        lt: 'laiptai',
        key: '61',
        norEgz: 'Hun gikk opp trappen.',
        soundLink: '',
        wordId: 61
      },
      {
        nor: 'å smake',
        eng: 'to taste',
        pl: 'smakować',
        ar: 'يتذوق',
        ger: 'schmecken',
        lt: 'ragauti',
        key: '62',
        norEgz: 'Hun smakte på suppen.',
        soundLink: '',
        wordId: 62
      },
      {
        nor: 'å tro',
        eng: 'to believe',
        pl: 'wierzyć',
        ar: 'يعتقد',
        ger: 'glauben',
        lt: 'tikėti',
        key: '63',
        norEgz: 'Jeg tror det kommer til å regne i morgen.',
        soundLink: '',
        wordId: 63
      },
      {
        nor: 'sunn',
        eng: 'healthy',
        pl: 'zdrowy',
        ar: 'صحي',
        ger: 'gesund',
        lt: 'sveikas',
        key: '64',
        norEgz: 'Grønnsaker er sunne.',
        soundLink: '',
        wordId: 64
      },
      {
        nor: 'usunn',
        eng: 'unhealthy',
        pl: 'niezdrowy',
        ar: 'غير صحي',
        ger: 'ungesund',
        lt: 'nesveikas',
        key: '65',
        norEgz: 'For mye sukker er usunt.',
        soundLink: '',
        wordId: 65
      },
      {
        nor: 'tykk',
        eng: 'thick',
        pl: 'gruby',
        ar: 'سميك',
        ger: 'dick',
        lt: 'storas',
        key: '66',
        norEgz: 'Denne boken er veldig tykk.',
        soundLink: '',
        wordId: 66
      },
      {
        nor: 'en musiker',
        eng: 'a musician',
        pl: 'muzyk',
        ar: 'موسيقي',
        ger: 'ein Musiker',
        lt: 'muzikantas',
        key: '67',
        norEgz: '',
        soundLink: 'Han er en stor musiker.',
        wordId: 67
      },
      {
        nor: 'en danser',
        eng: 'a dancer',
        pl: 'tancerz',
        ar: 'راقص',
        ger: 'ein Tänzer',
        lt: 'šokėjas',
        key: '68',
        norEgz: 'Hun er en talentfull danser.',
        soundLink: '',
        wordId: 68
      },
      {
        nor: 'en kunstner',
        eng: 'an artist',
        pl: 'artysta',
        ar: 'فنان',
        ger: 'ein Künstler',
        lt: 'menininkas',
        key: '69',
        norEgz: 'Han er en berømt kunstner.',
        soundLink: '',
        wordId: 69
      },
      {
        nor: 'en reporter',
        eng: 'a reporter',
        pl: 'reporter',
        ar: 'مراسل',
        ger: 'ein Reporter',
        lt: 'reporteris',
        key: '70',
        norEgz: 'Reporteren intervjuet politikeren.',
        soundLink: '',
        wordId: 70
      },
      {
        nor: 'jevn',
        eng: 'smooth',
        pl: 'gładki',
        ar: 'ناعم',
        ger: 'glatt',
        lt: 'lygus',
        key: '71',
        norEgz: 'Overflaten er jevn og fin.',
        soundLink: '',
        wordId: 71
      },
      {
        nor: 'å frykte',
        eng: 'to fear',
        pl: 'bać się',
        ar: 'خوف',
        ger: 'fürchten',
        lt: 'bijoti',
        key: '72',
        norEgz: 'Han frykter høyder.',
        soundLink: '',
        wordId: 72
      },
      {
        nor: 'å håpe',
        eng: 'to hope',
        pl: 'mieć nadzieję',
        ar: 'أمل',
        ger: 'hoffen',
        lt: 'tikėtis',
        key: '73',
        norEgz: 'Vi håper på godt vær i morgen.',
        soundLink: '',
        wordId: 73
      },
      {
        nor: 'en advokat',
        eng: 'a lawyer',
        pl: 'adwokat',
        ar: 'محام',
        ger: 'ein Anwalt',
        lt: 'advokatas',
        key: '74',
        norEgz: 'Hun er en dyktig advokat.',
        soundLink: '',
        wordId: 74
      },
      {
        nor: 'en kokk',
        eng: 'a cook',
        pl: 'kucharz',
        ar: 'طباخ',
        ger: 'ein Koch',
        lt: 'virtuvės šefas',
        key: '75',
        norEgz: 'Han er en talentfull kokk.',
        soundLink: '',
        wordId: 75
      },
      {
        nor: 'et instrument',
        eng: 'an instrument',
        pl: 'instrument',
        ar: 'آلة موسيقية',
        ger: 'ein Instrument',
        lt: 'instrumentas',
        key: '76',
        norEgz: 'Hun spiller et musikkinstrument.',
        soundLink: '',
        wordId: 76
      },
      {
        nor: 'en tromme',
        eng: 'a drum',
        pl: 'bęben',
        ar: 'طبل',
        ger: 'eine Trommel',
        lt: 'būgnas',
        key: '77',
        norEgz: 'Han spiller på en tromme.',
        soundLink: '',
        wordId: 77
      },
      {
        nor: 'en gitar',
        eng: 'a guitar',
        pl: 'gitara',
        ar: 'جيتار',
        ger: 'eine Gitarre',
        lt: 'gitara',
        key: '78',
        norEgz: 'Hun spiller gitar i et band.',
        soundLink: '',
        wordId: 78
      },
      {
        nor: 'å elske',
        eng: 'to love',
        pl: 'kochać',
        ar: 'يحب',
        ger: 'lieben',
        lt: 'mylėti',
        key: '79',
        norEgz: 'Jeg elsker deg.',
        soundLink: '',
        wordId: 79
      },
      {
        nor: 'å hate',
        eng: 'to hate',
        pl: 'nienawidzić',
        ar: 'يكره',
        ger: 'hassen',
        lt: 'nekęsti',
        key: '80',
        norEgz: 'Hun hater å vente.',
        soundLink: '',
        wordId: 80
      },
      {
        nor: 'å bære',
        eng: 'to carry',
        pl: 'nosić',
        ar: 'يحمل',
        ger: 'tragen',
        lt: 'nešti',
        key: '81',
        norEgz: 'Han bærer en tung ryggsekk.',
        soundLink: '',
        wordId: 81
      },
      {
        nor: 'å ringe',
        eng: 'to call',
        pl: 'dzwonić',
        ar: 'يتصل',
        ger: 'anrufen',
        lt: 'skambinti',
        key: '82',
        norEgz: 'Jeg ringer deg i kveld.',
        soundLink: '',
        wordId: 82
      },
      {
        nor: 'en reservasjon',
        eng: 'a reservation',
        pl: 'rezerwacja',
        ar: 'حجز',
        ger: 'eine Reservierung',
        lt: 'rezervacija',
        key: '83',
        norEgz: 'Vi har en reservasjon for to personer.',
        soundLink: '',
        wordId: 83
      },
      {
        nor: 'en planet',
        eng: 'a planet',
        pl: 'planeta',
        ar: 'كوكب',
        ger: 'ein Planet',
        lt: 'planeta',
        key: '84',
        norEgz: 'Jorden er en planet i solsystemet.',
        soundLink: '',
        wordId: 84
      },
      {
        nor: 'et høst',
        eng: 'an autumn',
        pl: 'jesień',
        ar: 'خريف',
        ger: 'ein Herbst',
        lt: 'ruduo',
        key: '85',
        norEgz: 'Høst er en vakker årstid med fargerike blader.',
        soundLink: '',
        wordId: 85
      },
      {
        nor: 'uviktig',
        eng: 'unimportant',
        pl: 'nieistotny',
        ar: 'غير مهم',
        ger: 'unwichtig',
        lt: 'nesvarbu',
        key: '86',
        norEgz: 'Det er uviktig hvilken farge du velger.',
        soundLink: '',
        wordId: 86
      },
      {
        nor: 'sulten',
        eng: 'hungry',
        pl: 'głodny',
        ar: 'جائع',
        ger: 'hungrig',
        lt: 'alčiai',
        key: '87',
        norEgz: 'Jeg er veldig sulten.',
        soundLink: '',
        wordId: 87
      },
      {
        nor: 'mett',
        eng: 'full',
        pl: 'pełny',
        ar: 'شبعان',
        ger: 'satt',
        lt: 'pilnas',
        key: '88',
        norEgz: 'Jeg er mett etter den store middagen.',
        soundLink: '',
        wordId: 88
      },
      {
        nor: 'en eksamen',
        eng: 'an exam',
        pl: 'egzamin',
        ar: 'امتحان',
        ger: 'eine Prüfung',
        lt: 'egzaminas',
        key: '89',
        norEgz: 'Jeg har en viktig eksamen i morgen.',
        soundLink: '',
        wordId: 89
      },
      {
        nor: 'et emne',
        eng: 'a subject',
        pl: 'przedmiot',
        ar: 'موضوع',
        ger: 'ein Fach',
        lt: 'tema',
        key: '90',
        norEgz: 'Matematikk er et utfordrende emne.',
        soundLink: '',
        wordId: 90
      },
      {
        nor: 'en timeplan',
        eng: 'a schedule',
        pl: 'plan',
        ar: 'جدول',
        ger: 'ein Zeitplan',
        lt: 'tvarkaraštis',
        key: '91',
        norEgz: 'Jeg må sjekke timeplanen min for neste uke.',
        soundLink: '',
        wordId: 91
      },
      {
        nor: 'en pause',
        eng: 'a break',
        pl: 'przerwa',
        ar: 'استراحة',
        ger: 'eine Pause',
        lt: 'pertrauka',
        key: '92',
        norEgz: 'Vi tar en pause etter denne økten.',
        soundLink: '',
        wordId: 92
      },
      {
        nor: 'å bruke',
        eng: 'to use',
        pl: 'używać',
        ar: 'استعمل',
        ger: 'benutzen',
        lt: 'naudoti',
        key: '93',
        norEgz: 'Jeg bruker en blyant for å tegne.',
        soundLink: '',
        wordId: 93
      },
      {
        nor: 'å skjære',
        eng: 'to cut',
        pl: 'kroić',
        ar: 'قطع',
        ger: 'schneiden',
        lt: 'pjaustyti',
        key: '94',
        norEgz: 'Kan du skjære brødet for meg?',
        soundLink: '',
        wordId: 94
      },
      {
        nor: 'å føle',
        eng: 'to feel',
        pl: 'czuć',
        ar: 'يشعر',
        ger: 'fühlen',
        lt: 'jausti',
        key: '95',
        norEgz: 'Jeg føler meg trøtt i dag.',
        soundLink: '',
        wordId: 95
      },
      {
        nor: 'et hjørne',
        eng: 'a corner',
        pl: 'róg',
        ar: 'زاوية',
        ger: 'eine Ecke',
        lt: 'kampas',
        key: '96',
        norEgz: 'Møt meg ved hjørnet av gaten.',
        soundLink: '',
        wordId: 96
      },
      {
        nor: 'en vegg',
        eng: 'a wall',
        pl: 'ściana',
        ar: 'جدار',
        ger: 'eine Wand',
        lt: 'siena',
        key: '97',
        norEgz: 'Han hang bildet på veggen.',
        soundLink: '',
        wordId: 97
      },
      {
        nor: 'en grense',
        eng: 'a border',
        pl: 'granica',
        ar: 'حدود',
        ger: 'eine Grenze',
        lt: 'siena',
        key: '98',
        norEgz: 'Vi krysset grensen til Sverige.',
        soundLink: '',
        wordId: 98
      },
      {
        nor: 'en inngang',
        eng: 'an entrance',
        pl: 'wejście',
        ar: 'مدخل',
        ger: 'ein Eingang',
        lt: 'įėjimas',
        key: '99',
        norEgz: 'Inngangen til bygningen er på baksiden.',
        soundLink: '',
        wordId: 99
      },
      {
        nor: 'en utgang',
        eng: 'an exit',
        pl: 'wyjście',
        ar: 'مخرج',
        ger: 'ein Ausgang',
        lt: 'išėjimas',
        key: '100',
        norEgz: 'Finn nærmeste utgang i tilfelle nødsituasjon.',
        soundLink: '',
        wordId: 100
      },
      {
        nor: 'tørst',
        eng: 'thirsty',
        pl: 'spragniony',
        ar: 'عطشان',
        ger: 'durstig',
        lt: 'ištroškęs',
        key: '101',
        norEgz: 'Jeg er tørst og trenger vann.',
        soundLink: '',
        wordId: 101
      },
      {
        nor: 'rik',
        eng: 'rich',
        pl: 'bogaty',
        ar: 'غني',
        ger: 'reich',
        lt: 'turtingas',
        key: '102',
        norEgz: 'Han er en rik forretningsmann.',
        soundLink: '',
        wordId: 102
      },
      {
        nor: 'et marked',
        eng: 'a market',
        pl: 'rynek',
        ar: 'سوق',
        ger: 'ein Markt',
        lt: 'turgus',
        key: '103',
        norEgz: 'Vi skal besøke det lokale markedet i morgen.',
        soundLink: '',
        wordId: 103
      },
      {
        nor: 'en dyrehage',
        eng: 'a zoo',
        pl: 'ogród zoologiczny',
        ar: 'حديقة حيوان',
        ger: 'ein Zoo',
        lt: 'zoologijos sodas',
        key: '104',
        norEgz: 'Vi tok barna med til dyrehagen i helgen.',
        soundLink: '',
        wordId: 104
      },
      {
        nor: 'en hage',
        eng: 'a garden',
        pl: 'ogród',
        ar: 'حديقة',
        ger: 'ein Garten',
        lt: 'sodas',
        key: '105',
        norEgz: 'Hun har en vakker hage bak huset sitt.',
        soundLink: '',
        wordId: 105
      },
      {
        nor: 'en strand',
        eng: 'a beach',
        pl: 'plaża',
        ar: 'شاطئ',
        ger: 'ein Strand',
        lt: 'paplūdimys',
        key: '106',
        norEgz: 'Vi tilbrakte dagen på stranden.',
        soundLink: '',
        wordId: 106
      },
      {
        nor: 'å holde',
        eng: 'to hold',
        pl: 'trzymać',
        ar: 'يمسك',
        ger: 'halten',
        lt: 'laikyti',
        key: '107',
        norEgz: 'Kan du holde vesken min et øyeblikk?',
        soundLink: '',
        wordId: 107
      },
      {
        nor: 'å skrike',
        eng: 'to scream',
        pl: 'krzyczeć',
        ar: 'يصرخ',
        ger: 'schreien',
        lt: 'šaukti',
        key: '108',
        norEgz: 'Hun skrek av smerte da hun falt.',
        soundLink: '',
        wordId: 108
      },
      {
        nor: 'å rope',
        eng: 'to shout',
        pl: 'wołać',
        ar: 'يصيح',
        ger: 'rufen',
        lt: 'šaukti',
        key: '109',
        norEgz: 'Han ropte navnet mitt fra den andre siden av gaten.',
        soundLink: '',
        wordId: 109
      },
      {
        nor: 'en tallerken',
        eng: 'a plate',
        pl: 'talerz',
        ar: 'طبق',
        ger: 'ein Teller',
        lt: 'lėkštė',
        key: '110',
        norEgz: 'Kan du sende meg den blå tallerkenen?',
        soundLink: '',
        wordId: 110
      },
      {
        nor: 'en skje',
        eng: 'a spoon',
        pl: 'łyżka',
        ar: 'ملعقة',
        ger: 'ein Löffel',
        lt: 'šaukštas',
        key: '111',
        norEgz: 'Jeg trenger en skje for å røre i suppen.',
        soundLink: '',
        wordId: 111
      },
      {
        nor: 'praktisk',
        eng: 'practical',
        pl: 'praktyczny',
        ar: 'عملي',
        ger: 'praktisch',
        lt: 'praktiškas',
        key: '112',
        norEgz: 'Å ha en bil er veldig praktisk i denne byen.',
        soundLink: '',
        wordId: 112
      },
      {
        nor: 'upraktisk',
        eng: 'impractical',
        pl: 'niepraktyczny',
        ar: 'غير عملي',
        ger: 'unpraktisch',
        lt: 'nepraktiškas',
        key: '113',
        norEgz: 'Denne vesken er upraktisk for reiser.',
        soundLink: '',
        wordId: 113
      },
      {
        nor: 'morsom',
        eng: 'fun',
        pl: 'zabawny',
        ar: 'ممتع',
        ger: 'lustig',
        lt: 'linksmas',
        key: '114',
        norEgz: 'Vi hadde en morsom dag på fornøyelsesparken.',
        soundLink: '',
        wordId: 114
      },
      {
        nor: 'en gaffel',
        eng: 'a fork',
        pl: 'widelec',
        ar: 'شوكة',
        ger: 'eine Gabel',
        lt: 'šakutė',
        key: '115',
        norEgz: 'Kan du gi meg en gaffel, vær så snill?',
        soundLink: '',
        wordId: 115
      },
      {
        nor: 'en kniv',
        eng: 'a knife',
        pl: 'nóż',
        ar: 'سكين',
        ger: 'ein Messer',
        lt: 'peilis',
        key: '116',
        norEgz: 'Pass på at du håndterer kniven forsiktig.',
        soundLink: '',
        wordId: 116
      },
      {
        nor: 'en blyant',
        eng: 'a pencil',
        pl: 'ołówek',
        ar: 'قلم رصاص',
        ger: 'ein Bleistift',
        lt: 'pieštukas',
        key: '117',
        norEgz: 'Hun tegnet et vakkert bilde med en blyant.',
        soundLink: '',
        wordId: 117
      },
      {
        nor: 'å kysse',
        eng: 'to kiss',
        pl: 'całować',
        ar: 'يُقبِّل',
        ger: 'küssen',
        lt: 'bučiuoti',
        key: '118',
        norEgz: 'De kysset hverandre under mistelteinen.',
        soundLink: '',
        wordId: 118
      },
      {
        nor: 'å sykle',
        eng: 'to cycle',
        pl: 'jeździć na rowerze',
        ar: 'يَركَب الدَرّاجَة',
        ger: 'Rad fahren',
        lt: 'važiuoti dviračiu',
        key: '119',
        norEgz: 'Vi liker å sykle sammen i parken.',
        soundLink: '',
        wordId: 119
      },
      {
        nor: 'å varsel',
        eng: 'to warn',
        pl: 'ostrzegać',
        ar: 'يحذر',
        ger: 'warnen',
        lt: 'įspėti',
        key: '120',
        norEgz: 'Han varslet oss om den kommende stormen.',
        soundLink: '',
        wordId: 120
      },
      {
        nor: 'fattig',
        eng: 'poor',
        pl: 'biedny',
        ar: 'فقير',
        ger: 'arm',
        lt: 'varžtas',
        key: '121',
        norEgz: 'Han vokste opp i en fattig familie.',
        soundLink: '',
        wordId: 121
      },
      {
        nor: 'en regnbue',
        eng: 'a rainbow',
        pl: 'tęcza',
        ar: 'قوس قزح',
        ger: 'ein Regenbogen',
        lt: 'vaivorykštė',
        key: '122',
        norEgz: 'Vi så en vakker regnbue etter regnet.',
        soundLink: '',
        wordId: 122
      },
      {
        nor: 'et kart',
        eng: 'a map',
        pl: 'mapa',
        ar: 'خريطة',
        ger: 'eine Karte',
        lt: 'žemėlapis',
        key: '123',
        norEgz: 'Hun studerte kartet før hun begynte å kjøre.',
        soundLink: '',
        wordId: 123
      },
      {
        nor: 'trøtt',
        eng: 'tired',
        pl: 'zmęczony',
        ar: 'متعب',
        ger: 'müde',
        lt: 'pavargęs',
        key: '124',
        norEgz: '',
        soundLink: 'Han er trøtt etter jobb.',
        wordId: 124
      },
      {
        nor: 'våken',
        eng: 'awake',
        pl: 'obudzony',
        ar: 'مستيقظ',
        ger: 'wach',
        lt: 'pabudęs',
        key: '125',
        norEgz: 'Hun var våken hele natten.',
        soundLink: '',
        wordId: 125
      },
      {
        nor: 'ærlig',
        eng: 'honest',
        pl: 'szczery',
        ar: 'صادق',
        ger: 'ehrlich',
        lt: 'nuoširdus',
        key: '126',
        norEgz: 'Han er en ærlig person.',
        soundLink: '',
        wordId: 126
      },
      {
        nor: 'uærlig',
        eng: 'dishonest',
        pl: 'nieuczciwy',
        ar: 'غير أمين',
        ger: 'unehrlich',
        lt: 'nepasitikintis',
        key: '127',
        norEgz: 'Uærlige mennesker er vanskelig å stole på.',
        soundLink: '',
        wordId: 127
      },
      {
        nor: 'å skjule',
        eng: 'to hide',
        pl: 'ukrywać',
        ar: 'يختبئ',
        ger: 'verstecken',
        lt: 'paslėpti',
        key: '128',
        norEgz: '',
        soundLink: 'Han prøver å skjule hemmeligheter.',
        wordId: 128
      },
      {
        nor: 'å puste',
        eng: 'to breathe',
        pl: 'oddychać',
        ar: 'يتنفس',
        ger: 'atmen',
        lt: 'kvėpuoti',
        key: '129',
        norEgz: 'Hun lærte å puste dypt under yoga-timene.',
        soundLink: '',
        wordId: 129
      },
      {
        nor: 'en festival',
        eng: 'a festival',
        pl: 'festiwal',
        ar: 'مهرجان',
        ger: 'ein Festival',
        lt: 'festivalis',
        key: '130',
        norEgz: 'Vi gleder oss til å delta på musikkfestivalen.',
        soundLink: '',
        wordId: 130
      },
      {
        nor: 'en bonde',
        eng: 'a farmer',
        pl: 'rolnik',
        ar: 'مزارع',
        ger: 'ein Bauer',
        lt: 'ūkininkas',
        key: '131',
        norEgz: 'Bonden jobber hardt for å dyrke avlingene sine.',
        soundLink: '',
        wordId: 131
      },
      {
        nor: 'mulig',
        eng: 'possible',
        pl: 'możliwy',
        ar: 'ممكن',
        ger: 'möglich',
        lt: 'galima',
        key: '132',
        norEgz: 'Det er mulig å reise til månen.',
        soundLink: '',
        wordId: 132
      }, 
      {
        nor: 'umulig',
        eng: 'impossible',
        pl: 'niemożliwe',
        ar: 'مستحيل',
        ger: 'unmöglich',
        lt: 'neįmanoma',
        key: '133',
        norEgz: 'Det virker umulig å fullføre oppgaven.',
        soundLink: '',
        wordId: 133
      },
      {
        nor: 'nødvendig',
        eng: 'necessary',
        pl: 'konieczny',
        ar: 'ضروري',
        ger: 'notwendig',
        lt: 'būtina',
        key: '134',
        norEgz: 'Det er nødvendig å forberede seg før eksamen.',
        soundLink: '',
        wordId: 134
      },
      {
        nor: 'en ferie',
        eng: 'a holiday',
        pl: 'wakacje',
        ar: 'عطلة',
        ger: 'ein Urlaub',
        lt: 'atostogos',
        key: '135',
        norEgz: 'Vi planlegger en ferie til Spania neste sommer.',
        soundLink: '',
        wordId: 135
      },
      {
        nor: 'en håndball',
        eng: 'a handball',
        pl: 'piłka ręczna',
        ar: 'كرة اليد',
        ger: 'ein Handball',
        lt: 'rankinis',
        key: '136',
        norEgz: 'Hun spiller håndball for skolelaget.',
        soundLink: '',
        wordId: 136
      },
      {
        nor: 'å smitte',
        eng: 'to infect',
        pl: 'zarażać',
        ar: 'يعدي',
        ger: 'anstecken',
        lt: 'užkrėsti',
        key: '137',
        norEgz: 'Influensaviruset kan smitte andre mennesker raskt.',
        soundLink: '',
        wordId: 137
      },
      {
        nor: 'å leve',
        eng: 'to live',
        pl: 'żyć',
        ar: 'يعيش',
        ger: 'leben',
        lt: 'gyventi',
        key: '138',
        norEgz: 'Vi må lære å leve i harmoni med naturen.',
        soundLink: '',
        wordId: 138
      },
      {
        nor: 'å beskytte',
        eng: 'to protect',
        pl: 'chronić',
        ar: 'يحمي',
        ger: 'schützen',
        lt: 'apsaugoti',
        key: '139',
        norEgz: 'Vi må beskytte miljøet for kommende generasjoner.',
        soundLink: '',
        wordId: 139
      },
      {
        nor: 'en svømming',
        eng: 'a swimming',
        pl: 'pływanie',
        ar: 'سباحة',
        ger: 'ein Schwimmen',
        lt: 'plaukimas',
        key: '140',
        norEgz: 'Han deltar i en svømming konkurranse neste uke.',
        soundLink: '',
        wordId: 140
      },
      {
        nor: 'en ski',
        eng: 'a ski',
        pl: 'narta',
        ar: 'تزلج',
        ger: 'ein Ski',
        lt: 'slidinė',
        key: '141',
        norEgz: 'Han kjøpte en ny ski for vinteren.',
        soundLink: '',
        wordId: 141
      },
      {
        nor: 'å dekke',
        eng: 'to cover',
        pl: 'pokrywać',
        ar: 'يغطي',
        ger: 'abdecken',
        lt: 'dengti',
        key: '142',
        norEgz: 'Vi må dekke bordet før gjestene kommer.',
        soundLink: '',
        wordId: 142
      },
      {
        nor: 'å grave',
        eng: 'to dig',
        pl: 'kopać',
        ar: 'يحفر',
        ger: 'graben',
        lt: 'kasti',
        key: '143',
        norEgz: 'Han begynte å grave et hull i hagen.',
        soundLink: '',
        wordId: 143
      },
      {
        nor: 'å fly',
        eng: 'to fly',
        pl: 'lecieć',
        ar: 'يطير',
        ger: 'fliegen',
        lt: 'skristi',
        key: '144',
        norEgz: 'Fuglene begynte å fly sørover for vinteren.',
        soundLink: '',
        wordId: 144
      },
      {
        nor: 'en ishockey',
        eng: 'ice hockey',
        pl: 'hokej na lodzie',
        ar: 'هوكي الجليد',
        ger: 'Eishockey',
        lt: 'ledoritulys',
        key: '145',
        norEgz: 'Han er en stor fan av ishockey.',
        soundLink: '',
        wordId: 145
      },
      {
        nor: 'en basket',
        eng: 'basketball',
        pl: 'koszykówka',
        ar: 'كرة السلة',
        ger: 'Basketball',
        lt: 'krepšinis',
        key: '146',
        norEgz: 'De spiller basket etter skolen.',
        soundLink: '',
        wordId: 146
      },
      {
        nor: 'en volleyball',
        eng: 'volleyball',
        pl: 'siatkówka',
        ar: 'كرة الطائرة',
        ger: 'Volleyball',
        lt: 'tinklinis',
        key: '147',
        norEgz: 'De deltar i en volleyball turnering.',
        soundLink: '',
        wordId: 147
      },
      {
        nor: 'unødvendig',
        eng: 'unnecessary',
        pl: 'niepotrzebny',
        ar: 'غير ضروري',
        ger: 'unnötig',
        lt: 'nereikalingas',
        key: '148',
        norEgz: 'Det er unødvendig å bekymre seg.',
        soundLink: '',
        wordId: 148
      },
      {
        nor: 'frisk',
        eng: 'fresh',
        pl: 'świeży',
        ar: 'طازج',
        ger: 'frisch',
        lt: 'šviežias',
        key: '149',
        norEgz: 'Luften er frisk her.',
        soundLink: '',
        wordId: 149
      },
      {
        nor: 'stille',
        eng: 'quiet',
        pl: 'cichy',
        ar: 'هادئ',
        ger: 'ruhig',
        lt: 'tylus',
        key: '150',
        norEgz: 'Det er så stille her.',
        soundLink: '',
        wordId: 150
      },
      {
        nor: 'en fiolin',
        eng: 'a violin',
        pl: 'skrzypce',
        ar: 'كمان',
        ger: 'eine Violine',
        lt: 'smuikas',
        key: '151',
        norEgz: 'Han spiller på en fiolin.',
        soundLink: '',
        wordId: 151
      },
      {
        nor: 'et medlem',
        eng: 'a member',
        pl: 'członek',
        ar: 'عضو',
        ger: 'ein Mitglied',
        lt: 'narys',
        key: '152',
        norEgz: 'Han er et medlem av klubben.',
        soundLink: '',
        wordId: 152
      },
      {
        nor: 'å bade',
        eng: 'to bathe',
        pl: 'kąpać się',
        ar: 'الاستحمام',
        ger: 'baden',
        lt: 'maudytis',
        key: '153',
        norEgz: 'Vi liker å bade i sjøen.',
        soundLink: '',
        wordId: 153
      },
      {
        nor: 'å vaske',
        eng: 'to wash',
        pl: 'myć',
        ar: 'غسل',
        ger: 'waschen',
        lt: 'plauti',
        key: '154',
        norEgz: 'Jeg må vaske klærne mine.',
        soundLink: '',
        wordId: 154
      },
      {
        nor: 'å tørke',
        eng: 'to dry',
        pl: 'suszyć',
        ar: 'يجف',
        ger: 'trocknen',
        lt: 'džiovinti',
        key: '155',
        norEgz: 'Jeg må tørke klærne mine.',
        soundLink: '',
        wordId: 155
        },
        {
        nor: 'en besøkende',
        eng: 'a visitor',
        pl: 'zwiedzający',
        ar: 'زائر',
        ger: 'ein Besucher',
        lt: 'lankytojas',
        key: '156',
        norEgz: 'Vi har en besøkende fra Tyskland.',
        soundLink: '',
        wordId: 156
        },
        {
        nor: 'en turist',
        eng: 'a tourist',
        pl: 'turysta',
        ar: 'سائح',
        ger: 'ein Tourist',
        lt: 'turistas',
        key: '157',
        norEgz: 'Turisten tok bilder av severdighetene.',
        soundLink: '',
        wordId: 157
        },
        {
        nor: 'ujevn',
        eng: 'uneven',
        pl: 'nierówny',
        ar: 'غير مستو',
        ger: 'unregelmäßig',
        lt: 'nelygus',
        key: '158',
        norEgz: 'Gulvet er ujevnt.',
        soundLink: '',
        wordId: 158
        },
        {
        nor: 'lokal',
        eng: 'local',
        pl: 'lokalny',
        ar: 'محلي',
        ger: 'lokal',
        lt: 'vietinis',
        key: '159',
        norEgz: 'Den lokale butikken har gode priser.',
        soundLink: '',
        wordId: 159
        },
        {
        nor: 'en konsert',
        eng: 'a concert',
        pl: 'koncert',
        ar: 'حفلة موسيقية',
        ger: 'ein Konzert',
        lt: 'koncertas',
        key: '160',
        norEgz: 'Jeg gleder meg til konserten i kveld.',
        soundLink: '',
        wordId: 160
        },
        {
        nor: 'en skuff',
        eng: 'a drawer',
        pl: 'szuflada',
        ar: 'درج',
        ger: 'eine Schublade',
        lt: 'stalčius',
        key: '161',
        norEgz: 'Jeg åpnet en skuff for å finne en skje.',
        soundLink: '',
        wordId: 161
        },
        {
        nor: 'å krympe',
        eng: 'to shrink',
        pl: 'kurczyć się',
        ar: 'تقلص',
        ger: 'schrumpfen',
        lt: 'traukti',
        key: '162',
        norEgz: 'Denne genseren krymper hvis du vasker den på høy temperatur.',
        soundLink: '',
        wordId: 162
        },
        {
        nor: 'å bli kvitt',
        eng: 'to get rid of',
        pl: 'pozbyć się',
        ar: 'التخلص من',
        ger: 'loswerden',
        lt: 'atbristi',
        key: '163',
        norEgz: 'Vi må bli kvitt dette gamle skapet.',
        soundLink: '',
        wordId: 163
        },
        {
        nor: 'å blande',
        eng: 'to mix',
        pl: 'mieszać',
        ar: 'خلط',
        ger: 'mischen',
        lt: 'maišyti',
        key: '164',
        norEgz: 'Hun blandet ingrediensene sammen i en bolle.',
        soundLink: '',
        wordId: 164
        },
        {
        nor: 'et skap',
        eng: 'a cabinet',
        pl: 'szafka',
        ar: 'خزانة',
        ger: 'ein Schrank',
        lt: 'spintelė',
        key: '165',
        norEgz: 'Hun hentet tallerkener fra skapet.',
        soundLink: '',
        wordId: 165
        },
        {
        nor: 'en leilighet',
        eng: 'an apartment',
        pl: 'mieszkanie',
        ar: 'شقة',
        ger: 'eine Wohnung',
        lt: 'butas',
        key: '166',
        norEgz: 'Hun bor i en liten leilighet i byen.',
        soundLink: '',
        wordId: 166
        },
        {
        nor: 'å riste',
        eng: 'to shake',
        pl: 'potrząsać',
        ar: 'هز',
        ger: 'schütteln',
        lt: 'kratyti',
        key: '167',
        norEgz: 'Hun ristet på hodet.',
        soundLink: '',
        wordId: 167
        },
        {
        nor: 'å bekymre',
        eng: 'to worry',
        pl: 'martwić się',
        ar: 'القلق',
        ger: 'sich sorgen',
        lt: 'nerimauti',
        key: '168',
        norEgz: 'Du trenger ikke å bekymre deg.',
        soundLink: '',
        wordId: 168
        },
        {
        nor: 'å forlate',
        eng: 'to leave',
        pl: 'opuścić',
        ar: 'ترك',
        ger: 'verlassen',
        lt: 'palikti',
        key: '169',
        norEgz: 'Han forlot rommet.',
        soundLink: '',
        wordId: 169
        },
        {
        nor: 'å sukke',
        eng: 'to sigh',
        pl: 'wzdychać',
        ar: 'تنهد',
        ger: 'seufzen',
        lt: 'atsidegti',
        key: '170',
        norEgz: 'Hun sukket dypt.',
        soundLink: '',
        wordId: 170
        },
        {
        nor: 'intelligent',
        eng: 'intelligent',
        pl: 'inteligentny',
        ar: 'ذكي',
        ger: 'intelligent',
        lt: 'intelektualus',
        key: '171',
        norEgz: 'Han er en intelligent person.',
        soundLink: '',
        wordId: 171
        },
        {
        nor: 'dum',
        eng: 'stupid',
        pl: 'głupi',
        ar: 'غبي',
        ger: 'dumm',
        lt: 'kvailas',
        key: '172',
        norEgz: 'Det var en dum feil.',
        soundLink: '',
        wordId: 172
        },
        {
        nor: 'å tørste',
        eng: 'to thirst',
        pl: 'pragnąć',
        ar: 'يعطش',
        ger: 'durstig sein',
        lt: 'trokšti',
        key: '173',
        norEgz: 'Etter en lang tur, begynte han å tørste.',
        soundLink: '',
        wordId: 173
        }
    
]