[
    {
    nor: 'å forklare',
    eng: 'to explain',
    pl: 'wyjaśniać',
    ar: 'شرح',
    ger: 'erklären',
    lt: 'paaiškinti',
    key: '0',
    norEgz: 'Kan du forklare dette for meg?',
    soundLink: '',
    wordId: 0
    },
    {
    nor: 'å forsøke',
    eng: 'to attempt',
    pl: 'próbować',
    ar: 'محاولة',
    ger: 'versuchen',
    lt: 'bandyti',
    key: '1',
    norEgz: 'Han forsøkte å løse problemet.',
    soundLink: '',
    wordId: 1
    },
    {
    nor: 'en snekker',
    eng: 'a carpenter',
    pl: 'stolarz',
    ar: 'نجار',
    ger: 'ein Tischler',
    lt: 'dailidė',
    key: '2',
    norEgz: 'Snekkeren bygde et bord.',
    soundLink: '',
    wordId: 2
    },
    {
    nor: 'et rådhus',
    eng: 'a town hall',
    pl: 'ratusz',
    ar: 'قاعة المدينة',
    ger: 'ein Rathaus',
    lt: 'rotušė',
    key: '3',
    norEgz: 'Møtet finner sted på rådhuset.',
    soundLink: '',
    wordId: 3
    },
    {
    nor: 'en skuespiller',
    eng: 'an actor',
    pl: 'aktor',
    ar: 'ممثل',
    ger: 'ein Schauspieler',
    lt: 'aktorius',
    key: '4',
    norEgz: 'Han er en kjent skuespiller.',
    soundLink: '',
    wordId: 4
    },
    {
    nor: 'en ørken',
    eng: 'a desert',
    pl: 'pustynia',
    ar: 'صحراء',
    ger: 'eine Wüste',
    lt: 'dykuma',
    key: '5',
    norEgz: 'Sahara er en stor ørken.',
    soundLink: '',
    wordId: 5
    },
    {
    nor: 'en kyst',
    eng: 'a coast',
    pl: 'wybrzeże',
    ar: 'ساحل',
    ger: 'eine Küste',
    lt: 'pakrantė',
    key: '6',
    norEgz: 'Vi gikk en tur langs kysten.',
    soundLink: '',
    wordId: 6
    },
    {
        nor: 'en evolusjon',
        eng: 'an evolution',
        pl: 'ewolucja',
        ar: 'تطور',
        ger: 'eine Evolution',
        lt: 'evoliucija',
        key: '7',
        norEgz: 'Evolusjon er en langsom prosess.',
        soundLink: '',
        wordId: 7
      },
    {
        nor: 'en foss',
        eng: 'a waterfall',
        pl: 'wodospad',
        ar: 'شلال',
        ger: 'ein Wasserfall',
        lt: 'krioklys',
        key: '8',
        norEgz: 'Vi besøkte en foss i ferien.',
        soundLink: '',
        wordId: 8
      },
      {
        nor: 'nøyaktig',
        eng: 'accurate',
        pl: 'dokładny',
        ar: 'دقيق',
        ger: 'genau',
        lt: 'tikslus',
        key: '9',
        norEgz: 'Målingene hans var nøyaktige.',
        soundLink: '',
        wordId: 9
      },
      {
        nor: 'unøyaktig',
        eng: 'inaccurate',
        pl: 'niedokładny',
        ar: 'غير دقيق',
        ger: 'ungenau',
        lt: 'netikslus',
        key: '10',
        norEgz: 'Rapporten inneholder unøyaktige data.',
        soundLink: '',
        wordId: 10
      },
      {
        nor: 'ambisiøs',
        eng: 'ambitious',
        pl: 'ambitny',
        ar: 'طموح',
        ger: 'ehrgeizig',
        lt: 'ambicingas',
        key: '11',
        norEgz: 'Hun er en ambisiøs student.',
        soundLink: '',
        wordId: 11
      },
      {
        nor: 'en politiker',
        eng: 'a politician',
        pl: 'polityk',
        ar: 'سياسي',
        ger: 'ein Politiker',
        lt: 'politikas',
        key: '12',
        norEgz: 'Han er en kjent politiker i Norge.',
        soundLink: '',
        wordId: 12
      },
      {
        nor: 'en historie',
        eng: 'a story',
        pl: 'historia',
        ar: 'قصة',
        ger: 'eine Geschichte',
        lt: 'istorija',
        key: '13',
        norEgz: 'Han fortalte en spennende historie.',
        soundLink: '',
        wordId: 13
      },
      {
        nor: 'en økonomi',
        eng: 'an economy',
        pl: 'gospodarka',
        ar: 'اقتصاد',
        ger: 'eine Wirtschaft',
        lt: 'ekonomika',
        key: '14',
        norEgz: 'Norge har en sterk økonomi.',
        soundLink: '',
        wordId: 14
      },
      {
        nor: 'selvsikker',
        eng: 'confident',
        pl: 'pewny siebie',
        ar: 'واثق',
        ger: 'selbstbewusst',
        lt: 'pasitikintis',
        key: '15',
        norEgz: 'Han er en selvsikker person.',
        soundLink: '',
        wordId: 15
      },
      {
        nor: 'å godta',
        eng: 'to accept',
        pl: 'akceptować',
        ar: 'يقبل',
        ger: 'akzeptieren',
        lt: 'priimti',
        key: '16',
        norEgz: 'Han bestemte seg for å godta tilbudet.',
        soundLink: '',
        wordId: 16
      },
      {
        nor: 'å handle',
        eng: 'to act',
        pl: 'działać',
        ar: 'يتصرف',
        ger: 'handeln',
        lt: 'veikti',
        key: '17',
        norEgz: 'Vi må handle raskt for å løse problemet.',
        soundLink: '',
        wordId: 17
      },
      {
        nor: 'å hjelpe',
        eng: 'to help',
        pl: 'pomagać',
        ar: 'مساعدة',
        ger: 'helfen',
        lt: 'padėti',
        key: '18',
        norEgz: 'Jeg er her for å hjelpe deg.',
        soundLink: '',
        wordId: 18
      },
      {
        nor: 'en politikk',
        eng: 'a policy',
        pl: 'polityka',
        ar: 'سياسة',
        ger: 'eine Politik',
        lt: 'politika',
        key: '19',
        norEgz: 'Regjeringen innførte en ny politikk.',
        soundLink: '',
        wordId: 19
      },
      {
        nor: 'en økologi',
        eng: 'an ecology',
        pl: 'ekologia',
        ar: 'بيئة',
        ger: 'eine Ökologie',
        lt: 'ekologija',
        key: '20',
        norEgz: 'Studenter lærer om økologi og miljøvern.',
        soundLink: '',
        wordId: 20
      },
      {
        nor: 'en art',
        eng: 'a species',
        pl: 'gatunek',
        ar: 'نوع',
        ger: 'eine Art',
        lt: 'rūšis',
        key: '21',
        norEgz: 'Denne planten tilhører en sjelden art.',
        soundLink: '',
        wordId: 21
      },
      {
        nor: 'usikker',
        eng: 'uncertain',
        pl: 'niepewny',
        ar: 'غير مؤكد',
        ger: 'unsicher',
        lt: 'neaiškus',
        key: '22',
        norEgz: 'Vi er usikre på hva vi skal gjøre.',
        soundLink: '',
        wordId: 22
      },
      {
        nor: 'kreativ',
        eng: 'creative',
        pl: 'kreatywny',
        ar: 'مبدع',
        ger: 'kreativ',
        lt: 'kūrybingas',
        key: '23',
        norEgz: 'Hun er en kreativ person.',
        soundLink: '',
        wordId: 23
      },
      {
        nor: 'lojal',
        eng: 'loyal',
        pl: 'lojalny',
        ar: 'مخلص',
        ger: 'loyal',
        lt: 'lojalus',
        key: '24',
        norEgz: 'Han er en lojal venn.',
        soundLink: '',
        wordId: 24
      },
      {
        nor: 'en arkeologi',
        eng: 'archaeology',
        pl: 'archeologia',
        ar: 'علم الآثار',
        ger: 'Archäologie',
        lt: 'arkeologija',
        key: '25',
        norEgz: 'Arkeologi er studiet av menneskets fortid.',
        soundLink: '',
        wordId: 25
      },
      {
        nor: 'et monument',
        eng: 'a monument',
        pl: 'pomnik',
        ar: 'نصب تذكاري',
        ger: 'ein Denkmal',
        lt: 'paminklas',
        key: '26',
        norEgz: 'Monumentet står i sentrum av byen.',
        soundLink: '',
        wordId: 26
      },
      {
        nor: 'en skulptur',
        eng: 'a sculpture',
        pl: 'rzeźba',
        ar: 'نحت',
        ger: 'eine Skulptur',
        lt: 'skulptūra',
        key: '27',
        norEgz: 'Skulpturen er laget av bronse.',
        soundLink: '',
        wordId: 27
      },
      {
        nor: 'en maleri',
        eng: 'a painting',
        pl: 'obraz',
        ar: 'لوحة',
        ger: 'ein Gemälde',
        lt: 'tapyba',
        key: '28',
        norEgz: 'Maleriet henger på veggen.',
        soundLink: '',
        wordId: 28
      },
      {
        nor: 'en fotografi',
        eng: 'a photograph',
        pl: 'fotografia',
        ar: 'صورة',
        ger: 'ein Foto',
        lt: 'fotografija',
        key: '29',
        norEgz: 'Fotografiet viser en vakker solnedgang.',
        soundLink: '',
        wordId: 29
      },
      {
        nor: 'en tekstil',
        eng: 'a textile',
        pl: 'tekstylia',
        ar: 'نسيج',
        ger: 'ein Textil',
        lt: 'tekstilė',
        key: '30',
        norEgz: 'Tekstilet er laget av bomull.',
        soundLink: '',
        wordId: 30
      },
      {
        nor: 'å invitere',
        eng: 'to invite',
        pl: 'zapraszać',
        ar: 'يدعو',
        ger: 'einladen',
        lt: 'pakviesti',
        key: '31',
        norEgz: 'Jeg vil invitere deg til festen.',
        soundLink: '',
        wordId: 31
      },
      {
        nor: 'å klage',
        eng: 'to complain',
        pl: 'skarżyć się',
        ar: 'يتذمر',
        ger: 'sich beschweren',
        lt: 'skųstis',
        key: '32',
        norEgz: 'Han klager alltid over været.',
        soundLink: '',
        wordId: 32
      },
      {
        nor: 'en teori',
        eng: 'a theory',
        pl: 'teoria',
        ar: 'نظرية',
        ger: 'eine Theorie',
        lt: 'teorija',
        key: '33',
        norEgz: 'Einsteins relativitetsteori endret fysikkens verden.',
        soundLink: '',
        wordId: 33
      },
      {
        nor: 'en hypotese',
        eng: 'a hypothesis',
        pl: 'hipoteza',
        ar: 'فرضية',
        ger: 'eine Hypothese',
        lt: 'hipotezė',
        key: '34',
        norEgz: 'Forskeren testet hypotesen sin gjennom eksperimenter.',
        soundLink: '',
        wordId: 34
      },
      {
        nor: 'en metode',
        eng: 'a method',
        pl: 'metoda',
        ar: 'طريقة',
        ger: 'eine Methode',
        lt: 'metodas',
        key: '35',
        norEgz: 'Han bruker en ny metode for å løse problemet.',
        soundLink: '',
        wordId: 35
      },
      {
        nor: 'en prosedyre',
        eng: 'a procedure',
        pl: 'procedura',
        ar: 'إجراء',
        ger: 'ein Verfahren',
        lt: 'procedūra',
        key: '36',
        norEgz: 'Legekontoret har en standard prosedyre for å håndtere pasienter.',
        soundLink: '',
        wordId: 36
      },
      {
        nor: 'et eksperiment',
        eng: 'an experiment',
        pl: 'eksperyment',
        ar: 'تجربة',
        ger: 'ein Experiment',
        lt: 'eksperimentas',
        key: '37',
        norEgz: 'Eksperimentet ble utført i laboratoriet.',
        soundLink: '',
        wordId: 37
      },
      {
        nor: 'å klatre',
        eng: 'to climb',
        pl: 'wspinać się',
        ar: 'تسلق',
        ger: 'klettern',
        lt: 'lipti',
        key: '38',
        norEgz: 'Han liker å klatre i fjellet.',
        soundLink: '',
        wordId: 38
      },
      {
        nor: 'en analyse',
        eng: 'an analysis',
        pl: 'analiza',
        ar: 'تحليل',
        ger: 'eine Analyse',
        lt: 'analizė',
        key: '39',
        norEgz: 'Analyse av dataene viste interessante mønstre.',
        soundLink: '',
        wordId: 39
      },
      {
        nor: 'sjalu',
        eng: 'jealous',
        pl: 'zazdrosny',
        ar: 'غيور',
        ger: 'eifersüchtig',
        lt: 'pavydus',
        key: '40',
        norEgz: 'Han var sjalu på sin brors suksess.',
        soundLink: '',
        wordId: 40
      },
      {
        nor: 'optimistisk',
        eng: 'optimistic',
        pl: 'optymistyczny',
        ar: 'متفائل',
        ger: 'optimistisch',
        lt: 'optimistiškas',
        key: '41',
        norEgz: 'Han er alltid optimistisk om fremtiden.',
        soundLink: '',
        wordId: 41
      },
      {
        nor: 'pessimistisk',
        eng: 'pessimistic',
        pl: 'pesymistyczny',
        ar: 'متشائم',
        ger: 'pessimistisch',
        lt: 'pesimistiškas',
        key: '42',
        norEgz: 'Hun har en pessimistisk holdning til livet.',
        soundLink: '',
        wordId: 42
      },
      {
        nor: 'en strategi',
        eng: 'a strategy',
        pl: 'strategia',
        ar: 'استراتيجية',
        ger: 'eine Strategie',
        lt: 'strategija',
        key: '43',
        norEgz: 'Bedriften trenger en ny markedsføringsstrategi.',
        soundLink: '',
        wordId: 43
      },
      {
        nor: 'en taktikk',
        eng: 'a tactic',
        pl: 'taktyka',
        ar: 'تكتيك',
        ger: 'eine Taktik',
        lt: 'taktika',
        key: '44',
        norEgz: 'Lagets taktikk førte til seier.',
        soundLink: '',
        wordId: 44
      },
      {
        nor: 'en logikk',
        eng: 'a logic',
        pl: 'logika',
        ar: 'منطق',
        ger: 'eine Logik',
        lt: 'logika',
        key: '45',
        norEgz: 'Det er viktig å forstå logikken bak beslutningen.',
        soundLink: '',
        wordId: 45
      },
      {
        nor: 'en grammatikk',
        eng: 'a grammar',
        pl: 'gramatyka',
        ar: 'قواعد',
        ger: 'eine Grammatik',
        lt: 'gramatika',
        key: '46',
        norEgz: 'Å lære grammatikk er viktig for språkforståelse.',
        soundLink: '',
        wordId: 46
      },
      {
        nor: 'å lage',
        eng: 'to make',
        pl: 'robić',
        ar: 'يصنع',
        ger: 'machen',
        lt: 'daryti',
        key: '47',
        norEgz: 'Hun liker å lage mat fra bunnen av.',
        soundLink: '',
        wordId: 47
      },
      {
        nor: 'å låne',
        eng: 'to borrow',
        pl: 'pożyczyć',
        ar: 'اقتراض',
        ger: 'ausleihen',
        lt: 'pasiskolinti',
        key: '48',
        norEgz: 'Han ba om å låne boken min.',
        soundLink: '',
        wordId: 48
      },
      {
        nor: 'å mene',
        eng: 'to think',
        pl: 'myśleć',
        ar: 'يظن',
        ger: 'meinen',
        lt: 'manyti',
        key: '49',
        norEgz: 'Hun mente at det var en god idé.',
        soundLink: '',
        wordId: 49
      },
      {
        nor: 'en kultur',
        eng: 'a culture',
        pl: 'kultura',
        ar: 'ثقافة',
        ger: 'eine Kultur',
        lt: 'kultūra',
        key: '50',
        norEgz: 'Norge har en rik kultur.',
        soundLink: '',
        wordId: 50
      },
      {
        nor: 'en tradisjon',
        eng: 'a tradition',
        pl: 'tradycja',
        ar: 'تقليد',
        ger: 'eine Tradition',
        lt: 'tradicija',
        key: '51',
        norEgz: 'Julen er en viktig tradisjon i Norge.',
        soundLink: '',
        wordId: 51
      },
      {
        nor: 'en ressurs',
        eng: 'a resource',
        pl: 'zasób',
        ar: 'مورد',
        ger: 'eine Ressource',
        lt: 'išteklius',
        key: '52',
        norEgz: 'Vann er en viktig ressurs for mennesker.',
        soundLink: '',
        wordId: 52
      },
      {
        nor: 'å nekte',
        eng: 'to deny',
        pl: 'zaprzeczać',
        ar: 'ينكر',
        ger: 'verneinen',
        lt: 'neigti',
        key: '53',
        norEgz: 'Han nektet for å ha tatt pengene.',
        soundLink: '',
        wordId: 53
      },
      {
        nor: 'å overraske',
        eng: 'to surprise',
        pl: 'zaskoczyć',
        ar: 'يفاجأ',
        ger: 'überraschen',
        lt: 'nustebinti',
        key: '54',
        norEgz: 'Hun overrasket ham med en gave.',
        soundLink: '',
        wordId: 54
      },
      {
        nor: 'å regne',
        eng: 'to count',
        pl: 'liczyć',
        ar: 'يعد',
        ger: 'zählen',
        lt: 'skaičiuoti',
        key: '55',
        norEgz: 'Han begynte å regne opp alle fordelene.',
        soundLink: '',
        wordId: 55
      },
      {
        nor: 'sjenerøs',
        eng: 'generous',
        pl: 'hojny',
        ar: 'كريم',
        ger: 'großzügig',
        lt: 'dosnus',
        key: '56',
        norEgz: 'Han er en sjenerøs person.',
        soundLink: '',
        wordId: 56
      },
      {
        nor: 'uvanlig',
        eng: 'unusual',
        pl: 'niezwykły',
        ar: 'غير عادي',
        ger: 'ungewöhnlich',
        lt: 'neįprastas',
        key: '57',
        norEgz: 'Det er uvanlig å se snø her.',
        soundLink: '',
        wordId: 57
      },
      {
        nor: 'vanlig',
        eng: 'usual',
        pl: 'zwykły',
        ar: 'عادي',
        ger: 'üblich',
        lt: 'įprastas',
        key: '58',
        norEgz: 'Det er vanlig å drikke kaffe om morgenen.',
        soundLink: '',
        wordId: 58
      },
      {
        nor: 'en empati',
        eng: 'empathy',
        pl: 'empatia',
        ar: 'التعاطف',
        ger: 'Empathie',
        lt: 'empatija',
        key: '59',
        norEgz: 'Han viste stor empati overfor andre.',
        soundLink: '',
        wordId: 59
      },
      {
        nor: 'en toleranse',
        eng: 'tolerance',
        pl: 'tolerancja',
        ar: 'التسامح',
        ger: 'Toleranz',
        lt: 'tolerancija',
        key: '60',
        norEgz: 'Samfunnet trenger mer toleranse.',
        soundLink: '',
        wordId: 60
      },
      {
        nor: 'en prestasjon',
        eng: 'achievement',
        pl: 'osiągnięcie',
        ar: 'إنجاز',
        ger: 'Leistung',
        lt: 'pasiekimas',
        key: '61',
        norEgz: 'Dette er en stor prestasjon for teamet.',
        soundLink: '',
        wordId: 61
      },
      {
        nor: 'en bordtennis',
        eng: 'table tennis',
        pl: 'tenis stołowy',
        ar: 'تنس الطاولة',
        ger: 'Tischtennis',
        lt: 'stalo tenisas',
        key: '62',
        norEgz: 'Vi spiller bordtennis etter jobb.',
        soundLink: '',
        wordId: 62
      },
      {
        nor: 'en borger',
        eng: 'citizen',
        pl: 'obywatel',
        ar: 'مواطن',
        ger: 'Bürger',
        lt: 'pilietis',
        key: '63',
        norEgz: 'Han er en stolt borger av sitt land.',
        soundLink: '',
        wordId: 63
      },
      {
        nor: 'en psykolog',
        eng: 'psychologist',
        pl: 'psycholog',
        ar: 'عالم نفس',
        ger: 'Psychologe',
        lt: 'psichologas',
        key: '64',
        norEgz: 'Hun besøkte en psykolog for å få hjelp.',
        soundLink: '',
        wordId: 64
      },
      {
        nor: 'en programmerer',
        eng: 'programmer',
        pl: 'programista',
        ar: 'مبرمج',
        ger: 'Programmierer',
        lt: 'programuotojas',
        key: '65',
        norEgz: 'Han jobber som en programmerer.',
        soundLink: '',
        wordId: 65
      },
      {
        nor: 'å skjønne',
        eng: 'to understand',
        pl: 'rozumieć',
        ar: 'أن يفهم',
        ger: 'verstehen',
        lt: 'suprasti',
        key: '66',
        norEgz: 'Jeg prøver å skjønne hva du mener.',
        soundLink: '',
        wordId: 66
      },
      {
        nor: 'å tillate',
        eng: 'to allow',
        pl: 'pozwalać',
        ar: 'السماح',
        ger: 'erlauben',
        lt: 'leisti',
        key: '67',
        norEgz: 'Foreldrene tillater ikke festen.',
        soundLink: '',
        wordId: 67
      },
      {
        nor: 'å trenge',
        eng: 'to need',
        pl: 'potrzebować',
        ar: 'يحتاج',
        ger: 'brauchen',
        lt: 'reikėti',
        key: '68',
        norEgz: 'Han trenger en ny bil.',
        soundLink: '',
        wordId: 68
      },
      {
        nor: 'en arkitekt',
        eng: 'architect',
        pl: 'architekt',
        ar: 'مهندس معماري',
        ger: 'Architekt',
        lt: 'architektas',
        key: '69',
        norEgz: 'Hun jobber som en arkitekt.',
        soundLink: '',
        wordId: 69
      },
      {
        nor: 'en kjemi',
        eng: 'chemistry',
        pl: 'chemia',
        ar: 'كيمياء',
        ger: 'Chemie',
        lt: 'chemija',
        key: '70',
        norEgz: 'Kjemi er et interessant fag.',
        soundLink: '',
        wordId: 70
      },
      {
        nor: 'en fysikk',
        eng: 'physics',
        pl: 'fizyka',
        ar: 'فيزياء',
        ger: 'Physik',
        lt: 'fizika',
        key: '71',
        norEgz: 'Fysikk er studiet av naturens lover.',
        soundLink: '',
        wordId: 71
      },
      {
        nor: 'å velge',
        eng: 'to choose',
        pl: 'wybierać',
        ar: 'اختيار',
        ger: 'wählen',
        lt: 'pasirinkti',
        key: '72',
        norEgz: 'Du må velge mellom de to alternativene.',
        soundLink: '',
        wordId: 72
      },
      {
        nor: 'å ønske',
        eng: 'to wish',
        pl: 'życzyć',
        ar: 'يتمنى',
        ger: 'wünschen',
        lt: 'norėti',
        key: '73',
        norEgz: 'Jeg ønsker deg alt godt.',
        soundLink: '',
        wordId: 73
      },
      {
        nor: 'å diskutere',
        eng: 'to discuss',
        pl: 'dyskutować',
        ar: 'يناقش',
        ger: 'diskutieren',
        lt: 'diskutuoti',
        key: '74',
        norEgz: 'Vi må diskutere problemet.',
        soundLink: '',
        wordId: 74
      },
      {
        nor: 'en advarsel',
        eng: 'a warning',
        pl: 'ostrzeżenie',
        ar: 'تحذير',
        ger: 'eine Warnung',
        lt: 'įspėjimas',
        key: '75',
        norEgz: 'Han ga en advarsel for å kjøre for fort.',
        soundLink: '',
        wordId: 75
      },
      {
        nor: 'en veiledning',
        eng: 'a guidance',
        pl: 'poradnictwo',
        ar: 'توجيه',
        ger: 'eine Anleitung',
        lt: 'vadovavimas',
        key: '76',
        norEgz: 'Han trenger veiledning for å forbedre ferdighetene sine.',
        soundLink: '',
        wordId: 76
      },
      {
        nor: 'en støtte',
        eng: 'a support',
        pl: 'wsparcie',
        ar: 'دعم',
        ger: 'eine Unterstützung',
        lt: 'parama',
        key: '77',
        norEgz: 'Familien ga ham støtte i vanskelige tider.',
        soundLink: '',
        wordId: 77
      },
      {
        nor: 'et samarbeid',
        eng: 'a cooperation',
        pl: 'współpraca',
        ar: 'تعاون',
        ger: 'eine Zusammenarbeit',
        lt: 'bendradarbiavimas',
        key: '78',
        norEgz: 'De hadde et godt samarbeid på prosjektet.',
        soundLink: '',
        wordId: 78
      },
      {
        nor: 'en kommunikasjon',
        eng: 'a communication',
        pl: 'komunikacja',
        ar: 'اتصال',
        ger: 'eine Kommunikation',
        lt: 'komunikacija',
        key: '79',
        norEgz: 'Kommunikasjon er nøkkelen til et godt forhold.',
        soundLink: '',
        wordId: 79
      },
      {
        nor: 'en forståelse',
        eng: 'an understanding',
        pl: 'zrozumienie',
        ar: 'فهم',
        ger: 'ein Verständnis',
        lt: 'supratimas',
        key: '80',
        norEgz: 'De kom til en forståelse etter samtalen.',
        soundLink: '',
        wordId: 80
      },
      {
        nor: 'solid',
        eng: 'solid',
        pl: 'solidny',
        ar: 'صلب',
        ger: 'solide',
        lt: 'tvirtas',
        key: '81',
        norEgz: 'Dette bordet er veldig solid og stødig.',
        soundLink: '',
        wordId: 81
      },
      {
        nor: 'å hente',
        eng: 'to fetch',
        pl: 'przynieść',
        ar: 'جلب',
        ger: 'holen',
        lt: 'atnešti',
        key: '82',
        norEgz: 'Kan du hente boken fra hylla?',
        soundLink: '',
        wordId: 82
      },
      {
        nor: 'spontan',
        eng: 'spontaneous',
        pl: 'spontaniczny',
        ar: 'عفوي',
        ger: 'spontan',
        lt: 'spontaniškas',
        key: '83',
        norEgz: 'Hun er en veldig spontan person.',
        soundLink: '',
        wordId: 83
      },
      {
        nor: 'forutsigbar',
        eng: 'predictable',
        pl: 'przewidywalny',
        ar: 'يمكن التنبؤ به',
        ger: 'vorhersehbar',
        lt: 'numatomas',
        key: '84',
        norEgz: 'Filmen var ganske forutsigbar.',
        soundLink: '',
        wordId: 84
      },
      {
        nor: 'å fryse',
        eng: 'to freeze',
        pl: 'zamrażać',
        ar: 'يتجمد',
        ger: 'einfrieren',
        lt: 'šaldyti',
        key: '85',
        norEgz: 'Vannet begynte å fryse i kaldt vær.',
        soundLink: '',
        wordId: 85
      },
      {
        nor: 'å varme',
        eng: 'to warm',
        pl: 'ogrzewać',
        ar: 'يدفئ',
        ger: 'erwärmen',
        lt: 'šildyti',
        key: '86',
        norEgz: 'Hun varmet hendene ved bålet.',
        soundLink: '',
        wordId: 86
      },
      {
        nor: 'å kaste',
        eng: 'to throw',
        pl: 'rzucać',
        ar: 'يلقي',
        ger: 'werfen',
        lt: 'mesti',
        key: '87',
        norEgz: 'Han kastet ballen til henne.',
        soundLink: '',
        wordId: 87
      },
      {
        nor: 'en matematikk',
        eng: 'a mathematics',
        pl: 'matematyka',
        ar: 'رياضيات',
        ger: 'eine Mathematik',
        lt: 'matematika',
        key: '88',
        norEgz: 'Matematikk er et viktig skolefag.',
        soundLink: '',
        wordId: 88
      },
      {
        nor: 'en geometri',
        eng: 'a geometry',
        pl: 'geometria',
        ar: 'هندسة',
        ger: 'eine Geometrie',
        lt: 'geometrija',
        key: '89',
        norEgz: 'Geometri er en gren av matematikk.',
        soundLink: '',
        wordId: 89
      },
      {
        nor: 'å smelte',
        eng: 'to melt',
        pl: 'topić',
        ar: 'يذوب',
        ger: 'schmelzen',
        lt: 'tirpinti',
        key: '90',
        norEgz: 'Isen begynte å smelte i solen.',
        soundLink: '',
        wordId: 90
      },
      {
        nor: 'å slå',
        eng: 'to hit',
        pl: 'uderzać',
        ar: 'يضرب',
        ger: 'schlagen',
        lt: 'mušti',
        key: '91',
        norEgz: 'Han slo ballen med racketen.',
        soundLink: '',
        wordId: 91
      },
      {
        nor: 'å klemme',
        eng: 'to squeeze',
        pl: 'ściskać',
        ar: 'يعصر',
        ger: 'quetschen',
        lt: 'spausti',
        key: '92',
        norEgz: 'Hun klemte sitronen for å lage juice.',
        soundLink: '',
        wordId: 92
      },
      {
        nor: 'å tegne',
        eng: 'to draw',
        pl: 'rysować',
        ar: 'يرسم',
        ger: 'zeichnen',
        lt: 'piešti',
        key: '93',
        norEgz: 'Barnet tegner en hund på papiret.',
        soundLink: '',
        wordId: 93
      },
      {
        nor: 'å male',
        eng: 'to paint',
        pl: 'malować',
        ar: 'يدهن',
        ger: 'malen',
        lt: 'dažyti',
        key: '94',
        norEgz: 'Han maler landskapet med akvarellfarger.',
        soundLink: '',
        wordId: 94
      },
      {
        nor: 'grundig',
        eng: 'thorough',
        pl: 'gruntowny',
        ar: 'دقيق',
        ger: 'gründlich',
        lt: 'išsamus',
        key: '95',
        norEgz: 'Han gjorde en grundig undersøkelse av saken.',
        soundLink: '',
        wordId: 95
      },
      {
        nor: 'fleksibel',
        eng: 'flexible',
        pl: 'elastyczny',
        ar: 'مرن',
        ger: 'flexibel',
        lt: 'lankstus',
        key: '96',
        norEgz: 'Hun er fleksibel med arbeidstiden sin.',
        soundLink: '',
        wordId: 96
      },
      {
        nor: 'stiv',
        eng: 'stiff',
        pl: 'sztywny',
        ar: 'جامد',
        ger: 'steif',
        lt: 'kietas',
        key: '97',
        norEgz: 'Han følte seg stiv etter å ha sittet lenge.',
        soundLink: '',
        wordId: 97
      },
      {
        nor: 'konservativ',
        eng: 'conservative',
        pl: 'konserwatywny',
        ar: 'محافظ',
        ger: 'konservativ',
        lt: 'konservatyvus',
        key: '98',
        norEgz: 'Hennes politiske syn er ganske konservativt.',
        soundLink: '',
        wordId: 98
      },
      {
        nor: 'liberal',
        eng: 'liberal',
        pl: 'liberalny',
        ar: 'ليبرالي',
        ger: 'liberal',
        lt: 'liberalus',
        key: '99',
        norEgz: 'Han har liberale politiske synspunkter.',
        soundLink: '',
        wordId: 99
      },
      {
        nor: 'et samfunn',
        eng: 'a society',
        pl: 'społeczeństwo',
        ar: 'مجتمع',
        ger: 'eine Gesellschaft',
        lt: 'visuomenė',
        key: '100',
        norEgz: 'Samfunnet har endret seg mye de siste årene.',
        soundLink: '',
        wordId: 100
      },
      {
        nor: 'en verdi',
        eng: 'a value',
        pl: 'wartość',
        ar: 'قيمة',
        ger: 'ein Wert',
        lt: 'vertė',
        key: '101',
        norEgz: 'Respekt er en viktig verdi i kulturen vår.',
        soundLink: '',
        wordId: 101
      },
      {
        nor: 'en holdning',
        eng: 'an attitude',
        pl: 'postawa',
        ar: 'موقف',
        ger: 'eine Einstellung',
        lt: 'požiūris',
        key: '102',
        norEgz: 'Hans holdning til arbeid er svært positiv.',
        soundLink: '',
        wordId: 102
      },
      {
        nor: 'en baking',
        eng: 'baking',
        pl: 'pieczenie',
        ar: 'خبز',
        ger: 'Backen',
        lt: 'kepti',
        key: '103',
        norEgz: 'Hun elsker baking og lager deilige kaker.',
        soundLink: '',
        wordId: 103
      },
      {
        nor: 'en strikking',
        eng: 'knitting',
        pl: 'dzierganie',
        ar: 'حياكة',
        ger: 'Stricken',
        lt: 'nėrimas',
        key: '104',
        norEgz: 'Hun lærte strikking fra sin bestemor.',
        soundLink: '',
        wordId: 104
      },
      {
        nor: 'å telle',
        eng: 'to count',
        pl: 'liczyć',
        ar: 'يعد',
        ger: 'zählen',
        lt: 'skaičiuoti',
        key: '105',
        norEgz: 'Barnet lærer å telle til ti.',
        soundLink: '',
        wordId: 105
      },
      {
        nor: 'å bygge',
        eng: 'to build',
        pl: 'budować',
        ar: 'يبني',
        ger: 'bauen',
        lt: 'statyti',
        key: '106',
        norEgz: 'De bygger et nytt hus i nabolaget.',
        soundLink: '',
        wordId: 106
      },
      {
        nor: 'å skyve',
        eng: 'to push',
        pl: 'pchać',
        ar: 'يدفع',
        ger: 'schieben',
        lt: 'stumti',
        key: '107',
        norEgz: 'Han skyver bilen ut av snøen.',
        soundLink: '',
        wordId: 107
      },
      {
        nor: 'en bakterie',
        eng: 'a bacterium',
        pl: 'bakteria',
        ar: 'بكتيريا',
        ger: 'ein Bakterium',
        lt: 'bakterija',
        key: '108',
        norEgz: 'Bakterier kan forårsake infeksjoner.',
        soundLink: '',
        wordId: 108
      },
      {
        nor: 'en virus',
        eng: 'a virus',
        pl: 'wirus',
        ar: 'فيروس',
        ger: 'ein Virus',
        lt: 'virusas',
        key: '109',
        norEgz: 'Influensa er forårsaket av et virus.',
        soundLink: '',
        wordId: 109
      },
      {
        nor: 'et mikroskop',
        eng: 'a microscope',
        pl: 'mikroskop',
        ar: 'مجهر',
        ger: 'ein Mikroskop',
        lt: 'mikroskopas',
        key: '110',
        norEgz: 'Han ser på cellene gjennom et mikroskop.',
        soundLink: '',
        wordId: 110
      },
      {
        nor: 'en vaksine',
        eng: 'a vaccine',
        pl: 'szczepionka',
        ar: 'لقاح',
        ger: 'ein Impfstoff',
        lt: 'vakcina',
        key: '111',
        norEgz: 'Vaksinen hjelper med å forebygge sykdom.',
        soundLink: '',
        wordId: 111
      },
      {
        nor: 'en astronom',
        eng: 'an astronomer',
        pl: 'astronom',
        ar: 'فلكي',
        ger: 'ein Astronom',
        lt: 'astronomas',
        key: '112',
        norEgz: 'Astronomen studerer stjerner og galakser.',
        soundLink: '',
        wordId: 112
      },
      {
        nor: 'en geolog',
        eng: 'a geologist',
        pl: 'geolog',
        ar: 'جيولوجي',
        ger: 'ein Geologe',
        lt: 'geologas',
        key: '113',
        norEgz: 'Geologen undersøker jordens struktur.',
        soundLink: '',
        wordId: 113
      },
      {
        nor: 'et kontinent',
        eng: 'a continent',
        pl: 'kontynent',
        ar: 'قارة',
        ger: 'ein Kontinent',
        lt: 'žemynas',
        key: '114',
        norEgz: 'Afrika er et stort kontinent.',
        soundLink: '',
        wordId: 114
      },
      {
        nor: 'misfornøyd',
        eng: 'dissatisfied',
        pl: 'niezadowolony',
        ar: 'غير راض',
        ger: 'unzufrieden',
        lt: 'nepatenkintas',
        key: '115',
        norEgz: 'Han er misfornøyd med resultatet.',
        soundLink: '',
        wordId: 115
      },
      {
        nor: 'følsom',
        eng: 'sensitive',
        pl: 'wrażliwy',
        ar: 'حساس',
        ger: 'empfindlich',
        lt: 'jautrus',
        key: '116',
        norEgz: 'Hun er følsom for sterke lukter.',
        soundLink: '',
        wordId: 116
      },
      {
        nor: 'ufølsom',
        eng: 'insensitive',
        pl: 'niewrażliwy',
        ar: 'غير حساس',
        ger: 'unempfindlich',
        lt: 'nejausmus',
        key: '117',
        norEgz: 'Han er ufølsom for andres følelser.',
        soundLink: '',
        wordId: 117
      },
      {
        nor: 'overfladisk',
        eng: 'superficial',
        pl: 'powierzchowny',
        ar: 'سطحي',
        ger: 'oberflächlich',
        lt: 'paviršutiniškas',
        key: '118',
        norEgz: 'Deres samtale var overfladisk.',
        soundLink: '',
        wordId: 118
      },
      {
        nor: 'en vulkan',
        eng: 'a volcano',
        pl: 'wulkan',
        ar: 'بركان',
        ger: 'ein Vulkan',
        lt: 'uždegimas',
        key: '119',
        norEgz: 'En vulkan kan forårsake stor ødeleggelse.',
        soundLink: '',
        wordId: 119
      },
      {
        nor: 'en innvandring',
        eng: 'an immigration',
        pl: 'imigracja',
        ar: 'هجرة',
        ger: 'eine Einwanderung',
        lt: 'imigracija',
        key: '120',
        norEgz: 'Innvandring har formet Norge gjennom historien.',
        soundLink: '',
        wordId: 120
      },
      {
        nor: 'en utvandring',
        eng: 'an emigration',
        pl: 'emigracja',
        ar: 'هجرة',
        ger: 'eine Auswanderung',
        lt: 'emigracija',
        key: '121',
        norEgz: 'Mange nordmenn deltok i utvandring til USA på 1800-tallet.',
        soundLink: '',
        wordId: 121
      },
      {
        nor: 'en emigrasjon',
        eng: 'an emigration',
        pl: 'emigracja',
        ar: 'هجرة',
        ger: 'eine Auswanderung',
        lt: 'emigracija',
        key: '122',
        norEgz: 'Familien hans vurderte emigrasjon til Australia.',
        soundLink: '',
        wordId: 122
      },
      {
        nor: 'en inkludering',
        eng: 'an inclusion',
        pl: 'włączenie',
        ar: 'إدراج',
        ger: 'eine Einbeziehung',
        lt: 'įtraukimas',
        key: '123',
        norEgz: 'Inkludering er viktig i et mangfoldig samfunn.',
        soundLink: '',
        wordId: 123
      },
      {
        nor: 'å dra',
        eng: 'to pull',
        pl: 'ciągnąć',
        ar: 'يسحب',
        ger: 'ziehen',
        lt: 'traukti',
        key: '124',
        norEgz: 'Du må dra døren for å åpne den.',
        soundLink: '',
        wordId: 124
      },
      {
        nor: 'å brenne',
        eng: 'to burn',
        pl: 'palić',
        ar: 'يحترق',
        ger: 'brennen',
        lt: 'degti',
        key: '125',
        norEgz: 'Papiret begynte å brenne når det kom i kontakt med ilden.',
        soundLink: '',
        wordId: 125
      },
      {
        nor: 'å falle',
        eng: 'to fall',
        pl: 'upadać',
        ar: 'يسقط',
        ger: 'fallen',
        lt: 'kristi',
        key: '126',
        norEgz: 'Han snublet og falt på bakken.',
        soundLink: '',
        wordId: 126
      },
      {
        nor: 'å vokse',
        eng: 'to grow',
        pl: 'rosnąć',
        ar: 'ينمو',
        ger: 'wachsen',
        lt: 'augti',
        key: '127',
        norEgz: 'Trærne vokser hvert år.',
        soundLink: '',
        wordId: 127
      },
      {
        nor: 'en dialekt',
        eng: 'a dialect',
        pl: 'dialekt',
        ar: 'لهجة',
        ger: 'ein Dialekt',
        lt: 'tarmė',
        key: '128',
        norEgz: 'Norge har mange forskjellige dialekter.',
        soundLink: '',
        wordId: 128
      },
      {
        nor: 'en retorikk',
        eng: 'a rhetoric',
        pl: 'retoryka',
        ar: 'بلاغة',
        ger: 'eine Rhetorik',
        lt: 'retorika',
        key: '129',
        norEgz: 'Politikere bruker ofte overbevisende retorikk.',
        soundLink: '',
        wordId: 129
      },
      {
        nor: 'en poesi',
        eng: 'a poetry',
        pl: 'poezja',
        ar: 'شعر',
        ger: 'eine Poesie',
        lt: 'poezija',
        key: '130',
        norEgz: 'Hans poesi er både vakker og tankevekkende.',
        soundLink: '',
        wordId: 130
      },
      {
        nor: 'en oppgave',
        eng: 'a task',
        pl: 'zadanie',
        ar: 'مهمة',
        ger: 'eine Aufgabe',
        lt: 'užduotis',
        key: '131',
        norEgz: 'Han fikk en vanskelig oppgave å løse.',
        soundLink: '',
        wordId: 131
      },
      {
        nor: 'en avhandling',
        eng: 'a thesis',
        pl: 'rozprawa',
        ar: 'أطروحة',
        ger: 'eine Abhandlung',
        lt: 'disertacija',
        key: '132',
        norEgz: 'Hun skrev en avhandling om klimaendringer.',
        soundLink: '',
        wordId: 132
      },
      {
        nor: 'en kommentar',
        eng: 'a comment',
        pl: 'komentarz',
        ar: 'تعليق',
        ger: 'ein Kommentar',
        lt: 'komentaras',
        key: '133',
        norEgz: 'Hun la igjen en kommentar på bloggen hans.',
        soundLink: '',
        wordId: 133
      },
      {
        nor: 'respektfull',
        eng: 'respectful',
        pl: 'pełen szacunku',
        ar: 'محترم',
        ger: 'respektvoll',
        lt: 'gerbiantis',
        key: '134',
        norEgz: 'Han var alltid respektfull overfor sine lærere.',
        soundLink: '',
        wordId: 134
      },
      {
        nor: 'respektløs',
        eng: 'disrespectful',
        pl: 'lekkoduchny',
        ar: 'غير محترم',
        ger: 'respektlos',
        lt: 'nepagarbus',
        key: '135',
        norEgz: 'Det er respektløst å avbryte noen mens de snakker.',
        soundLink: '',
        wordId: 135
      },
      {
        nor: 'ansvarlig',
        eng: 'responsible',
        pl: 'odpowiedzialny',
        ar: 'مسؤول',
        ger: 'verantwortlich',
        lt: 'atsakingas',
        key: '136',
        norEgz: 'Han er ansvarlig for å organisere arrangementet.',
        soundLink: '',
        wordId: 136
      },
      {
        nor: 'uansvarlig',
        eng: 'irresponsible',
        pl: 'nieodpowiedzialny',
        ar: 'غير مسؤول',
        ger: 'unverantwortlich',
        lt: 'neatsakingas',
        key: '137',
        norEgz: 'Å kjøre uten førerkort er uansvarlig.',
        soundLink: '',
        wordId: 137
      },
      {
        nor: 'tilfreds',
        eng: 'satisfied',
        pl: 'zadowolony',
        ar: 'راض',
        ger: 'zufrieden',
        lt: 'patenkintas',
        key: '138',
        norEgz: 'Han var tilfreds med resultatene av arbeidet sitt.',
        soundLink: '',
        wordId: 138
      },
      {
        nor: 'en skildring',
        eng: 'a portrayal',
        pl: 'ukazanie',
        ar: 'تصوير',
        ger: 'eine Darstellung',
        lt: 'vaizdavimas',
        key: '139',
        norEgz: 'Skildringen av karakteren i boken var veldig detaljert.',
        soundLink: '',
        wordId: 139
      },
      {
        nor: 'en artikkel',
        eng: 'an article',
        pl: 'artykuł',
        ar: 'مقالة',
        ger: 'ein Artikel',
        lt: 'straipsnis',
        key: '140',
        norEgz: 'Han leste en interessant artikkel om klimaendringer.',
        soundLink: '',
        wordId: 140
      },
      {
        nor: 'en rapport',
        eng: 'a report',
        pl: 'raport',
        ar: 'تقرير',
        ger: 'ein Bericht',
        lt: 'ataskaita',
        key: '141',
        norEgz: 'Han skrev en rapport om prosjektets fremgang.',
        soundLink: '',
        wordId: 141
      },
      {
        nor: 'en prosess',
        eng: 'a process',
        pl: 'proces',
        ar: 'عملية',
        ger: 'ein Prozess',
        lt: 'procesas',
        key: '142',
        norEgz: 'Læringsprosessen tar tid og krefter.',
        soundLink: '',
        wordId: 142
      },
      {
        nor: 'en standard',
        eng: 'a standard',
        pl: 'standard',
        ar: 'معيار',
        ger: 'ein Standard',
        lt: 'standartas',
        key: '143',
        norEgz: 'Selskapet følger strenge kvalitetsstandarder.',
        soundLink: '',
        wordId: 143
      },
      {
        nor: 'en kvalitet',
        eng: 'a quality',
        pl: 'jakość',
        ar: 'جودة',
        ger: 'eine Qualität',
        lt: 'kokybė',
        key: '144',
        norEgz: 'Produktet er kjent for sin gode kvalitet.',
        soundLink: '',
        wordId: 144
      },
      {
        nor: 'en oversettelse',
        eng: 'a translation',
        pl: 'tłumaczenie',
        ar: 'ترجمة',
        ger: 'eine Übersetzung',
        lt: 'vertimas',
        key: '145',
        norEgz: 'Han jobber med en oversettelse av boken.',
        soundLink: '',
        wordId: 145
      },
      {
        nor: 'en medisin',
        eng: 'a medicine',
        pl: 'lekarstwo',
        ar: 'دواء',
        ger: 'eine Medizin',
        lt: 'vaistas',
        key: '146',
        norEgz: 'Hun må ta medisinen tre ganger om dagen.',
        soundLink: '',
        wordId: 146
      },
      {
        nor: 'å dele',
        eng: 'to share',
        pl: 'dzielić',
        ar: 'مشاركة',
        ger: 'teilen',
        lt: 'dalytis',
        key: '147',
        norEgz: 'Han delte godteriet med vennene sine.',
        soundLink: '',
        wordId: 147
      },
      {
        nor: 'å tilbringe',
        eng: 'to spend',
        pl: 'spędzać',
        ar: 'قضاء',
        ger: 'verbringen',
        lt: 'praleisti',
        key: '148',
        norEgz: 'De tilbringer sommerferien i Spania.',
        soundLink: '',
        wordId: 148
      },
      {
        nor: 'å sende',
        eng: 'to send',
        pl: 'wysyłać',
        ar: 'إرسال',
        ger: 'senden',
        lt: 'siųsti',
        key: '149',
        norEgz: 'Hun sendte en e-post til sjefen sin.',
        soundLink: '',
        wordId: 149
      },
      {
        nor: 'åpen',
        eng: 'open',
        pl: 'otwarty',
        ar: 'مفتوح',
        ger: 'offen',
        lt: 'atviras',
        key: '150',
        norEgz: 'Butikken er åpen fra 10 til 18.',
        soundLink: '',
        wordId: 150
      },
      {
        nor: 'lukket',
        eng: 'closed',
        pl: 'zamknięty',
        ar: 'مغلق',
        ger: 'geschlossen',
        lt: 'uždarytas',
        key: '151',
        norEgz: 'Skolen er lukket på grunn av snøstormen.',
        soundLink: '',
        wordId: 151
      },
      {
        nor: 'å miste',
        eng: 'to lose',
        pl: 'tracić',
        ar: 'تفقد',
        ger: 'verlieren',
        lt: 'prarasti',
        key: '152',
        norEgz: 'Jeg er redd for å miste nøklene mine.',
        soundLink: '',
        wordId: 152
      },
      {
        nor: 'en ingeniør',
        eng: 'an engineer',
        pl: 'inżynier',
        ar: 'مهندس',
        ger: 'ein Ingenieur',
        lt: 'inžinierius',
        key: '153',
        norEgz: 'Han er en dyktig ingeniør.',
        soundLink: '',
        wordId: 153
      },
      {
        nor: 'et pass',
        eng: 'a passport',
        pl: 'paszport',
        ar: 'جواز سفر',
        ger: 'ein Pass',
        lt: 'pasas',
        key: '154',
        norEgz: 'Hun glemte passet sitt hjemme.',
        soundLink: '',
        wordId: 154
      },
      {
        nor: 'en kunde',
        eng: 'a customer',
        pl: 'klient',
        ar: 'عميل',
        ger: 'ein Kunde',
        lt: 'klientas',
        key: '155',
        norEgz: 'En kunde spurte etter prisen på varen.',
        soundLink: '',
        wordId: 155
      },
      {
        nor: 'en guide',
        eng: 'a guide',
        pl: 'przewodnik',
        ar: 'مرشد',
        ger: 'ein Reiseführer',
        lt: 'gidas',
        key: '156',
        norEgz: 'Vi leide en guide for å vise oss rundt i byen.',
        soundLink: '',
        wordId: 156
      },
      {
        nor: 'en forsker',
        eng: 'a researcher',
        pl: 'badacz',
        ar: 'باحث',
        ger: 'ein Forscher',
        lt: 'tyrėjas',
        key: '157',
        norEgz: 'Forskeren presenterte sine funn på konferansen.',
        soundLink: '',
        wordId: 157
      },
      {
        nor: 'en tannlege',
        eng: 'a dentist',
        pl: 'dentysta',
        ar: 'طبيب الأسنان',
        ger: 'ein Zahnarzt',
        lt: 'dantistas',
        key: '158',
        norEgz: 'Tannlegen sa at jeg må pusse tennene oftere.',
        soundLink: '',
        wordId: 158
      },
      {
        nor: 'falsk',
        eng: 'false',
        pl: 'fałszywy',
        ar: 'كاذب',
        ger: 'falsch',
        lt: 'netikras',
        key: '159',
        norEgz: 'Han ble anklaget for å gi falsk informasjon.',
        soundLink: '',
        wordId: 159
      },
      {
        nor: 'flat',
        eng: 'flat',
        pl: 'płaski',
        ar: 'مسطح',
        ger: 'flach',
        lt: 'plokščias',
        key: '160',
        norEgz: 'Landskapet er veldig flatt her.',
        soundLink: '',
        wordId: 160
      },
      {
        nor: 'rund',
        eng: 'round',
        pl: 'okrągły',
        ar: 'مستدير',
        ger: 'rund',
        lt: 'apvalus',
        key: '161',
        norEgz: 'Bordet har en rund form.',
        soundLink: '',
        wordId: 161
      },
      {
        nor: 'å låse',
        eng: 'to lock',
        pl: 'zamykać na klucz',
        ar: 'قفل',
        ger: 'abschließen',
        lt: 'užrakinti',
        key: '162',
        norEgz: 'Husk å låse døren når du går ut.',
        soundLink: '',
        wordId: 162
      }
      
]