[
    {
    nor: 'å forklare',
    eng: 'to explain',
    pl: 'wyjaśniać',
    ar: 'شرح',
    ger: 'erklären',
    lt: 'paaiškinti',
    ua: 'пояснювати',
    sp: 'explicar',
    key: '0',
    norEgz: 'Kan du forklare dette for meg?',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforklare.mp3?alt=media&token=8f68d18f-5d74-401f-beaa-d896f5938eff',
    wordId: 0
    },
    {
    nor: 'å forsøke',
    eng: 'to attempt',
    pl: 'próbować',
    ar: 'محاولة',
    ger: 'versuchen',
    lt: 'bandyti',
    ua: 'намагатися',
    sp: 'intentar',
    key: '1',
    norEgz: 'Han forsøkte å løse problemet.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforsooke.mp3?alt=media&token=b30f5ef4-22a8-48ed-a7c1-f04ebf13af53',
    wordId: 1
    },
    {
    nor: 'en snekker',
    eng: 'a carpenter',
    pl: 'stolarz',
    ar: 'نجار',
    ger: 'ein Tischler',
    lt: 'dailidė',
    ua: 'столяр',
    sp: 'un carpintero',
    key: '2',
    norEgz: 'Snekkeren bygde et bord.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsnekker.mp3?alt=media&token=4fa72bd3-f6d6-4617-a6d1-825fcb437037',
    wordId: 2
    },
    {
    nor: 'et rådhus',
    eng: 'a town hall',
    pl: 'ratusz',
    ar: 'قاعة المدينة',
    ger: 'ein Rathaus',
    lt: 'rotušė',
    ua: 'ратуша',
    sp: 'un ayuntamiento',
    key: '3',
    norEgz: 'Møtet finner sted på rådhuset.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fraadhus.mp3?alt=media&token=3399d1cc-55a7-46ae-9f9d-68436e29860a',
    wordId: 3
    },
    {
    nor: 'en skuespiller',
    eng: 'an actor',
    pl: 'aktor',
    ar: 'ممثل',
    ger: 'ein Schauspieler',
    lt: 'aktorius',
    ua: 'актор',
    sp: 'un actor',
    key: '4',
    norEgz: 'Han er en kjent skuespiller.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskuespiller.mp3?alt=media&token=4b90678b-d256-46a8-88e7-8763ce056228',
    wordId: 4
    },
    {
    nor: 'en ørken',
    eng: 'a desert',
    pl: 'pustynia',
    ar: 'صحراء',
    ger: 'eine Wüste',
    lt: 'dykuma',
    ua: 'пустеля',
    sp: 'un desierto',
    key: '5',
    norEgz: 'Sahara er en stor ørken.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foorken.mp3?alt=media&token=edb7d771-8971-4a65-b695-4c6c169dd9a8',
    wordId: 5
    },
    {
    nor: 'en kyst',
    eng: 'a coast',
    pl: 'wybrzeże',
    ar: 'ساحل',
    ger: 'eine Küste',
    lt: 'pakrantė',
    ua: 'берег',
    sp: 'una costa',
    key: '6',
    norEgz: 'Vi gikk en tur langs kysten.',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkyst.mp3?alt=media&token=ee562e3a-5710-436a-a4b7-1f01476f699e',
    wordId: 6
    },
    {
      nor: 'en kunde',
      eng: 'a customer',
      pl: 'klient',
      ar: 'عميل',
      ger: 'ein Kunde',
      lt: 'klientas',
      ua: 'клієнт',
      sp: 'un cliente',
      key: '7',
      norEgz: 'En kunde spurte etter prisen på varen.',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkunde.mp3?alt=media&token=acf1c0cf-b3cc-4379-a5e8-316f8810b485',
      wordId: 7
    },
    {
        nor: 'en foss',
        eng: 'a waterfall',
        pl: 'wodospad',
        ar: 'شلال',
        ger: 'ein Wasserfall',
        lt: 'krioklys',
        ua: 'водоспад',
        sp: 'una cascada',
        key: '8',
        norEgz: 'Vi besøkte en foss i ferien.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffoss.mp3?alt=media&token=9cd94831-e75f-4a31-b6da-91a7d85a8478',
        wordId: 8
      },
      {
        nor: 'nøyaktig',
        eng: 'accurate',
        pl: 'dokładny',
        ar: 'دقيق',
        ger: 'genau',
        lt: 'tikslus',
        ua: 'точний',
        sp: 'exacto',
        key: '9',
        norEgz: 'Målingene hans var nøyaktige.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnooyaktig.mp3?alt=media&token=7f6d18e3-b611-45fa-a1c1-315412e9d484',
        wordId: 9
      },
      {
        nor: 'unøyaktig',
        eng: 'inaccurate',
        pl: 'niedokładny',
        ar: 'غير دقيق',
        ger: 'ungenau',
        lt: 'netikslus',
        ua: 'неточний',
        sp: 'inexacto',
        key: '10',
        norEgz: 'Rapporten inneholder unøyaktige data.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Funooyaktig.mp3?alt=media&token=a9e542f8-9c44-44dd-9727-ff902219d78e',
        wordId: 10
      },
      {
        nor: 'ambisiøs',
        eng: 'ambitious',
        pl: 'ambitny',
        ar: 'طموح',
        ger: 'ehrgeizig',
        lt: 'ambicingas',
        ua: 'амбітний',
        sp: 'ambicioso',
        key: '11',
        norEgz: 'Hun er en ambisiøs student.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fambisioos.mp3?alt=media&token=0ae7bafb-3f5b-4032-b5b5-ff33fab5afae',
        wordId: 11
      },
      {
        nor: 'overfladisk',
        eng: 'superficial',
        pl: 'powierzchowny',
        ar: 'سطحي',
        ger: 'oberflächlich',
        lt: 'paviršutiniškas',
        ua: 'поверхневий',
        sp: 'superficial',
        key: '12',
        norEgz: 'Deres samtale var overfladisk.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foverfladisk.mp3?alt=media&token=58b33775-8033-422d-9c4b-6344200faae1',
        wordId: 12
      },
      {
        nor: 'en historie',
        eng: 'a story',
        pl: 'historia',
        ar: 'قصة',
        ger: 'eine Geschichte',
        lt: 'istorija',
        ua: 'історія',
        sp: 'una historia',
        key: '13',
        norEgz: 'Han fortalte en spennende historie.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhistorie.mp3?alt=media&token=440155cf-0366-43be-b669-a26863742a9c',
        wordId: 13
      },
      {
        nor: 'en økonomi',
        eng: 'an economy',
        pl: 'gospodarka',
        ar: 'اقتصاد',
        ger: 'eine Wirtschaft',
        lt: 'ekonomika',
        ua: 'економіка',
        sp: 'una economía',
        key: '14',
        norEgz: 'Norge har en sterk økonomi.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fookonomi.mp3?alt=media&token=2df20954-b2a6-4dc5-9991-e6d5bfd4da13',
        wordId: 14
      },
      {
        nor: 'selvsikker',
        eng: 'confident',
        pl: 'pewny siebie',
        ar: 'واثق',
        ger: 'selbstbewusst',
        lt: 'pasitikintis',
        ua: 'впевнений у собі',
        sp: 'seguro de sí mismo',
        key: '15',
        norEgz: 'Han er en selvsikker person.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fselvsikker.mp3?alt=media&token=b3bf08a5-63e2-4f40-af6d-7df5c934c973',
        wordId: 15
      },
      {
        nor: 'å godta',
        eng: 'to accept',
        pl: 'akceptować',
        ar: 'يقبل',
        ger: 'akzeptieren',
        lt: 'priimti',
        ua: 'приймати',
        sp: 'aceptar',
        key: '16',
        norEgz: 'Han bestemte seg for å godta tilbudet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgodta.mp3?alt=media&token=b42d089e-d21b-4ff5-8309-51630d0aa3a8',
        wordId: 16
      },
      {
        nor: 'følsom',
        eng: 'sensitive',
        pl: 'wrażliwy',
        ar: 'حساس',
        ger: 'empfindlich',
        lt: 'jautrus',
        ua: 'чутливий',
        sp: 'sensible',
        key: '17',
        norEgz: 'Hun er følsom for sterke lukter.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffoolsom.mp3?alt=media&token=bf589058-726c-41b6-b77b-ef5b45d51187',
        wordId: 17
      },
      {
        nor: 'å hjelpe',
        eng: 'to help',
        pl: 'pomagać',
        ar: 'مساعدة',
        ger: 'helfen',
        lt: 'padėti',
        ua: 'допомагати',
        sp: 'ayudar',
        key: '18',
        norEgz: 'Jeg er her for å hjelpe deg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhjelpe.mp3?alt=media&token=b88f5831-b259-4f15-8146-4514f77a83ac',
        wordId: 18
      },
      {
        nor: 'ufølsom',
        eng: 'insensitive',
        pl: 'niewrażliwy',
        ar: 'غير حساس',
        ger: 'unempfindlich',
        lt: 'nejausmus',
        ua: 'нечутливий',
        sp: 'insensible',
        key: '19',
        norEgz: 'Han er ufølsom for andres følelser.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fufoolsom.mp3?alt=media&token=85375818-acf1-4176-b2e3-3c0182e3eb79',
        wordId: 19
      },
      {
        nor: 'en økologi',
        eng: 'an ecology',
        pl: 'ekologia',
        ar: 'بيئة',
        ger: 'eine Ökologie',
        lt: 'ekologija',
        ua: 'екологія',
        sp: 'una ecología',
        key: '20',
        norEgz: 'Studenter lærer om økologi og miljøvern.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fookologi.mp3?alt=media&token=364e280f-9645-416f-ba37-ccb1f89b6a34',
        wordId: 20
      },
      {
        nor: 'en art',
        eng: 'a species',
        pl: 'gatunek',
        ar: 'نوع',
        ger: 'eine Art',
        lt: 'rūšis',
        ua: 'вид',
        sp: 'una especie',
        key: '21',
        norEgz: 'Denne planten tilhører en sjelden art.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fart.mp3?alt=media&token=8a285c9c-885c-45d5-9be5-9934f0a800ab',
        wordId: 21
      },
      {
        nor: 'usikker',
        eng: 'uncertain',
        pl: 'niepewny',
        ar: 'غير مؤكد',
        ger: 'unsicher',
        lt: 'neaiškus',
        ua: 'невпевнений',
        sp: 'inseguro',
        key: '22',
        norEgz: 'Vi er usikre på hva vi skal gjøre.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fusikker.mp3?alt=media&token=5127e8c9-f607-404b-8ca2-ef40259e4c99',
        wordId: 22
      },
      {
        nor: 'et pass',
        eng: 'a passport',
        pl: 'paszport',
        ar: 'جواز سفر',
        ger: 'ein Pass',
        lt: 'pasas',
        ua: 'паспорт',
        sp: 'un pasaporte',
        key: '23',
        norEgz: 'Hun glemte passet sitt hjemme.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpass.mp3?alt=media&token=d0dc75bf-db40-4ec6-87ee-ad094785da50',
        wordId: 23
      },
      {
        nor: 'misfornøyd',
        eng: 'dissatisfied',
        pl: 'niezadowolony',
        ar: 'غير راض',
        ger: 'unzufrieden',
        lt: 'nepatenkintas',
        ua: 'незадоволений',
        sp: 'insatisfecho',
        key: '24',
        norEgz: 'Han er misfornøyd med resultatet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmisfornooyd.mp3?alt=media&token=97902a24-daf0-4c40-accf-8e3e3130f729',
        wordId: 24
      },
      {
        nor: 'en innvandring',
        eng: 'an immigration',
        pl: 'imigracja',
        ar: 'هجرة',
        ger: 'eine Einwanderung',
        lt: 'imigracija',
        ua: 'імміграція',
        sp: 'una inmigración',
        key: '25',
        norEgz: 'Innvandring har formet Norge gjennom historien.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finnvandring.mp3?alt=media&token=1bf665c7-19e1-48c2-9068-1e925ffe2fc9',
        wordId: 25
      },
      {
        nor: 'et monument',
        eng: 'a monument',
        pl: 'pomnik',
        ar: 'نصب تذكاري',
        ger: 'ein Denkmal',
        lt: 'paminklas',
        ua: 'пам’ятник',
        sp: 'un monumento',
        key: '26',
        norEgz: 'Monumentet står i sentrum av byen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmonument.mp3?alt=media&token=6b31e01b-c48e-47dd-9f22-9ae665e7c462',
        wordId: 26
      },
      {
        nor: 'en skulptur',
        eng: 'a sculpture',
        pl: 'rzeźba',
        ar: 'نحت',
        ger: 'eine Skulptur',
        lt: 'skulptūra',
        ua: 'скульптура',
        sp: 'una escultura',
        key: '27',
        norEgz: 'Skulpturen er laget av bronse.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskulptur.mp3?alt=media&token=e828edb7-bfe7-493e-b943-d8bfe650c021',
        wordId: 27
      },
      {
        nor: 'en maleri',
        eng: 'a painting',
        pl: 'obraz',
        ar: 'لوحة',
        ger: 'ein Gemälde',
        lt: 'tapyba',
        ua: 'картина',
        sp: 'una pintura',
        key: '28',
        norEgz: 'Maleriet henger på veggen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaleri.mp3?alt=media&token=76841d5e-a7a3-4691-bc5a-2e72b0e74d69',
        wordId: 28
      },
      {
        nor: 'en fotografi',
        eng: 'a photograph',
        pl: 'fotografia',
        ar: 'صورة',
        ger: 'ein Foto',
        lt: 'fotografija',
        ua: 'фотографія',
        sp: 'una fotografía',
        key: '29',
        norEgz: 'Fotografiet viser en vakker solnedgang.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffotografi.mp3?alt=media&token=54fd6638-034e-46c5-b214-b1b03293b24d',
        wordId: 29
      },
      {
        nor: 'en utvandring',
        eng: 'an emigration',
        pl: 'emigracja',
        ar: 'هجرة',
        ger: 'eine Auswanderung',
        lt: 'emigracija',
        ua: 'еміграція',
        sp: 'una emigración',
        key: '30',
        norEgz: 'Mange nordmenn deltok i utvandring til USA på 1800-tallet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futvandring.mp3?alt=media&token=a3fc14e2-ae7c-4c6e-b013-ae29c02ed682',
        wordId: 30
      },
      {
        nor: 'å invitere',
        eng: 'to invite',
        pl: 'zapraszać',
        ar: 'يدعو',
        ger: 'einladen',
        lt: 'pakviesti',
        ua: 'запрошувати',
        sp: 'invitar',
        key: '31',
        norEgz: 'Jeg vil invitere deg til festen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finvitere.mp3?alt=media&token=e7118e87-6a73-4b0a-bb88-039b95bdf52d',
        wordId: 31
      },
      {
        nor: 'å klage',
        eng: 'to complain',
        pl: 'skarżyć się',
        ar: 'يتذمر',
        ger: 'sich beschweren',
        lt: 'skųstis',
        ua: 'скаржитися',
        sp: 'quejar',
        key: '32',
        norEgz: 'Han klager alltid over været.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklage.mp3?alt=media&token=91b20990-f63d-4281-b0e9-b2d3419713f5',
        wordId: 32
      },
      {
        nor: 'å låse',
        eng: 'to lock',
        pl: 'zamykać na klucz',
        ar: 'قفل',
        ger: 'abschließen',
        lt: 'užrakinti',
        ua: 'замикати',
        sp: 'cerrar con llave',
        key: '33',
        norEgz: 'Husk å låse døren når du går ut.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flaase.mp3?alt=media&token=f4b89df4-5422-459c-87aa-6c2b7f30f34b',
        wordId: 33
      },
      {
        nor: 'en inkludering',
        eng: 'an inclusion',
        pl: 'włączenie',
        ar: 'إدراج',
        ger: 'eine Einbeziehung',
        lt: 'įtraukimas',
        ua: 'інклюзія',
        sp: 'una inclusión',
        key: '34',
        norEgz: 'Inkludering er viktig i et mangfoldig samfunn.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finkludering.mp3?alt=media&token=a714b303-f09b-4b4c-a52a-5a0802202cd3',
        wordId: 34
      },
      {
        nor: 'å dra',
        eng: 'to pull',
        pl: 'ciągnąć',
        ar: 'يسحب',
        ger: 'ziehen',
        lt: 'traukti',
        ua: 'їхати',
        sp: 'ir',
        key: '35',
        norEgz: 'Du må dra døren for å åpne den.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdra.mp3?alt=media&token=69107f6a-cf4d-4e22-8140-09f2af86a2ae',
        wordId: 35
      },
      {
        nor: 'å brenne',
        eng: 'to burn',
        pl: 'palić',
        ar: 'يحترق',
        ger: 'brennen',
        lt: 'degti',
        ua: 'горіти',
        sp: 'quemar',
        key: '36',
        norEgz: 'Papiret begynte å brenne når det kom i kontakt med ilden.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbrenne.mp3?alt=media&token=cae53ee0-80ed-4e59-a9a8-63b3de058a74',
        wordId: 36
      },
      {
        nor: 'å falle',
        eng: 'to fall',
        pl: 'upadać',
        ar: 'يسقط',
        ger: 'fallen',
        lt: 'kristi',
        ua: 'падати',
        sp: 'caer',
        key: '37',
        norEgz: 'Han snublet og falt på bakken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffalle.mp3?alt=media&token=b0a55019-4863-475a-9b4a-49e26afd9f17',
        wordId: 37
      },
      {
        nor: 'å klatre',
        eng: 'to climb',
        pl: 'wspinać się',
        ar: 'تسلق',
        ger: 'klettern',
        lt: 'lipti',
        ua: 'лазити',
        sp: 'escalar',
        key: '38',
        norEgz: 'Han liker å klatre i fjellet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklatre.mp3?alt=media&token=f4d24127-ba61-4af3-9b77-e050466e8e3c',
        wordId: 38
      },
      {
        nor: 'å vokse',
        eng: 'to grow',
        pl: 'rosnąć',
        ar: 'ينمو',
        ger: 'wachsen',
        lt: 'augti',
        ua: 'рости',
        sp: 'crecer',
        key: '39',
        norEgz: 'Trærne vokser hvert år.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvokse.mp3?alt=media&token=a4dbf538-cfa0-4601-af00-50459756393f',
        wordId: 39
      },
      {
        nor: 'sjalu',
        eng: 'jealous',
        pl: 'zazdrosny',
        ar: 'غيور',
        ger: 'eifersüchtig',
        lt: 'pavydus',
        ua: 'ревнивий',
        sp: 'celoso',
        key: '40',
        norEgz: 'Han var sjalu på sin brors suksess.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsjalu.mp3?alt=media&token=9498cfb8-88c6-4bb0-9909-3d165caa96a9',
        wordId: 40
      },
      {
        nor: 'en forsker',
        eng: 'a researcher',
        pl: 'badacz',
        ar: 'باحث',
        ger: 'ein Forscher',
        lt: 'tyrėjas',
        ua: 'дослідник',
        sp: 'un investigador',
        key: '41',
        norEgz: 'Forskeren presenterte sine funn på konferansen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforsker.mp3?alt=media&token=5497950b-aa81-406d-944a-afdab2df65c4',
        wordId: 41
      },
      {
        nor: 'en tannlege',
        eng: 'a dentist',
        pl: 'dentysta',
        ar: 'طبيب الأسنان',
        ger: 'ein Zahnarzt',
        lt: 'dantistas',
        ua: 'стоматолог',
        sp: 'un dentista',
        key: '42',
        norEgz: 'Tannlegen sa at jeg må pusse tennene oftere.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftannlege.mp3?alt=media&token=0ce134c7-554a-48fa-a32e-61cd5498c1e6',
        wordId: 42
      },
      {
        nor: 'en guide',
        eng: 'a guide',
        pl: 'przewodnik',
        ar: 'مرشد',
        ger: 'ein Reiseführer',
        lt: 'gidas',
        ua: 'гід',
        sp: 'un guía',
        key: '43',
        norEgz: 'Vi leide en guide for å vise oss rundt i byen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fguide.mp3?alt=media&token=89c09027-5707-4f8b-8546-ce9a1f55ffd5',
        wordId: 43
      },
      {
        nor: 'en oppgave',
        eng: 'a task',
        pl: 'zadanie',
        ar: 'مهمة',
        ger: 'eine Aufgabe',
        lt: 'užduotis',
        ua: 'завдання',
        sp: 'una tarea',
        key: '44',
        norEgz: 'Han fikk en vanskelig oppgave å løse.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foppgave.mp3?alt=media&token=766ba5ea-0cfc-4bb6-ae05-f194334eeaf7',
        wordId: 44
      },
      {
        nor: 'en avhandling',
        eng: 'a thesis',
        pl: 'rozprawa',
        ar: 'أطروحة',
        ger: 'eine Abhandlung',
        lt: 'disertacija',
        ua: 'дисертація',
        sp: 'una disertación',
        key: '45',
        norEgz: 'Hun skrev en avhandling om klimaendringer.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Favhandling.mp3?alt=media&token=47a7b95c-ff31-42ea-9511-ab6332bae8ca',
        wordId: 45
      },
      {
        nor: 'falsk',
        eng: 'false',
        pl: 'fałszywy',
        ar: 'كاذب',
        ger: 'falsch',
        lt: 'netikras',
        ua: 'несправжній',
        sp: 'falso',
        key: '46',
        norEgz: 'Han ble anklaget for å gi falsk informasjon.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffalsk.mp3?alt=media&token=f05d43d1-9726-440b-a0d7-d211fed47d67',
        wordId: 46
      },
      {
        nor: 'å lage',
        eng: 'to make',
        pl: 'robić',
        ar: 'يصنع',
        ger: 'machen',
        lt: 'daryti',
        ua: 'робити',
        sp: 'hacer',
        key: '47',
        norEgz: 'Hun liker å lage mat fra bunnen av.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flage.mp3?alt=media&token=8754ce1f-532f-43b2-92e7-2978d4f25017',
        wordId: 47
      },
      {
        nor: 'å låne',
        eng: 'to borrow',
        pl: 'pożyczyć',
        ar: 'اقتراض',
        ger: 'ausleihen',
        lt: 'pasiskolinti',
        ua: 'позичати',
        sp: 'prestar',
        key: '48',
        norEgz: 'Han ba om å låne boken min.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flaane.mp3?alt=media&token=0b32cf74-f3bc-4876-ad4d-460e6c39c782',
        wordId: 48
      },
      {
        nor: 'å mene',
        eng: 'to think',
        pl: 'myśleć',
        ar: 'يظن',
        ger: 'meinen',
        lt: 'manyti',
        ua: 'вважати',
        sp: 'pensar',
        key: '49',
        norEgz: 'Hun mente at det var en god idé.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmene.mp3?alt=media&token=26123744-6154-436b-94ca-aad7c013e6a4',
        wordId: 49
      },
      {
        nor: 'respektfull',
        eng: 'respectful',
        pl: 'pełen szacunku',
        ar: 'محترم',
        ger: 'respektvoll',
        lt: 'gerbiantis',
        ua: 'шанобливий',
        sp: 'respetuoso',
        key: '50',
        norEgz: 'Han var alltid respektfull overfor sine lærere.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frespektfull.mp3?alt=media&token=1bb86b6c-bd85-498f-84b1-470ae4983fde',
        wordId: 50
      },
      {
        nor: 'respektløs',
        eng: 'disrespectful',
        pl: 'lekceważący',
        ar: 'غير محترم',
        ger: 'respektlos',
        lt: 'nepagarbus',
        ua: 'нешанобливий',
        sp: 'irrespetuoso',
        key: '51',
        norEgz: 'Det er respektløst å avbryte noen mens de snakker.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frespektloos.mp3?alt=media&token=3dfc4157-0535-4fbc-a090-e20bda4e9ca0',
        wordId: 51
      },
      {
        nor: 'en ressurs',
        eng: 'a resource',
        pl: 'zasób',
        ar: 'مورد',
        ger: 'eine Ressource',
        lt: 'išteklius',
        ua: 'ресурс',
        sp: 'un recurso',
        key: '52',
        norEgz: 'Vann er en viktig ressurs for mennesker.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fressurs.mp3?alt=media&token=c81fe7ca-b954-497d-949e-8e0a6365c437',
        wordId: 52
      },
      {
        nor: 'å nekte',
        eng: 'to deny',
        pl: 'zaprzeczać',
        ar: 'ينكر',
        ger: 'verneinen',
        lt: 'neigti',
        ua: 'відмовляти',
        sp: 'negar',
        key: '53',
        norEgz: 'Han nektet for å ha tatt pengene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnekte.mp3?alt=media&token=dd5b783b-5249-4733-a370-8ec21523f29c',
        wordId: 53
      },
      {
        nor: 'å overraske',
        eng: 'to surprise',
        pl: 'zaskoczyć',
        ar: 'يفاجأ',
        ger: 'überraschen',
        lt: 'nustebinti',
        ua: 'здивувати',
        sp: 'sorprender',
        key: '54',
        norEgz: 'Hun overrasket ham med en gave.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foverraske.mp3?alt=media&token=8920ee41-aaee-4c27-a968-ee9e3baf1741',
        wordId: 54
      },
      {
        nor: 'å regne',
        eng: 'to count',
        pl: 'liczyć',
        ar: 'يعد',
        ger: 'zählen',
        lt: 'skaičiuoti',
        ua: 'рахувати',
        sp: 'contar',
        key: '55',
        norEgz: 'Han begynte å regne opp alle fordelene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fregne.mp3?alt=media&token=b0b63901-e554-4e5f-a52f-6c918e6cfcf1',
        wordId: 55
      },
      {
        nor: 'sjenerøs',
        eng: 'generous',
        pl: 'hojny',
        ar: 'كريم',
        ger: 'großzügig',
        lt: 'dosnus',
        ua: 'щедрий',
        sp: 'generoso',
        key: '56',
        norEgz: 'Han er en sjenerøs person.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsjeneroos.mp3?alt=media&token=5e4e178d-3387-42f7-aa39-a09d2c160245',
        wordId: 56
      },
      {
        nor: 'uvanlig',
        eng: 'unusual',
        pl: 'niezwykły',
        ar: 'غير عادي',
        ger: 'ungewöhnlich',
        lt: 'neįprastas',
        ua: 'незвичайний',
        sp: 'inusual',
        key: '57',
        norEgz: 'Det er uvanlig å se snø her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fuvanlig.mp3?alt=media&token=e5e4e61d-cad6-4381-b4ff-1f3beca5779b',
        wordId: 57
      },
      {
        nor: 'vanlig',
        eng: 'usual',
        pl: 'zwykły',
        ar: 'عادي',
        ger: 'üblich',
        lt: 'įprastas',
        ua: 'звичайний',
        sp: 'común',
        key: '58',
        norEgz: 'Det er vanlig å drikke kaffe om morgenen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvanlig.mp3?alt=media&token=de651bd9-1d43-4bde-b901-2f5ff86e7b14',
        wordId: 58
      },
      {
        nor: 'ansvarlig',
        eng: 'responsible',
        pl: 'odpowiedzialny',
        ar: 'مسؤول',
        ger: 'verantwortlich',
        lt: 'atsakingas',
        ua: 'відповідальний',
        sp: 'responsable',
        key: '59',
        norEgz: 'Han er ansvarlig for å organisere arrangementet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fansvarlig.mp3?alt=media&token=7fea835e-d6e4-4fde-a9b2-afac3920084a',
        wordId: 59
      },
      {
        nor: 'uansvarlig',
        eng: 'irresponsible',
        pl: 'nieodpowiedzialny',
        ar: 'غير مسؤول',
        ger: 'unverantwortlich',
        lt: 'neatsakingas',
        ua: 'не відповідальний',
        sp: 'irresponsable',
        key: '60',
        norEgz: 'Å kjøre uten førerkort er uansvarlig.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fuansvarlig.mp3?alt=media&token=27775147-bb88-425d-b475-d4a9dc03e727',
        wordId: 60
      },
      {
        nor: 'en prestasjon',
        eng: 'achievement',
        pl: 'osiągnięcie',
        ar: 'إنجاز',
        ger: 'Leistung',
        lt: 'pasiekimas',
        ua: 'досягнення',
        sp: 'un logro',
        key: '61',
        norEgz: 'Dette er en stor prestasjon for teamet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fprestasjon.mp3?alt=media&token=9a483a81-6593-4942-af7d-270efb6b1dc2',
        wordId: 61
      },
      {
        nor: 'en bordtennis',
        eng: 'table tennis',
        pl: 'tenis stołowy',
        ar: 'تنس الطاولة',
        ger: 'Tischtennis',
        lt: 'stalo tenisas',
        ua: 'настільний теніс',
        sp: 'un ping-pong',
        key: '62',
        norEgz: 'Vi spiller bordtennis etter jobb.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbordtennis.mp3?alt=media&token=1a1e51f2-029b-4374-bde5-dfb9550c4b59',
        wordId: 62
      },
      {
        nor: 'en borger',
        eng: 'citizen',
        pl: 'obywatel',
        ar: 'مواطن',
        ger: 'Bürger',
        lt: 'pilietis',
        ua: 'громадянин',
        sp: 'un ciudadano',
        key: '63',
        norEgz: 'Han er en stolt borger av sitt land.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fborger.mp3?alt=media&token=e8777e47-46a6-4284-9181-ce4621ebc93f',
        wordId: 63
      },
      {
        nor: 'en skildring',
        eng: 'a portrayal',
        pl: 'ukazanie',
        ar: 'تصوير',
        ger: 'eine Darstellung',
        lt: 'vaizdavimas',
        ua: 'опис',
        sp: 'una descripción',
        key: '64',
        norEgz: 'Skildringen av karakteren i boken var veldig detaljert.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskildring.mp3?alt=media&token=09a93222-e7bc-4afe-9e31-4225ed50435f',
        wordId: 64
      },
      {
        nor: 'en rapport',
        eng: 'a report',
        pl: 'raport',
        ar: 'تقرير',
        ger: 'ein Bericht',
        lt: 'ataskaita',
        ua: 'звіт',
        sp: 'un informe',
        key: '65',
        norEgz: 'Han skrev en rapport om prosjektets fremgang.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frapport.mp3?alt=media&token=c8cc9129-dfdf-4a6a-a8fb-e850ba4be0e3',
        wordId: 65
      },
      {
        nor: 'å skjønne',
        eng: 'to understand',
        pl: 'rozumieć',
        ar: 'أن يفهم',
        ger: 'verstehen',
        lt: 'suprasti',
        ua: 'розуміти',
        sp: 'entender',
        key: '66',
        norEgz: 'Jeg prøver å skjønne hva du mener.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjoonne.mp3?alt=media&token=94e1b9cc-a6a0-4807-8e7b-61d14ebbce6e',
        wordId: 66
      },
      {
        nor: 'å tillate',
        eng: 'to allow',
        pl: 'pozwalać',
        ar: 'السماح',
        ger: 'erlauben',
        lt: 'leisti',
        ua: 'дозволити',
        sp: 'permitir',
        key: '67',
        norEgz: 'Foreldrene tillater ikke festen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftillate.mp3?alt=media&token=4e466c3d-dfbd-4267-b4b6-536a9b53294c',
        wordId: 67
      },
      {
        nor: 'å trenge',
        eng: 'to need',
        pl: 'potrzebować',
        ar: 'يحتاج',
        ger: 'brauchen',
        lt: 'reikėti',
        ua: 'потребувати',
        sp: 'necesitar',
        key: '68',
        norEgz: 'Han trenger en ny bil.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftrenge.mp3?alt=media&token=bbec5f45-c3d1-4a6c-a377-00470dcde450',
        wordId: 68
      },
      {
        nor: 'tilfreds',
        eng: 'satisfied',
        pl: 'zadowolony',
        ar: 'راض',
        ger: 'zufrieden',
        lt: 'patenkintas',
        ua: 'задоволений',
        sp: 'satisfecho',
        key: '69',
        norEgz: 'Han var tilfreds med resultatene av arbeidet sitt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftilfreds.mp3?alt=media&token=0cbe55ed-0c10-44db-985e-8d916a86da55',
        wordId: 69
      },
      {
        nor: 'en kjemi',
        eng: 'chemistry',
        pl: 'chemia',
        ar: 'كيمياء',
        ger: 'Chemie',
        lt: 'chemija',
        ua: 'хімія',
        sp: 'una química',
        key: '70',
        norEgz: 'Kjemi er et interessant fag.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjemi.mp3?alt=media&token=f7a5baf2-e8fd-41d5-9ab3-06d417b1d2f5',
        wordId: 70
      },
      {
        nor: 'flat',
        eng: 'flat',
        pl: 'płaski',
        ar: 'مسطح',
        ger: 'flach',
        lt: 'plokščias',
        ua: 'плоский',
        sp: 'plano',
        key: '71',
        norEgz: 'Landskapet er veldig flatt her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fflat.mp3?alt=media&token=93edf19e-da06-4b5a-97d4-2541b4c118ba',
        wordId: 71
      },
      {
        nor: 'å velge',
        eng: 'to choose',
        pl: 'wybierać',
        ar: 'اختيار',
        ger: 'wählen',
        lt: 'pasirinkti',
        ua: 'вибирати',
        sp: 'elegir',
        key: '72',
        norEgz: 'Du må velge mellom de to alternativene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvelge.mp3?alt=media&token=872381ee-26de-49b8-9020-ff87c2b0fbb9',
        wordId: 72
      },
      {
        nor: 'å ønske',
        eng: 'to wish',
        pl: 'życzyć',
        ar: 'يتمنى',
        ger: 'wünschen',
        lt: 'norėti',
        ua: 'бажати',
        sp: 'desear',
        key: '73',
        norEgz: 'Jeg ønsker deg alt godt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foonske.mp3?alt=media&token=29551ed8-a1d1-4756-9e17-8645b664e51b',
        wordId: 73
      },
      {
        nor: 'å diskutere',
        eng: 'to discuss',
        pl: 'dyskutować',
        ar: 'يناقش',
        ger: 'diskutieren',
        lt: 'diskutuoti',
        ua: 'обговорювати',
        sp: 'discutir',
        key: '74',
        norEgz: 'Vi må diskutere problemet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdiskutere.mp3?alt=media&token=b6baa901-24a5-4d7a-9a18-3f5dbe0151a5',
        wordId: 74
      },
      {
        nor: 'en advarsel',
        eng: 'a warning',
        pl: 'ostrzeżenie',
        ar: 'تحذير',
        ger: 'eine Warnung',
        lt: 'įspėjimas',
        ua: 'попередження',
        sp: 'una advertencia',
        key: '75',
        norEgz: 'Han ga en advarsel for å kjøre for fort.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fadvarsel.mp3?alt=media&token=d18230eb-5cbd-41c1-b9b9-4c6bb8e8e4d7',
        wordId: 75
      },
      {
        nor: 'en veiledning',
        eng: 'a guidance',
        pl: 'poradnictwo',
        ar: 'توجيه',
        ger: 'eine Anleitung',
        lt: 'vadovavimas',
        ua: 'керівництво',
        sp: 'una guía',
        key: '76',
        norEgz: 'Han trenger veiledning for å forbedre ferdighetene sine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fveiledning.mp3?alt=media&token=97f94d38-9b0a-41f1-96b1-ef3496ff0b1c',
        wordId: 76
      },
      {
        nor: 'en støtte',
        eng: 'a support',
        pl: 'wsparcie',
        ar: 'دعم',
        ger: 'eine Unterstützung',
        lt: 'parama',
        ua: 'підтримка',
        sp: 'un apoyo',
        key: '77',
        norEgz: 'Familien ga ham støtte i vanskelige tider.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstootte.mp3?alt=media&token=d03386cc-a717-4bb1-81c3-06df2950624b',
        wordId: 77
      },
      {
        nor: 'et samarbeid',
        eng: 'a cooperation',
        pl: 'współpraca',
        ar: 'تعاون',
        ger: 'eine Zusammenarbeit',
        lt: 'bendradarbiavimas',
        ua: 'співпраця',
        sp: 'una colaboración',
        key: '78',
        norEgz: 'De hadde et godt samarbeid på prosjektet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsamarbeid.mp3?alt=media&token=59acf19c-bd79-424a-9356-3fb1fce021a7',
        wordId: 78
      },
      {
        nor: 'rund',
        eng: 'round',
        pl: 'okrągły',
        ar: 'مستدير',
        ger: 'rund',
        lt: 'apvalus',
        ua: 'круглий',
        sp: 'redondo',
        key: '79',
        norEgz: 'Bordet har en rund form.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frund.mp3?alt=media&token=84424bbf-c372-46b4-a005-20d4caf1c3cc',
        wordId: 79
      },
      {
        nor: 'en forståelse',
        eng: 'an understanding',
        pl: 'zrozumienie',
        ar: 'فهم',
        ger: 'ein Verständnis',
        lt: 'supratimas',
        ua: 'розуміння',
        sp: 'una comprensión',
        key: '80',
        norEgz: 'De kom til en forståelse etter samtalen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforstaaelse.mp3?alt=media&token=d75e8987-fcd6-4505-a5b9-a0e8b1d980a3',
        wordId: 80
      },
      {
        nor: 'solid',
        eng: 'solid',
        pl: 'solidny',
        ar: 'صلب',
        ger: 'solide',
        lt: 'tvirtas',
        ua: 'міцний',
        sp: 'sólido',
        key: '81',
        norEgz: 'Dette bordet er veldig solid og stødig.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsolid.mp3?alt=media&token=7732e352-7f20-45fc-b7d5-8206ffe7df71',
        wordId: 81
      },
      {
        nor: 'å hente',
        eng: 'to fetch',
        pl: 'przynieść',
        ar: 'جلب',
        ger: 'holen',
        lt: 'atnešti',
        ua: 'забирати',
        sp: 'recoger',
        key: '82',
        norEgz: 'Kan du hente boken fra hylla?',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhente.mp3?alt=media&token=330ef0dd-d570-4525-8598-54c1cdd92bec',
        wordId: 82
      },
      {
        nor: 'spontan',
        eng: 'spontaneous',
        pl: 'spontaniczny',
        ar: 'عفوي',
        ger: 'spontan',
        lt: 'spontaniškas',
        ua: 'спонтанний',
        sp: 'espontáneo',
        key: '83',
        norEgz: 'Hun er en veldig spontan person.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspontan.mp3?alt=media&token=993b6f0f-6639-4c55-8bec-4c82b565586b',
        wordId: 83
      },
      {
        nor: 'forutsigbar',
        eng: 'predictable',
        pl: 'przewidywalny',
        ar: 'يمكن التنبؤ به',
        ger: 'vorhersehbar',
        lt: 'numatomas',
        ua: 'передбачуваний',
        sp: 'predecible',
        key: '84',
        norEgz: 'Filmen var ganske forutsigbar.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforutsigbar.mp3?alt=media&token=520d5acf-09ee-4388-a585-5284daac3ece',
        wordId: 84
      },
      {
        nor: 'å fryse',
        eng: 'to freeze',
        pl: 'zamrażać',
        ar: 'يتجمد',
        ger: 'einfrieren',
        lt: 'šaldyti',
        ua: 'замерзати',
        sp: 'congelar',
        key: '85',
        norEgz: 'Vannet begynte å fryse i kaldt vær.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffryse.mp3?alt=media&token=4cd7d625-d85b-41a7-9b02-2badd29b0aec',
        wordId: 85
      },
      {
        nor: 'å varme',
        eng: 'to warm',
        pl: 'ogrzewać',
        ar: 'يدفئ',
        ger: 'erwärmen',
        lt: 'šildyti',
        ua: 'гріти',
        sp: 'calentar',
        key: '86',
        norEgz: 'Hun varmet hendene ved bålet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvarme.mp3?alt=media&token=e054e240-8966-40e2-8c94-8552da5f543e',
        wordId: 86
      },
      {
        nor: 'å kaste',
        eng: 'to throw',
        pl: 'rzucać',
        ar: 'يلقي',
        ger: 'werfen',
        lt: 'mesti',
        ua: 'кидати',
        sp: 'lanzar',
        key: '87',
        norEgz: 'Han kastet ballen til henne.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkaste.mp3?alt=media&token=45112afc-681a-4e9e-add1-2301c3b71206',
        wordId: 87
      },
      {
        nor: 'en kvalitet',
        eng: 'a quality',
        pl: 'jakość',
        ar: 'جودة',
        ger: 'eine Qualität',
        lt: 'kokybė',
        ua: 'якість',
        sp: 'una calidad',
        key: '88',
        norEgz: 'Produktet er kjent for sin gode kvalitet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkvalitet.mp3?alt=media&token=4cb4e15f-c940-4a1f-91d3-d3805045503b',
        wordId: 88
      },
      {
        nor: 'en oversettelse',
        eng: 'a translation',
        pl: 'tłumaczenie',
        ar: 'ترجمة',
        ger: 'eine Übersetzung',
        lt: 'vertimas',
        ua: 'переклад',
        sp: 'una traducción',
        key: '89',
        norEgz: 'Han jobber med en oversettelse av boken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foversettelse.mp3?alt=media&token=69d3a2f7-3360-438c-934d-b472616f41dd',
        wordId: 89
      },
      {
        nor: 'å smelte',
        eng: 'to melt',
        pl: 'topić',
        ar: 'يذوب',
        ger: 'schmelzen',
        lt: 'tirpinti',
        ua: 'танути',
        sp: 'derretir',
        key: '90',
        norEgz: 'Isen begynte å smelte i solen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmelte.mp3?alt=media&token=ec175d6d-35d9-47dc-b0ea-386195e67424',
        wordId: 90
      },
      {
        nor: 'å slå',
        eng: 'to hit',
        pl: 'uderzać',
        ar: 'يضرب',
        ger: 'schlagen',
        lt: 'mušti',
        ua: 'бити',
        sp: 'golpear',
        key: '91',
        norEgz: 'Han slo ballen med racketen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fslaa.mp3?alt=media&token=6e7abc6d-b375-488c-994d-188b8a56e3a4',
        wordId: 91
      },
      {
        nor: 'å klemme',
        eng: 'to squeeze',
        pl: 'ściskać',
        ar: 'يعصر',
        ger: 'quetschen',
        lt: 'spausti',
        ua: 'обіймати',
        sp: 'abrazar',
        key: '92',
        norEgz: 'Hun klemte sitronen for å lage juice.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklemme.mp3?alt=media&token=009976ae-4653-4407-bceb-2f78e0d95e8e',
        wordId: 92
      },
      {
        nor: 'å tegne',
        eng: 'to draw',
        pl: 'rysować',
        ar: 'يرسم',
        ger: 'zeichnen',
        lt: 'piešti',
        ua: 'малювати',
        sp: 'dibujar',
        key: '93',
        norEgz: 'Barnet tegner en hund på papiret.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftegne.mp3?alt=media&token=a8024084-54c6-4483-9e4b-7df00d403a77',
        wordId: 93
      },
      {
        nor: 'å male',
        eng: 'to paint',
        pl: 'malować',
        ar: 'يدهن',
        ger: 'malen',
        lt: 'dažyti',
        ua: 'фарбувати',
        sp: 'pintar',
        key: '94',
        norEgz: 'Han maler landskapet med akvarellfarger.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmale.mp3?alt=media&token=ad998837-34fd-4802-941b-bfdd21f90eb6',
        wordId: 94
      },
      {
        nor: 'grundig',
        eng: 'thorough',
        pl: 'gruntowny',
        ar: 'دقيق',
        ger: 'gründlich',
        lt: 'išsamus',
        ua: 'грунтовний',
        sp: 'minucioso',
        key: '95',
        norEgz: 'Han gjorde en grundig undersøkelse av saken.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrundig.mp3?alt=media&token=ca45dbe4-9184-4132-8fe3-bbfd90a4435c',
        wordId: 95
      },
      {
        nor: 'fleksibel',
        eng: 'flexible',
        pl: 'elastyczny',
        ar: 'مرن',
        ger: 'flexibel',
        lt: 'lankstus',
        ua: 'гнучкий',
        sp: 'flexible',
        key: '96',
        norEgz: 'Hun er fleksibel med arbeidstiden sin.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffleksibel.mp3?alt=media&token=9bfed043-b467-4da7-a0aa-4bb6354b1bd7',
        wordId: 96
      },
      {
        nor: 'stiv',
        eng: 'stiff',
        pl: 'sztywny',
        ar: 'جامد',
        ger: 'steif',
        lt: 'kietas',
        ua: 'жорсткий',
        sp: 'rígido',
        key: '97',
        norEgz: 'Han følte seg stiv etter å ha sittet lenge.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstiv.mp3?alt=media&token=4f8836be-b61f-4107-a38d-0559e394a500',
        wordId: 97
      },
      {
        nor: 'en medisin',
        eng: 'a medicine',
        pl: 'lekarstwo',
        ar: 'دواء',
        ger: 'eine Medizin',
        lt: 'vaistas',
        ua: 'медицина',
        sp: 'una medicina',
        key: '98',
        norEgz: 'Hun må ta medisinen tre ganger om dagen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmedisin.mp3?alt=media&token=1fdc476d-b10c-4435-bb3f-72af81aa5549',
        wordId: 98
      },
      {
        nor: 'å dele',
        eng: 'to share',
        pl: 'dzielić',
        ar: 'مشاركة',
        ger: 'teilen',
        lt: 'dalytis',
        ua: 'ділити',
        sp: 'compartir',
        key: '99',
        norEgz: 'Han delte godteriet med vennene sine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdele.mp3?alt=media&token=df44b9e7-8a1a-45e8-b662-c0e5caf627e4',
        wordId: 99
      },
      {
        nor: 'et samfunn',
        eng: 'a society',
        pl: 'społeczeństwo',
        ar: 'مجتمع',
        ger: 'eine Gesellschaft',
        lt: 'visuomenė',
        ua: 'суспільство',
        sp: 'una sociedad',
        key: '100',
        norEgz: 'Samfunnet har endret seg mye de siste årene.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsamfunn.mp3?alt=media&token=51425ee7-aa95-4cde-8a9a-6ae292fe20a3',
        wordId: 100
      },
      {
        nor: 'en verdi',
        eng: 'a value',
        pl: 'wartość',
        ar: 'قيمة',
        ger: 'ein Wert',
        lt: 'vertė',
        ua: 'цінність',
        sp: 'un valor',
        key: '101',
        norEgz: 'Respekt er en viktig verdi i kulturen vår.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fverdi.mp3?alt=media&token=0bfa4a19-6ae3-4a83-a5d5-6307aeadc65f',
        wordId: 101
      },
      {
        nor: 'en holdning',
        eng: 'an attitude',
        pl: 'postawa',
        ar: 'موقف',
        ger: 'eine Einstellung',
        lt: 'požiūris',
        ua: 'ставлення',
        sp: 'una actitud',
        key: '102',
        norEgz: 'Hans holdning til arbeid er svært positiv.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fholdning.mp3?alt=media&token=7705b57f-9b64-4a01-9f28-f2a54046bbd6',
        wordId: 102
      },
      {
        nor: 'en baking',
        eng: 'baking',
        pl: 'pieczenie',
        ar: 'خبز',
        ger: 'Backen',
        lt: 'kepti',
        ua: 'випічка',
        sp: 'una repostería',
        key: '103',
        norEgz: 'Hun elsker baking og lager deilige kaker.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbaking.mp3?alt=media&token=92e0f493-7c54-476e-b18d-c53c2ac4051a',
        wordId: 103
      },
      {
        nor: 'en strikking',
        eng: 'knitting',
        pl: 'dzierganie',
        ar: 'حياكة',
        ger: 'Stricken',
        lt: 'nėrimas',
        ua: "в'язання",
        sp: 'un tejido',
        key: '104',
        norEgz: 'Hun lærte strikking fra sin bestemor.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstrikking.mp3?alt=media&token=b652a21f-7151-4203-9279-da21fb63ec47',
        wordId: 104
      },
      {
        nor: 'å telle',
        eng: 'to count',
        pl: 'liczyć',
        ar: 'يعد',
        ger: 'zählen',
        lt: 'skaičiuoti',
        ua: 'рахувати',
        sp: 'contar',
        key: '105',
        norEgz: 'Barnet lærer å telle til ti.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftelle.mp3?alt=media&token=96392374-3905-4746-9775-1f5ad190eadf',
        wordId: 105
      },
      {
        nor: 'å bygge',
        eng: 'to build',
        pl: 'budować',
        ar: 'يبني',
        ger: 'bauen',
        lt: 'statyti',
        ua: 'будувати',
        sp: 'construir',
        key: '106',
        norEgz: 'De bygger et nytt hus i nabolaget.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbygge.mp3?alt=media&token=b5a76118-d96f-49a9-9f0b-b55c1da824db',
        wordId: 106
      },
      {
        nor: 'å skyve',
        eng: 'to push',
        pl: 'pchać',
        ar: 'يدفع',
        ger: 'schieben',
        lt: 'stumti',
        ua: 'штовхати',
        sp: 'empujar',
        key: '107',
        norEgz: 'Han skyver bilen ut av snøen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskyve.mp3?alt=media&token=375a7313-029b-4e0f-ba83-1748a31ec214',
        wordId: 107
      },
      {
        nor: 'å tilbringe',
        eng: 'to spend (time)',
        pl: 'spędzać (czas)',
        ar: 'قضاء',
        ger: 'verbringen',
        lt: 'praleisti',
        ua: 'проводити (час)',
        sp: 'pasar (tiempo)',
        key: '108',
        norEgz: 'De tilbringer sommerferien i Spania.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftilbringe.mp3?alt=media&token=9535a0f7-c755-43ea-bcc1-1e1e9ab22baa',
        wordId: 108
      },
      {
        nor: 'å sende',
        eng: 'to send',
        pl: 'wysyłać',
        ar: 'إرسال',
        ger: 'senden',
        lt: 'siųsti',
        ua: 'надсилати',
        sp: 'enviar',
        key: '109',
        norEgz: 'Hun sendte en e-post til sjefen sin.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsende.mp3?alt=media&token=2a9d988e-29ed-4911-bfa2-feb0ed88b301',
        wordId: 109
      },
      {
        nor: 'åpen',
        eng: 'open',
        pl: 'otwarty',
        ar: 'مفتوح',
        ger: 'offen',
        lt: 'atviras',
        ua: 'відкритий',
        sp: 'abierto',
        key: '110',
        norEgz: 'Butikken er åpen fra 10 til 18.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faapen.mp3?alt=media&token=0095f888-ff57-41b1-82fc-00fe86e8217a',
        wordId: 110
      },
      {
        nor: 'lukket',
        eng: 'closed',
        pl: 'zamknięty',
        ar: 'مغلق',
        ger: 'geschlossen',
        lt: 'uždarytas',
        ua: 'закритий',
        sp: 'cerrado',
        key: '111',
        norEgz: 'Skolen er lukket på grunn av snøstormen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flukket.mp3?alt=media&token=2b8541a0-30e8-4950-83d5-e03c2d0811a8',
        wordId: 111
      },
      {
        nor: 'å miste',
        eng: 'to lose',
        pl: 'tracić',
        ar: 'تفقد',
        ger: 'verlieren',
        lt: 'prarasti',
        ua: 'губити',
        sp: 'perder',
        key: '112',
        norEgz: 'Jeg er redd for å miste nøklene mine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmiste.mp3?alt=media&token=a12846bf-20d1-41cf-8a2e-7c70c796e780',
        wordId: 112
      },
      {
        nor: 'en ingeniør',
        eng: 'an engineer',
        pl: 'inżynier',
        ar: 'مهندس',
        ger: 'ein Ingenieur',
        lt: 'inžinierius',
        ua: 'інженер',
        sp: 'un ingeniero',
        key: '113',
        norEgz: 'Han er en dyktig ingeniør.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fingenioor.mp3?alt=media&token=0fb02641-fb21-4dcc-b59b-8e8a9bc7500e',
        wordId: 113
      },
      {
        nor: 'et pass',
        eng: 'a passport',
        pl: 'paszport',
        ar: 'جواز سفر',
        ger: 'ein Pass',
        lt: 'pasas',
        ua: 'паспорт',
        sp: 'un pasaporte',
        key: '114',
        norEgz: 'Hun glemte passet sitt hjemme.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpass.mp3?alt=media&token=d0dc75bf-db40-4ec6-87ee-ad094785da50',
        wordId: 114
      },
      {
        nor: 'misfornøyd',
        eng: 'dissatisfied',
        pl: 'niezadowolony',
        ar: 'غير راض',
        ger: 'unzufrieden',
        lt: 'nepatenkintas',
        ua: 'незадоволений',
        sp: 'insatisfecho',
        key: '115',
        norEgz: 'Han er misfornøyd med resultatet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmisfornooyd.mp3?alt=media&token=97902a24-daf0-4c40-accf-8e3e3130f729',
        wordId: 115
      },
      {
        nor: 'dum',
        eng: 'stupid',
        pl: 'głupi',
        ar: 'غبي',
        ger: 'dumm',
        lt: 'kvailas',
        ua: 'дурний',
        sp: 'tonto',
        key: '116',
        norEgz: 'Det var en dum feil.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdum.mp3?alt=media&token=87d6235e-3a3d-4a93-aa38-9451ca3b6420',
        wordId: 116
        },
        {
          nor: 'en etasje',
          eng: 'a floor',
          pl: 'piętro',
          ar: 'طابق',
          ger: 'eine Etage',
          lt: 'aukštas',
          ua: 'поверх',
          sp: 'piso',
          key: '117',
          norEgz: 'Heisen går til den femte etasjen.',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fetasje.mp3?alt=media&token=85ef3ac2-e70a-4915-aa8d-a90f5c87c545',
          wordId: 117
        },
        {
        nor: 'ujevn',
        eng: 'uneven',
        pl: 'nierówny',
        ar: 'غير مستو',
        ger: 'unregelmäßig',
        lt: 'nelygus',
        ua: 'нерівний',
        sp: 'desigual',
        key: '118',
        norEgz: 'Gulvet er ujevnt.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fujevn.mp3?alt=media&token=a6c8189e-1d9b-46c2-af68-2246206bb5e8',
        wordId: 118
        },
        {
        nor: 'lokal',
        eng: 'local',
        pl: 'lokalny',
        ar: 'محلي',
        ger: 'lokal',
        lt: 'vietinis',
        ua: 'місцевий',
        sp: 'local',
        key: '119',
        norEgz: 'Den lokale butikken har gode priser.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flokal.mp3?alt=media&token=82cc4296-806c-4faa-9996-98467fd03d04',
        wordId: 119
        },
        {
        nor: 'en konsert',
        eng: 'a concert',
        pl: 'koncert',
        ar: 'حفلة موسيقية',
        ger: 'ein Konzert',
        lt: 'koncertas',
        ua: 'концерт',
        sp: 'un concierto',
        key: '120',
        norEgz: 'Jeg gleder meg til konserten i kveld.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkonsert.mp3?alt=media&token=cbd03b88-1637-44aa-a3a8-a3ceebdd33b3',
        wordId: 120
        },
        {
        nor: 'en skuff',
        eng: 'a drawer',
        pl: 'szuflada',
        ar: 'درج',
        ger: 'eine Schublade',
        lt: 'stalčius',
        ua: 'шухляда',
        sp: 'un cajón',
        key: '121',
        norEgz: 'Jeg åpnet en skuff for å finne en skje.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskuff.mp3?alt=media&token=66848a16-5daa-428f-a3fe-c8504989b4ff',
        wordId: 121
        },
        {
        nor: 'å krympe',
        eng: 'to shrink',
        pl: 'kurczyć się',
        ar: 'تقلص',
        ger: 'schrumpfen',
        lt: 'traukti',
        ua: 'скорочувати',
        sp: 'encoger',
        key: '122',
        norEgz: 'Denne genseren krymper hvis du vasker den på høy temperatur.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkrympe.mp3?alt=media&token=3ec5eba9-7749-443d-ae6d-b86672c351db',
        wordId: 122
        },
        {
        nor: 'å bli kvitt',
        eng: 'to get rid of',
        pl: 'pozbyć się',
        ar: 'التخلص من',
        ger: 'loswerden',
        lt: 'atbristi',
        ua: 'позбутися',
        sp: 'deshacerse',
        key: '123',
        norEgz: 'Vi må bli kvitt dette gamle skapet.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblikvitt.mp3?alt=media&token=d9cc0af5-b2d7-4d31-bcbf-c9e0fe8e4601',
        wordId: 123
        },
        {
        nor: 'å blande',
        eng: 'to mix',
        pl: 'mieszać',
        ar: 'خلط',
        ger: 'mischen',
        lt: 'maišyti',
        ua: 'змішувати',
        sp: 'mezclar',
        key: '124',
        norEgz: 'Hun blandet ingrediensene sammen i en bolle.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblande.mp3?alt=media&token=e73249ee-b2b1-4e9d-95bd-6ac7070ecfcf',
        wordId: 124
        },
        {
        nor: 'en leilighet',
        eng: 'an apartment',
        pl: 'mieszkanie',
        ar: 'شقة',
        ger: 'eine Wohnung',
        lt: 'butas',
        ua: 'квартира',
        sp: 'un apartamento',
        key: '125',
        norEgz: 'Hun bor i en liten leilighet i byen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleilighet.mp3?alt=media&token=623cea77-8155-4c2b-97d4-d3c1aa9b3021',
        wordId: 125
        },
      {
        nor: 'unødvendig',
        eng: 'unnecessary',
        pl: 'niepotrzebny',
        ar: 'غير ضروري',
        ger: 'unnötig',
        lt: 'nereikalingas',
        ua: 'непотрібний',
        sp: 'innecesario',
        key: '126',
        norEgz: 'Det er unødvendig å bekymre seg.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Funoodvendig.mp3?alt=media&token=ae116600-1f50-4389-8596-5028be33f21f',
        wordId: 126
      },
      {
        nor: 'frisk',
        eng: 'fresh',
        pl: 'świeży',
        ar: 'طازج',
        ger: 'frisch',
        lt: 'šviežias',
        ua: 'свіжий',
        sp: 'fresco',
        key: '127',
        norEgz: 'Luften er frisk her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrisk.mp3?alt=media&token=ffa59af5-0ef3-44f7-b4c4-d3e10755e4a3',
        wordId: 127
      },
      {
        nor: 'stille',
        eng: 'quiet',
        pl: 'cichy',
        ar: 'هادئ',
        ger: 'ruhig',
        lt: 'tylus',
        ua: 'тихо',
        sp: 'tranquilo',
        key: '128',
        norEgz: 'Det er så stille her.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstille.mp3?alt=media&token=089460e2-31ff-4986-b742-3d80efc716bf',
        wordId: 128
      },
      {
        nor: 'en fiolin',
        eng: 'a violin',
        pl: 'skrzypce',
        ar: 'كمان',
        ger: 'eine Violine',
        lt: 'smuikas',
        ua: 'скрипка',
        sp: 'un violín',
        key: '129',
        norEgz: 'Han spiller på en fiolin.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffiolin.mp3?alt=media&token=73001e51-049c-4289-8f78-91a0c2b193d8',
        wordId: 129
      },
      {
        nor: 'et medlem',
        eng: 'a member',
        pl: 'członek',
        ar: 'عضو',
        ger: 'ein Mitglied',
        lt: 'narys',
        ua: 'член',
        sp: 'un miembro',
        key: '130',
        norEgz: 'Han er et medlem av klubben.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmedlem.mp3?alt=media&token=3672ff38-9c4e-49ef-bdee-a057911ab053',
        wordId: 130
      },
      {
        nor: 'å bade',
        eng: 'to bathe',
        pl: 'kąpać się',
        ar: 'الاستحمام',
        ger: 'baden',
        lt: 'maudytis',
        ua: 'купатися',
        sp: 'bañar',
        key: '131',
        norEgz: 'Vi liker å bade i sjøen.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbade.mp3?alt=media&token=53bdc581-7da3-4d9b-9e6e-295980120faf',
        wordId: 131
      },
      {
        nor: 'å vaske',
        eng: 'to wash',
        pl: 'myć',
        ar: 'غسل',
        ger: 'waschen',
        lt: 'plauti',
        ua: 'мити',
        sp: 'lavar',
        key: '132',
        norEgz: 'Jeg må vaske klærne mine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaske.mp3?alt=media&token=b363426e-2cae-4833-b80b-862602903ab0',
        wordId: 132
      },
      {
        nor: 'å tørke',
        eng: 'to dry',
        pl: 'suszyć',
        ar: 'يجف',
        ger: 'trocknen',
        lt: 'džiovinti',
        ua: 'сушити',
        sp: 'secar',
        key: '133',
        norEgz: 'Jeg må tørke klærne mine.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorke.mp3?alt=media&token=892da2c3-16bb-4db1-bfbb-92712b11d023',
        wordId: 133
        },
        {
        nor: 'en besøkende',
        eng: 'a visitor',
        pl: 'zwiedzający',
        ar: 'زائر',
        ger: 'ein Besucher',
        lt: 'lankytojas',
        ua: 'відвідувач',
        sp: 'un visitante',
        key: '134',
        norEgz: 'Vi har en besøkende fra Tyskland.',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbesookende.mp3?alt=media&token=c979fa2e-9ee7-44ad-bac2-c311536e5b83',
        wordId: 134
        },
        {
          nor: 'å dekke',
          eng: 'to cover',
          pl: 'pokrywać',
          ar: 'يغطي',
          ger: 'abdecken',
          lt: 'dengti',
          ua: 'покривати',
          sp: 'cubrir',
          key: '135',
          norEgz: 'Vi må dekke bordet før gjestene kommer.',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdekke.mp3?alt=media&token=1046b9ad-57bd-46f5-92ba-82ac86a73508',
          wordId: 135
        },
        {
          nor: 'å grave',
          eng: 'to dig',
          pl: 'kopać',
          ar: 'يحفر',
          ger: 'graben',
          lt: 'kasti',
          ua: 'копати',
          sp: 'excavar',
          key: '136',
          norEgz: 'Han begynte å grave et hull i hagen.',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrave.mp3?alt=media&token=c4c3fa74-9799-4e06-b6c3-337a7ac2ccad',
          wordId: 136
        },
          
  
      
      
]

