[
    {
      nor: 'å akseptere',
      eng: 'to accept',
      pl: 'akceptować',
      ar: 'يقبل',
      ger: 'akzeptieren',
      lt: 'priimti',
      key: '0',
      norEgz: 'Du må lære å akseptere kritikk.',
      soundLink: '',
      wordId: 0
    },
    {
      nor: 'å analysere',
      eng: 'to analyze',
      pl: 'analizować',
      ar: 'تحليل',
      ger: 'analysieren',
      lt: 'analizuoti',
      key: '1',
      norEgz: 'Vi må analysere dataene nøye.',
      soundLink: '',
      wordId: 1
    },
    {
      nor: 'å endre',
      eng: 'to change',
      pl: 'zmieniać',
      ar: 'تغيير',
      ger: 'ändern',
      lt: 'keisti',
      key: '2',
      norEgz: 'Han bestemte seg for å endre livsstilen sin.',
      soundLink: '',
      wordId: 2
    },
    {
      nor: 'en oppfinnelse',
      eng: 'an invention',
      pl: 'wynalazek',
      ar: 'اختراع',
      ger: 'eine Erfindung',
      lt: 'išradimas',
      key: '3',
      norEgz: 'Telefonen er en viktig oppfinnelse.',
      soundLink: '',
      wordId: 3
    },
    {
      nor: 'en oppdagelse',
      eng: 'a discovery',
      pl: 'odkrycie',
      ar: 'اكتشاف',
      ger: 'eine Entdeckung',
      lt: 'atrada',
      key: '4',
      norEgz: 'Oppdagelsen av penicillin var et gjennombrudd i medisin.',
      soundLink: '',
      wordId: 4
    },
    {
      nor: 'en undersøkelse',
      eng: 'an investigation',
      pl: 'dochodzenie',
      ar: 'تحقيق',
      ger: 'eine Untersuchung',
      lt: 'tyrimas',
      key: '5',
      norEgz: 'Politiet startet en undersøkelse etter ulykken.',
      soundLink: '',
      wordId: 5
    },
    {
      nor: 'en studie',
      eng: 'a study',
      pl: 'badanie',
      ar: 'دراسة',
      ger: 'eine Studie',
      lt: 'studija',
      key: '6',
      norEgz: 'Studien viser at trening er bra for helsen.',
      soundLink: '',
      wordId: 6
    },
    {
      nor: 'en forskning',
      eng: 'research',
      pl: 'badanie naukowe',
      ar: 'بحث',
      ger: 'Forschung',
      lt: 'mokslinis tyrimas',
      key: '7',
      norEgz: 'Hun jobber med forskning på kreftbehandling.',
      soundLink: '',
      wordId: 7
    },
    {
        nor: 'analytisk',
        eng: 'analytical',
        pl: 'analityczny',
        ar: 'تحليلي',
        ger: 'analytisch',
        lt: 'analitinis',
        key: '8',
        norEgz: 'Han har en analytisk tilnærming til problemløsning.',
        soundLink: '',
        wordId: 8
      },
      {
        nor: 'autoritær',
        eng: 'authoritarian',
        pl: 'autorytarny',
        ar: 'مستبد',
        ger: 'autoritär',
        lt: 'autoritarinis',
        key: '9',
        norEgz: 'Lederen hennes har en autoritær lederstil.',
        soundLink: '',
        wordId: 9
      },
      {
        nor: 'byråkratisk',
        eng: 'bureaucratic',
        pl: 'biurokratyczny',
        ar: 'بيروقراطي',
        ger: 'bürokratisch',
        lt: 'biurokratinis',
        key: '10',
        norEgz: 'Mange klager over det byråkratiske systemet.',
        soundLink: '',
        wordId: 10
      },
      {
        nor: 'diplomatisk',
        eng: 'diplomatic',
        pl: 'dyplomatyczny',
        ar: 'دبلوماسي',
        ger: 'diplomatisch',
        lt: 'diplomatiškas',
        key: '11',
        norEgz: 'Hun håndterte situasjonen på en diplomatisk måte.',
        soundLink: '',
        wordId: 11
      },
      {
        nor: 'en utvikling',
        eng: 'a development',
        pl: 'rozwój',
        ar: 'تطور',
        ger: 'eine Entwicklung',
        lt: 'vystymasis',
        key: '12',
        norEgz: 'Det har vært en positiv utvikling i teknologi de siste årene.',
        soundLink: '',
        wordId: 12
      },
      {
        nor: 'en forbedring',
        eng: 'an improvement',
        pl: 'ulepszenie',
        ar: 'تحسين',
        ger: 'eine Verbesserung',
        lt: 'pagerinimas',
        key: '13',
        norEgz: 'Vi ser en forbedring i hans ytelse på jobben.',
        soundLink: '',
        wordId: 13
      },
      {
        nor: 'et forhold',
        eng: 'a relationship',
        pl: 'związek',
        ar: 'علاقة',
        ger: 'eine Beziehung',
        lt: 'santykis',
        key: '14',
        norEgz: 'De har et godt forhold til hverandre.',
        soundLink: '',
        wordId: 14
      },
      {
        nor: 'en konflikt',
        eng: 'a conflict',
        pl: 'konflikt',
        ar: 'صراع',
        ger: 'ein Konflikt',
        lt: 'konfliktas',
        key: '15',
        norEgz: 'Vi må finne en løsning på konflikt.',
        soundLink: '',
        wordId: 15
      },
      {
        nor: 'å etablere',
        eng: 'to establish',
        pl: 'ustanowić',
        ar: 'تأسيس',
        ger: 'etablieren',
        lt: 'įkurti',
        key: '16',
        norEgz: 'De ønsker å etablere en ny bedrift.',
        soundLink: '',
        wordId: 16
      },
      {
        nor: 'å forbedre',
        eng: 'to improve',
        pl: 'poprawić',
        ar: 'تحسين',
        ger: 'verbessern',
        lt: 'pagerinti',
        key: '17',
        norEgz: 'Han prøver å forbedre sine språkferdigheter.',
        soundLink: '',
        wordId: 17
      },
      {
        nor: 'en løsning',
        eng: 'a solution',
        pl: 'rozwiązanie',
        ar: 'حل',
        ger: 'eine Lösung',
        lt: 'sprendimas',
        key: '18',
        norEgz: 'Vi må finne en løsning på problemet.',
        soundLink: '',
        wordId: 18
      },
      {
        nor: 'en forhandling',
        eng: 'a negotiation',
        pl: 'negocjacje',
        ar: 'تفاوض',
        ger: 'eine Verhandlung',
        lt: 'derybos',
        key: '19',
        norEgz: 'Forhandlingene mellom partene pågår.',
        soundLink: '',
        wordId: 19
      },
      {
        nor: 'en beslutning',
        eng: 'a decision',
        pl: 'decyzja',
        ar: 'قرار',
        ger: 'eine Entscheidung',
        lt: 'sprendimas',
        key: '20',
        norEgz: 'Han tok en viktig beslutning om sin fremtid.',
        soundLink: '',
        wordId: 20
      },
      {
        nor: 'en enighet',
        eng: 'an agreement',
        pl: 'porozumienie',
        ar: 'اتفاق',
        ger: 'eine Einigung',
        lt: 'sutartis',
        key: '21',
        norEgz: 'De kom til en enighet om betingelsene.',
        soundLink: '',
        wordId: 21
      },
      {
        nor: 'en uenighet',
        eng: 'a disagreement',
        pl: 'nieporozumienie',
        ar: 'خلاف',
        ger: 'eine Meinungsverschiedenheit',
        lt: 'nesutarimas',
        key: '22',
        norEgz: 'Det var en uenighet mellom dem om prisen.',
        soundLink: '',
        wordId: 22
      },
      {
        nor: 'en jordskjelv',
        eng: 'an earthquake',
        pl: 'trzęsienie ziemi',
        ar: 'زلزال',
        ger: 'ein Erdbeben',
        lt: 'žemės drebėjimas',
        key: '23',
        norEgz: 'Et kraftig jordskjelv rammet regionen.',
        soundLink: '',
        wordId: 23
      },
      {
        nor: 'et økosystem',
        eng: 'an ecosystem',
        pl: 'ekosystem',
        ar: 'نظام بيئي',
        ger: 'ein Ökosystem',
        lt: 'ekosistema',
        key: '24',
        norEgz: 'Regnskogen er et komplekst økosystem.',
        soundLink: '',
        wordId: 24
      },
      {
        nor: 'dogmatisk',
        eng: 'dogmatic',
        pl: 'dogmatyczny',
        ar: 'متعصب',
        ger: 'dogmatisch',
        lt: 'dogmatiškas',
        key: '25',
        norEgz: 'Hans dogmatiske holdning skapte konflikt i diskusjonen.',
        soundLink: '',
        wordId: 25
      },
      {
        nor: 'egosentrisk',
        eng: 'egocentric',
        pl: 'egocentryczny',
        ar: 'الأنانية',
        ger: 'egozentrisch',
        lt: 'egocentriškas',
        key: '26',
        norEgz: 'Hun var kjent for å være en egosentrisk person.',
        soundLink: '',
        wordId: 26
      },
      {
        nor: 'elastisk',
        eng: 'elastic',
        pl: 'elastyczny',
        ar: 'مرن',
        ger: 'elastisch',
        lt: 'elastingas',
        key: '27',
        norEgz: 'Dette materialet er veldig elastisk og komfortabelt.',
        soundLink: '',
        wordId: 27
      },
      {
        nor: 'empatisk',
        eng: 'empathetic',
        pl: 'empatyczny',
        ar: 'التعاطف',
        ger: 'empathisch',
        lt: 'empatiškas',
        key: '28',
        norEgz: 'Hun er en empatisk person som forstår andres følelser.',
        soundLink: '',
        wordId: 28
      },
      {
        nor: 'en habitat',
        eng: 'a habitat',
        pl: 'siedlisko',
        ar: 'موطن',
        ger: 'ein Lebensraum',
        lt: 'biotopas',
        key: '29',
        norEgz: 'Myrer er et viktig habitat for mange arter.',
        soundLink: '',
        wordId: 29
      },
      {
        nor: 'en nedbør',
        eng: 'precipitation',
        pl: 'opad atmosferyczny',
        ar: 'هطول',
        ger: 'Niederschlag',
        lt: 'krituliai',
        key: '30',
        norEgz: 'Det er ventet mye nedbør i løpet av helgen.',
        soundLink: '',
        wordId: 30
      },
      {
        nor: 'en tørke',
        eng: 'a drought',
        pl: 'susza',
        ar: 'جفاف',
        ger: 'eine Dürre',
        lt: 'saulėgraža',
        key: '31',
        norEgz: 'Bøndene lider under en langvarig tørke.',
        soundLink: '',
        wordId: 31
      },
      {
        nor: 'en forurensning',
        eng: 'pollution',
        pl: 'zanieczyszczenie',
        ar: 'تلوث',
        ger: 'Verschmutzung',
        lt: 'tarša',
        key: '32',
        norEgz: 'Forurensning fra biltrafikk påvirker luftkvaliteten.',
        soundLink: '',
        wordId: 32
      },
      {
        nor: 'en resirkulering',
        eng: 'recycling',
        pl: 'recykling',
        ar: 'إعادة التدوير',
        ger: 'Recycling',
        lt: 'perdirbimas',
        key: '33',
        norEgz: 'Resirkulering av plast reduserer avfallsmengden.',
        soundLink: '',
        wordId: 33
      },
      {
        nor: 'en konservasjon',
        eng: 'conservation',
        pl: 'konserwacja',
        ar: 'حفظ',
        ger: 'Erhaltung',
        lt: 'konservavimas',
        key: '34',
        norEgz: 'Konservasjon av kulturminner er viktig for samfunnet.',
        soundLink: '',
        wordId: 34
      },
      {
        nor: 'en praksis',
        eng: 'practice',
        pl: 'praktyka',
        ar: 'ممارسة',
        ger: 'Praxis',
        lt: 'praktika',
        key: '35',
        norEgz: 'Yoga er en praksis som kan bidra til bedre helse.',
        soundLink: '',
        wordId: 35
      },
      {
        nor: 'å forvente',
        eng: 'to expect',
        pl: 'oczekiwać',
        ar: 'يتوقع',
        ger: 'erwarten',
        lt: 'tikėtis',
        key: '36',
        norEgz: 'Vi forventer at prisene vil øke neste år.',
        soundLink: '',
        wordId: 36
      },
      {
        nor: 'å fremme',
        eng: 'to promote',
        pl: 'promować',
        ar: 'تعزيز',
        ger: 'fördern',
        lt: 'skatinti',
        key: '37',
        norEgz: 'Hun ønsker å fremme en sunn livsstil.',
        soundLink: '',
        wordId: 37
      },
      {
        nor: 'en oksygen',
        eng: 'oxygen',
        pl: 'tlen',
        ar: 'أكسجين',
        ger: 'Sauerstoff',
        lt: 'deguonis',
        key: '38',
        norEgz: 'Oksygen er nødvendig for å opprettholde liv.',
        soundLink: '',
        wordId: 38
      },
      {
        nor: 'et karbon',
        eng: 'carbon',
        pl: 'węgiel',
        ar: 'كربون',
        ger: 'Kohlenstoff',
        lt: 'anglis',
        key: '39',
        norEgz: 'Karbon er et grunnstoff som finnes i alle levende organismer.',
        soundLink: '',
        wordId: 39
      },
      {
        nor: 'en befolkning',
        eng: 'population',
        pl: 'populacja',
        ar: 'السكان',
        ger: 'Bevölkerung',
        lt: 'gyventojai',
        key: '40',
        norEgz: 'Befolkningen i dette landet er i vekst.',
        soundLink: '',
        wordId: 40
      },
      {
        nor: 'en beskyttelse',
        eng: 'protection',
        pl: 'ochrona',
        ar: 'حماية',
        ger: 'Schutz',
        lt: 'apsauga',
        key: '41',
        norEgz: 'Hjelmen gir god beskyttelse for hodet.',
        soundLink: '',
        wordId: 41
      },
      {
        nor: 'en betennelse',
        eng: 'inflammation',
        pl: 'zapalenie',
        ar: 'التهاب',
        ger: 'Entzündung',
        lt: 'uždegimas',
        key: '42',
        norEgz: 'Han har en betennelse i kneet.',
        soundLink: '',
        wordId: 42
      },
      {
        nor: 'en blanding',
        eng: 'mixture',
        pl: 'mieszanina',
        ar: 'مزيج',
        ger: 'Mischung',
        lt: 'mišinys',
        key: '43',
        norEgz: 'Dette er en blanding av forskjellige ingredienser.',
        soundLink: '',
        wordId: 43
      },
      {
        nor: 'euforisk',
        eng: 'euphoric',
        pl: 'euforyczny',
        ar: 'نشوة',
        ger: 'euphorisch',
        lt: 'euforinis',
        key: '44',
        norEgz: 'Han følte seg euforisk etter å ha vunnet løpet.',
        soundLink: '',
        wordId: 44
      },
      {
        nor: 'fanatisk',
        eng: 'fanatical',
        pl: 'fanatyczny',
        ar: 'متعصب',
        ger: 'fanatisch',
        lt: 'fanatiškas',
        key: '45',
        norEgz: 'Hun er en fanatisk tilhenger av bandet.',
        soundLink: '',
        wordId: 45
      },
      {
        nor: 'flittig',
        eng: 'diligent',
        pl: 'pracowity',
        ar: 'مجتهد',
        ger: 'fleißig',
        lt: 'diligentas',
        key: '46',
        norEgz: 'Han er en flittig student som alltid gjør leksene sine.',
        soundLink: '',
        wordId: 46
      },
      {
        nor: 'fornuftig',
        eng: 'sensible',
        pl: 'rozsądny',
        ar: 'عاقل',
        ger: 'vernünftig',
        lt: 'protingas',
        key: '47',
        norEgz: 'Det er fornuftig å spare penger til fremtiden.',
        soundLink: '',
        wordId: 47
      },
      {
        nor: 'en brosjyre',
        eng: 'brochure',
        pl: 'broszura',
        ar: 'كتيب',
        ger: 'Broschüre',
        lt: 'brošiūra',
        key: '48',
        norEgz: 'Jeg fant en interessant brosjyre om reisemålet.',
        soundLink: '',
        wordId: 48
      },
      {
        nor: 'en bølge',
        eng: 'wave',
        pl: 'fala',
        ar: 'موجة',
        ger: 'Welle',
        lt: 'banga',
        key: '49',
        norEgz: 'Bølgene på stranden var veldig høye.',
        soundLink: '',
        wordId: 49
      },
      {
        nor: 'en dybde',
        eng: 'depth',
        pl: 'głębokość',
        ar: 'عمق',
        ger: 'Tiefe',
        lt: 'gylis',
        key: '50',
        norEgz: 'Sjøen hadde en imponerende dybde.',
        soundLink: '',
        wordId: 50
      },
      {
        nor: 'en forbindelse',
        eng: 'connection',
        pl: 'połączenie',
        ar: 'اتصال',
        ger: 'Verbindung',
        lt: 'ryšys',
        key: '51',
        norEgz: 'Det er en god forbindelse mellom de to byene.',
        soundLink: '',
        wordId: 51
      },
      {
        nor: 'en forfatter',
        eng: 'author',
        pl: 'autor',
        ar: 'مؤلف',
        ger: 'Autor',
        lt: 'autorius',
        key: '52',
        norEgz: 'Hun er en kjent forfatter i Norge.',
        soundLink: '',
        wordId: 52
      },
      {
        nor: 'en forlengelse',
        eng: 'extension',
        pl: 'przedłużenie',
        ar: 'تمديد',
        ger: 'Verlängerung',
        lt: 'pratęsimas',
        key: '53',
        norEgz: 'De har bedt om en forlengelse av fristen.',
        soundLink: '',
        wordId: 53
      },
      {
        nor: 'å hindre',
        eng: 'prevent',
        pl: 'zapobiegać',
        ar: 'منع',
        ger: 'verhindern',
        lt: 'užkirsti kelią',
        key: '54',
        norEgz: 'Vi må hindre at dette skjer igjen.',
        soundLink: '',
        wordId: 54
      },
      {
        nor: 'å lykkes',
        eng: 'succeed',
        pl: 'odnieść sukces',
        ar: 'ينجح',
        ger: 'Erfolg haben',
        lt: 'pasisekti',
        key: '55',
        norEgz: 'Hun arbeidet hardt for å lykkes.',
        soundLink: '',
        wordId: 55
      },{
        nor: 'å nøle',
        eng: 'hesitate',
        pl: 'wahać się',
        ar: 'تردد',
        ger: 'zögern',
        lt: 'nedrąsoti',
        key: '56',
        norEgz: 'Han nølte før han svarte på spørsmålet.',
        soundLink: '',
        wordId: 56
      },
      {
        nor: 'en forsikring',
        eng: 'insurance',
        pl: 'ubezpieczenie',
        ar: 'تأمين',
        ger: 'Versicherung',
        lt: 'draudimas',
        key: '57',
        norEgz: 'Jeg må tegne en reiseforsikring før ferien.',
        soundLink: '',
        wordId: 57
      },
      {
        nor: 'en forskjell',
        eng: 'difference',
        pl: 'różnica',
        ar: 'فرق',
        ger: 'Unterschied',
        lt: 'skirtumas',
        key: '58',
        norEgz: 'Det er stor forskjell på de to produktene.',
        soundLink: '',
        wordId: 58
      },
      {
        nor: 'en frustrasjon',
        eng: 'frustration',
        pl: 'frustracja',
        ar: 'إحباط',
        ger: 'Frustration',
        lt: 'frustracija',
        key: '59',
        norEgz: 'Hans frustrasjon vokste etter hvert som tiden gikk.',
        soundLink: '',
        wordId: 59
      },
      {
        nor: 'en følelse',
        eng: 'feeling',
        pl: 'uczucie',
        ar: 'شعور',
        ger: 'Gefühl',
        lt: 'jausmas',
        key: '60',
        norEgz: 'Hun hadde en rar følelse i magen.',
        soundLink: '',
        wordId: 60
      },
      {
        nor: 'en gjenoppbygging',
        eng: 'reconstruction',
        pl: 'odbudowa',
        ar: 'إعادة بناء',
        ger: 'Rekonstruktion',
        lt: 'atstatymas',
        key: '61',
        norEgz: 'Gjenoppbyggingen av byen tok flere år.',
        soundLink: '',
        wordId: 61
      },
      {
        nor: 'en hevn',
        eng: 'revenge',
        pl: 'zemsta',
        ar: 'انتقام',
        ger: 'Rache',
        lt: 'kerštas',
        key: '62',
        norEgz: 'Han søkte hevn for sin brors død.',
        soundLink: '',
        wordId: 62
      },
      {
        nor: 'frekk',
        eng: 'cheeky',
        pl: 'bezczelny',
        ar: 'وقح',
        ger: 'frech',
        lt: 'drąsus',
        key: '63',
        norEgz: 'Han hadde et frekt smil.',
        soundLink: '',
        wordId: 63
      },
      {
        nor: 'frivillig',
        eng: 'voluntary',
        pl: 'dobrowolny',
        ar: 'طوعي',
        ger: 'freiwillig',
        lt: 'savaiminis',
        key: '64',
        norEgz: 'Han deltok frivillig i prosjektet.',
        soundLink: '',
        wordId: 64
      },
      {
        nor: 'galant',
        eng: 'gallant',
        pl: 'gallant',
        ar: 'بطولي',
        ger: 'galant',
        lt: 'galantas',
        key: '65',
        norEgz: 'Han opptrådte galant mot damene.',
        soundLink: '',
        wordId: 65
      },
      {
        nor: 'harmonisk',
        eng: 'harmonious',
        pl: 'harmonijny',
        ar: 'متناسق',
        ger: 'harmonisch',
        lt: 'harmoningas',
        key: '66',
        norEgz: 'De hadde et harmonisk forhold.',
        soundLink: '',
        wordId: 66
      },
      {
        nor: 'idealistisk',
        eng: 'idealistic',
        pl: 'idealistyczny',
        ar: 'مثالي',
        ger: 'idealistisch',
        lt: 'idealistiškas',
        key: '67',
        norEgz: 'Hans idealistiske syn på verden er inspirerende.',
        soundLink: '',
        wordId: 67
      },
      {
        nor: 'å observere',
        eng: 'observe',
        pl: 'obserwować',
        ar: 'ملاحظة',
        ger: 'beobachten',
        lt: 'stebėti',
        key: '68',
        norEgz: 'Han observerte fuglene i skogen.',
        soundLink: '',
        wordId: 68
      },
      {
        nor: 'å prioritere',
        eng: 'prioritize',
        pl: 'priorytet',
        ar: 'أعطي الأولوية',
        ger: 'priorisieren',
        lt: 'prioritetizuoti',
        key: '69',
        norEgz: 'Hun måtte prioritere oppgavene sine.',
        soundLink: '',
        wordId: 69
      },
      {
        nor: 'å redusere',
        eng: 'reduce',
        pl: 'redukować',
        ar: 'تخفيض',
        ger: 'reduzieren',
        lt: 'sumažinti',
        key: '70',
        norEgz: 'De prøver å redusere utslippene av karbondioksid.',
        soundLink: '',
        wordId: 70
      },
      {
        nor: 'å reflektere',
        eng: 'reflect',
        pl: 'rozważać',
        ar: 'تفكير',
        ger: 'nachdenken',
        lt: 'atsispindėti',
        key: '71',
        norEgz: 'Han trenger tid til å reflektere over beslutningen.',
        soundLink: '',
        wordId: 71
      },
      {
        nor: 'en hjerne',
        eng: 'a brain',
        pl: 'mózg',
        ar: 'دماغ',
        ger: 'ein Gehirn',
        lt: 'smegenys',
        key: '72',
        norEgz: 'Hjernen er kroppens kontrollsentrum.',
        soundLink: '',
        wordId: 72
      },
      {
        nor: 'en innflytelse',
        eng: 'an influence',
        pl: 'wpływ',
        ar: 'تأثير',
        ger: 'ein Einfluss',
        lt: 'įtaka',
        key: '73',
        norEgz: 'Hans innflytelse på teamet var betydelig.',
        soundLink: '',
        wordId: 73
      },
      {
        nor: 'en anbefaling',
        eng: 'a recommendation',
        pl: 'rekomendacja',
        ar: 'توصية',
        ger: 'eine Empfehlung',
        lt: 'rekomendacija',
        key: '74',
        norEgz: 'Han ga en anbefaling for den nye boken.',
        soundLink: '',
        wordId: 74
      },
      {
        nor: 'en anerkjennelse',
        eng: 'an acknowledgment',
        pl: 'uznanie',
        ar: 'اعتراف',
        ger: 'eine Anerkennung',
        lt: 'pripažinimas',
        key: '75',
        norEgz: 'Han mottok en anerkjennelse for sitt arbeid.',
        soundLink: '',
        wordId: 75
      },
      {
        nor: 'en avtale',
        eng: 'an agreement',
        pl: 'umowa',
        ar: 'اتفاق',
        ger: 'eine Vereinbarung',
        lt: 'sutartis',
        key: '76',
        norEgz: 'De inngikk en avtale om samarbeid.',
        soundLink: '',
        wordId: 76
      },
      {
        nor: 'en bekjennelse',
        eng: 'a confession',
        pl: 'wyznanie',
        ar: 'اعتراف',
        ger: 'ein Geständnis',
        lt: 'prisipažinimas',
        key: '77',
        norEgz: 'Hun ga en ærlig bekjennelse til politiet.',
        soundLink: '',
        wordId: 77
      },
      {
        nor: 'impulsiv',
        eng: 'impulsive',
        pl: 'impulsywny',
        ar: 'اندفاعي',
        ger: 'impulsiv',
        lt: 'impulsyvus',
        key: '78',
        norEgz: 'Han er kjent for å være impulsiv.',
        soundLink: '',
        wordId: 78
      },
      {
        nor: 'inkompetent',
        eng: 'incompetent',
        pl: 'niekompetentny',
        ar: 'غير كفء',
        ger: 'inkompetent',
        lt: 'nekvalifikuotas',
        key: '79',
        norEgz: 'Den inkompetente lederen skapte problemer for selskapet.',
        soundLink: '',
        wordId: 79
      },
      {
        nor: 'innovativ',
        eng: 'innovative',
        pl: 'innowacyjny',
        ar: 'مبتكر',
        ger: 'innovativ',
        lt: 'inovatyvus',
        key: '80',
        norEgz: 'Selskapet er kjent for sine innovative løsninger.',
        soundLink: '',
        wordId: 80
      },
      {
        nor: 'intellektuell',
        eng: 'intellectual',
        pl: 'intelektualny',
        ar: 'فكري',
        ger: 'intellektuell',
        lt: 'intelektualus',
        key: '81',
        norEgz: 'Han er en intellektuell person.',
        soundLink: '',
        wordId: 81
      },
      {
        nor: 'introvert',
        eng: 'introverted',
        pl: 'introwertyk',
        ar: 'منطوي',
        ger: 'introvertiert',
        lt: 'introvertas',
        key: '82',
        norEgz: 'Han er en introvert person.',
        soundLink: '',
        wordId: 82
      },
      {
        nor: 'å sette pris på',
        eng: 'to appreciate',
        pl: 'doceniać',
        ar: 'يقدر',
        ger: 'schätzen',
        lt: 'įvertinti',
        key: '83',
        norEgz: 'Jeg setter pris på din hjelp.',
        soundLink: '',
        wordId: 83
      },
      {
        nor: 'å skuffe',
        eng: 'to disappoint',
        pl: 'rozczarować',
        ar: 'يخيب الامل',
        ger: 'enttäuschen',
        lt: 'nuvilti',
        key: '84',
        norEgz: 'Jeg ønsker ikke å skuffe deg.',
        soundLink: '',
        wordId: 84
      },
      {
        nor: 'å tolerere',
        eng: 'to tolerate',
        pl: 'tolerować',
        ar: 'يتسامح',
        ger: 'tolerieren',
        lt: 'toleruoti',
        key: '85',
        norEgz: 'Vi må lære å tolerere forskjeller.',
        soundLink: '',
        wordId: 85
      },
      {
        nor: 'å utvikle',
        eng: 'to develop',
        pl: 'rozwijać',
        ar: 'يطور',
        ger: 'entwickeln',
        lt: 'plėtoti',
        key: '86',
        norEgz: 'Vi må utvikle en ny strategi.',
        soundLink: '',
        wordId: 86
      },
      {
        nor: 'en bekreftelse',
        eng: 'a confirmation',
        pl: 'potwierdzenie',
        ar: 'تأكيد',
        ger: 'eine Bestätigung',
        lt: 'patvirtinimas',
        key: '87',
        norEgz: 'Vi trenger en bekreftelse på bestillingen.',
        soundLink: '',
        wordId: 87
      },
      {
        nor: 'en affære',
        eng: 'an affair',
        pl: 'afera',
        ar: 'علاقة',
        ger: 'eine Affäre',
        lt: 'reikalas',
        key: '88',
        norEgz: 'Han hadde en affære med sin kollega.',
        soundLink: '',
        wordId: 88
      },
      {
        nor: 'en anklage',
        eng: 'an accusation',
        pl: 'oskarżenie',
        ar: 'اتهام',
        ger: 'eine Anklage',
        lt: 'kaltinimas',
        key: '89',
        norEgz: 'Anklagen mot ham var ubegrunnet.',
        soundLink: '',
        wordId: 89
      },
      {
        nor: 'en arbeidsgiver',
        eng: 'an employer',
        pl: 'pracodawca',
        ar: 'صاحب العمل',
        ger: 'ein Arbeitgeber',
        lt: 'darbdavys',
        key: '90',
        norEgz: 'Arbeidsgiveren hans er et stort firma.',
        soundLink: '',
        wordId: 90
      },
      {
        nor: 'en balanse',
        eng: 'a balance',
        pl: 'równowaga',
        ar: 'توازن',
        ger: 'eine Balance',
        lt: 'pusiausvyra',
        key: '91',
        norEgz: 'Vi må finne en balanse mellom arbeid og fritid.',
        soundLink: '',
        wordId: 91
      },
      {
        nor: 'ekstrovert',
        eng: 'extroverted',
        pl: 'ekstrawertyk',
        ar: 'منبسط',
        ger: 'extrovertiert',
        lt: 'ekstrovertas',
        key: '92',
        norEgz: 'Hun er en ekstrovert person.',
        soundLink: '',
        wordId: 92
      },
      {
        nor: 'naiv',
        eng: 'naive',
        pl: 'naiwny',
        ar: 'ساذج',
        ger: 'naiv',
        lt: 'naivus',
        key: '93',
        norEgz: 'Han var naiv nok til å tro på løgnene.',
        soundLink: '',
        wordId: 93
      },
      {
        nor: 'nøysom',
        eng: 'frugal',
        pl: 'oszczędny',
        ar: 'مقتصد',
        ger: 'genügsam',
        lt: 'tausus',
        key: '94',
        norEgz: 'Hun er nøysom og sparer penger der hun kan.',
        soundLink: '',
        wordId: 94
      },
      {
        nor: 'objektiv',
        eng: 'objective',
        pl: 'obiektywny',
        ar: 'موضوعي',
        ger: 'objektiv',
        lt: 'objektyvus',
        key: '95',
        norEgz: 'Vi må være objektive når vi vurderer situasjonen.',
        soundLink: '',
        wordId: 95
      },
      {
        nor: 'subjektiv',
        eng: 'subjective',
        pl: 'subiektywny',
        ar: 'ذاتي',
        ger: 'subjektiv',
        lt: 'subjektyvus',
        key: '96',
        norEgz: 'Hans mening er subjektiv.',
        soundLink: '',
        wordId: 96
      },
      {
        nor: 'å vedta',
        eng: 'to adopt',
        pl: 'przyjąć',
        ar: 'تبنى',
        ger: 'annehmen',
        lt: 'priimti',
        key: '97',
        norEgz: 'De bestemte seg for å vedta forslaget.',
        soundLink: '',
        wordId: 97
      },
      {
        nor: 'å være enig',
        eng: 'to agree',
        pl: 'zgadzać się',
        ar: 'يوافق',
        ger: 'zustimmen',
        lt: 'sutikti',
        key: '98',
        norEgz: 'Vi er enige om at dette er den beste løsningen.',
        soundLink: '',
        wordId: 98
      },
      {
        nor: 'å oppdage',
        eng: 'to discover',
        pl: 'odkryć',
        ar: 'اكتشاف',
        ger: 'entdecken',
        lt: 'atrasti',
        key: '99',
        norEgz: 'Han oppdaget en ny metode for å løse problemet.',
        soundLink: '',
        wordId: 99
      },
      {
        nor: 'en påvirkning',
        eng: 'an influence',
        pl: 'wpływ',
        ar: 'تأثير',
        ger: 'ein Einfluss',
        lt: 'įtaka',
        key: '100',
        norEgz: 'Hennes påvirkning på ham var tydelig.',
        soundLink: '',
        wordId: 100
      },
      {
        nor: 'en konsekvens',
        eng: 'a consequence',
        pl: 'konsekwencja',
        ar: 'عاقبة',
        ger: 'eine Konsequenz',
        lt: 'pasekmė',
        key: '101',
        norEgz: 'Hans handlinger hadde alvorlige konsekvenser.',
        soundLink: '',
        wordId: 101
      },
      {
        nor: 'en risiko',
        eng: 'a risk',
        pl: 'ryzyko',
        ar: 'مخاطرة',
        ger: 'ein Risiko',
        lt: 'rizika',
        key: '102',
        norEgz: 'Vi må vurdere risikoen før vi tar en beslutning.',
        soundLink: '',
        wordId: 102
      },
      {
        nor: 'en sikkerhet',
        eng: 'a security',
        pl: 'bezpieczeństwo',
        ar: 'أمان',
        ger: 'eine Sicherheit',
        lt: 'saugumas',
        key: '103',
        norEgz: 'Sikkerhet er viktig i denne bransjen.',
        soundLink: '',
        wordId: 103
      },
      {
        nor: 'en beskyttelse',
        eng: 'a protection',
        pl: 'ochrona',
        ar: 'حماية',
        ger: 'ein Schutz',
        lt: 'apsauga',
        key: '104',
        norEgz: 'De trengte beskyttelse mot solen.',
        soundLink: '',
        wordId: 104
      },
      {
        nor: 'patriotisk',
        eng: 'patriotic',
        pl: 'patriotyczny',
        ar: 'وطني',
        ger: 'patriotisch',
        lt: 'patriotinis',
        key: '105',
        norEgz: 'Han er en patriotisk person.',
        soundLink: '',
        wordId: 105
      },
      {
        nor: 'pragmatisk',
        eng: 'pragmatic',
        pl: 'pragmatyczny',
        ar: 'عملي',
        ger: 'pragmatisch',
        lt: 'pragmatiškas',
        key: '106',
        norEgz: 'Hun har en pragmatisk tilnærming til problemet.',
        soundLink: '',
        wordId: 106
      },
      {
        nor: 'provoserende',
        eng: 'provocative',
        pl: 'prowokacyjny',
        ar: 'مستفز',
        ger: 'provokativ',
        lt: 'provokuojantis',
        key: '107',
        norEgz: 'Han hadde en provoserende holdning.',
        soundLink: '',
        wordId: 107
      },
      {
        nor: 'skeptisk',
        eng: 'skeptical',
        pl: 'sceptyczny',
        ar: 'متشكك',
        ger: 'skeptisch',
        lt: 'skeptiškas',
        key: '108',
        norEgz: 'Hun er skeptisk til det nye forslaget.',
        soundLink: '',
        wordId: 108
      },
      {
        nor: 'systematisk',
        eng: 'systematic',
        pl: 'systematyczny',
        ar: 'منهجي',
        ger: 'systematisch',
        lt: 'sistemingas',
        key: '109',
        norEgz: 'Vi må være systematiske i arbeidet vårt.',
        soundLink: '',
        wordId: 109
      },
      {
        nor: 'å uttrykke',
        eng: 'to express',
        pl: 'wyrażać',
        ar: 'للتعبير',
        ger: 'ausdrücken',
        lt: 'išreikšti',
        key: '110',
        norEgz: 'Han ønsket å uttrykke sin takknemlighet.',
        soundLink: '',
        wordId: 110
      },
      {
        nor: 'å vurdere',
        eng: 'to assess',
        pl: 'oceniać',
        ar: 'تقييم',
        ger: 'bewerten',
        lt: 'įvertinti',
        key: '111',
        norEgz: 'Vi må vurdere situasjonen nøye.',
        soundLink: '',
        wordId: 111
      },
      {
        nor: 'å sammenligne',
        eng: 'to compare',
        pl: 'porównywać',
        ar: 'للمقارنة',
        ger: 'vergleichen',
        lt: 'palyginti',
        key: '112',
        norEgz: 'Vi må sammenligne prisene før vi kjøper.',
        soundLink: '',
        wordId: 112
      },
      {
        nor: 'å anbefale',
        eng: 'to recommend',
        pl: 'polecać',
        ar: 'للتوصية',
        ger: 'empfehlen',
        lt: 'rekomenduoti',
        key: '113',
        norEgz: 'Jeg vil anbefale denne boken til deg.',
        soundLink: '',
        wordId: 113
      },
      {
        nor: 'en barndom',
        eng: 'a childhood',
        pl: 'dzieciństwo',
        ar: 'طفولة',
        ger: 'eine Kindheit',
        lt: 'vaikystė',
        key: '114',
        norEgz: 'Hun hadde en lykkelig barndom.',
        soundLink: '',
        wordId: 114
      },
      {
        nor: 'en bedrift',
        eng: 'a company',
        pl: 'firma',
        ar: 'شركة',
        ger: 'ein Unternehmen',
        lt: 'įmonė',
        key: '115',
        norEgz: 'Han jobber for en stor bedrift.',
        soundLink: '',
        wordId: 115
      },
      {
        nor: 'en begrensning',
        eng: 'a limitation',
        pl: 'ograniczenie',
        ar: 'تحديد',
        ger: 'eine Begrenzung',
        lt: 'apribojimas',
        key: '116',
        norEgz: 'Det er en begrensning på hvor mye vi kan gjøre.',
        soundLink: '',
        wordId: 116
      },
      {
        nor: 'en bein',
        eng: 'a bone',
        pl: 'kość',
        ar: 'عظم',
        ger: 'ein Knochen',
        lt: 'kaulas',
        key: '117',
        norEgz: 'Hunden gnager på en bein.',
        soundLink: '',
        wordId: 117
      },
      {
        nor: 'en beskrivelse',
        eng: 'a description',
        pl: 'opis',
        ar: 'وصف',
        ger: 'eine Beschreibung',
        lt: 'aprašymas',
        key: '118',
        norEgz: 'Han ga en detaljert beskrivelse av hendelsen.',
        soundLink: '',
        wordId: 118
      },
      {
        nor: 'uavhengig',
        eng: 'independent',
        pl: 'niezależny',
        ar: 'مستقل',
        ger: 'unabhängig',
        lt: 'nepriklausomas',
        key: '119',
        norEgz: 'Han ønsker å være økonomisk uavhengig.',
        soundLink: '',
        wordId: 119
      },
      {
        nor: 'underdanig',
        eng: 'submissive',
        pl: 'pokorny',
        ar: 'خاضع',
        ger: 'unterwürfig',
        lt: 'paklusnus',
        key: '120',
        norEgz: 'Hun var underdanig i sin oppførsel.',
        soundLink: '',
        wordId: 120
      },
      {
        nor: 'unik',
        eng: 'unique',
        pl: 'unikalny',
        ar: 'فريد',
        ger: 'einzigartig',
        lt: 'unikalus',
        key: '121',
        norEgz: 'Dette smykket er unikt og håndlaget.',
        soundLink: '',
        wordId: 121
      },
      {
        nor: 'hjelpsom',
        eng: 'helpful',
        pl: 'pomocny',
        ar: 'مفيد',
        ger: 'hilfreich',
        lt: 'pagalbinis',
        key: '122',
        norEgz: 'Han er alltid hjelpsom og støttende.',
        soundLink: '',
        wordId: 122
      },
      {
        nor: 'egoistisk',
        eng: 'selfish',
        pl: 'samolubny',
        ar: 'أناني',
        ger: 'egoistisch',
        lt: 'saviškas',
        key: '123',
        norEgz: 'Hans egoistiske holdning skapte problemer for gruppen.',
        soundLink: '',
        wordId: 123
      },
      {
        nor: 'å beskrive',
        eng: 'to describe',
        pl: 'opisywać',
        ar: 'لوصف',
        ger: 'beschreiben',
        lt: 'apibūdinti',
        key: '124',
        norEgz: 'Kan du beskrive personen for meg?',
        soundLink: '',
        wordId: 124
      },
      {
        nor: 'å bestemme',
        eng: 'to decide',
        pl: 'zdecydować',
        ar: 'للتحديد',
        ger: 'entscheiden',
        lt: 'nuspręsti',
        key: '125',
        norEgz: 'Vi må bestemme hvor vi skal dra på ferie.',
        soundLink: '',
        wordId: 125
      },
      {
        nor: 'en erfaring',
        eng: 'an experience',
        pl: 'doświadczenie',
        ar: 'تجربة',
        ger: 'eine Erfahrung',
        lt: 'patirtis',
        key: '126',
        norEgz: 'Reisen var en uforglemmelig erfaring.',
        soundLink: '',
        wordId: 126
      },
      {
        nor: 'en etasje',
        eng: 'a floor',
        pl: 'piętro',
        ar: 'طابق',
        ger: 'eine Etage',
        lt: 'aukštas',
        key: '127',
        norEgz: 'Heisen går til den femte etasjen.',
        soundLink: '',
        wordId: 127
      },
      {
        nor: 'selvkritisk',
        eng: 'self-critical',
        pl: 'samokrytyczny',
        ar: 'نقدي للنفس',
        ger: 'selbstkritisch',
        lt: 'saviškas',
        key: '128',
        norEgz: 'Han er veldig selvkritisk og analyserer alltid sitt eget arbeid.',
        soundLink: '',
        wordId: 128
      },
      {
        nor: 'selvgod',
        eng: 'smug',
        pl: 'próżny',
        ar: 'مغرور',
        ger: 'selbstgefällig',
        lt: 'pasipūtęs',
        key: '129',
        norEgz: 'Hun virket selvgod etter å ha vunnet prisen.',
        soundLink: '',
        wordId: 129
      },
      {
        nor: 'en bevegelse',
        eng: 'a movement',
        pl: 'ruch',
        ar: 'حركة',
        ger: 'eine Bewegung',
        lt: 'judesys',
        key: '130',
        norEgz: 'Han gjorde en rask bevegelse med hånden.',
        soundLink: '',
        wordId: 130
      },
      {
        nor: 'en boliglån',
        eng: 'a mortgage',
        pl: 'kredyt hipoteczny',
        ar: 'رهن عقاري',
        ger: 'eine Hypothek',
        lt: 'būsto paskola',
        key: '131',
        norEgz: 'Vi tok opp boliglån for å kjøpe huset.',
        soundLink: '',
        wordId: 131
      },
      {
        nor: 'en bondegård',
        eng: 'a farmhouse',
        pl: 'gospodarstwo wiejskie',
        ar: 'مزرعة',
        ger: 'ein Bauernhaus',
        lt: 'ūkininko sodyba',
        key: '132',
        norEgz: 'De bodde på en sjarmerende bondegård i landsbygda.',
        soundLink: '',
        wordId: 132
      },
      {
        nor: 'en bryllupsreise',
        eng: 'a honeymoon',
        pl: 'podróż poślubna',
        ar: 'شهر العسل',
        ger: 'eine Flitterwochen',
        lt: 'medaus mėnuo',
        key: '133',
        norEgz: 'Paret dro på bryllupsreise til Maldivene.',
        soundLink: '',
        wordId: 133
      },
      {
        nor: 'snill',
        eng: 'kind',
        pl: 'uprzejmy',
        ar: 'طيب',
        ger: 'liebenswürdig',
        lt: 'malonus',
        key: '134',
        norEgz: 'Hun er alltid snill og hjelpsom mot alle.',
        soundLink: '',
        wordId: 134
      },
      {
        nor: 'klok',
        eng: 'wise',
        pl: 'mądry',
        ar: 'حكيم',
        ger: 'weise',
        lt: 'išmintingas',
        key: '135',
        norEgz: 'Hans kloke råd hjalp oss med å ta en bedre beslutning.',
        soundLink: '',
        wordId: 135
    },
    {
        nor: 'energisk',
        eng: 'energetic',
        pl: 'energiczny',
        ar: 'مفعم بالحيوية',
        ger: 'energisch',
        lt: 'energingas',
        key: '136',
        norEgz: 'Han er alltid så energisk og entusiastisk.',
        soundLink: '',
        wordId: 136
      },
      {
        nor: 'sliten',
        eng: 'tired',
        pl: 'zmęczony',
        ar: 'متعب',
        ger: 'müde',
        lt: 'pavargęs',
        key: '137',
        norEgz: 'Etter en lang dag på jobben, er jeg veldig sliten.',
        soundLink: '',
        wordId: 137
      },
      {
        nor: 'spennende',
        eng: 'exciting',
        pl: 'ekscytujący',
        ar: 'مثير',
        ger: 'aufregend',
        lt: 'įdomus',
        key: '138',
        norEgz: 'Dette er en spennende mulighet for oss alle.',
        soundLink: '',
        wordId: 138
      },
      {
        nor: 'å bevare',
        eng: 'to preserve',
        pl: 'zachować',
        ar: 'للحفاظ على',
        ger: 'erhalten',
        lt: 'išsaugoti',
        key: '139',
        norEgz: 'Vi må bevare naturen for fremtidige generasjoner.',
        soundLink: '',
        wordId: 139
      },
      {
        nor: 'å delta',
        eng: 'to participate',
        pl: 'uczestniczyć',
        ar: 'المشاركة',
        ger: 'teilnehmen',
        lt: 'dalyvauti',
        key: '140',
        norEgz: 'Han ønsker å delta i konkurransen.',
        soundLink: '',
        wordId: 140
      },
      {
        nor: 'en fagforening',
        eng: 'a trade union',
        pl: 'związek zawodowy',
        ar: 'نقابة عمال',
        ger: 'eine Gewerkschaft',
        lt: 'profesinė sąjunga',
        key: '141',
        norEgz: 'Fagforeningen representerer arbeidernes interesser.',
        soundLink: '',
        wordId: 141
      },
      {
        nor: 'en fallskjerm',
        eng: 'a parachute',
        pl: 'spadochron',
        ar: 'مظلة',
        ger: 'ein Fallschirm',
        lt: 'parasiutas',
        key: '142',
        norEgz: 'Han hoppet ut av flyet med en fallskjerm.',
        soundLink: '',
        wordId: 142
      },
      {
        nor: 'ydmyk',
        eng: 'humble',
        pl: 'pokorny',
        ar: 'متواضع',
        ger: 'bescheiden',
        lt: 'nusižeminęs',
        key: '143',
        norEgz: 'Han er en ydmyk person som alltid hjelper andre.',
        soundLink: '',
        wordId: 143
      },
      {
        nor: 'arrogant',
        eng: 'arrogant',
        pl: 'arogancki',
        ar: 'متعجرف',
        ger: 'arrogant',
        lt: 'arogantiškas',
        key: '144',
        norEgz: 'Han oppfører seg arrogant og uhøflig.',
        soundLink: '',
        wordId: 144
      },
      {
        nor: 'å banke',
        eng: 'to knock',
        pl: 'pukać',
        ar: 'يطرق',
        ger: 'klopfen',
        lt: 'belsti',
        key: '145',
        norEgz: 'Han banket på døren før han gikk inn.',
        soundLink: '',
        wordId: 145
      },
      {
        nor: 'en bursdag',
        eng: 'a birthday',
        pl: 'urodziny',
        ar: 'عيد ميلاد',
        ger: 'ein Geburtstag',
        lt: 'gimtadienis',
        key: '146',
        norEgz: 'Vi feirer bursdagen hennes i kveld.',
        soundLink: '',
        wordId: 146
      },
      {
        nor: 'en bytte',
        eng: 'an exchange',
        pl: 'wymiana',
        ar: 'تبادل',
        ger: 'ein Austausch',
        lt: 'keitimas',
        key: '147',
        norEgz: 'De gjorde en bytte av varer og tjenester.',
        soundLink: '',
        wordId: 147
      },
      {
        nor: 'en børst',
        eng: 'a brush',
        pl: 'szczotka',
        ar: 'فرشاة',
        ger: 'eine Bürste',
        lt: 'šepetys',
        key: '148',
        norEgz: 'Han bruker en børst til å male veggen.',
        soundLink: '',
        wordId: 148
      },
      {
        nor: 'en død',
        eng: 'a death',
        pl: 'śmierć',
        ar: 'وفاة',
        ger: 'ein Tod',
        lt: 'mirtis',
        key: '149',
        norEgz: 'En død i familien er en trist hendelse.',
        soundLink: '',
        wordId: 149
      },
      {
        nor: 'en endring',
        eng: 'a change',
        pl: 'zmiana',
        ar: 'تغيير',
        ger: 'eine Änderung',
        lt: 'pakeitimas',
        key: '150',
        norEgz: 'Vi trenger en endring i planene våre.',
        soundLink: '',
        wordId: 150
      },
      {
        nor: 'gjerrig',
        eng: 'stingy',
        pl: 'skąpy',
        ar: 'بخيل',
        ger: 'geizig',
        lt: 'šykštus',
        key: '151',
        norEgz: 'Han er kjent for å være gjerrig med pengene sine.',
        soundLink: '',
        wordId: 151
      },
      {
        nor: 'oppmerksom',
        eng: 'attentive',
        pl: 'uważny',
        ar: 'منتبه',
        ger: 'aufmerksam',
        lt: 'dėmesingas',
        key: '152',
        norEgz: 'Han er alltid oppmerksom på detaljer.',
        soundLink: '',
        wordId: 152
      },
      {
        nor: 'uoppmerksom',
        eng: 'inattentive',
        pl: 'nieuważny',
        ar: 'غير منتبه',
        ger: 'unaufmerksam',
        lt: 'neįdėmesingas',
        key: '153',
        norEgz: 'Han fikk en bot fordi han var uoppmerksom mens han kjørte.',
        soundLink: '',
        wordId: 153
      }
  ]