[
  {
    nor: 'å anerkjenne',
    eng: 'to acknowledge',
    pl: 'uznać',
    ar: 'الاعتراف',
    ger: 'anerkennen',
    lt: 'pripažinti',
    key: '0',
    norEgz: 'Han måtte anerkjenne sine feil.',
    soundLink: '',
    wordId: 0
  },
  {
    nor: 'å antyde',
    eng: 'to imply',
    pl: 'sugerować',
    ar: 'يلمح',
    ger: 'andeuten',
    lt: 'užsiminti',
    key: '1',
    norEgz: 'Han antydet at han visste sannheten.',
    soundLink: '',
    wordId: 1
  },
  {
    nor: 'å avsløre',
    eng: 'to reveal',
    pl: 'ujawnić',
    ar: 'كشف',
    ger: 'aufdecken',
    lt: 'atskleisti',
    key: '2',
    norEgz: 'Hun avslørte hemmeligheten sin til vennene sine.',
    soundLink: '',
    wordId: 2
  },
  {
    nor: 'en partikkel',
    eng: 'a particle',
    pl: 'cząstka',
    ar: 'جسيم',
    ger: 'Teilchen',
    lt: 'dalelė',
    key: '3',
    norEgz: 'En partikkel er en liten del av et atom.',
    soundLink: '',
    wordId: 3
  },
  {
    nor: 'en benådning',
    eng: 'a pardon',
    pl: 'łaska',
    ar: 'عفو',
    ger: 'Begnadigung',
    lt: 'malonė',
    key: '4',
    norEgz: 'Presidenten ga en benådning til fangen.',
    soundLink: '',
    wordId: 4
  },
  {
    nor: 'en appell',
    eng: 'an appeal',
    pl: 'apelacja',
    ar: 'استئناف',
    ger: 'Berufung',
    lt: 'apelis',
    key: '5',
    norEgz: 'Hans advokat sendte inn en appell til domstolen.',
    soundLink: '',
    wordId: 5
  },
  {
    nor: 'abstrakt',
    eng: 'abstract',
    pl: 'abstrakcyjny',
    ar: 'مجرد',
    ger: 'abstrakt',
    lt: 'abstraktus',
    key: '6',
    norEgz: 'Maleriet har et abstrakt design.',
    soundLink: '',
    wordId: 6
  },
  {
    nor: 'akademisk',
    eng: 'academic',
    pl: 'akademicki',
    ar: 'أكاديمي',
    ger: 'akademisch',
    lt: 'akademinis',
    key: '7',
    norEgz: 'Hun har en sterk akademisk bakgrunn.',
    soundLink: '',
    wordId: 7
  },
  {
    nor: 'allegorisk',
    eng: 'allegorical',
    pl: 'alegoryczny',
    ar: 'رمزي',
    ger: 'allegorisch',
    lt: 'allegorinis',
    key: '8',
    norEgz: 'Diktet har en allegorisk betydning.',
    soundLink: '',
    wordId: 8
  },
  {
    nor: 'allsidig',
    eng: 'versatile',
    pl: 'wszechstronny',
    ar: 'متعدد الاستعمالات',
    ger: 'vielseitig',
    lt: 'universalus',
    key: '9',
    norEgz: 'Han er en allsidig skuespiller.',
    soundLink: '',
    wordId: 9
  },
  {
    nor: 'å bekrefte',
    eng: 'to confirm',
    pl: 'potwierdzić',
    ar: 'أكد',
    ger: 'bestätigen',
    lt: 'patvirtinti',
    key: '10',
    norEgz: 'Kan du bekrefte at du kommer på festen?',
    soundLink: '',
    wordId: 10
  },
  {
    nor: 'å benekte',
    eng: 'to deny',
    pl: 'zaprzeczyć',
    ar: 'أنكر',
    ger: 'leugnen',
    lt: 'neigti',
    key: '11',
    norEgz: 'Han benektet å ha gjort noe galt.',
    soundLink: '',
    wordId: 11
  },
  {
    nor: 'å betvile',
    eng: 'to doubt',
    pl: 'wątpić',
    ar: 'شك',
    ger: 'bezweifeln',
    lt: 'abejoti',
    key: '12',
    norEgz: 'Jeg betviler at han vil komme i tide.',
    soundLink: '',
    wordId: 12
  },
  {
    nor: 'en fortolkning',
    eng: 'an interpretation',
    pl: 'interpretacja',
    ar: 'تفسير',
    ger: 'Interpretation',
    lt: 'interpretacija',
    key: '13',
    norEgz: 'Hans fortolkning av sangen var imponerende.',
    soundLink: '',
    wordId: 13
  },
  {
    nor: 'en frigjøring',
    eng: 'a liberation',
    pl: 'wyzwolenie',
    ar: 'تحرير',
    ger: 'Befreiung',
    lt: 'išlaisvinimas',
    key: '14',
    norEgz: 'Frigjøringen av byen var en stor seier.',
    soundLink: '',
    wordId: 14
  },
  {
    nor: 'en anerkjennelse',
    eng: 'an acknowledgement',
    pl: 'uznanie',
    ar: 'اعتراف',
    ger: 'Anerkennung',
    lt: 'pripažinimas',
    key: '15',
    norEgz: 'Hun mottok en anerkjennelse for sitt arbeid.',
    soundLink: '',
    wordId: 15
  },
  {
    nor: 'en avkastning',
    eng: 'a return',
    pl: 'zwrot',
    ar: 'عائد',
    ger: 'Rendite',
    lt: 'grąža',
    key: '16',
    norEgz: 'Investeringen hadde en god avkastning.',
    soundLink: '',
    wordId: 16
  },
  {
    nor: 'avantgardistisk',
    eng: 'avant-garde',
    pl: 'awangardowy',
    ar: 'طليعي',
    ger: 'avantgardistisch',
    lt: 'avangardinis',
    key: '17',
    norEgz: 'Hun er kjent for sin avantgardistiske kunst.',
    soundLink: '',
    wordId: 17
  },
  {
    nor: 'bedøvende',
    eng: 'stupefying',
    pl: 'oszałamiający',
    ar: 'مذهل',
    ger: 'betäubend',
    lt: 'apstulbinantis',
    key: '18',
    norEgz: 'Musikken var bedøvende høy.',
    soundLink: '',
    wordId: 18
  },
  {
    nor: 'besluttsom',
    eng: 'decisive',
    pl: 'zdecydowany',
    ar: 'حاسم',
    ger: 'entschlossen',
    lt: 'ryžtingas',
    key: '19',
    norEgz: 'Hun er en besluttsom leder.',
    soundLink: '',
    wordId: 19
  },
  {
    nor: 'desillusjonert',
    eng: 'disillusioned',
    pl: 'rozczarowany',
    ar: 'محبط',
    ger: 'desillusioniert',
    lt: 'nusivylęs',
    key: '20',
    norEgz: 'Han ble desillusjonert etter å ha mistet jobben.',
    soundLink: '',
    wordId: 20
  },
  {
    nor: 'å dedikere',
    eng: 'to dedicate',
    pl: 'poświęcić',
    ar: 'كرّس',
    ger: 'widmen',
    lt: 'dedikuoti',
    key: '21',
    norEgz: 'Hun dedikerte boken til sin mor.',
    soundLink: '',
    wordId: 21
  },
  {
    nor: 'å fordype seg',
    eng: 'to immerse oneself',
    pl: 'zanurzyć się',
    ar: 'ينغمس',
    ger: 'sich vertiefen',
    lt: 'pasinerti',
    key: '22',
    norEgz: 'Han fordypet seg i studiene sine.',
    soundLink: '',
    wordId: 22
  },
  {
    nor: 'å motvirke',
    eng: 'to counteract',
    pl: 'przeciwdziałać',
    ar: 'عكس',
    ger: 'entgegenwirken',
    lt: 'priešgynimas',
    key: '23',
    norEgz: 'Vi må motvirke klimaendringene.',
    soundLink: '',
    wordId: 23
  },
  {
    nor: 'en generalisering',
    eng: 'a generalization',
    pl: 'uogólnienie',
    ar: 'تعميم',
    ger: 'Verallgemeinerung',
    lt: 'generalizacija',
    key: '24',
    norEgz: 'Dette er en unøyaktig generalisering.',
    soundLink: '',
    wordId: 24
  },
  {
    nor: 'en hjernevasking',
    eng: 'a brainwashing',
    pl: 'pranie mózgów',
    ar: 'غسيل دماغ',
    ger: 'Gehirnwäsche',
    lt: 'smegenų plovimas',
    key: '25',
    norEgz: 'Han ble utsatt for hjernevasking.',
    soundLink: '',
    wordId: 25
  },
  {
    nor: 'en inkompetanse',
    eng: 'an incompetence',
    pl: 'niekompetencja',
    ar: 'عجز',
    ger: 'Inkompetenz',
    lt: 'nekvalifikacija',
    key: '26',
    norEgz: 'Inkompetansen hans førte til store problemer.',
    soundLink: '',
    wordId: 26
  },
  {
    nor: 'en kollaps',
    eng: 'a collapse',
    pl: 'kolaps',
    ar: 'انهيار',
    ger: 'Zusammenbruch',
    lt: 'kolapsas',
    key: '27',
    norEgz: 'Bygningen var i fare for å kollapse.',
    soundLink: '',
    wordId: 27
  },
  {
    nor: 'en kvasivitenskap',
    eng: 'a pseudoscience',
    pl: 'pseudonauka',
    ar: 'علم زائف',
    ger: 'Pseudowissenschaft',
    lt: 'pseudo mokslas',
    key: '28',
    norEgz: 'Astrologi anses ofte som en kvasivitenskap.',
    soundLink: '',
    wordId: 28
  },
  {
    nor: 'didaktisk',
    eng: 'didactic',
    pl: 'dydaktyczny',
    ar: 'تعليمي',
    ger: 'didaktisch',
    lt: 'daktaras',
    key: '29',
    norEgz: 'Hans didaktiske stil hjalp studentene å lære raskere.',
    soundLink: '',
    wordId: 29
  },
  {
    nor: 'eksentrisk',
    eng: 'eccentric',
    pl: 'ekscentryczny',
    ar: 'غريب الأطوار',
    ger: 'exzentrisch',
    lt: 'ekscentriškas',
    key: '30',
    norEgz: 'Han er en eksentrisk kunstner.',
    soundLink: '',
    wordId: 30
  },
  {
    nor: 'ekspansiv',
    eng: 'expansive',
    pl: 'ekspansywny',
    ar: 'متسع',
    ger: 'expansiv',
    lt: 'ekspansyvus',
    key: '31',
    norEgz: 'Selskapet har en ekspansiv vekststrategi.',
    soundLink: '',
    wordId: 31
  },
  {
    nor: 'ironisk',
    eng: 'ironic',
    pl: 'ironiczny',
    ar: 'ساخر',
    ger: 'ironisch',
    lt: 'ironiškas',
    key: '32',
    norEgz: 'Han hadde et ironisk smil om munnen.',
    soundLink: '',
    wordId: 32
  },
  {
    nor: 'kompromissløs',
    eng: 'uncompromising',
    pl: 'bezkompromisowy',
    ar: 'لا يعرف التسوية',
    ger: 'kompromisslos',
    lt: 'nepasiduodantis',
    key: '33',
    norEgz: 'Hun er kjent for sin kompromissløse holdning.',
    soundLink: '',
    wordId: 33
  },
  {
    nor: 'å omskrive',
    eng: 'to rewrite',
    pl: 'przepisać',
    ar: 'إعادة كتابة',
    ger: 'umschreiben',
    lt: 'perrašyti',
    key: '34',
    norEgz: 'Han måtte omskrive hele avsnittet.',
    soundLink: '',
    wordId: 34
  },
  {
    nor: 'å simulere',
    eng: 'to simulate',
    pl: 'symulować',
    ar: 'محاكاة',
    ger: 'simulieren',
    lt: 'simuliuoti',
    key: '35',
    norEgz: 'De simulerer situasjonen for å forberede seg.',
    soundLink: '',
    wordId: 35
  },
  {
    nor: 'å spesifisere',
    eng: 'to specify',
    pl: 'określić',
    ar: 'تحديد',
    ger: 'spezifizieren',
    lt: 'nurodyti',
    key: '36',
    norEgz: 'Kan du spesifisere hva du mener?',
    soundLink: '',
    wordId: 36
  },
  {
    nor: 'en omdømme',
    eng: 'a reputation',
    pl: 'reputacja',
    ar: 'سمعة',
    ger: 'ein Ruf',
    lt: 'reputacija',
    key: '37',
    norEgz: 'Selskapet har et godt omdømme.',
    soundLink: '',
    wordId: 37
  },
  {
    nor: 'en omstilling',
    eng: 'a restructuring',
    pl: 'restrukturyzacja',
    ar: 'إعادة هيكلة',
    ger: 'eine Umstrukturierung',
    lt: 'pertvarkymas',
    key: '38',
    norEgz: 'Bedriften gjennomgår en omstilling.',
    soundLink: '',
    wordId: 38
  },
  {
    nor: 'en åpenbaring',
    eng: 'a revelation',
    pl: 'objawienie',
    ar: 'وحي',
    ger: 'eine Offenbarung',
    lt: 'atskleidimas',
    key: '39',
    norEgz: 'Møtet med ham var en åpenbaring for henne.',
    soundLink: '',
    wordId: 39
  },
  {
    nor: 'en bedrag',
    eng: 'a deception',
    pl: 'oszustwo',
    ar: 'خداع',
    ger: 'eine Täuschung',
    lt: 'apgaule',
    key: '40',
    norEgz: 'Han ble lurt av en bedrag.',
    soundLink: '',
    wordId: 40
  },
  {
    nor: 'en begjær',
    eng: 'a desire',
    pl: 'pożądanie',
    ar: 'رغبة',
    ger: 'ein Verlangen',
    lt: 'trokštamas',
    key: '41',
    norEgz: 'Hun kjente en sterk begjær for ham.',
    soundLink: '',
    wordId: 41
  },
  {
    nor: 'kontroversiell',
    eng: 'controversial',
    pl: 'kontrowersyjny',
    ar: 'مثير للجدل',
    ger: 'kontrovers',
    lt: 'kontroversiškas',
    key: '42',
    norEgz: 'Hans uttalelser var kontroversielle.',
    soundLink: '',
    wordId: 42
  },
  {
    nor: 'utfordrende',
    eng: 'challenging',
    pl: 'wymagający',
    ar: 'تحدي',
    ger: 'herausfordernd',
    lt: 'iššūkį keliantis',
    key: '43',
    norEgz: 'Det var en utfordrende oppgave.',
    soundLink: '',
    wordId: 43
  },
  {
    nor: 'kresen',
    eng: 'picky',
    pl: 'wybredny',
    ar: 'منتق',
    ger: 'wählerisch',
    lt: 'išrankus',
    key: '44',
    norEgz: 'Hun er veldig kresen når det gjelder mat.',
    soundLink: '',
    wordId: 44
  },
  {
    nor: 'uredd',
    eng: 'fearless',
    pl: 'nieustraszony',
    ar: 'لا يعرف الخوف',
    ger: 'furchtlos',
    lt: 'nebijantis',
    key: '45',
    norEgz: 'Han er uredd i møte med utfordringer.',
    soundLink: '',
    wordId: 45
  },
  {
    nor: 'raus',
    eng: 'generous',
    pl: 'hojny',
    ar: 'سخي',
    ger: 'großzügig',
    lt: 'dosnus',
    key: '46',
    norEgz: 'Hun er en raus person.',
    soundLink: '',
    wordId: 46
  },
  {
    nor: 'å utforske',
    eng: 'to explore',
    pl: 'badać',
    ar: 'للاستكشاف',
    ger: 'erkunden',
    lt: 'tirti',
    key: '47',
    norEgz: 'Vi ønsker å utforske den nye byen.',
    soundLink: '',
    wordId: 47
  },
  {
    nor: 'å beundre',
    eng: 'to admire',
    pl: 'podziwiać',
    ar: 'يعجب',
    ger: 'bewundern',
    lt: 'grožėtis',
    key: '48',
    norEgz: 'Hun beundret maleriet på veggen.',
    soundLink: '',
    wordId: 48
  },
  {
    nor: 'å gjenkjenne',
    eng: 'to recognize',
    pl: 'rozpoznać',
    ar: 'الاعتراف',
    ger: 'erkennen',
    lt: 'atpažinti',
    key: '49',
    norEgz: 'Han kunne ikke gjenkjenne henne etter så mange år.',
    soundLink: '',
    wordId: 49
  },
  {
    nor: 'en beleiring',
    eng: 'a siege',
    pl: 'oblężenie',
    ar: 'حصار',
    ger: 'eine Belagerung',
    lt: 'apšauda',
    key: '50',
    norEgz: 'Byen var under en lang beleiring.',
    soundLink: '',
    wordId: 50
  },
  {
    nor: 'en borgerkrig',
    eng: 'a civil war',
    pl: 'wojna domowa',
    ar: 'حرب أهلية',
    ger: 'ein Bürgerkrieg',
    lt: 'pilietinis karas',
    key: '51',
    norEgz: 'Landet har vært gjennom en borgerkrig.',
    soundLink: '',
    wordId: 51
  },
  {
    nor: 'en brøkdeler',
    eng: 'a fraction',
    pl: 'ułamek',
    ar: 'كسر',
    ger: 'ein Bruchteil',
    lt: 'dalis',
    key: '52',
    norEgz: 'En brøkdeler av tiden ble brukt på dette prosjektet.',
    soundLink: '',
    wordId: 52
  },
  {
    nor: 'en avhending',
    eng: 'a disposal',
    pl: 'utrata',
    ar: 'تصرف',
    ger: 'eine Verfügung',
    lt: 'atidavimas',
    key: '53',
    norEgz: 'Avhending av eiendommen skjedde raskt.',
    soundLink: '',
    wordId: 53
  },
  {
    nor: 'eventyrlig',
    eng: 'adventurous',
    pl: 'przygodowy',
    ar: 'مغامر',
    ger: 'abenteuerlustig',
    lt: 'nuotykių',
    key: '54',
    norEgz: 'Han er en eventyrlig person.',
    soundLink: '',
    wordId: 54
  },
  {
    nor: 'nysgjerrig',
    eng: 'curious',
    pl: 'ciekawy',
    ar: 'فضولي',
    ger: 'neugierig',
    lt: 'smalsus',
    key: '55',
    norEgz: 'Barnet var nysgjerrig på hva som var i boksen.',
    soundLink: '',
    wordId: 55
  },
  {
    nor: 'ordentlig',
    eng: 'proper',
    pl: 'porządny',
    ar: 'مناسب',
    ger: 'ordentlich',
    lt: 'tvarkingas',
    key: '56',
    norEgz: 'Han oppfører seg alltid ordentlig.',
    soundLink: '',
    wordId: 56
  },
  {
    nor: 'uordentlig',
    eng: 'messy',
    pl: 'niechlujny',
    ar: 'فوضوي',
    ger: 'unordentlich',
    lt: 'netvarkingas',
    key: '57',
    norEgz: 'Rommet hennes er alltid uordentlig.',
    soundLink: '',
    wordId: 57
  },
  {
    nor: 'uvitende',
    eng: 'ignorant',
    pl: 'nieświadomy',
    ar: 'جاهل',
    ger: 'unwissend',
    lt: 'nežinojęs',
    key: '58',
    norEgz: 'Han var uvitende om konsekvensene av sine handlinger.',
    soundLink: '',
    wordId: 58
  },
  {
    nor: 'å gjenvinne',
    eng: 'to recover',
    pl: 'odzyskać',
    ar: 'استعادة',
    ger: 'wiederherstellen',
    lt: 'atgauti',
    key: '59',
    norEgz: 'Hun prøver å gjenvinne kontrollen over situasjonen.',
    soundLink: '',
    wordId: 59
  },
  {
    nor: 'å implementere',
    eng: 'to implement',
    pl: 'wdrażać',
    ar: 'تنفيذ',
    ger: 'implementieren',
    lt: 'įgyvendinti',
    key: '60',
    norEgz: 'Vi må implementere nye strategier for å forbedre salget.',
    soundLink: '',
    wordId: 60
  },
  {
    nor: 'å kritisere',
    eng: 'to criticize',
    pl: 'krytykować',
    ar: 'ينتقد',
    ger: 'kritisieren',
    lt: 'kritikuoti',
    key: '61',
    norEgz: 'Han liker å kritisere andres arbeid.',
    soundLink: '',
    wordId: 61
  },
  {
    nor: 'en avvikling',
    eng: 'a liquidation',
    pl: 'likwidacja',
    ar: 'تصفية',
    ger: 'eine Liquidation',
    lt: 'likvidacija',
    key: '62',
    norEgz: 'Firmaet gikk gjennom en avvikling.',
    soundLink: '',
    wordId: 62
  },
  {
    nor: 'en betegnelse',
    eng: 'a designation',
    pl: 'określenie',
    ar: 'تعيين',
    ger: 'eine Bezeichnung',
    lt: 'pavadinimas',
    key: '63',
    norEgz: 'Dette er en vanlig betegnelse for fenomenet.',
    soundLink: '',
    wordId: 63,
  },
  {
    nor: 'en byråkrati',
    eng: 'a bureaucracy',
    pl: 'biurokracja',
    ar: 'بيروقراطية',
    ger: 'eine Bürokratie',
    lt: 'biurokratija',
    key: '64',
    norEgz: 'Byråkratiet i regjeringen er vanskelig å navigere.',
    soundLink: '',
    wordId: 64
  },
  {
    nor: 'en avveining',
    eng: 'a trade-off',
    pl: 'kompromis',
    ar: 'توازن',
    ger: 'ein Kompromiss',
    lt: 'kompromisas',
    key: '65',
    norEgz: 'Det er alltid en avveining mellom kvalitet og pris.',
    soundLink: '',
    wordId: 65
  },
  {
    nor: 'en avgift',
    eng: 'a fee',
    pl: 'opłata',
    ar: 'رسم',
    ger: 'eine Gebühr',
    lt: 'mokestis',
    key: '66',
    norEgz: 'Banken tar en avgift for å bruke minibanken.',
    soundLink: '',
    wordId: 66
  },
  {
    nor: 'en avløp',
    eng: 'a drain',
    pl: 'odpływ',
    ar: 'مصرف',
    ger: 'ein Abfluss',
    lt: 'nutekėjimas',
    key: '67',
    norEgz: 'Vannet forsvinner ned i avløpet.',
    soundLink: '',
    wordId: 67
  },
  {
    nor: 'strålende',
    eng: 'brilliant',
    pl: 'wspaniały',
    ar: 'رائع',
    ger: 'brillant',
    lt: 'nuostabus',
    key: '68',
    norEgz: 'Hun gjorde en strålende jobb med presentasjonen.',
    soundLink: '',
    wordId: 68
  },
  {
    nor: 'beroligende',
    eng: 'soothing',
    pl: 'kojący',
    ar: 'مهدئ',
    ger: 'beruhigend',
    lt: 'raminantis',
    key: '69',
    norEgz: 'Musikken har en beroligende effekt på henne.',
    soundLink: '',
    wordId: 69
  },
  {
    nor: 'grusom',
    eng: 'cruel',
    pl: 'okrutny',
    ar: 'قاس',
    ger: 'grausam',
    lt: 'žiaurus',
    key: '70',
    norEgz: 'Han ble dømt for sin grusomme behandling av dyrene.',
    soundLink: '',
    wordId: 70
  },
  {
    nor: 'en direktør',
    eng: 'a director',
    pl: 'dyrektor',
    ar: 'مدير',
    ger: 'ein Direktor',
    lt: 'direktorius',
    key: '71',
    norEgz: 'Direktøren ønsket å møte alle ansatte personlig.',
    soundLink: '',
    wordId: 71
  },
  {
    nor: 'en dovenhet',
    eng: 'a laziness',
    pl: 'lenistwo',
    ar: 'كسل',
    ger: 'eine Faulheit',
    lt: 'tinginystė',
    key: '72',
    norEgz: 'Dovenhet kan føre til mange problemer i livet.',
    soundLink: '',
    wordId: 72
  },
  {
    nor: 'en drage',
    eng: 'a kite',
    pl: 'latawiec',
    ar: 'طائرة ورقية',
    ger: 'ein Drachen',
    lt: 'aštuonkojis',
    key: '73',
    norEgz: 'Barna liker å fly drager om sommeren.',
    soundLink: '',
    wordId: 73
  },
  {
    nor: 'en drakt',
    eng: 'a suit',
    pl: 'garnitur',
    ar: 'بدلة',
    ger: 'ein Anzug',
    lt: 'švarkas',
    key: '74',
    norEgz: 'Han kjøpte en ny drakt for jobbintervjuet.',
    soundLink: '',
    wordId: 74
  },
  {
    nor: 'en dristighet',
    eng: 'a boldness',
    pl: 'śmiałość',
    ar: 'جرأة',
    ger: 'eine Kühnheit',
    lt: 'drąsos',
    key: '75',
    norEgz: 'Hennes dristighet imponerte alle.',
    soundLink: '',
    wordId: 75
  },
  {
    nor: 'bløt',
    eng: 'soft',
    pl: 'miękki',
    ar: 'ناعم',
    ger: 'weich',
    lt: 'minkštas',
    key: '76',
    norEgz: 'Putene var bløte og komfortable.',
    soundLink: '',
    wordId: 76
  },
  {
    nor: 'sprø',
    eng: 'crispy',
    pl: 'chrupiący',
    ar: 'مقرمش',
    ger: 'knusprig',
    lt: 'trapus',
    key: '77',
    norEgz: 'Potetgullene er sprø og smakfulle.',
    soundLink: '',
    wordId: 77
  },
  {
    nor: 'smuldrete',
    eng: 'crumbly',
    pl: 'kruchy',
    ar: 'هش',
    ger: 'bröselig',
    lt: 'trapus',
    key: '78',
    norEgz: 'Kaken var smuldrete og deilig.',
    soundLink: '',
    wordId: 78
  },
  {
    nor: 'en duell',
    eng: 'a duel',
    pl: 'pojedynek',
    ar: 'ثنائي',
    ger: 'ein Duell',
    lt: 'dvikova',
    key: '79',
    norEgz: 'De to rivalene forberedte seg på en duell.',
    soundLink: '',
    wordId: 79
  },
  {
    nor: 'en dyd',
    eng: 'a virtue',
    pl: 'cnota',
    ar: 'فضيلة',
    ger: 'eine Tugend',
    lt: 'dorybė',
    key: '80',
    norEgz: 'Tålmodighet er en dyd.',
    soundLink: '',
    wordId: 80
  },
  {
    nor: 'en dykker',
    eng: 'a diver',
    pl: 'nurek',
    ar: 'غواص',
    ger: 'ein Taucher',
    lt: 'nardymo',
    key: '81',
    norEgz: 'Dykkeren svømte dypt under vannet.',
    soundLink: '',
    wordId: 81
  },
  {
    nor: 'en dørstokk',
    eng: 'a doorstep',
    pl: 'próg',
    ar: 'عتبة',
    ger: 'eine Türschwelle',
    lt: 'slenkstis',
    key: '82',
    norEgz: 'Han satte seg på dørstokken og ventet.',
    soundLink: '',
    wordId: 82
  },
  {
    nor: 'en døvstum',
    eng: 'a deaf-mute',
    pl: 'głuchoniemy',
    ar: 'صم غير ناطق',
    ger: 'ein Taubstummer',
    lt: 'kurčias ir nebylus',
    key: '83',
    norEgz: 'Døvstum person bruker tegnspråk for å kommunisere.',
    soundLink: '',
    wordId: 83
  },
  {
    nor: 'feig',
    eng: 'cowardly',
    pl: 'tchórzliwy',
    ar: 'جبان',
    ger: 'feige',
    lt: 'bailus',
    key: '84',
    norEgz: 'Han ble beskyldt for å være feig under konflikten.',
    soundLink: '',
    wordId: 84
  },
  {
    nor: 'skuffet',
    eng: 'disappointed',
    pl: 'rozczarowany',
    ar: 'خائب الأمل',
    ger: 'enttäuscht',
    lt: 'nusivylęs',
    key: '85',
    norEgz: 'Hun var skuffet over resultatene.',
    soundLink: '',
    wordId: 85
  },
  {
    nor: 'en bark',
    eng: 'a bark',
    pl: 'kora',
    ar: 'قشرة',
    ger: 'eine Rinde',
    lt: 'žievė',
    key: '86',
    norEgz: 'Barken beskytter treet mot skadedyr og sykdommer.',
    soundLink: '',
    wordId: 86
  },
  {
    nor: 'en badekåpe',
    eng: 'a bathrobe',
    pl: 'szlafrok',
    ar: 'روب الاستحمام',
    ger: 'ein Bademantel',
    lt: 'vonios kombinezonas',
    key: '87',
    norEgz: 'Hun pakket seg inn i en badekåpe etter dusjen.',
    soundLink: '',
    wordId: 87
  },
  {
    nor: 'en bevissthet',
    eng: 'consciousness',
    pl: 'świadomość',
    ar: 'الوعي',
    ger: 'Bewusstsein',
    lt: 'sąmoningumas',
    key: '88',
    norEgz: 'Bevissthet er en viktig del av menneskelig erfaring.',
    soundLink: '',
    wordId: 88
  },
  {
    nor: 'en blodpropp',
    eng: 'blood clot',
    pl: 'zakrzep krwi',
    ar: 'جلطة دموية',
    ger: 'Blutgerinnsel',
    lt: 'kraujo krešulys',
    key: '89',
    norEgz: 'Han hadde en blodpropp i benet.',
    soundLink: '',
    wordId: 89
  },
  {
    nor: 'en byrde',
    eng: 'burden',
    pl: 'ciężar',
    ar: 'عبء',
    ger: 'Last',
    lt: 'našta',
    key: '90',
    norEgz: 'Å ta vare på syke familiemedlemmer kan være en tung byrde.',
    soundLink: '',
    wordId: 90
  },
  {
    nor: 'en bukt',
    eng: 'bay',
    pl: 'zatoka',
    ar: 'خليج',
    ger: 'Bucht',
    lt: 'įlanka',
    key: '91',
    norEgz: 'Vi seilte inn i en vakker bukt.',
    soundLink: '',
    wordId: 91
  },
  {
    nor: 'å modifisere',
    eng: 'to modify',
    pl: 'modyfikować',
    ar: 'تعديل',
    ger: 'modifizieren',
    lt: 'modifikuoti',
    key: '92',
    norEgz: 'Han modifiserte bilens motor for bedre ytelse.',
    soundLink: '',
    wordId: 92
  },
  {
    nor: 'å overbevise',
    eng: 'to convince',
    pl: 'przekonać',
    ar: 'إقناع',
    ger: 'überzeugen',
    lt: 'įtikinti',
    key: '93',
    norEgz: 'Det var vanskelig å overbevise henne om å endre mening.',
    soundLink: '',
    wordId: 93
  },
  {
    nor: 'å tilegne seg',
    eng: 'to acquire',
    pl: 'nabywać',
    ar: 'اكتساب',
    ger: 'erwerben',
    lt: 'įgyti',
    key: '94',
    norEgz: 'Han tilegnet seg nye ferdigheter raskt.',
    soundLink: '',
    wordId: 94
  },
  {
    nor: 'en aksept',
    eng: 'acceptance',
    pl: 'akceptacja',
    ar: 'قبول',
    ger: 'Akzeptanz',
    lt: 'priėmimas',
    key: '95',
    norEgz: 'Hun søkte om aksept.',
    soundLink: '',
    wordId: 95
  },
  {
    nor: 'en eskalering',
    eng: 'escalation',
    pl: 'eskalacja',
    ar: 'تصعيد',
    ger: 'Eskalation',
    lt: 'eskalacija',
    key: '96',
    norEgz: 'Konflikten førte til en eskalering av vold.',
    soundLink: '',
    wordId: 96
  },
  {
    nor: 'en arrangør',
    eng: 'organizer',
    pl: 'organizator',
    ar: 'منظم',
    ger: 'Organisator',
    lt: 'organizatorius',
    key: '97',
    norEgz: 'Han var arrangøren av konferansen.',
    soundLink: '',
    wordId: 97
  },
  {
    nor: 'en effektivitet',
    eng: 'efficiency',
    pl: 'wydajność',
    ar: 'كفاءة',
    ger: 'Effizienz',
    lt: 'efektyvumas',
    key: '98',
    norEgz: 'Bedriften prøver å øke sin effektivitet.',
    soundLink: '',
    wordId: 98
  },
  {
    nor: 'en fiendtlighet',
    eng: 'hostility',
    pl: 'wrogość',
    ar: 'عداء',
    ger: 'Feindseligkeit',
    lt: 'priešiškumas',
    key: '99',
    norEgz: 'Hans fiendtlighet var tydelig.',
    soundLink: '',
    wordId: 99
  },
  {
    nor: 'en flukt',
    eng: 'escape',
    pl: 'ucieczka',
    ar: 'هروب',
    ger: 'Flucht',
    lt: 'pabėgimas',
    key: '100',
    norEgz: 'Fangen planla en flukt fra fengselet.',
    soundLink: '',
    wordId: 100
  },
  {
    nor: 'modig',
    eng: 'brave',
    pl: 'odważny',
    ar: 'شجاع',
    ger: 'mutig',
    lt: 'drąsus',
    key: '101',
    norEgz: 'Han var modig nok til å stå opp for sine overbevisninger.',
    soundLink: '',
    wordId: 101
  },
  {
    nor: 'mystisk',
    eng: 'mysterious',
    pl: 'tajemniczy',
    ar: 'غامض',
    ger: 'mysteriös',
    lt: 'paslaptingas',
    key: '102',
    norEgz: 'Det var en mystisk lyd utenfor vinduet.',
    soundLink: '',
    wordId: 102
  },
  {
    nor: 'sjarmerende',
    eng: 'charming',
    pl: 'urokliwy',
    ar: 'ساحر',
    ger: 'charmant',
    lt: 'žavus',
    key: '103',
    norEgz: 'Hun hadde en sjarmerende personlighet.',
    soundLink: '',
    wordId: 103
  },
  {
    nor: 'overrasket',
    eng: 'surprised',
    pl: 'zaskoczony',
    ar: 'متفاجئ',
    ger: 'überrascht',
    lt: 'nustebęs',
    key: '104',
    norEgz: 'Han var overrasket over å se henne her.',
    soundLink: '',
    wordId: 104
  },
  {
    nor: 'firkantet',
    eng: 'square',
    pl: 'kwadratowy',
    ar: 'مربع',
    ger: 'quadratisch',
    lt: 'kvadratinis',
    key: '105',
    norEgz: 'Bordet var firkantet i form.',
    soundLink: '',
    wordId: 105
  },
  {
    nor: 'å sammenfatte',
    eng: 'to summarize',
    pl: 'podsumować',
    ar: 'لخص',
    ger: 'zusammenfassen',
    lt: 'apibendrinti',
    key: '106',
    norEgz: 'Hun prøvde å sammenfatte bokens hovedpunkter.',
    soundLink: '',
    wordId: 106
  },
  {
    nor: 'å grine',
    eng: 'to laugh',
    pl: 'śmiać się',
    ar: 'يضحك',
    ger: 'lachen',
    lt: 'juoktis',
    key: '107',
    norEgz: 'Barna griner og leker sammen.',
    soundLink: '',
    wordId: 107
  },
  {
    nor: 'en etterforskning',
    eng: 'investigation',
    pl: 'dochodzenie',
    ar: 'تحقيق',
    ger: 'Ermittlung',
    lt: 'tyrimas',
    key: '108',
    norEgz: 'Politiet har startet en etterforskning.',
    soundLink: '',
    wordId: 108
  },
  {
    nor: 'en ettergivelse',
    eng: 'concession',
    pl: 'ustępstwo',
    ar: 'تنازل',
    ger: 'Zugeständnis',
    lt: 'nuolaida',
    key: '109',
    norEgz: 'Han ga en ettergivelse i forhandlingene.',
    soundLink: '',
    wordId: 109
  },
  {
    nor: 'en ettertanke',
    eng: 'reflection',
    pl: 'refleksja',
    ar: 'تأمل',
    ger: 'Nachdenken',
    lt: 'apmąstymas',
    key: '110',
    norEgz: 'Han satt i stillhet og ettertanke.',
    soundLink: '',
    wordId: 110
  },
  {
    nor: 'en evakuering',
    eng: 'evacuation',
    pl: 'ewakuacja',
    ar: 'إخلاء',
    ger: 'Evakuierung',
    lt: 'evakuacija',
    key: '111',
    norEgz: 'Myndighetene beordret en evakuering på grunn av flommen.',
    soundLink: '',
    wordId: 111
  },
  {
    nor: 'klissete',
    eng: 'sticky',
    pl: 'lepki',
    ar: 'لزج',
    ger: 'klebrig',
    lt: 'lipnus',
    key: '112',
    norEgz: 'Dette sukkeret er veldig klissete.',
    soundLink: '',
    wordId: 112
  },
  {
  nor: 'glatt',
  eng: 'smooth',
  pl: 'gładki',
  ar: 'ناعم',
  ger: 'glatt',
  lt: 'švelnus',
  key: '113',
  norEgz: 'Overflaten er veldig glatt.',
  soundLink: '',
  wordId: 113
  },
  {
  nor: 'grov',
  eng: 'rough',
  pl: 'szorstki',
  ar: 'خشن',
  ger: 'rau',
  lt: 'šiurkštus',
  key: '114',
  norEgz: 'Denne veggen er grov å ta på.',
  soundLink: '',
  wordId: 114
  },
  {
  nor: 'krydret',
  eng: 'spicy',
  pl: 'ostry',
  ar: 'مبهر',
  ger: 'würzig',
  lt: 'aštrus',
  key: '115',
  norEgz: 'Denne maten er veldig krydret.',
  soundLink: '',
  wordId: 115
  },
  {
  nor: 'fruktig',
  eng: 'fruity',
  pl: 'owocowy',
  ar: 'فاكهي',
  ger: 'fruchtig',
  lt: 'vaisiškas',
  key: '116',
  norEgz: 'Denne drikken har en fruktig smak.',
  soundLink: '',
  wordId: 116
  },
  {
  nor: 'en evighet',
  eng: 'an eternity',
  pl: 'wieczność',
  ar: 'أبدية',
  ger: 'eine Ewigkeit',
  lt: 'amžinybė',
  key: '117',
  norEgz: 'Det føles som en evighet siden sist.',
  soundLink: '',
  wordId: 117
  },
  {
  nor: 'en enke',
  eng: 'a widow',
  pl: 'wdowa',
  ar: 'أرملة',
  ger: 'eine Witwe',
  lt: 'našlė',
  key: '118',
  norEgz: 'Hun er en enke etter at mannen hennes døde.',
  soundLink: '',
  wordId: 118
  },
  {
  nor: 'en eremitt',
  eng: 'a hermit',
  pl: 'pustelnik',
  ar: 'ناسك',
  ger: 'ein Einsiedler',
  lt: 'eremitas',
  key: '119',
  norEgz: 'Han lever som en eremitt i skogen.',
  soundLink: '',
  wordId: 119
  },
  {
  nor: 'en evaluering',
  eng: 'an evaluation',
  pl: 'ewaluacja',
  ar: 'تقييم',
  ger: 'eine Bewertung',
  lt: 'vertinimas',
  key: '120',
  norEgz: 'Vi trenger en evaluering av prosjektet.',
  soundLink: '',
  wordId: 120
  },
  {
  nor: 'en begivenhet',
  eng: 'an event',
  pl: 'wydarzenie',
  ar: 'حدث',
  ger: 'eine Veranstaltung',
  lt: 'įvykis',
  key: '121',
  norEgz: 'Dette er en viktig begivenhet for oss.',
  soundLink: '',
  wordId: 121
  },
  {
  nor: 'å adaptere',
  eng: 'to adapt',
  pl: 'dostosować',
  ar: 'يتأقلم',
  ger: 'anpassen',
  lt: 'pritaikyti',
  key: '122',
  norEgz: 'Vi må adaptere oss til endringer.',
  soundLink: '',
  wordId: 122
  },
  {
  nor: 'å integrere',
  eng: 'to integrate',
  pl: 'zintegrować',
  ar: 'يدمج',
  ger: 'integrieren',
  lt: 'integruoti',
  key: '123',
  norEgz: 'Vi ønsker å integrere alle i samfunnet.',
  soundLink: '',
  wordId: 123
  },
  {
  nor: 'en forvandling',
  eng: 'a transformation',
  pl: 'przemiana',
  ar: 'تحول',
  ger: 'eine Verwandlung',
  lt: 'transformacija',
  key: '124',
  norEgz: 'Forvandlingen fra sommer til høst er vakker.',
  soundLink: '',
  wordId: 124
  },
  {
  nor: 'en fornektelse',
  eng: 'a denial',
  pl: 'zaprzeczenie',
  ar: 'إنكار',
  ger: 'eine Ablehnung',
  lt: 'neigimas',
  key: '125',
  norEgz: 'Han er i fornektelse av sannheten.',
  soundLink: '',
  wordId: 125
  },
  {
  nor: 'en fundamentalist',
  eng: 'a fundamentalist',
  pl: 'fundamentalista',
  ar: 'أصولي',
  ger: 'ein Fundamentalist',
  lt: 'fundamentalistas',
  key: '126',
  norEgz: 'Fundamentalister kan være ekstreme i sine synspunkter.',
  soundLink: '',
  wordId: 126
  },
  {
  nor: 'en beist',
  eng: 'a beast',
  pl: 'bestia',
  ar: 'وحش',
  ger: 'ein Tier',
  lt: 'žvėris',
  key: '127',
  norEgz: 'En bjørn er et kraftig beist.',
  soundLink: '',
  wordId: 127
  },
  {
  nor: 'en belastning',
  eng: 'a burden',
  pl: 'obciążenie',
  ar: 'عبء',
  ger: 'eine Belastung',
  lt: 'našta',
  key: '128',
  norEgz: 'Å være i gjeld kan være en stor belastning.',
  soundLink: '',
  wordId: 128
  },
  {
  nor: 'glitrende',
  eng: 'sparkling',
  pl: 'błyszczący',
  ar: 'متلألئ',
  ger: 'funkelnd',
  lt: 'žėrintis',
  key: '129',
  norEgz: 'Smykkene hennes er glitrende og vakre.',
  soundLink: '',
  wordId: 129
  },
  {
  nor: 'matt',
  eng: 'matte',
  pl: 'matowy',
  ar: 'غير لامع',
  ger: 'matt',
  lt: 'matinis',
  key: '130',
  norEgz: 'Jeg foretrekker en matt finish på neglelakken min.',
  soundLink: '',
  wordId: 130
  },
  {
  nor: 'gjennomsiktig',
  eng: 'transparent',
  pl: 'przezroczysty',
  ar: 'شفاف',
  ger: 'transparent',
  lt: 'permatomas',
  key: '131',
  norEgz: 'Denne blusen er for gjennomsiktig for meg.',
  soundLink: '',
  wordId: 131
  },
  {
  nor: 'ugjennomsiktig',
  eng: 'opaque',
  pl: 'nieprzezroczysty',
  ar: 'غير شفاف',
  ger: 'undurchsichtig',
  lt: 'nepermatomas',
  key: '132',
  norEgz: 'Vinduene er ugjennomsiktige for å bevare personvernet.',
  soundLink: '',
  wordId: 132
  },
  {
  nor: 'fargerik',
  eng: 'colorful',
  pl: 'kolorowy',
  ar: 'ملون',
  ger: 'farbenfroh',
  lt: 'spalvingas',
  key: '133',
  norEgz: 'Hun hadde på seg en fargerik kjole.',
  soundLink: '',
  wordId: 133
  },
  {
  nor: 'fargeløs',
  eng: 'colorless',
  pl: 'bezbarwny',
  ar: 'عديم اللون',
  ger: 'farblos',
  lt: 'bespalvis',
  key: '134',
  norEgz: 'Diamanten var nesten helt fargeløs.',
  soundLink: '',
  wordId: 134
  },
  {
  nor: "å kategorisere",
  eng: "to categorize",
  pl: "kategoryzować",
  ar: "تصنيف",
  ger: "kategorisieren",
  lt: "kategorizuoti",
  key: "135",
  norEgz: "Vi må kategorisere dataene før analyse.",
  soundLink: "",
  wordId: 135
  },
  {
  nor: "å kompensere",
  eng: "to compensate",
  pl: "rekompensować",
  ar: "تعويض",
  ger: "kompensieren",
  lt: "kompensuoti",
  key: "136",
  norEgz: "Han prøvde å kompensere for tapet.",
  soundLink: "",
  wordId: 136
  },
  {
  nor: "en besettelse",
  eng: "an obsession",
  pl: "obsesja",
  ar: "هاجس",
  ger: "eine Besessenheit",
  lt: "obsesija",
  key: "137",
  norEgz: "Hans besettelse med biler er tydelig.",
  soundLink: "",
  wordId: 137
  },
  {
  nor: "en bærekraft",
  eng: "a sustainability",
  pl: "zrównoważony rozwój",
  ar: "استدامة",
  ger: "eine Nachhaltigkeit",
  lt: "tvarumas",
  key: "138",
  norEgz: "Bærekraft er viktig for miljøet.",
  soundLink: "",
  wordId: 138
  },
  {
  nor: "en bønne",
  eng: "a bean",
  pl: "fasola",
  ar: "فاصوليا",
  ger: "eine Bohne",
  lt: "pupelė",
  key: "139",
  norEgz: "Hun la en bønne i suppen.",
  soundLink: "",
  wordId: 139
  },
  {
  nor: "en cellekjerne",
  eng: "a cell nucleus",
  pl: "jądro komórkowe",
  ar: "نواة الخلية",
  ger: "ein Zellkern",
  lt: "ląstelės branduolys",
  key: "140",
  norEgz: "Cellekjernen inneholder arvestoffet.",
  soundLink: "",
  wordId: 140
  },
  {
  nor: "en dimensjon",
  eng: "a dimension",
  pl: "wymiar",
  ar: "بعد",
  ger: "eine Dimension",
  lt: "dimensija",
  key: "141",
  norEgz: "Vi må vurdere problemet i flere dimensjoner.",
  soundLink: "",
  wordId: 141
  },
  {
    nor: 'mønstret',
    eng: 'patterned',
    pl: 'wzorzysty',
    ar: 'منقط',
    ger: 'gemustert',
    lt: 'raštuotas',
    key: '142',
    norEgz: 'Hun hadde en mønstret kjole.',
    soundLink: '',
    wordId: 142
  },
  {
    nor: 'stripete',
    eng: 'striped',
    pl: 'w paski',
    ar: 'مخطط',
    ger: 'gestreift',
    lt: 'juostuotas',
    key: '143',
    norEgz: 'Han hadde på seg en stripete skjorte.',
    soundLink: '',
    wordId: 143
  },
  {
    nor: 'prikkete',
    eng: 'spotted',
    pl: 'w kropki',
    ar: 'منقط',
    ger: 'gepunktet',
    lt: 'taškuotas',
    key: '144',
    norEgz: 'Kjolen hennes var prikkete.',
    soundLink: '',
    wordId: 144
  },
  {
    nor: 'blomstret',
    eng: 'floral',
    pl: 'kwiecisty',
    ar: 'زهري',
    ger: 'geblümt',
    lt: 'gėlinis',
    key: '145',
    norEgz: 'Hun hadde en blomstret kjole på seg.',
    soundLink: '',
    wordId: 145
  },
  {
    nor: 'bølgete',
    eng: 'wavy',
    pl: 'falisty',
    ar: 'متموج',
    ger: 'gewellt',
    lt: 'bangotas',
    key: '146',
    norEgz: 'Hun har langt, bølgete hår.',
    soundLink: '',
    wordId: 146
  },
  {
    nor: 'å evaluere',
    eng: 'to evaluate',
    pl: 'oceniać',
    ar: 'تقييم',
    ger: 'bewerten',
    lt: 'vertinti',
    key: '147',
    norEgz: 'Vi må evaluere prosjektets suksess.',
    soundLink: '',
    wordId: 147
  },
  {
    nor: 'å generalisere',
    eng: 'to generalize',
    pl: 'generalizować',
    ar: 'تعميم',
    ger: 'verallgemeinern',
    lt: 'generalizuoti',
    key: '148',
    norEgz: 'Det er viktig å ikke generalisere.',
    soundLink: '',
    wordId: 148
  }


        
        
]