[
  {
    nor: 'en mangfoldighet',
    eng: 'a diversity',
    pl: 'różnorodność',
    ar: 'تنوع',
    ger: 'eine Vielfalt',
    lt: 'įvairovė',
    key: '0',
    norEgz: 'Vi må fremme en mangfoldighet av ideer.',
    soundLink: '',
    wordId: 0
  },
  {
    nor: 'en attføring',
    eng: 'a defecation',
    pl: 'defekacja',
    ar: 'تبرز',
    ger: 'eine Stuhlentleerung',
    lt: 'tuštinimasis',
    key: '1',
    norEgz: 'Attføring er en naturlig kroppsfunksjon.',
    soundLink: '',
    wordId: 1
  },
  {
    nor: 'å undergrave',
    eng: 'to undermine',
    pl: 'podważać',
    ar: 'تقويض',
    ger: 'untergraben',
    lt: 'kelti abejones',
    key: '2',
    norEgz: 'Hun prøvde å undergrave hans autoritet.',
    soundLink: '',
    wordId: 2
  },
  {
    nor: 'en bivirkning',
    eng: 'a side effect',
    pl: 'efekt uboczny',
    ar: 'تأثير جانبي',
    ger: 'eine Nebenwirkung',
    lt: 'šalutinis poveikis',
    key: '3',
    norEgz: 'Søvnløshet er en bivirkning av dette legemidlet.',
    soundLink: '',
    wordId: 3
  },
  {
    nor: 'en selvfølelse',
    eng: 'a self-esteem',
    pl: 'poczucie własnej wartości',
    ar: 'تقدير الذات',
    ger: 'ein Selbstwertgefühl',
    lt: 'savigarbos jausmas',
    key: '4',
    norEgz: 'Selvfølelse er viktig for mental helse.',
    soundLink: '',
    wordId: 4
  },
  {
    nor: 'ekstravagant',
    eng: 'extravagant',
    pl: 'ekstrawagancki',
    ar: 'مسرف',
    ger: 'extravagant',
    lt: 'švaistus',
    key: '5',
    norEgz: 'Hun er kjent for sin ekstravagante livsstil.',
    soundLink: '',
    wordId: 5
  },
  {
    nor: "eksponentiell",
    eng: "exponential",
    pl: "ekspotencjalny",
    ar: "أسي",
    ger: "exponentiell",
    lt: "eksponentinis",
    key: "6",
    norEgz: "Veksten i selskapet har vært eksponentiell.",
    soundLink: "",
    wordId: 6
  },
  {
    nor: "forsonende",
    eng: "conciliatory",
    pl: "pojednawczy",
    ar: "مصالح",
    ger: "versöhnlich",
    lt: "sutaikinantis",
    key: "7",
    norEgz: "Han hadde en forsonende tone i samtalen.",
    soundLink: "",
    wordId: 7
  },
  {
    nor: "fragmentert",
    eng: "fragmented",
    pl: "rozdrobniony",
    ar: "مجزأ",
    ger: "fragmentiert",
    lt: "suskaidytas",
    key: "8",
    norEgz: "Informasjonen var fragmentert og vanskelig å forstå.",
    soundLink: "",
    wordId: 8
  },
  {
    nor: "å approbere",
    eng: "to approve",
    pl: "zatwierdzać",
    ar: "يوافق",
    ger: "zustimmen",
    lt: "patvirtinti",
    key: "9",
    norEgz: "Sjefen må approbere endringene før de implementeres.",
    soundLink: "",
    wordId: 9
  },
  {
    nor: "å arbitrere",
    eng: "to arbitrate",
    pl: "arbitrażować",
    ar: "يحكم",
    ger: "schlichten",
    lt: "arbitruoti",
    key: "10",
    norEgz: "Dommeren ble bedt om å arbitrere tvisten.",
    soundLink: "",
    wordId: 10
  },
  {
    nor: "å dekonstruere",
    eng: "to deconstruct",
    pl: "dekonstruować",
    ar: "تفكيك",
    ger: "dekonstruieren",
    lt: "dekonstruoti",
    key: "11",
    norEgz: "Hun prøvde å dekonstruere argumentet for å finne svakheter.",
    soundLink: "",
    wordId: 11
  },
  {
    nor: "en kjernefysikk",
    eng: "nuclear physics",
    pl: "fizyka jądrowa",
    ar: "فيزياء نووية",
    ger: "Kernphysik",
    lt: "branduolinė fizika",
    key: "12",
    norEgz: "Han studerer en kjernefysikk ved universitetet.",
    soundLink: "",
    wordId: 12
  },
  {
  nor: 'flekkvis',
  eng: 'patchy',
  pl: 'plamisty',
  ar: 'عرقي',
  ger: 'fleckig',
  lt: 'dėmėtas',
  key: '13',
  norEgz: 'Jakken hans er flekkvis farget.',
  soundLink: '',
  wordId: 13
  },
  {
  nor: 'nostalgisk',
  eng: 'nostalgic',
  pl: 'nostalgiczny',
  ar: 'حنين إلى الماضي',
  ger: 'nostalgisch',
  lt: 'nostalgiškas',
  key: '14',
  norEgz: 'Hun følte seg nostalgisk da hun besøkte hjembyen sin.',
  soundLink: '',
  wordId: 14
  },
  {
  nor: 'puritansk',
  eng: 'puritanical',
  pl: 'purytański',
  ar: 'متزمت',
  ger: 'puritanisch',
  lt: 'puritoniškas',
  key: '15',
  norEgz: 'Hans puritanske holdning tillot ingen feil.',
  soundLink: '',
  wordId: 15
  },
  {
  nor: 'reflektert',
  eng: 'reflective',
  pl: 'refleksyjny',
  ar: 'تأملي',
  ger: 'nachdenklich',
  lt: 'atsispindintis',
  key: '16',
  norEgz: 'Hun er en reflektert person.',
  soundLink: '',
  wordId: 16
  },
  {
  nor: 'retorisk',
  eng: 'rhetorical',
  pl: 'retoryczny',
  ar: 'بلاغي',
  ger: 'rhetorisch',
  lt: 'retorinis',
  key: '17',
  norEgz: 'Han stilte et retorisk spørsmål.',
  soundLink: '',
  wordId: 17
  },
  {
  nor: 'å differensiere',
  eng: 'to differentiate',
  pl: 'różnicować',
  ar: 'للتفريق',
  ger: 'differenzieren',
  lt: 'diferencijuoti',
  key: '18',
  norEgz: 'Vi må differensiere mellom de to begrepene.',
  soundLink: '',
  wordId: 18
  },
  {
  nor: 'å ekstrapolere',
  eng: 'to extrapolate',
  pl: 'ekstrapolować',
  ar: 'استقراء',
  ger: 'extrapolieren',
  lt: 'ekstrapoliuoti',
  key: '19',
  norEgz: 'Vi må ekstrapolere dataene for å lage en prognose.',
  soundLink: '',
  wordId: 19
  },
  {
  nor: 'å harmonisere',
  eng: 'to harmonize',
  pl: 'harmonizować',
  ar: 'توافق',
  ger: 'harmonisieren',
  lt: 'suderinti',
  key: '20',
  norEgz: 'De prøvde å harmonisere arbeidsrutinene.',
  soundLink: '',
  wordId: 20
  },
  {
  nor: 'et paradigme',
  eng: 'a paradigm',
  pl: 'paradygmat',
  ar: 'نموذج',
  ger: 'ein Paradigma',
  lt: 'paradigma',
  key: '21',
  norEgz: 'Dette konseptet er et paradigme for moderne forskning.',
  soundLink: '',
  wordId: 21
  },
  {
  nor: 'en syntese',
  eng: 'a synthesis',
  pl: 'synteza',
  ar: 'توليف',
  ger: 'eine Synthese',
  lt: 'sintezė',
  key: '22',
  norEgz: 'Vi må lage en syntese av disse ideene.',
  soundLink: '',
  wordId: 22
  },
  {
  nor: 'en dialektikk',
  eng: 'a dialectic',
  pl: 'dialektyka',
  ar: 'جدلية',
  ger: 'eine Dialektik',
  lt: 'dialektika',
  key: '23',
  norEgz: 'Dialektikken mellom motsetninger fører til utvikling.',
  soundLink: '',
  wordId: 23
  },
  {
  nor: 'paternalistisk',
  eng: 'paternalistic',
  pl: 'paternalistyczny',
  ar: 'أبوي',
  ger: 'paternalistisch',
  lt: 'paternalistinis',
  key: '24',
  norEgz: 'Hans paternalistiske holdning kan virke irriterende.',
  soundLink: '',
  wordId: 24
  },
  {
  nor: 'pluralistisk',
  eng: 'pluralistic',
  pl: 'pluralistyczny',
  ar: 'تعددي',
  ger: 'pluralistisch',
  lt: 'pluralistinis',
  key: '25',
  norEgz: 'Samfunnet vårt blir stadig mer pluralistisk.',
  soundLink: '',
  wordId: 25
  },
  {
  nor: 'pompøs',
  eng: 'pompous',
  pl: 'pompatyczny',
  ar: 'متكبر',
  ger: 'pompös',
  lt: 'pompiškas',
  key: '26',
  norEgz: 'Talen hans var pompøs og overdreven.',
  soundLink: '',
  wordId: 26
  },
  {
  nor: 'prosaisk',
  eng: 'prosaic',
  pl: 'prozaiczny',
  ar: 'عادي',
  ger: 'prosaisch',
  lt: 'proziškas',
  key: '27',
  norEgz: 'Beskrivelsen hennes var prosaisk og kjedelig.',
  soundLink: '',
  wordId: 27
  },
  {
  nor: 'metaforisk',
  eng: 'metaphorical',
  pl: 'metaforyczny',
  ar: 'مجازي',
  ger: 'metaphorisch',
  lt: 'metaforiškas',
  key: '28',
  norEgz: 'Hun brukte en metaforisk sammenligning for å forklare situasjonen.',
  soundLink: '',
  wordId: 28
  },
  {
  nor: 'å inkorporere',
  eng: 'to incorporate',
  pl: 'inkorporować',
  ar: 'لدمج',
  ger: 'inkorporieren',
  lt: 'inkorporuoti',
  key: '29',
  norEgz: 'Vi må inkorporere disse endringene i planene våre.',
  soundLink: '',
  wordId: 29
  },
  {
  nor: 'å karakterisere',
  eng: 'to characterize',
  pl: 'charakteryzować',
  ar: 'وصف',
  ger: 'charakterisieren',
  lt: 'charakterizuoti',
  key: '30',
  norEgz: 'Hun forsøkte å karakterisere situasjonen.',
  soundLink: '',
  wordId: 30
  },
  {
  nor: 'en selvtillit',
  eng: 'a self-confidence',
  pl: 'pewność siebie',
  ar: 'ثقة بالنفس',
  ger: 'ein Selbstvertrauen',
  lt: 'savigarba',
  key: '31',
  norEgz: 'Han har en høy selvtillit.',
  soundLink: '',
  wordId: 31
  },
  {
  nor: 'en demografi',
  eng: 'a demography',
  pl: 'demografia',
  ar: 'الديموغرافيا',
  ger: 'eine Demografie',
  lt: 'demografija',
  key: '32',
  norEgz: 'Studiet av demografi er viktig for samfunnsplanlegging.',
  soundLink: '',
  wordId: 32
  },
  {
  nor: 'en forfengelighet',
  eng: 'a vanity',
  pl: 'próżność',
  ar: 'غرور',
  ger: 'eine Eitelkeit',
  lt: 'tuštumas',
  key: '33',
  norEgz: 'Forfengelighet kan være en ulempe.',
  soundLink: '',
  wordId: 33
  },
  {
  nor: 'utilgjengelig',
  eng: 'unavailable',
  pl: 'niedostępny',
  ar: 'غير متاح',
  ger: 'nicht verfügbar',
  lt: 'neprieinamas',
  key: '34',
  norEgz: 'Ressursene er utilgjengelige på grunn av konflikten.',
  soundLink: '',
  wordId: 34
  },
  {
  nor: 'xenofobisk',
  eng: 'xenophobic',
  pl: 'ksenofobiczny',
  ar: 'كراهية الأجانب',
  ger: 'fremdenfeindlich',
  lt: 'ksenofobiškas',
  key: '35',
  norEgz: 'Xenofobiske holdninger er skadelige for samfunnet.',
  soundLink: '',
  wordId: 35
  },
  {
  nor: 'nihilistisk',
  eng: 'nihilistic',
  pl: 'nihilistyczny',
  ar: 'عدمي',
  ger: 'nihilistisch',
  lt: 'nihilistinis',
  key: '36',
  norEgz: 'Hans nihilistiske syn på livet gjorde ham ofte deprimert.',
  soundLink: '',
  wordId: 36
  },
  {
    nor: 'paradoksal',
    eng: 'paradoxical',
    pl: 'paradoksalny',
    ar: 'متناقض',
    ger: 'paradox',
    lt: 'paradoksalus',
    key: '37',
    norEgz: 'Denne situasjonen er paradoksal.',
    soundLink: '',
    wordId: 37
  },
  {
    nor: 'å objektivere',
    eng: 'to objectify',
    pl: 'uprzedmiotowić',
    ar: 'تجسيم',
    ger: 'objektivieren',
    lt: 'objektyvuoti',
    key: '38',
    norEgz: 'Han prøver å objektivere situasjonen.',
    soundLink: '',
    wordId: 38
  },
  {
    nor: 'å optimere',
    eng: 'to optimize',
    pl: 'optymalizować',
    ar: 'تحسين',
    ger: 'optimieren',
    lt: 'optimizuoti',
    key: '39',
    norEgz: 'Vi ønsker å optimere prosessen.',
    soundLink: '',
    wordId: 39
  },
  {
    nor: 'å postulere',
    eng: 'to postulate',
    pl: 'postulować',
    ar: 'استدعاء',
    ger: 'postulieren',
    lt: 'postuliuoti',
    key: '40',
    norEgz: 'Han postulerer at jorden er flat.',
    soundLink: '',
    wordId: 40
  },
  {
    nor: 'å redegjøre',
    eng: 'to explain',
    pl: 'wyjaśnić',
    ar: 'شرح',
    ger: 'erklären',
    lt: 'paaiškinti',
    key: '41',
    norEgz: 'Kan du redegjøre for dine handlinger?',
    soundLink: '',
    wordId: 41
  },
  {
    nor: 'en forræderi',
    eng: 'a betrayal',
    pl: 'zdrada',
    ar: 'خيانة',
    ger: 'ein Verrat',
    lt: 'išdavystė',
    key: '42',
    norEgz: 'Han begikk en forræderi mot sitt eget folk.',
    soundLink: '',
    wordId: 42
  },
  {
    nor: 'en fremmedgjøring',
    eng: 'alienation',
    pl: 'alienacja',
    ar: 'اغتراب',
    ger: 'Entfremdung',
    lt: 'atsvetimėjimas',
    key: '43',
    norEgz: 'Teknologi kan føre til fremmedgjøring.',
    soundLink: '',
    wordId: 43
  },
  {
    nor: 'en eksil',
    eng: 'an exile',
    pl: 'wygnanie',
    ar: 'منفى',
    ger: 'ein Exil',
    lt: 'tremtis',
    key: '44',
    norEgz: 'Forfatteren levde i eksil i mange år.',
    soundLink: '',
    wordId: 44
  },
  {
    nor: 'omnipotent',
    eng: 'omnipotent',
    pl: 'wszechmocny',
    ar: 'القادر على كل شيء',
    ger: 'allmächtig',
    lt: 'visagalis',
    key: '45',
    norEgz: 'Gud er ofte beskrevet som omnipotent.',
    soundLink: '',
    wordId: 45
  },
  {
    nor: 'patosfylt',
    eng: 'pathos-filled',
    pl: 'pełen patosu',
    ar: 'مليء بالعاطفة',
    ger: 'pathetisch',
    lt: 'pilnas patoso',
    key: '46',
    norEgz: 'Talen hans var patosfylt og rørende.',
    soundLink: '',
    wordId: 46
  },
  {
    nor: 'sublim',
    eng: 'sublime',
    pl: 'wzniosły',
    ar: 'سام',
    ger: 'erhaben',
    lt: 'sublimiškas',
    key: '47',
    norEgz: 'Landskapet her er virkelig sublim.',
    soundLink: '',
    wordId: 47
  },
  {
    nor: 'surrealistisk',
    eng: 'surrealistic',
    pl: 'surrealistyczny',
    ar: 'سريالي',
    ger: 'surrealistisch',
    lt: 'surrealistinis',
    key: '48',
    norEgz: 'Denne filmen har en surrealistisk atmosfære.',
    soundLink: '',
    wordId: 48
  },
  {
    nor: 'transcendental',
    eng: 'transcendental',
    pl: 'transcendentalny',
    ar: 'متعال',
    ger: 'transzendental',
    lt: 'transcendentinis',
    key: '49',
    norEgz: 'Meditasjon kan føre til en transcendental opplevelse.',
    soundLink: '',
    wordId: 49
  },
  {
    nor: 'en bevoktning',
    eng: 'a guarding',
    pl: 'straż',
    ar: 'حراسة',
    ger: 'eine Bewachung',
    lt: 'sargyba',
    key: '50',
    norEgz: 'Banken har døgnet rundt bevoktning.',
    soundLink: '',
    wordId: 50
  },
  {
    nor: 'å resonere',
    eng: 'to resonate',
    pl: 'rezonować',
    ar: 'يتردد',
    ger: 'resonieren',
    lt: 'rezonuoti',
    key: '51',
    norEgz: 'Hans ord resonerte med publikum.',
    soundLink: '',
    wordId: 51
  },
  {
    nor: 'å restrukturere',
    eng: 'to restructure',
    pl: 'restrukturyzować',
    ar: 'إعادة هيكلة',
    ger: 'umstrukturieren',
    lt: 'restruktūrizuoti',
    key: '52',
    norEgz: 'Selskapet må restrukturere for å overleve.',
    soundLink: '',
    wordId: 52
  },
  {
    nor: 'en erklæring',
    eng: 'a declaration',
    pl: 'oświadczenie',
    ar: 'إعلان',
    ger: 'eine Erklärung',
    lt: 'deklaracija',
    key: '53',
    norEgz: 'Han ga en offisiell erklæring om situasjonen.',
    soundLink: '',
    wordId: 53
  },
  {
    nor: 'en erkjennelse',
    eng: 'an acknowledgment',
    pl: 'uznanie',
    ar: 'اعتراف',
    ger: 'eine Anerkennung',
    lt: 'pripažinimas',
    key: '54',
    norEgz: 'Han kom fram til en viktig erkjennelse.',
    soundLink: '',
    wordId: 54
  },
  {
    nor: 'en erobring',
    eng: 'a conquest',
    pl: 'zdobycie',
    ar: 'غزو',
    ger: 'eine Eroberung',
    lt: 'užkariavimas',
    key: '55',
    norEgz: 'Romerriket hadde mange erobringer.',
    soundLink: '',
    wordId: 55
  },
  {
    nor: 'kvasivitenskapelig',
    eng: 'pseudoscientific',
    pl: 'pseudonaukowy',
    ar: 'زائف العلم',
    ger: 'pseudowissenschaftlich',
    lt: 'pseudo-mokslinis',
    key: '56',
    norEgz: 'Denne teorien er kvasivitenskapelig og upålitelig.',
    soundLink: '',
    wordId: 56
  },
  {
    nor: 'kverulerende',
    eng: 'querulous',
    pl: 'kłótliwy',
    ar: 'متشكي',
    ger: 'querulatorisch',
    lt: 'skundikas',
    key: '57',
    norEgz: 'Han har en kverulerende personlighet.',
    soundLink: '',
    wordId: 57
  },
  {
    nor: 'melankolsk',
    eng: 'melancholic',
    pl: 'melancholijny',
    ar: 'كئيب',
    ger: 'melancholisch',
    lt: 'melancholiškas',
    key: '59',
    norEgz: 'Hun følte seg melankolsk etter å ha sett filmen.',
    soundLink: '',
    wordId: 59
  },
  {
    nor: 'nihilistisk',
    eng: 'nihilistic',
    pl: 'nihilistyczny',
    ar: 'عقيدة العدمية',
    ger: 'nihilistisch',
    lt: 'nihilistinis',
    key: '60',
    norEgz: 'Hans nihilistiske syn på verden var forstyrrende.',
    soundLink: '',
    wordId: 60
  },
  {
    nor: 'å systematisere',
    eng: 'to systematize',
    pl: 'systematyzować',
    ar: 'تنظيم',
    ger: 'systematisieren',
    lt: 'sistematizuoti',
    key: '61',
    norEgz: 'Han prøvde å systematisere arbeidsprosessen.',
    soundLink: '',
    wordId: 61
  },
  {
    nor: 'å teoretisere',
    eng: 'to theorize',
    pl: 'teoretyzować',
    ar: 'يفسر نظريًا',
    ger: 'theoretisieren',
    lt: 'teoretizuoti',
    key: '62',
    norEgz: 'Forskere teoretiserer om mørk materie.',
    soundLink: '',
    wordId: 62
  },
  {
    nor: 'en avsky',
    eng: 'a disgust',
    pl: 'wstręt',
    ar: 'اشمئزاز',
    ger: 'ein Ekel',
    lt: 'pasibjaurėjimas',
    key: '63',
    norEgz: 'Hun følte avsky for den grusomme handlingen.',
    soundLink: '',
    wordId: 63
  },
  {
    nor: 'en avbetaling',
    eng: 'an installment',
    pl: 'rata',
    ar: 'قسط',
    ger: 'eine Rate',
    lt: 'įmoka',
    key: '64',
    norEgz: 'Han betalte for bilen i månedlige avdrag.',
    soundLink: '',
    wordId: 64
  },
  {
    nor: 'inkarnert',
    eng: 'incarnate',
    pl: 'wcielony',
    ar: 'متجسد',
    ger: 'inkarniert',
    lt: 'įkūnijęs',
    key: '65',
    norEgz: 'Han var ondskapen inkarnert.',
    soundLink: '',
    wordId: 65
  },
  {
    nor: 'irrasjonell',
    eng: 'irrational',
    pl: 'niedorzeczny',
    ar: 'غير عقلاني',
    ger: 'irrational',
    lt: 'neracionalus',
    key: '66',
    norEgz: 'Hans oppførsel var fullstendig irrasjonell.',
    soundLink: '',
    wordId: 66
  },
  {
    nor: 'juxtaposert',
    eng: 'juxtaposed',
    pl: 'sąsiadujący',
    ar: 'متوازي',
    ger: 'nebeneinander gestellt',
    lt: 'greta',
    key: '67',
    norEgz: 'Bildene var nøye juxtaposert for å skape kontrast.',
    soundLink: '',
    wordId: 67
  },
  {
    nor: 'katarsisk',
    eng: 'cathartic',
    pl: 'katharsis',
    ar: 'كاثارسي',
    ger: 'kathartisch',
    lt: 'katarinis',
    key: '68',
    norEgz: 'Opplevelsen var katarsisk for henne.',
    soundLink: '',
    wordId: 68
  },
  {
    nor: 'kosmopolitisk',
    eng: 'cosmopolitan',
    pl: 'kosmopolityczny',
    ar: 'كوزموبوليتي',
    ger: 'kosmopolitisch',
    lt: 'kosmopolitiškas',
    key: '69',
    norEgz: 'Byen har en kosmopolitisk atmosfære.',
    soundLink: '',
    wordId: 69
  },
  {
    nor: 'å visualisere',
    eng: 'to visualize',
    pl: 'wizualizować',
    ar: 'تصور',
    ger: 'visualisieren',
    lt: 'vaizduoti',
    key: '70',
    norEgz: 'Hun prøvde å visualisere resultatet av prosjektet.',
    soundLink: '',
    wordId: 70
  },
  {
    nor: 'å konsolidere',
    eng: 'to consolidate',
    pl: 'konsolidować',
    ar: 'توحيد',
    ger: 'konsolidieren',
    lt: 'konsoliduoti',
    key: '71',
    norEgz: 'Selskapet ønsker å konsolidere sin posisjon i markedet.',
    soundLink: '',
    wordId: 71
  },
  {
    nor: 'å abstrahere',
    eng: 'to abstract',
    pl: 'abstrahować',
    ar: 'تجريد',
    ger: 'abstrahieren',
    lt: 'abstrahuoti',
    key: '72',
    norEgz: 'Kunstneren forsøkte å abstrahere formene i maleriet.',
    soundLink: '',
    wordId: 72
  },
  
]