[
  {
    nor: 'en mangfoldighet',
    eng: 'a diversity',
    pl: 'różnorodność',
    ar: 'تنوع',
    ger: 'eine Vielfalt',
    lt: 'įvairovė',
    key: '0',
    norEgz: 'Vi må fremme en mangfoldighet av ideer.',
    soundLink: '',
    wordId: 0
  },
  {
    nor: 'en attføring',
    eng: 'a defecation',
    pl: 'defekacja',
    ar: 'تبرز',
    ger: 'eine Stuhlentleerung',
    lt: 'tuštinimasis',
    key: '1',
    norEgz: 'Attføring er en naturlig kroppsfunksjon.',
    soundLink: '',
    wordId: 1
  },
  {
    nor: 'å undergrave',
    eng: 'to undermine',
    pl: 'podważać',
    ar: 'تقويض',
    ger: 'untergraben',
    lt: 'kelti abejones',
    key: '2',
    norEgz: 'Hun prøvde å undergrave hans autoritet.',
    soundLink: '',
    wordId: 2
  },
  {
    nor: 'en bivirkning',
    eng: 'a side effect',
    pl: 'efekt uboczny',
    ar: 'تأثير جانبي',
    ger: 'eine Nebenwirkung',
    lt: 'šalutinis poveikis',
    key: '3',
    norEgz: 'Søvnløshet er en bivirkning av dette legemidlet.',
    soundLink: '',
    wordId: 3
  },
  {
    nor: 'en selvfølelse',
    eng: 'a self-esteem',
    pl: 'poczucie własnej wartości',
    ar: 'تقدير الذات',
    ger: 'ein Selbstwertgefühl',
    lt: 'savigarbos jausmas',
    key: '4',
    norEgz: 'Selvfølelse er viktig for mental helse.',
    soundLink: '',
    wordId: 4
  },
  {
    nor: 'oppsiktsvekkende',
    eng: 'eye-catching',
    pl: 'przyciągający wzrok',
    ar: 'لافت للنظر',
    ger: 'auffällig',
    lt: 'kreipiantis dėmesį',
    key: '5',
    norEgz: 'Hun bar en oppsiktsvekkende kjole på festen.',
    soundLink: '',
    wordId: 5
  },
  {
    nor: "eksponentiell",
    eng: "exponential",
    pl: "ekspotencjalny",
    ar: "أسي",
    ger: "exponentiell",
    lt: "eksponentinis",
    key: "6",
    norEgz: "Veksten i selskapet har vært eksponentiell.",
    soundLink: "",
    wordId: 6
  },
  {
    nor: "forsonende",
    eng: "conciliatory",
    pl: "pojednawczy",
    ar: "مصالح",
    ger: "versöhnlich",
    lt: "sutaikinantis",
    key: "7",
    norEgz: "Han hadde en forsonende tone i samtalen.",
    soundLink: "",
    wordId: 7
  },
  {
    nor: "fragmentert",
    eng: "fragmented",
    pl: "rozdrobniony",
    ar: "مجزأ",
    ger: "fragmentiert",
    lt: "suskaidytas",
    key: "8",
    norEgz: "Informasjonen var fragmentert og vanskelig å forstå.",
    soundLink: "",
    wordId: 8
  },
  {
    nor: "å approbere",
    eng: "to approve",
    pl: "zatwierdzać",
    ar: "يوافق",
    ger: "zustimmen",
    lt: "patvirtinti",
    key: "9",
    norEgz: "Sjefen må approbere endringene før de implementeres.",
    soundLink: "",
    wordId: 9
  },
  {
    nor: "å arbitrere",
    eng: "to arbitrate",
    pl: "arbitrażować",
    ar: "يحكم",
    ger: "schlichten",
    lt: "arbitruoti",
    key: "10",
    norEgz: "Dommeren ble bedt om å arbitrere tvisten.",
    soundLink: "",
    wordId: 10
  },
  {
    nor: "å dekonstruere",
    eng: "to deconstruct",
    pl: "dekonstruować",
    ar: "تفكيك",
    ger: "dekonstruieren",
    lt: "dekonstruoti",
    key: "11",
    norEgz: "Hun prøvde å dekonstruere argumentet for å finne svakheter.",
    soundLink: "",
    wordId: 11
  },
  {
    nor: "en kjernefysikk",
    eng: "nuclear physics",
    pl: "fizyka jądrowa",
    ar: "فيزياء نووية",
    ger: "Kernphysik",
    lt: "branduolinė fizika",
    key: "12",
    norEgz: "Han studerer en kjernefysikk ved universitetet.",
    soundLink: "",
    wordId: 12
  },
  {
  nor: 'flekkvis',
  eng: 'patchy',
  pl: 'plamisty',
  ar: 'عرقي',
  ger: 'fleckig',
  lt: 'dėmėtas',
  key: '13',
  norEgz: 'Jakken hans er flekkvis farget.',
  soundLink: '',
  wordId: 13
  },
  {
    nor: 'grasiøs',
    eng: 'graceful',
    pl: 'pełen gracji',
    ar: 'أنيق',
    ger: 'anmutig',
    lt: 'gracingas',
    key: '14',
    norEgz: 'Ballerinaen danset grasiøst over scenen.',
    soundLink: '',
    wordId: 14
  },
  {
    nor: 'flersidig',
    eng: 'multifaceted',
    pl: 'wieloaspektowy',
    ar: 'متعدد الجوانب',
    ger: 'vielseitig',
    lt: 'daugiasluoksnis',
    key: '15',
    norEgz: 'Hun har en flersidig personlighet.',
    soundLink: '',
    wordId: 15
  },
  {
    nor: 'prangende',
    eng: 'ostentatious',
    pl: 'krzykliwy',
    ar: 'باهر',
    ger: 'prunkvoll',
    lt: 'iššūkio keliantis',
    key: '16',
    norEgz: 'Han kjører en prangende sportsbil.',
    soundLink: '',
    wordId: 16
  },
  {
    nor: 'retorisk',
    eng: 'rhetorical',
    pl: 'retoryczny',
    ar: 'بلاغي',
    ger: 'rhetorisch',
    lt: 'retorinis',
    key: '17',
    norEgz: 'Han stilte et retorisk spørsmål.',
    soundLink: '',
    wordId: 17
  },
  {
    nor: 'å engasjere',
    eng: 'to engage',
    pl: 'angażować',
    ar: 'انخرط',
    ger: 'engagieren',
    lt: 'įtraukti',
    key: '18',
    norEgz: 'Det er viktig å engasjere elevene i læring.',
    soundLink: '',
    wordId: 18
  },
  {
    nor: 'fortvilet',
    eng: 'desperate',
    pl: 'zrozpaczony',
    ar: 'يائس',
    ger: 'verzweifelt',
    lt: 'neviltis',
    key: '19',
    norEgz: 'Han var fortvilet over å ha mistet jobben.',
    soundLink: '',
    wordId: 19
  },
  {
    nor: 'uforklarlig',
    eng: 'inexplicable',
    pl: 'niewytłumaczalny',
    ar: 'غير قابل للتفسير',
    ger: 'unerklärlich',
    lt: 'nepaaiškinamas',
    key: '20',
    norEgz: 'Det var en uforklarlig hendelse.',
    soundLink: '',
    wordId: 20
  },
  {
    nor: 'grenseløs',
    eng: 'boundless',
    pl: 'bezgraniczny',
    ar: 'غير محدود',
    ger: 'grenzenlos',
    lt: 'beribis',
    key: '21',
    norEgz: 'Hun har en grenseløs kjærlighet for sine barn.',
    soundLink: '',
    wordId: 21
  },
  {
    nor: 'uhyrlig',
    eng: 'monstrous',
    pl: 'potworny',
    ar: 'وحشي',
    ger: 'ungeheuerlich',
    lt: 'baisus',
    key: '22',
    norEgz: 'Hun begikk en uhyrlig handling.',
    soundLink: '',
    wordId: 22
  },
  {
    nor: 'foruroligende',
    eng: 'disturbing',
    pl: 'niepokojący',
    ar: 'مقلق',
    ger: 'beunruhigend',
    lt: 'neraminantis',
    key: '23',
    norEgz: 'Det var noen foruroligende nyheter.',
    soundLink: '',
    wordId: 23
  },
  {
    nor: 'ugjennomtrengelig',
    eng: 'impenetrable',
    pl: 'nieprzenikniony',
    ar: 'غير قابل للإختراق',
    ger: 'undurchdringlich',
    lt: 'nepralaidus',
    key: '24',
    norEgz: 'Skogen var uoverkommelig og uforutsigbar.',
    soundLink: '',
    wordId: 24
  },
  {
    nor: 'utilnærmelig',
    eng: 'unapproachable',
    pl: 'nieprzystępny',
    ar: 'غير قابل للوصول',
    ger: 'unzugänglich',
    lt: 'nepasiekiamas',
    key: '25',
    norEgz: 'Sjefen virker utilnærmelig og streng.',
    soundLink: '',
    wordId: 25
  },
  {
    nor: 'ugjestmild',
    eng: 'inhospitable',
    pl: 'niegościnny',
    ar: 'غير مضياف',
    ger: 'ungastlich',
    lt: 'nesvetingas',
    key: '26',
    norEgz: 'Ørkenen kan være et ugjestmildt sted.',
    soundLink: '',
    wordId: 26
  },
  {
    nor: 'uberegnelig',
    eng: 'unpredictable',
    pl: 'nieobliczalny',
    ar: 'غير قابل للتوقع',
    ger: 'unberechenbar',
    lt: 'nenuspėjamas',
    key: '27',
    norEgz: 'Været er ofte uberegnelig.',
    soundLink: '',
    wordId: 27
  },
  {
    nor: 'uovertruffen',
    eng: 'unmatched',
    pl: 'niezrównany',
    ar: 'لا مثيل له',
    ger: 'unübertroffen',
    lt: 'nepakartotas',
    key: '28',
    norEgz: 'Hans evner som musiker er uovertruffen.',
    soundLink: '',
    wordId: 28
  },
  {
    nor: 'inderlig',
    eng: 'sincere',
    pl: 'szczery',
    ar: 'صادق',
    ger: 'innig',
    lt: 'nuoširdus',
    key: '29',
    norEgz: 'Hun uttrykte en inderlig bønn.',
    soundLink: '',
    wordId: 29
  },
  {
    nor: 'ubetydelig',
    eng: 'insignificant',
    pl: 'nieistotny',
    ar: 'غير مهم',
    ger: 'unbedeutend',
    lt: 'nesvarbus',
    key: '30',
    norEgz: 'For ham var det en ubetydelig detalj.',
    soundLink: '',
    wordId: 30
  },
  {
  nor: 'en selvtillit',
  eng: 'a self-confidence',
  pl: 'pewność siebie',
  ar: 'ثقة بالنفس',
  ger: 'ein Selbstvertrauen',
  lt: 'savigarba',
  key: '31',
  norEgz: 'Han har en høy selvtillit.',
  soundLink: '',
  wordId: 31
  },
  {
    nor: 'uovertruffen',
    eng: 'unmatched',
    pl: 'niezrównany',
    ar: 'لا مثيل له',
    ger: 'unübertroffen',
    lt: 'nepakartotas',
    key: '32',
    norEgz: 'Hans evner som musiker er uovertruffen.',
    soundLink: '',
    wordId: 32
  },
  {
  nor: 'en forfengelighet',
  eng: 'a vanity',
  pl: 'próżność',
  ar: 'غرور',
  ger: 'eine Eitelkeit',
  lt: 'tuštumas',
  key: '33',
  norEgz: 'Forfengelighet kan være en ulempe.',
  soundLink: '',
  wordId: 33
  },
  {
  nor: 'utilgjengelig',
  eng: 'unavailable',
  pl: 'niedostępny',
  ar: 'غير متاح',
  ger: 'nicht verfügbar',
  lt: 'neprieinamas',
  key: '34',
  norEgz: 'Ressursene er utilgjengelige på grunn av konflikten.',
  soundLink: '',
  wordId: 34
  },
  {
    nor: 'utilnærmelig',
    eng: 'unapproachable',
    pl: 'nieprzystępny',
    ar: 'غير قابل للوصول',
    ger: 'unzugänglich',
    lt: 'nepasiekiamas',
    key: '35',
    norEgz: 'Sjefen virker utilnærmelig og streng.',
    soundLink: '',
    wordId: 35
  },
  {
    nor: 'ugjestmild',
    eng: 'inhospitable',
    pl: 'niegościnny',
    ar: 'غير مضياف',
    ger: 'ungastlich',
    lt: 'nesvetingas',
    key: '36',
    norEgz: 'Ørkenen kan være et ugjestmildt sted.',
    soundLink: '',
    wordId: 36
  },
  {
    nor: 'uberegnelig',
    eng: 'unpredictable',
    pl: 'nieobliczalny',
    ar: 'غير قابل للتوقع',
    ger: 'unberechenbar',
    lt: 'nenuspėjamas',
    key: '37',
    norEgz: 'Været er ofte uberegnelig.',
    soundLink: '',
    wordId: 37
  },
  {
    nor: 'antiklimaktisk',
    eng: 'anticlimactic',
    pl: 'rozczarowujący',
    ar: 'مُقَلّب',
    ger: 'antiklimaktisch',
    lt: 'nuviliantis',
    key: '38',
    norEgz: 'Avslutningen på boken var antiklimaktisk.',
    soundLink: '',
    wordId: 38
  },
  {
    nor: 'å erverve',
    eng: 'to acquire',
    pl: 'nabyć',
    ar: 'اكتساب',
    ger: 'erwerben',
    lt: 'įsigyti',
    key: '39',
    norEgz: 'De prøver å erverve en ny eiendom.',
    soundLink: '',
    wordId: 39
  },
  {
    nor: 'inkonsekvent',
    eng: 'inconsistent',
    pl: 'niespójny',
    ar: 'غير متسق',
    ger: 'inkonsistent',
    lt: 'nenuoseklus',
    key: '40',
    norEgz: 'Hans historie virker inkonsekvent og usammenhengende.',
    soundLink: '',
    wordId: 40
  },
  {
    nor: 'å redegjøre',
    eng: 'to explain',
    pl: 'wyjaśnić',
    ar: 'شرح',
    ger: 'erklären',
    lt: 'paaiškinti',
    key: '41',
    norEgz: 'Kan du redegjøre for dine handlinger?',
    soundLink: '',
    wordId: 41
  },
  {
    nor: 'en forræderi',
    eng: 'a betrayal',
    pl: 'zdrada',
    ar: 'خيانة',
    ger: 'ein Verrat',
    lt: 'išdavystė',
    key: '42',
    norEgz: 'Han begikk en forræderi mot sitt eget folk.',
    soundLink: '',
    wordId: 42
  },
  {
    nor: 'en fremmedgjøring',
    eng: 'alienation',
    pl: 'alienacja',
    ar: 'اغتراب',
    ger: 'Entfremdung',
    lt: 'atsvetimėjimas',
    key: '43',
    norEgz: 'Teknologi kan føre til fremmedgjøring.',
    soundLink: '',
    wordId: 43
  },
  {
    nor: 'en eksil',
    eng: 'an exile',
    pl: 'wygnanie',
    ar: 'منفى',
    ger: 'ein Exil',
    lt: 'tremtis',
    key: '44',
    norEgz: 'Forfatteren levde i eksil i mange år.',
    soundLink: '',
    wordId: 44
  },
  {
    nor: 'omnipotent',
    eng: 'omnipotent',
    pl: 'wszechmocny',
    ar: 'القادر على كل شيء',
    ger: 'allmächtig',
    lt: 'visagalis',
    key: '45',
    norEgz: 'Gud er ofte beskrevet som omnipotent.',
    soundLink: '',
    wordId: 45
  },
  {
    nor: 'patosfylt',
    eng: 'pathos-filled',
    pl: 'pełen patosu',
    ar: 'مليء بالعاطفة',
    ger: 'pathetisch',
    lt: 'pilnas patoso',
    key: '46',
    norEgz: 'Talen hans var patosfylt og rørende.',
    soundLink: '',
    wordId: 46
  },
  {
    nor: 'sublim',
    eng: 'sublime',
    pl: 'wzniosły',
    ar: 'سام',
    ger: 'erhaben',
    lt: 'sublimiškas',
    key: '47',
    norEgz: 'Landskapet her er virkelig sublim.',
    soundLink: '',
    wordId: 47
  },
  {
    nor: 'foruroligende',
    eng: 'disturbing',
    pl: 'niepokojący',
    ar: 'مقلق',
    ger: 'beunruhigend',
    lt: 'neraminantis',
    key: '48',
    norEgz: 'Det var noen foruroligende nyheter.',
    soundLink: '',
    wordId: 48
  },
  {
    nor: 'ugjennomtrengelig',
    eng: 'impenetrable',
    pl: 'nieprzenikniony',
    ar: 'غير قابل للإختراق',
    ger: 'undurchdringlich',
    lt: 'nepralaidus',
    key: '49',
    norEgz: 'Skogen var uoverkommelig og uforutsigbar.',
    soundLink: '',
    wordId: 49
  },
  {
    nor: 'en bevoktning',
    eng: 'a guarding',
    pl: 'straż',
    ar: 'حراسة',
    ger: 'eine Bewachung',
    lt: 'sargyba',
    key: '50',
    norEgz: 'Banken har døgnet rundt bevoktning.',
    soundLink: '',
    wordId: 50
  },
  {
    nor: 'å resonere',
    eng: 'to resonate',
    pl: 'rezonować',
    ar: 'يتردد',
    ger: 'resonieren',
    lt: 'rezonuoti',
    key: '51',
    norEgz: 'Hans ord resonerte med publikum.',
    soundLink: '',
    wordId: 51
  },
  {
    nor: 'inntagende',
    eng: 'ingratiating',
    pl: 'przymilny',
    ar: 'مستأنس',
    ger: 'einschmeichelnd',
    lt: 'patrauklus',
    key: '52',
    norEgz: 'Han har en inntagende personlighet.',
    soundLink: '',
    wordId: 52
  },
  {
    nor: 'en erklæring',
    eng: 'a declaration',
    pl: 'oświadczenie',
    ar: 'إعلان',
    ger: 'eine Erklärung',
    lt: 'deklaracija',
    key: '53',
    norEgz: 'Han ga en offisiell erklæring om situasjonen.',
    soundLink: '',
    wordId: 53
  },
  {
    nor: 'en erkjennelse',
    eng: 'an acknowledgment',
    pl: 'uznanie',
    ar: 'اعتراف',
    ger: 'eine Anerkennung',
    lt: 'pripažinimas',
    key: '54',
    norEgz: 'Han kom fram til en viktig erkjennelse.',
    soundLink: '',
    wordId: 54
  },
  {
    nor: 'en erobring',
    eng: 'a conquest',
    pl: 'zdobycie',
    ar: 'غزو',
    ger: 'eine Eroberung',
    lt: 'užkariavimas',
    key: '55',
    norEgz: 'Romerriket hadde mange erobringer.',
    soundLink: '',
    wordId: 55
  },
  {
    nor: 'kvasivitenskapelig',
    eng: 'pseudoscientific',
    pl: 'pseudonaukowy',
    ar: 'زائف العلم',
    ger: 'pseudowissenschaftlich',
    lt: 'pseudo-mokslinis',
    key: '56',
    norEgz: 'Denne teorien er kvasivitenskapelig og upålitelig.',
    soundLink: '',
    wordId: 56
  },
  {
    nor: 'kverulerende',
    eng: 'querulous',
    pl: 'kłótliwy',
    ar: 'متشكي',
    ger: 'querulatorisch',
    lt: 'skundikas',
    key: '57',
    norEgz: 'Han har en kverulerende personlighet.',
    soundLink: '',
    wordId: 57
  },
  {
    nor: 'fengslende',
    eng: 'captivating',
    pl: 'urokliwy',
    ar: 'ساحر',
    ger: 'fesselnd',
    lt: 'pavergiantis',
    key: '59',
    norEgz: 'Hun fortalte en fengslende historie.',
    soundLink: '',
    wordId: 59
  },
  {
    nor: 'overdådig',
    eng: 'lavish',
    pl: 'rozrzutny',
    ar: 'فخم',
    ger: 'üppig',
    lt: 'prabangus',
    key: '60',
    norEgz: 'Festen var overdådig med mye mat og drikke.',
    soundLink: '',
    wordId: 60
  },
  {
    nor: 'en samvittighet',
    eng: 'a conscience',
    pl: 'sumienie',
    ar: 'ضمير',
    ger: 'ein Gewissen',
    lt: 'sąžinė',
    key: '61',
    norEgz: 'Han hadde en ren samvittighet etter å ha gjort det rette.',
    soundLink: '',
    wordId: 61
  },
  {
    nor: 'en avskaffelse',
    eng: 'an abolition',
    pl: 'zniesienie',
    ar: 'إلغاء',
    ger: 'eine Abschaffung',
    lt: 'panaikinimas',
    key: '62',
    norEgz: 'Avskaffelsen av slaveri var et viktig skritt.',
    soundLink: '',
    wordId: 62
  },
  {
    nor: 'en avsky',
    eng: 'a disgust',
    pl: 'wstręt',
    ar: 'اشمئزاز',
    ger: 'ein Ekel',
    lt: 'pasibjaurėjimas',
    key: '63',
    norEgz: 'Hun følte avsky for den grusomme handlingen.',
    soundLink: '',
    wordId: 63
  },
  {
    nor: 'en avbetaling',
    eng: 'an installment',
    pl: 'rata',
    ar: 'قسط',
    ger: 'eine Rate',
    lt: 'įmoka',
    key: '64',
    norEgz: 'Han betalte for bilen i månedlige avdrag.',
    soundLink: '',
    wordId: 64
  },
  {
    nor: 'lunefull',
    eng: 'capricious',
    pl: 'kapryśny',
    ar: 'متقلب',
    ger: 'launisch',
    lt: 'kaitrus',
    key: '65',
    norEgz: 'Været kan være lunefullt på fjellet.',
    soundLink: '',
    wordId: 65
  },
  {
    nor: 'irrasjonell',
    eng: 'irrational',
    pl: 'niedorzeczny',
    ar: 'غير عقلاني',
    ger: 'irrational',
    lt: 'neracionalus',
    key: '66',
    norEgz: 'Hans oppførsel var fullstendig irrasjonell.',
    soundLink: '',
    wordId: 66
  },
  {
    nor: 'svimlende',
    eng: 'dizzying',
    pl: 'oszałamiający',
    ar: 'مُرَوِّح',
    ger: 'schwindelerregend',
    lt: 'sukeliantis svaigulį',
    key: '67',
    norEgz: 'Høyden var svimlende.',
    soundLink: '',
    wordId: 67
  },
  {
    nor: 'avskyelig',
    eng: 'disgusting',
    pl: 'odrażający',
    ar: 'مقرف',
    ger: 'widerlich',
    lt: 'pasibjaurėtinas',
    key: '68',
    norEgz: 'Oppførselen hans var avskyelig.',
    soundLink: '',
    wordId: 68
  },
  {
    nor: 'lunefull',
    eng: 'capricious',
    pl: 'kapryśny',
    ar: 'متقلب',
    ger: 'launisch',
    lt: 'kaitrus',
    key: '69',
    norEgz: 'Været kan være lunefullt på fjellet.',
    soundLink: '',
    wordId: 69
  },
  {
    nor: 'veltalende',
    eng: 'eloquent',
    pl: 'elokwentny',
    ar: 'بليغ',
    ger: 'redegewandt',
    lt: 'iškalbingas',
    key: '70',
    norEgz: 'Han er en veltalende talsmann.',
    soundLink: '',
    wordId: 70
  },
  {
    nor: 'viljesterk',
    eng: 'strong-willed',
    pl: 'silnowolny',
    ar: 'عنيد',
    ger: 'willensstark',
    lt: 'valingas',
    key: '71',
    norEgz: 'Hun er en viljesterk person.',
    soundLink: '',
    wordId: 71
  },
  {
    nor: 'en avholdenhet',
    eng: 'an abstinence',
    pl: 'wstrzemięźliwość',
    ar: 'امتناع',
    ger: 'eine Enthaltsamkeit',
    lt: 'susilaikymas',
    key: '72',
    norEgz: 'Han praktiserer en avholdenhet fra alkohol.',
    soundLink: '',
    wordId: 72
  },
  {
    nor: 'ytterliggående',
    eng: 'extreme',
    pl: 'skrajny',
    ar: 'متطرف',
    ger: 'extrem',
    lt: 'kraštutinis',
    key: '73',
    norEgz: 'Han har ytterliggående synspunkter.',
    soundLink: '',
    wordId: 73
  },
  {
    nor: 'en antakelse',
    eng: 'an assumption',
    pl: 'założenie',
    ar: 'افتراض',
    ger: 'eine Annahme',
    lt: 'prielaida',
    key: '74',
    norEgz: 'Vi baserer dette på en antakelse om økonomisk vekst.',
    soundLink: '',
    wordId: 74
  },
  {
    nor: 'en bevilling',
    eng: 'an allocation',
    pl: 'przydział',
    ar: 'تخصيص',
    ger: 'eine Zuteilung',
    lt: 'skirtis',
    key: '75',
    norEgz: 'Kommunen fikk en bevilling til nytt utstyr.',
    soundLink: '',
    wordId: 75
  },
  {
    nor: 'en avsked',
    eng: 'a farewell',
    pl: 'pożegnanie',
    ar: 'وداع',
    ger: 'ein Abschied',
    lt: 'atsisveikinimas',
    key: '76',
    norEgz: 'Dette er en avsked mellom gode venner.',
    soundLink: '',
    wordId: 76
  },
  {
    nor: 'å reevaluere',
    eng: 'to reevaluate',
    pl: 'przeocenić',
    ar: 'إعادة التقييم',
    ger: 'neu bewerten',
    lt: 'pervertinti',
    key: '77',
    norEgz: 'Vi må reevaluere strategien vår.',
    soundLink: '',
    wordId: 77
  },
  {
    nor: 'kynisk',
    eng: 'cynical',
    pl: 'cyniczny',
    ar: 'ساخر',
    ger: 'zynisch',
    lt: 'ciniškas',
    key: '78',
    norEgz: 'Han hadde et kynisk smil om munnen.',
    soundLink: '',
    wordId: 78
  },
  {
    nor: 'å frigjøre',
    eng: 'to liberate',
    pl: 'uwolnić',
    ar: 'تحرر',
    ger: 'befreien',
    lt: 'išlaisvinti',
    key: '79',
    norEgz: 'Målet er å frigjøre landet fra undertrykkelse.',
    soundLink: '',
    wordId: 79
  },
  {
    nor: 'øredøvende',
    eng: 'deafening',
    pl: 'ogłuszający',
    ar: 'صاخب',
    ger: 'ohrenbetäubend',
    lt: 'kurstantis',
    key: '80',
    norEgz: 'Musikken på konserten var øredøvende.',
    soundLink: '',
    wordId: 80
  },
  {
    nor: 'illusorisk',
    eng: 'illusory',
    pl: 'iluzoryczny',
    ar: 'وهمي',
    ger: 'illusorisch',
    lt: 'iliuzinis',
    key: '81',
    norEgz: 'Fremgangen viste seg å være illusorisk.',
    soundLink: '',
    wordId: 81
  },
  {
    nor: 'å kontemplere',
    eng: 'to contemplate',
    pl: 'kontemplować',
    ar: 'تأمل',
    ger: 'kontemplieren',
    lt: 'kontempliuoti',
    key: '82',
    norEgz: 'Han satt og kontemplerte livets mysterier.',
    soundLink: '',
    wordId: 82
  },
  {
    nor: 'en arvegang',
    eng: 'inheritance',
    pl: 'dziedziczenie',
    ar: 'وراثة',
    ger: 'Erbschaft',
    lt: 'paveldėjimas',
    key: '83',
    norEgz: 'Arvegangen i familien var komplisert.',
    soundLink: '',
    wordId: 83
  },
  {
    nor: 'en beplantning',
    eng: 'planting',
    pl: 'nasadzenia',
    ar: 'زراعة',
    ger: 'Bepflanzung',
    lt: 'auginimas',
    key: '84',
    norEgz: 'Beplantningen i hagen ser fantastisk ut.',
    soundLink: '',
    wordId: 84
  },
  {
    nor: 'uforlignelig',
    eng: 'incomparable',
    pl: 'nieporównywalny',
    ar: 'لا يقارن',
    ger: 'unvergleichlich',
    lt: 'nelyginamas',
    key: '85',
    norEgz: 'Hans talent er uforlignelig.',
    soundLink: '',
    wordId: 85
  },
  {
    nor: 'skjør',
    eng: 'fragile',
    pl: 'kruchy',
    ar: 'هش',
    ger: 'zerbrechlich',
    lt: 'trapus',
    key: '86',
    norEgz: 'Vasen er veldig skjør, vær forsiktig.',
    soundLink: '',
    wordId: 86
  },
  {
    nor: 'eksplicit',
    eng: 'explicit',
    pl: 'wyraźny',
    ar: 'صريح',
    ger: 'explizit',
    lt: 'aiškus',
    key: '87',
    norEgz: 'Instruksjonene var eksplicitte og klare.',
    soundLink: '',
    wordId: 87
  },
  {
    nor: 'implisitt',
    eng: 'implicit',
    pl: 'domniemany',
    ar: 'ضمني',
    ger: 'implizit',
    lt: 'neišreikštas',
    key: '88',
    norEgz: 'Hans implisitte forståelse var tydelig.',
    soundLink: '',
    wordId: 88
  },
  {
    nor: 'å besitte',
    eng: 'to possess',
    pl: 'posiadać',
    ar: 'امتلك',
    ger: 'besitzen',
    lt: 'turėti',
    key: '89',
    norEgz: 'Han besitter en sjelden samling mynter.',
    soundLink: '',
    wordId: 89
  },
  {
    nor: 'å meditere',
    eng: 'to meditate',
    pl: 'medytować',
    ar: 'تأمل',
    ger: 'meditieren',
    lt: 'medituoti',
    key: '90',
    norEgz: 'Hun liker å meditere hver morgen.',
    soundLink: '',
    wordId: 90
  },
  {
    nor: 'å revidere',
    eng: 'to revise',
    pl: 'zrewidować',
    ar: 'تنقيح',
    ger: 'revidieren',
    lt: 'peržiūrėti',
    key: '91',
    norEgz: 'Vi må revidere planene våre.',
    soundLink: '',
    wordId: 91
  },
  {
    nor: 'gripende',
    eng: 'moving',
    pl: 'poruszający',
    ar: 'مؤثر',
    ger: 'bewegend',
    lt: 'judinantis',
    key: '92',
    norEgz: 'Det var en gripende historie om overlevelse.',
    soundLink: '',
    wordId: 92
  },
  {
    nor: 'tåkefull',
    eng: 'foggy',
    pl: 'mglisty',
    ar: 'ضبابي',
    ger: 'neblig',
    lt: 'rūkas',
    key: '93',
    norEgz: 'Det var en tåkefull morgen.',
    soundLink: '',
    wordId: 93
  },
  {
    nor: 'henrivende',
    eng: 'captivating',
    pl: 'urokliwy',
    ar: 'ساحر',
    ger: 'bezaubernd',
    lt: 'pavergiantis',
    key: '94',
    norEgz: 'Hennes henrivende smil lyste opp rommet.',
    soundLink: '',
    wordId: 94
  },
  {
    nor: 'betagende',
    eng: 'breathtaking',
    pl: 'zapierający dech',
    ar: 'مدهش',
    ger: 'atemberaubend',
    lt: 'kvapą gniaužiantis',
    key: '95',
    norEgz: 'Utsikten fra toppen av fjellet var betagende.',
    soundLink: '',
    wordId: 95
  },
  {
    nor: 'utrettelig',
    eng: 'tireless',
    pl: 'niestrudzony',
    ar: 'متعب',
    ger: 'unermüdlich',
    lt: 'neprisotinęs',
    key: '96',
    norEgz: 'Han er en utrettelig arbeider.',
    soundLink: '',
    wordId: 96
  },
  {
    nor: 'usammenhengende',
    eng: 'incoherent',
    pl: 'niespójny',
    ar: 'غير مترابط',
    ger: 'unzusammenhängend',
    lt: 'nesuderinamas',
    key: '97',
    norEgz: 'Hans tale var usammenhengende etter ulykken.',
    soundLink: '',
    wordId: 97
  },
  {
    nor: 'omfattende',
    eng: 'comprehensive',
    pl: 'obszerny',
    ar: 'شامل',
    ger: 'umfassend',
    lt: 'išsamus',
    key: '98',
    norEgz: 'Det var en omfattende undersøkelse av saken.',
    soundLink: '',
    wordId: 98
  },
  {
    nor: 'å synkronisere',
    eng: 'to synchronize',
    pl: 'synchronizować',
    ar: 'مزامنة',
    ger: 'synchronisieren',
    lt: 'sinchronizuoti',
    key: '99',
    norEgz: 'Vi må synkronisere klokkene våre.',
    soundLink: '',
    wordId: 99
  },
  {
    nor: 'å delegere',
    eng: 'to delegate',
    pl: 'delegować',
    ar: 'تفويض',
    ger: 'delegieren',
    lt: 'deleguoti',
    key: '100',
    norEgz: 'Han må delegere oppgaver til teamet sitt.',
    soundLink: '',
    wordId: 100
  },
  {
    nor: 'å eliminere',
    eng: 'to eliminate',
    pl: 'eliminować',
    ar: 'استبعاد',
    ger: 'eliminieren',
    lt: 'eliminuoti',
    key: '101',
    norEgz: 'Vi må eliminere feilene i systemet.',
    soundLink: '',
    wordId: 101
  },
  {
    nor: 'malerisk',
    eng: 'picturesque',
    pl: 'malowniczy',
    ar: 'خلاب',
    ger: 'malerisch',
    lt: 'vaizdingas',
    key: '102',
    norEgz: 'Landskapet var malerisk med fargerike blomster.',
    soundLink: '',
    wordId: 102
  },
  {
    nor: 'opphøyet',
    eng: 'exalted',
    pl: 'wzniosły',
    ar: 'مرتفع',
    ger: 'erhöht',
    lt: 'išaukštinamas',
    key: '103',
    norEgz: 'Hun hadde en opphøyet posisjon i samfunnet.',
    soundLink: '',
    wordId: 103
  },
  {
    nor: 'uforutsigbar',
    eng: 'unpredictable',
    pl: 'nieprzewidywalny',
    ar: 'غير قابل للتوقع',
    ger: 'unberechenbar',
    lt: 'nuspėjamas',
    key: '104',
    norEgz: 'Været kan være uforutsigbar i fjellet.',
    soundLink: '',
    wordId: 104
  },
  {
    nor: 'oppriktig',
    eng: 'sincere',
    pl: 'szczery',
    ar: 'صادق',
    ger: 'aufrichtig',
    lt: 'nuoširdus',
    key: '105',
    norEgz: 'Hun ga en oppriktig unnskyldning.',
    soundLink: '',
    wordId: 105
  },
  {
    nor: 'utsøkt',
    eng: 'exquisite',
    pl: 'wyśmienity',
    ar: 'رائع',
    ger: 'exquisit',
    lt: 'puikus',
    key: '106',
    norEgz: 'Maten på restauranten var utsøkt.',
    soundLink: '',
    wordId: 106
  },
  {
    nor: 'å formulere',
    eng: 'to formulate',
    pl: 'sformułować',
    ar: 'صياغة',
    ger: 'formulieren',
    lt: 'formuluoti',
    key: '107',
    norEgz: 'Han prøver å formulere en ny teori.',
    soundLink: '',
    wordId: 107
  },
  {
    nor: 'å fortolke',
    eng: 'to interpret',
    pl: 'interpretować',
    ar: 'تفسير',
    ger: 'interpretieren',
    lt: 'interpretuoti',
    key: '108',
    norEgz: 'Vi må fortolke dataene nøye.',
    soundLink: '',
    wordId: 108
  },
  {
    nor: 'å innovere',
    eng: 'to innovate',
    pl: 'wprowadzać innowacje',
    ar: 'ابتكار',
    ger: 'innovieren',
    lt: 'inovuoti',
    key: '109',
    norEgz: 'Bedriften vår må innovere for å være konkurransedyktig.',
    soundLink: '',
    wordId: 109
  },
  {
    nor: 'forbløffende',
    eng: 'astonishing',
    pl: 'zdumiewający',
    ar: 'مدهش',
    ger: 'erstaunlich',
    lt: 'nuostabus',
    key: '110',
    norEgz: 'Det var en forbløffende oppdagelse.',
    soundLink: '',
    wordId: 110
  },
  {
    nor: 'å avhenge',
    eng: 'to depend',
    pl: 'zależeć',
    ar: 'يعتمد على',
    ger: 'abhängen',
    lt: 'priklauso',
    key: '111',
    norEgz: 'Suksessen vår vil avhenge av hardt arbeid.',
    soundLink: '',
    wordId: 111
  },
  {
    nor: 'å betrakte',
    eng: 'to consider',
    pl: 'rozważać',
    ar: 'أعتبر',
    ger: 'betrachten',
    lt: 'laikyti',
    key: '112',
    norEgz: 'Jeg betrakter ham som en venn.',
    soundLink: '',
    wordId: 112
  },
  {
    nor: 'å bevise',
    eng: 'to prove',
    pl: 'udowodnić',
    ar: 'أثبت',
    ger: 'beweisen',
    lt: 'įrodyti',
    key: '113',
    norEgz: 'Han prøver å bevise sin uskyld.',
    soundLink: '',
    wordId: 113
  },
  {
    nor: 'å forhandle',
    eng: 'to negotiate',
    pl: 'negocjować',
    ar: 'تفاوض',
    ger: 'verhandeln',
    lt: 'derybuoti',
    key: '114',
    norEgz: 'Vi må forhandle om en bedre avtale.',
    soundLink: '',
    wordId: 114
  },
  {
    nor: 'å formidle',
    eng: 'to convey',
    pl: 'przekazać',
    ar: 'نقل',
    ger: 'vermitteln',
    lt: 'perduoti',
    key: '115',
    norEgz: 'Hun formidler en sterk budskap gjennom kunsten sin.',
    soundLink: '',
    wordId: 115
  },
  {
    nor: 'å forske',
    eng: 'to research',
    pl: 'badac',
    ar: 'أبحث',
    ger: 'forschen',
    lt: 'tyrimai',
    key: '116',
    norEgz: 'Hun forsker på klimaendringer.',
    soundLink: '',
    wordId: 116
  },
  {
    nor: 'å gruble',
    eng: 'to ponder',
    pl: 'rozmyślać',
    ar: 'تأمل',
    ger: 'grübeln',
    lt: 'svarstyti',
    key: '117',
    norEgz: 'Han satt og grublet over problemet.',
    soundLink: '',
    wordId: 117
  },
  {
    nor: 'å håndtere',
    eng: 'to handle',
    pl: 'zajmować się',
    ar: 'يتعامل',
    ger: 'handhaben',
    lt: 'tvarkyti',
    key: '118',
    norEgz: 'Du må lære å håndtere kritikk.',
    soundLink: '',
    wordId: 118
  },
  {
    nor: 'å instruere',
    eng: 'to instruct',
    pl: 'instruować',
    ar: 'أعلم',
    ger: 'instruieren',
    lt: 'instruktuoti',
    key: '119',
    norEgz: 'Han ble bedt om å instruere de nye medarbeiderne.',
    soundLink: '',
    wordId: 119
  },
  {
    nor: 'å klargjøre',
    eng: 'to clarify',
    pl: 'wyjaśnić',
    ar: 'أوضح',
    ger: 'klären',
    lt: 'paaiškinti',
    key: '120',
    norEgz: 'Kan du klargjøre hva du mener med det?',
    soundLink: '',
    wordId: 120
  },
  {
    nor: 'å konkludere',
    eng: 'to conclude',
    pl: 'wywnioskować',
    ar: 'خلص',
    ger: 'schließen',
    lt: 'baigti',
    key: '121',
    norEgz: 'Vi kan konkludere at innsatsen var verdt det.',
    soundLink: '',
    wordId: 121
  },
  {
    nor: 'å oppmuntre',
    eng: 'to encourage',
    pl: 'zachęcić',
    ar: 'شجع',
    ger: 'ermutigen',
    lt: 'skatinti',
    key: '122',
    norEgz: 'Vi bør alltid oppmuntre til kreativitet.',
    soundLink: '',
    wordId: 122
  },
  {
    nor: 'å opprettholde',
    eng: 'to maintain',
    pl: 'utrzymać',
    ar: 'حافظ على',
    ger: 'aufrechterhalten',
    lt: 'palaikyti',
    key: '123',
    norEgz: 'Vi må opprettholde en høy standard.',
    soundLink: '',
    wordId: 123
  },
  {
    nor: 'å samhandle',
    eng: 'to interact',
    pl: 'współdziałać',
    ar: 'تفاعل',
    ger: 'interagieren',
    lt: 'bendrauti',
    key: '124',
    norEgz: 'Barn lærer gjennom å samhandle med andre.',
    soundLink: '',
    wordId: 124
  },
  {
    nor: 'å skille',
    eng: 'to separate',
    pl: 'separować',
    ar: 'فصل',
    ger: 'trennen',
    lt: 'atskirti',
    key: '125',
    norEgz: 'Vi må skille mellom fakta og meninger.',
    soundLink: '',
    wordId: 125
  },
  {
    nor: 'å verdsette',
    eng: 'to appreciate',
    pl: 'cenić',
    ar: 'قدر',
    ger: 'schätzen',
    lt: 'įvertinti',
    key: '126',
    norEgz: 'Jeg verdsetter din hjelp veldig.',
    soundLink: '',
    wordId: 126
  },
  {
    nor: 'å ydmyke',
    eng: 'to humble',
    pl: 'pokornić',
    ar: 'أذل',
    ger: 'demütigen',
    lt: 'pažeminti',
    key: '127',
    norEgz: 'Han prøvde å ydmyke meg i offentligheten.',
    soundLink: '',
    wordId: 127
  },
  {
    nor: 'å ødelegge',
    eng: 'to destroy',
    pl: 'zniszczyć',
    ar: 'دمر',
    ger: 'zerstören',
    lt: 'sugriauti',
    key: '128',
    norEgz: 'Brannen klarte å ødelegge hele bygningen.',
    soundLink: '',
    wordId: 128
  },
  {
    nor: 'å diversifisere',
    eng: 'to diversify',
    pl: 'dywersyfikować',
    ar: 'تنوع',
    ger: 'diversifizieren',
    lt: 'diversifikuoti',
    key: '129',
    norEgz: 'Selskapet planlegger å diversifisere sine produkter.',
    soundLink: '',
    wordId: 129
  },
  {
    nor: 'å vandre',
    eng: 'to wander',
    pl: 'włóczyć się',
    ar: 'تجول',
    ger: 'wandern',
    lt: 'klajoti',
    key: '130',
    norEgz: 'Han liker å vandre i skogen.',
    soundLink: '',
    wordId: 130
  },
  {
    nor: 'å styrke',
    eng: 'to strengthen',
    pl: 'wzmocnić',
    ar: 'عزز',
    ger: 'stärken',
    lt: 'sustiprinti',
    key: '131',
    norEgz: 'Vi må styrke vårt forsvar mot sykdommer.',
    soundLink: '',
    wordId: 131
  },
  {
    nor: 'å vekke',
    eng: 'to awaken',
    pl: 'obudzić',
    ar: 'أيقظ',
    ger: 'erwecken',
    lt: 'pažadinti',
    key: '132',
    norEgz: 'Den gode nyheten klarte å vekke hans interesse.',
    soundLink: '',
    wordId: 132
  },
  {
    nor: 'å sammensmelte',
    eng: 'to merge',
    pl: 'połączyć',
    ar: 'دمج',
    ger: 'verschmelzen',
    lt: 'sujungti',
    key: '133',
    norEgz: 'Vi planlegger å sammensmelte de to selskapene.',
    soundLink: '',
    wordId: 133
  },
  {
    nor: 'å differensiere',
    eng: 'to differentiate',
    pl: 'rozróżnić',
    ar: 'ميّز',
    ger: 'differenzieren',
    lt: 'diferencijuoti',
    key: '134',
    norEgz: 'Lærere må lære å differensiere instruksjonen.',
    soundLink: '',
    wordId: 134
  },
  {
    nor: 'å omskolere',
    eng: 'to retrain',
    pl: 'przeszkolić',
    ar: 'إعادة تدريب',
    ger: 'umschulen',
    lt: 'perkvalifikuoti',
    key: '135',
    norEgz: 'Mange arbeidere må omskolere for nye jobber.',
    soundLink: '',
    wordId: 135
  }
  
  
]