[
  {
    nor: 'en mangfoldighet',
    eng: 'a diversity',
    pl: 'różnorodność',
    ar: 'تنوع',
    ger: 'eine Vielfalt',
    lt: 'įvairovė',
    key: '0',
    norEgz: 'Vi må fremme en mangfoldighet av ideer.',
    soundLink: '',
    wordId: 0
  },
  {
    nor: 'en attføring',
    eng: 'a defecation',
    pl: 'defekacja',
    ar: 'تبرز',
    ger: 'eine Stuhlentleerung',
    lt: 'tuštinimasis',
    key: '1',
    norEgz: 'Attføring er en naturlig kroppsfunksjon.',
    soundLink: '',
    wordId: 1
  },
  {
    nor: 'å undergrave',
    eng: 'to undermine',
    pl: 'podważać',
    ar: 'تقويض',
    ger: 'untergraben',
    lt: 'kelti abejones',
    key: '2',
    norEgz: 'Hun prøvde å undergrave hans autoritet.',
    soundLink: '',
    wordId: 2
  },
  {
    nor: 'en bivirkning',
    eng: 'a side effect',
    pl: 'efekt uboczny',
    ar: 'تأثير جانبي',
    ger: 'eine Nebenwirkung',
    lt: 'šalutinis poveikis',
    key: '3',
    norEgz: 'Søvnløshet er en bivirkning av dette legemidlet.',
    soundLink: '',
    wordId: 3
  },
  {
    nor: 'en selvfølelse',
    eng: 'a self-esteem',
    pl: 'poczucie własnej wartości',
    ar: 'تقدير الذات',
    ger: 'ein Selbstwertgefühl',
    lt: 'savigarbos jausmas',
    key: '4',
    norEgz: 'Selvfølelse er viktig for mental helse.',
    soundLink: '',
    wordId: 4
  },
  {
    nor: 'ekstravagant',
    eng: 'extravagant',
    pl: 'ekstrawagancki',
    ar: 'مسرف',
    ger: 'extravagant',
    lt: 'švaistus',
    key: '5',
    norEgz: 'Hun er kjent for sin ekstravagante livsstil.',
    soundLink: '',
    wordId: 5
  },
  {
    nor: "eksponentiell",
    eng: "exponential",
    pl: "ekspotencjalny",
    ar: "أسي",
    ger: "exponentiell",
    lt: "eksponentinis",
    key: "6",
    norEgz: "Veksten i selskapet har vært eksponentiell.",
    soundLink: "",
    wordId: 6
  },
  {
    nor: "forsonende",
    eng: "conciliatory",
    pl: "pojednawczy",
    ar: "مصالح",
    ger: "versöhnlich",
    lt: "sutaikinantis",
    key: "7",
    norEgz: "Han hadde en forsonende tone i samtalen.",
    soundLink: "",
    wordId: 7
  },
  {
    nor: "fragmentert",
    eng: "fragmented",
    pl: "rozdrobniony",
    ar: "مجزأ",
    ger: "fragmentiert",
    lt: "suskaidytas",
    key: "8",
    norEgz: "Informasjonen var fragmentert og vanskelig å forstå.",
    soundLink: "",
    wordId: 8
  },
  {
    nor: "å approbere",
    eng: "to approve",
    pl: "zatwierdzać",
    ar: "يوافق",
    ger: "zustimmen",
    lt: "patvirtinti",
    key: "9",
    norEgz: "Sjefen må approbere endringene før de implementeres.",
    soundLink: "",
    wordId: 9
  },
  {
    nor: "å arbitrere",
    eng: "to arbitrate",
    pl: "arbitrażować",
    ar: "يحكم",
    ger: "schlichten",
    lt: "arbitruoti",
    key: "10",
    norEgz: "Dommeren ble bedt om å arbitrere tvisten.",
    soundLink: "",
    wordId: 10
  },
  {
    nor: "å dekonstruere",
    eng: "to deconstruct",
    pl: "dekonstruować",
    ar: "تفكيك",
    ger: "dekonstruieren",
    lt: "dekonstruoti",
    key: "11",
    norEgz: "Hun prøvde å dekonstruere argumentet for å finne svakheter.",
    soundLink: "",
    wordId: 11
  },
  {
    nor: "en kjernefysikk",
    eng: "nuclear physics",
    pl: "fizyka jądrowa",
    ar: "فيزياء نووية",
    ger: "Kernphysik",
    lt: "branduolinė fizika",
    key: "12",
    norEgz: "Han studerer en kjernefysikk ved universitetet.",
    soundLink: "",
    wordId: 12
  },
  {
  nor: 'flekkvis',
  eng: 'patchy',
  pl: 'plamisty',
  ar: 'عرقي',
  ger: 'fleckig',
  lt: 'dėmėtas',
  key: '13',
  norEgz: 'Jakken hans er flekkvis farget.',
  soundLink: '',
  wordId: 13
  },
  {
  nor: 'nostalgisk',
  eng: 'nostalgic',
  pl: 'nostalgiczny',
  ar: 'حنين إلى الماضي',
  ger: 'nostalgisch',
  lt: 'nostalgiškas',
  key: '14',
  norEgz: 'Hun følte seg nostalgisk da hun besøkte hjembyen sin.',
  soundLink: '',
  wordId: 14
  },
  {
  nor: 'puritansk',
  eng: 'puritanical',
  pl: 'purytański',
  ar: 'متزمت',
  ger: 'puritanisch',
  lt: 'puritoniškas',
  key: '15',
  norEgz: 'Hans puritanske holdning tillot ingen feil.',
  soundLink: '',
  wordId: 15
  },
  {
  nor: 'reflektert',
  eng: 'reflective',
  pl: 'refleksyjny',
  ar: 'تأملي',
  ger: 'nachdenklich',
  lt: 'atsispindintis',
  key: '16',
  norEgz: 'Hun er en reflektert person.',
  soundLink: '',
  wordId: 16
  },
  {
  nor: 'retorisk',
  eng: 'rhetorical',
  pl: 'retoryczny',
  ar: 'بلاغي',
  ger: 'rhetorisch',
  lt: 'retorinis',
  key: '17',
  norEgz: 'Han stilte et retorisk spørsmål.',
  soundLink: '',
  wordId: 17
  },
  {
  nor: 'å differensiere',
  eng: 'to differentiate',
  pl: 'różnicować',
  ar: 'للتفريق',
  ger: 'differenzieren',
  lt: 'diferencijuoti',
  key: '18',
  norEgz: 'Vi må differensiere mellom de to begrepene.',
  soundLink: '',
  wordId: 18
  },
  {
  nor: 'å ekstrapolere',
  eng: 'to extrapolate',
  pl: 'ekstrapolować',
  ar: 'استقراء',
  ger: 'extrapolieren',
  lt: 'ekstrapoliuoti',
  key: '19',
  norEgz: 'Vi må ekstrapolere dataene for å lage en prognose.',
  soundLink: '',
  wordId: 19
  },
  {
  nor: 'å harmonisere',
  eng: 'to harmonize',
  pl: 'harmonizować',
  ar: 'توافق',
  ger: 'harmonisieren',
  lt: 'suderinti',
  key: '20',
  norEgz: 'De prøvde å harmonisere arbeidsrutinene.',
  soundLink: '',
  wordId: 20
  },
  {
  nor: 'et paradigme',
  eng: 'a paradigm',
  pl: 'paradygmat',
  ar: 'نموذج',
  ger: 'ein Paradigma',
  lt: 'paradigma',
  key: '21',
  norEgz: 'Dette konseptet er et paradigme for moderne forskning.',
  soundLink: '',
  wordId: 21
  },
  {
  nor: 'en syntese',
  eng: 'a synthesis',
  pl: 'synteza',
  ar: 'توليف',
  ger: 'eine Synthese',
  lt: 'sintezė',
  key: '22',
  norEgz: 'Vi må lage en syntese av disse ideene.',
  soundLink: '',
  wordId: 22
  },
  {
  nor: 'en dialektikk',
  eng: 'a dialectic',
  pl: 'dialektyka',
  ar: 'جدلية',
  ger: 'eine Dialektik',
  lt: 'dialektika',
  key: '23',
  norEgz: 'Dialektikken mellom motsetninger fører til utvikling.',
  soundLink: '',
  wordId: 23
  },
  {
  nor: 'paternalistisk',
  eng: 'paternalistic',
  pl: 'paternalistyczny',
  ar: 'أبوي',
  ger: 'paternalistisch',
  lt: 'paternalistinis',
  key: '24',
  norEgz: 'Hans paternalistiske holdning kan virke irriterende.',
  soundLink: '',
  wordId: 24
  },
  {
  nor: 'pluralistisk',
  eng: 'pluralistic',
  pl: 'pluralistyczny',
  ar: 'تعددي',
  ger: 'pluralistisch',
  lt: 'pluralistinis',
  key: '25',
  norEgz: 'Samfunnet vårt blir stadig mer pluralistisk.',
  soundLink: '',
  wordId: 25
  },
  {
  nor: 'pompøs',
  eng: 'pompous',
  pl: 'pompatyczny',
  ar: 'متكبر',
  ger: 'pompös',
  lt: 'pompiškas',
  key: '26',
  norEgz: 'Talen hans var pompøs og overdreven.',
  soundLink: '',
  wordId: 26
  },
  {
  nor: 'prosaisk',
  eng: 'prosaic',
  pl: 'prozaiczny',
  ar: 'عادي',
  ger: 'prosaisch',
  lt: 'proziškas',
  key: '27',
  norEgz: 'Beskrivelsen hennes var prosaisk og kjedelig.',
  soundLink: '',
  wordId: 27
  },
  {
  nor: 'metaforisk',
  eng: 'metaphorical',
  pl: 'metaforyczny',
  ar: 'مجازي',
  ger: 'metaphorisch',
  lt: 'metaforiškas',
  key: '28',
  norEgz: 'Hun brukte en metaforisk sammenligning for å forklare situasjonen.',
  soundLink: '',
  wordId: 28
  },
  {
  nor: 'å inkorporere',
  eng: 'to incorporate',
  pl: 'inkorporować',
  ar: 'لدمج',
  ger: 'inkorporieren',
  lt: 'inkorporuoti',
  key: '29',
  norEgz: 'Vi må inkorporere disse endringene i planene våre.',
  soundLink: '',
  wordId: 29
  },
  {
  nor: 'å karakterisere',
  eng: 'to characterize',
  pl: 'charakteryzować',
  ar: 'وصف',
  ger: 'charakterisieren',
  lt: 'charakterizuoti',
  key: '30',
  norEgz: 'Hun forsøkte å karakterisere situasjonen.',
  soundLink: '',
  wordId: 30
  },
  {
  nor: 'en selvtillit',
  eng: 'a self-confidence',
  pl: 'pewność siebie',
  ar: 'ثقة بالنفس',
  ger: 'ein Selbstvertrauen',
  lt: 'savigarba',
  key: '31',
  norEgz: 'Han har en høy selvtillit.',
  soundLink: '',
  wordId: 31
  },
  {
  nor: 'en demografi',
  eng: 'a demography',
  pl: 'demografia',
  ar: 'الديموغرافيا',
  ger: 'eine Demografie',
  lt: 'demografija',
  key: '32',
  norEgz: 'Studiet av demografi er viktig for samfunnsplanlegging.',
  soundLink: '',
  wordId: 32
  },
  {
  nor: 'en forfengelighet',
  eng: 'a vanity',
  pl: 'próżność',
  ar: 'غرور',
  ger: 'eine Eitelkeit',
  lt: 'tuštumas',
  key: '33',
  norEgz: 'Forfengelighet kan være en ulempe.',
  soundLink: '',
  wordId: 33
  },
  {
  nor: 'utilgjengelig',
  eng: 'unavailable',
  pl: 'niedostępny',
  ar: 'غير متاح',
  ger: 'nicht verfügbar',
  lt: 'neprieinamas',
  key: '34',
  norEgz: 'Ressursene er utilgjengelige på grunn av konflikten.',
  soundLink: '',
  wordId: 34
  },
  {
  nor: 'xenofobisk',
  eng: 'xenophobic',
  pl: 'ksenofobiczny',
  ar: 'كراهية الأجانب',
  ger: 'fremdenfeindlich',
  lt: 'ksenofobiškas',
  key: '35',
  norEgz: 'Xenofobiske holdninger er skadelige for samfunnet.',
  soundLink: '',
  wordId: 35
  },
  {
  nor: 'nihilistisk',
  eng: 'nihilistic',
  pl: 'nihilistyczny',
  ar: 'عدمي',
  ger: 'nihilistisch',
  lt: 'nihilistinis',
  key: '36',
  norEgz: 'Hans nihilistiske syn på livet gjorde ham ofte deprimert.',
  soundLink: '',
  wordId: 36
  },
  {
    nor: 'paradoksal',
    eng: 'paradoxical',
    pl: 'paradoksalny',
    ar: 'متناقض',
    ger: 'paradox',
    lt: 'paradoksalus',
    key: '37',
    norEgz: 'Denne situasjonen er paradoksal.',
    soundLink: '',
    wordId: 37
  },
  {
    nor: 'å objektivere',
    eng: 'to objectify',
    pl: 'uprzedmiotowić',
    ar: 'تجسيم',
    ger: 'objektivieren',
    lt: 'objektyvuoti',
    key: '38',
    norEgz: 'Han prøver å objektivere situasjonen.',
    soundLink: '',
    wordId: 38
  },
  {
    nor: 'å optimere',
    eng: 'to optimize',
    pl: 'optymalizować',
    ar: 'تحسين',
    ger: 'optimieren',
    lt: 'optimizuoti',
    key: '39',
    norEgz: 'Vi ønsker å optimere prosessen.',
    soundLink: '',
    wordId: 39
  },
  {
    nor: 'å postulere',
    eng: 'to postulate',
    pl: 'postulować',
    ar: 'استدعاء',
    ger: 'postulieren',
    lt: 'postuliuoti',
    key: '40',
    norEgz: 'Han postulerer at jorden er flat.',
    soundLink: '',
    wordId: 40
  },
  {
    nor: 'å redegjøre',
    eng: 'to explain',
    pl: 'wyjaśnić',
    ar: 'شرح',
    ger: 'erklären',
    lt: 'paaiškinti',
    key: '41',
    norEgz: 'Kan du redegjøre for dine handlinger?',
    soundLink: '',
    wordId: 41
  },
  {
    nor: 'en forræderi',
    eng: 'a betrayal',
    pl: 'zdrada',
    ar: 'خيانة',
    ger: 'ein Verrat',
    lt: 'išdavystė',
    key: '42',
    norEgz: 'Han begikk en forræderi mot sitt eget folk.',
    soundLink: '',
    wordId: 42
  },
  {
    nor: 'en fremmedgjøring',
    eng: 'alienation',
    pl: 'alienacja',
    ar: 'اغتراب',
    ger: 'Entfremdung',
    lt: 'atsvetimėjimas',
    key: '43',
    norEgz: 'Teknologi kan føre til fremmedgjøring.',
    soundLink: '',
    wordId: 43
  },
  {
    nor: 'en eksil',
    eng: 'an exile',
    pl: 'wygnanie',
    ar: 'منفى',
    ger: 'ein Exil',
    lt: 'tremtis',
    key: '44',
    norEgz: 'Forfatteren levde i eksil i mange år.',
    soundLink: '',
    wordId: 44
  },
  {
    nor: 'omnipotent',
    eng: 'omnipotent',
    pl: 'wszechmocny',
    ar: 'القادر على كل شيء',
    ger: 'allmächtig',
    lt: 'visagalis',
    key: '45',
    norEgz: 'Gud er ofte beskrevet som omnipotent.',
    soundLink: '',
    wordId: 45
  },
  {
    nor: 'patosfylt',
    eng: 'pathos-filled',
    pl: 'pełen patosu',
    ar: 'مليء بالعاطفة',
    ger: 'pathetisch',
    lt: 'pilnas patoso',
    key: '46',
    norEgz: 'Talen hans var patosfylt og rørende.',
    soundLink: '',
    wordId: 46
  },
  {
    nor: 'sublim',
    eng: 'sublime',
    pl: 'wzniosły',
    ar: 'سام',
    ger: 'erhaben',
    lt: 'sublimiškas',
    key: '47',
    norEgz: 'Landskapet her er virkelig sublim.',
    soundLink: '',
    wordId: 47
  },
  {
    nor: 'surrealistisk',
    eng: 'surrealistic',
    pl: 'surrealistyczny',
    ar: 'سريالي',
    ger: 'surrealistisch',
    lt: 'surrealistinis',
    key: '48',
    norEgz: 'Denne filmen har en surrealistisk atmosfære.',
    soundLink: '',
    wordId: 48
  },
  {
    nor: 'transcendental',
    eng: 'transcendental',
    pl: 'transcendentalny',
    ar: 'متعال',
    ger: 'transzendental',
    lt: 'transcendentinis',
    key: '49',
    norEgz: 'Meditasjon kan føre til en transcendental opplevelse.',
    soundLink: '',
    wordId: 49
  },
  {
    nor: 'en bevoktning',
    eng: 'a guarding',
    pl: 'straż',
    ar: 'حراسة',
    ger: 'eine Bewachung',
    lt: 'sargyba',
    key: '50',
    norEgz: 'Banken har døgnet rundt bevoktning.',
    soundLink: '',
    wordId: 50
  },
  {
    nor: 'å resonere',
    eng: 'to resonate',
    pl: 'rezonować',
    ar: 'يتردد',
    ger: 'resonieren',
    lt: 'rezonuoti',
    key: '51',
    norEgz: 'Hans ord resonerte med publikum.',
    soundLink: '',
    wordId: 51
  },
  {
    nor: 'å restrukturere',
    eng: 'to restructure',
    pl: 'restrukturyzować',
    ar: 'إعادة هيكلة',
    ger: 'umstrukturieren',
    lt: 'restruktūrizuoti',
    key: '52',
    norEgz: 'Selskapet må restrukturere for å overleve.',
    soundLink: '',
    wordId: 52
  },
  {
    nor: 'en erklæring',
    eng: 'a declaration',
    pl: 'oświadczenie',
    ar: 'إعلان',
    ger: 'eine Erklärung',
    lt: 'deklaracija',
    key: '53',
    norEgz: 'Han ga en offisiell erklæring om situasjonen.',
    soundLink: '',
    wordId: 53
  },
  {
    nor: 'en erkjennelse',
    eng: 'an acknowledgment',
    pl: 'uznanie',
    ar: 'اعتراف',
    ger: 'eine Anerkennung',
    lt: 'pripažinimas',
    key: '54',
    norEgz: 'Han kom fram til en viktig erkjennelse.',
    soundLink: '',
    wordId: 54
  },
  {
    nor: 'en erobring',
    eng: 'a conquest',
    pl: 'zdobycie',
    ar: 'غزو',
    ger: 'eine Eroberung',
    lt: 'užkariavimas',
    key: '55',
    norEgz: 'Romerriket hadde mange erobringer.',
    soundLink: '',
    wordId: 55
  },
  {
    nor: 'kvasivitenskapelig',
    eng: 'pseudoscientific',
    pl: 'pseudonaukowy',
    ar: 'زائف العلم',
    ger: 'pseudowissenschaftlich',
    lt: 'pseudo-mokslinis',
    key: '56',
    norEgz: 'Denne teorien er kvasivitenskapelig og upålitelig.',
    soundLink: '',
    wordId: 56
  },
  {
    nor: 'kverulerende',
    eng: 'querulous',
    pl: 'kłótliwy',
    ar: 'متشكي',
    ger: 'querulatorisch',
    lt: 'skundikas',
    key: '57',
    norEgz: 'Han har en kverulerende personlighet.',
    soundLink: '',
    wordId: 57
  },
  {
    nor: 'melankolsk',
    eng: 'melancholic',
    pl: 'melancholijny',
    ar: 'كئيب',
    ger: 'melancholisch',
    lt: 'melancholiškas',
    key: '59',
    norEgz: 'Hun følte seg melankolsk etter å ha sett filmen.',
    soundLink: '',
    wordId: 59
  },
  {
    nor: 'nihilistisk',
    eng: 'nihilistic',
    pl: 'nihilistyczny',
    ar: 'عقيدة العدمية',
    ger: 'nihilistisch',
    lt: 'nihilistinis',
    key: '60',
    norEgz: 'Hans nihilistiske syn på verden var forstyrrende.',
    soundLink: '',
    wordId: 60
  },
  {
    nor: 'å systematisere',
    eng: 'to systematize',
    pl: 'systematyzować',
    ar: 'تنظيم',
    ger: 'systematisieren',
    lt: 'sistematizuoti',
    key: '61',
    norEgz: 'Han prøvde å systematisere arbeidsprosessen.',
    soundLink: '',
    wordId: 61
  },
  {
    nor: 'å teoretisere',
    eng: 'to theorize',
    pl: 'teoretyzować',
    ar: 'يفسر نظريًا',
    ger: 'theoretisieren',
    lt: 'teoretizuoti',
    key: '62',
    norEgz: 'Forskere teoretiserer om mørk materie.',
    soundLink: '',
    wordId: 62
  },
  {
    nor: 'en avsky',
    eng: 'a disgust',
    pl: 'wstręt',
    ar: 'اشمئزاز',
    ger: 'ein Ekel',
    lt: 'pasibjaurėjimas',
    key: '63',
    norEgz: 'Hun følte avsky for den grusomme handlingen.',
    soundLink: '',
    wordId: 63
  },
  {
    nor: 'en avbetaling',
    eng: 'an installment',
    pl: 'rata',
    ar: 'قسط',
    ger: 'eine Rate',
    lt: 'įmoka',
    key: '64',
    norEgz: 'Han betalte for bilen i månedlige avdrag.',
    soundLink: '',
    wordId: 64
  },
  {
    nor: 'inkarnert',
    eng: 'incarnate',
    pl: 'wcielony',
    ar: 'متجسد',
    ger: 'inkarniert',
    lt: 'įkūnijęs',
    key: '65',
    norEgz: 'Han var ondskapen inkarnert.',
    soundLink: '',
    wordId: 65
  },
  {
    nor: 'irrasjonell',
    eng: 'irrational',
    pl: 'niedorzeczny',
    ar: 'غير عقلاني',
    ger: 'irrational',
    lt: 'neracionalus',
    key: '66',
    norEgz: 'Hans oppførsel var fullstendig irrasjonell.',
    soundLink: '',
    wordId: 66
  },
  {
    nor: 'juxtaposert',
    eng: 'juxtaposed',
    pl: 'sąsiadujący',
    ar: 'متوازي',
    ger: 'nebeneinander gestellt',
    lt: 'greta',
    key: '67',
    norEgz: 'Bildene var nøye juxtaposert for å skape kontrast.',
    soundLink: '',
    wordId: 67
  },
  {
    nor: 'katarsisk',
    eng: 'cathartic',
    pl: 'katharsis',
    ar: 'كاثارسي',
    ger: 'kathartisch',
    lt: 'katarinis',
    key: '68',
    norEgz: 'Opplevelsen var katarsisk for henne.',
    soundLink: '',
    wordId: 68
  },
  {
    nor: 'kosmopolitisk',
    eng: 'cosmopolitan',
    pl: 'kosmopolityczny',
    ar: 'كوزموبوليتي',
    ger: 'kosmopolitisch',
    lt: 'kosmopolitiškas',
    key: '69',
    norEgz: 'Byen har en kosmopolitisk atmosfære.',
    soundLink: '',
    wordId: 69
  },
  {
    nor: 'å visualisere',
    eng: 'to visualize',
    pl: 'wizualizować',
    ar: 'تصور',
    ger: 'visualisieren',
    lt: 'vaizduoti',
    key: '70',
    norEgz: 'Hun prøvde å visualisere resultatet av prosjektet.',
    soundLink: '',
    wordId: 70
  },
  {
    nor: 'å konsolidere',
    eng: 'to consolidate',
    pl: 'konsolidować',
    ar: 'توحيد',
    ger: 'konsolidieren',
    lt: 'konsoliduoti',
    key: '71',
    norEgz: 'Selskapet ønsker å konsolidere sin posisjon i markedet.',
    soundLink: '',
    wordId: 71
  },
  {
    nor: 'å abstrahere',
    eng: 'to abstract',
    pl: 'abstrahować',
    ar: 'تجريد',
    ger: 'abstrahieren',
    lt: 'abstrahuoti',
    key: '72',
    norEgz: 'Kunstneren forsøkte å abstrahere formene i maleriet.',
    soundLink: '',
    wordId: 72
  },
  {
    nor: 'å plausibilisere',
    eng: 'to make plausible',
    pl: 'uczynić wiarygodnym',
    ar: 'جعلها معقولة',
    ger: 'plausibel machen',
    lt: 'padaryti tikėtinu',
    key: '73',
    norEgz: 'Han forsøkte å plausibilisere sin historie.',
    soundLink: '',
    wordId: 73
  },
  {
    nor: 'en binær',
    eng: 'binary',
    pl: 'binarny',
    ar: 'ثنائي',
    ger: 'binär',
    lt: 'dvejetainis',
    key: '74',
    norEgz: 'Datamaskiner bruker et binært tallsystem.',
    soundLink: '',
    wordId: 74
  },
  {
    nor: 'en båndbredde',
    eng: 'bandwidth',
    pl: 'szerokość pasma',
    ar: 'عرض النطاق',
    ger: 'Bandbreite',
    lt: 'juosta',
    key: '75',
    norEgz: 'Vi trenger mer båndbredde for å streame videoen.',
    soundLink: '',
    wordId: 75
  },
  {
    nor: 'en avsked',
    eng: 'a farewell',
    pl: 'pożegnanie',
    ar: 'وداع',
    ger: 'ein Abschied',
    lt: 'atsisveikinimas',
    key: '76',
    norEgz: 'Dette er en avsked mellom gode venner.',
    soundLink: '',
    wordId: 76
  },
  {
    nor: 'filosofisk',
    eng: 'philosophical',
    pl: 'filozoficzny',
    ar: 'فلسفي',
    ger: 'philosophisch',
    lt: 'filosofinis',
    key: '77',
    norEgz: 'Han hadde en filosofisk tilnærming til livet.',
    soundLink: '',
    wordId: 77
  },
  {
    nor: 'hedonistisk',
    eng: 'hedonistic',
    pl: 'hedonistyczny',
    ar: 'هدوني',
    ger: 'hedonistisch',
    lt: 'hedonistinis',
    key: '78',
    norEgz: 'Hans hedonistiske livsstil førte til mange problemer.',
    soundLink: '',
    wordId: 78
  },
  {
    nor: 'hermetisk',
    eng: 'hermetic',
    pl: 'hermetyczny',
    ar: 'محكم',
    ger: 'hermetisch',
    lt: 'hermetiškas',
    key: '79',
    norEgz: 'Denne boksen er hermetisk forseglet.',
    soundLink: '',
    wordId: 79
  },
  {
    nor: 'idiosynkratisk',
    eng: 'idiosyncratic',
    pl: 'idiomatyczny',
    ar: 'متفرد',
    ger: 'idiosynkratisch',
    lt: 'idiosinkratinis',
    key: '80',
    norEgz: 'Hans idiosynkratiske stil skilte seg ut.',
    soundLink: '',
    wordId: 80
  },
  {
    nor: 'illusorisk',
    eng: 'illusory',
    pl: 'iluzoryczny',
    ar: 'وهمي',
    ger: 'illusorisch',
    lt: 'iliuzinis',
    key: '81',
    norEgz: 'Fremgangen viste seg å være illusorisk.',
    soundLink: '',
    wordId: 81
  },
  {
    nor: 'å kontemplere',
    eng: 'to contemplate',
    pl: 'kontemplować',
    ar: 'تأمل',
    ger: 'kontemplieren',
    lt: 'kontempliuoti',
    key: '82',
    norEgz: 'Han satt og kontemplerte livets mysterier.',
    soundLink: '',
    wordId: 82
  },
  {
    nor: 'en arvegang',
    eng: 'inheritance',
    pl: 'dziedziczenie',
    ar: 'وراثة',
    ger: 'Erbschaft',
    lt: 'paveldėjimas',
    key: '83',
    norEgz: 'Arvegangen i familien var komplisert.',
    soundLink: '',
    wordId: 83
  },
  {
    nor: 'en beplantning',
    eng: 'planting',
    pl: 'nasadzenia',
    ar: 'زراعة',
    ger: 'Bepflanzung',
    lt: 'auginimas',
    key: '84',
    norEgz: 'Beplantningen i hagen ser fantastisk ut.',
    soundLink: '',
    wordId: 84
  },
  {
    nor: 'epistemologisk',
    eng: 'epistemological',
    pl: 'epistemologiczny',
    ar: 'معرفي',
    ger: 'erkenntnistheoretisch',
    lt: 'epistemologinis',
    key: '85',
    norEgz: 'Epistemologisk forskning fokuserer på kunnskap og tro.',
    soundLink: '',
    wordId: 85
  },
  {
    nor: 'eufemistisk',
    eng: 'euphemistic',
    pl: 'eufemistyczny',
    ar: 'تهجير الكلمات',
    ger: 'euphemistisch',
    lt: 'eufemistiškas',
    key: '86',
    norEgz: 'Han brukte et eufemistisk uttrykk for å beskrive situasjonen.',
    soundLink: '',
    wordId: 86
  },
  {
    nor: 'eksplicit',
    eng: 'explicit',
    pl: 'wyraźny',
    ar: 'صريح',
    ger: 'explizit',
    lt: 'aiškus',
    key: '87',
    norEgz: 'Instruksjonene var eksplicitte og klare.',
    soundLink: '',
    wordId: 87
  },
  {
    nor: 'implisitt',
    eng: 'implicit',
    pl: 'domniemany',
    ar: 'ضمني',
    ger: 'implizit',
    lt: 'neišreikštas',
    key: '88',
    norEgz: 'Hans implisitte forståelse var tydelig.',
    soundLink: '',
    wordId: 88
  },
  {
    nor: 'å besitte',
    eng: 'to possess',
    pl: 'posiadać',
    ar: 'امتلك',
    ger: 'besitzen',
    lt: 'turėti',
    key: '89',
    norEgz: 'Han besitter en sjelden samling mynter.',
    soundLink: '',
    wordId: 89
  },
  {
    nor: 'å meditere',
    eng: 'to meditate',
    pl: 'medytować',
    ar: 'تأمل',
    ger: 'meditieren',
    lt: 'medituoti',
    key: '90',
    norEgz: 'Hun liker å meditere hver morgen.',
    soundLink: '',
    wordId: 90
  },
  {
    nor: 'å revidere',
    eng: 'to revise',
    pl: 'zrewidować',
    ar: 'تنقيح',
    ger: 'revidieren',
    lt: 'peržiūrėti',
    key: '91',
    norEgz: 'Vi må revidere planene våre.',
    soundLink: '',
    wordId: 91
  },
  {
    nor: 'en antropologi',
    eng: 'anthropology',
    pl: 'antropologia',
    ar: 'علم الإنسان',
    ger: 'Anthropologie',
    lt: 'antropologija',
    key: '92',
    norEgz: 'Hun studerer antropologi ved universitetet.',
    soundLink: '',
    wordId: 92
  },
  {
    nor: 'en etnografi',
    eng: 'ethnography',
    pl: 'etnografia',
    ar: 'الإثنوغرافيا',
    ger: 'Ethnographie',
    lt: 'etnografija',
    key: '93',
    norEgz: 'Etnografi er en viktig metode i antropologi.',
    soundLink: '',
    wordId: 93
  },
  {
    nor: 'despotisk',
    eng: 'despotic',
    pl: 'despotyczny',
    ar: 'ديكتاتوري',
    ger: 'despotisch',
    lt: 'despotiškas',
    key: '94',
    norEgz: 'Hans despotiske styre førte til opprør.',
    soundLink: '',
    wordId: 94
  },
  {
    nor: 'dissonant',
    eng: 'dissonant',
    pl: 'dyskordantny',
    ar: 'غير متناسق',
    ger: 'dissonant',
    lt: 'nesuderintas',
    key: '95',
    norEgz: 'Musikken var dissonant og forvirrende.',
    soundLink: '',
    wordId: 95
  },
  {
    nor: 'dogmefri',
    eng: 'dogma-free',
    pl: 'wolny od dogmatów',
    ar: 'خال من العقائد',
    ger: 'dogmenfrei',
    lt: 'be dogmų',
    key: '96',
    norEgz: 'Han foretrakk en dogmefri tilnærming til religion.',
    soundLink: '',
    wordId: 96
  },
  {
    nor: 'eksistensiell',
    eng: 'existential',
    pl: 'egzystencjalny',
    ar: 'وجودي',
    ger: 'existenziell',
    lt: 'egzistencinis',
    key: '97',
    norEgz: 'Eksistensiell krise påvirker mange mennesker.',
    soundLink: '',
    wordId: 97
  },
  {
    nor: 'enigmatisk',
    eng: 'enigmatic',
    pl: 'enigmatyczny',
    ar: 'غامض',
    ger: 'rätselhaft',
    lt: 'paslaptingas',
    key: '98',
    norEgz: 'Hun hadde et enigmatisk smil.',
    soundLink: '',
    wordId: 98
  },
  {
    nor: 'å synkronisere',
    eng: 'to synchronize',
    pl: 'synchronizować',
    ar: 'مزامنة',
    ger: 'synchronisieren',
    lt: 'sinchronizuoti',
    key: '99',
    norEgz: 'Vi må synkronisere klokkene våre.',
    soundLink: '',
    wordId: 99
  },
  {
    nor: 'å delegere',
    eng: 'to delegate',
    pl: 'delegować',
    ar: 'تفويض',
    ger: 'delegieren',
    lt: 'deleguoti',
    key: '100',
    norEgz: 'Han må delegere oppgaver til teamet sitt.',
    soundLink: '',
    wordId: 100
  },
  {
    nor: 'å eliminere',
    eng: 'to eliminate',
    pl: 'eliminować',
    ar: 'استبعاد',
    ger: 'eliminieren',
    lt: 'eliminuoti',
    key: '101',
    norEgz: 'Vi må eliminere feilene i systemet.',
    soundLink: '',
    wordId: 101
  },
  {
    nor: 'en subversjon',
    eng: 'subversion',
    pl: 'subwersja',
    ar: 'تخريب',
    ger: 'Subversion',
    lt: 'subversija',
    key: '102',
    norEgz: 'Subversjon kan føre til politisk ustabilitet.',
    soundLink: '',
    wordId: 102
  },
  {
    nor: 'en enklave',
    eng: 'enclave',
    pl: 'enklawa',
    ar: 'مقاطعة',
    ger: 'Enklave',
    lt: 'enklavas',
    key: '103',
    norEgz: 'En enklave er et landområde omgitt av et annet land.',
    soundLink: '',
    wordId: 103
  },
  {
    nor: 'asketisk',
    eng: 'ascetic',
    pl: 'ascetyczny',
    ar: 'زاهد',
    ger: 'asketisch',
    lt: 'asketiškas',
    key: '104',
    norEgz: 'Han levde et asketisk liv i klosteret.',
    soundLink: '',
    wordId: 104
  },
  {
    nor: 'axiomatisk',
    eng: 'axiomatic',
    pl: 'aksjomatyczny',
    ar: 'ذاتي البيان',
    ger: 'axiomatisch',
    lt: 'aksiomatinis',
    key: '105',
    norEgz: 'Noen prinsipper er axiomatiske i matematikk.',
    soundLink: '',
    wordId: 105
  },
  {
    nor: 'bestialsk',
    eng: 'bestial',
    pl: 'bestialski',
    ar: 'وحشي',
    ger: 'bestialisch',
    lt: 'žvėriškas',
    key: '106',
    norEgz: 'Hans bestialske oppførsel skremte alle.',
    soundLink: '',
    wordId: 106
  },
  {
    nor: 'å formulere',
    eng: 'to formulate',
    pl: 'sformułować',
    ar: 'صياغة',
    ger: 'formulieren',
    lt: 'formuluoti',
    key: '107',
    norEgz: 'Han prøver å formulere en ny teori.',
    soundLink: '',
    wordId: 107
  },
  {
    nor: 'å fortolke',
    eng: 'to interpret',
    pl: 'interpretować',
    ar: 'تفسير',
    ger: 'interpretieren',
    lt: 'interpretuoti',
    key: '108',
    norEgz: 'Vi må fortolke dataene nøye.',
    soundLink: '',
    wordId: 108
  },
  {
    nor: 'å innovere',
    eng: 'to innovate',
    pl: 'innowować',
    ar: 'ابتكار',
    ger: 'innovieren',
    lt: 'inovuoti',
    key: '109',
    norEgz: 'Bedriften vår må innovere for å være konkurransedyktig.',
    soundLink: '',
    wordId: 109
  },
  {
    nor: 'en artikulasjon',
    eng: 'articulation',
    pl: 'artykulacja',
    ar: 'مفصل',
    ger: 'Artikulation',
    lt: 'artikuliacija',
    key: '110',
    norEgz: 'Hans artikulasjon var tydelig og presis.',
    soundLink: '',
    wordId: 110
  },
  {
    nor: 'abnorm',
    eng: 'abnormal',
    pl: 'nienormalny',
    ar: 'غير طبيعي',
    ger: 'anormal',
    lt: 'neįprastas',
    key: '111',
    norEgz: 'De oppdaget en abnorm vekst på røntgenbildet.',
    soundLink: '',
    wordId: 111
  },
  {
    nor: 'amorf',
    eng: 'amorphous',
    pl: 'amorficzny',
    ar: 'غير متبلور',
    ger: 'amorph',
    lt: 'amorfinis',
    key: '112',
    norEgz: 'Amorf materiale mangler krystallinsk struktur.',
    soundLink: '',
    wordId: 112
  },
  {
    nor: 'antiklimaktisk',
    eng: 'anticlimactic',
    pl: 'rozczarowujący',
    ar: 'مُقَلّب',
    ger: 'antiklimaktisch',
    lt: 'nuviliantis',
    key: '113',
    norEgz: 'Avslutningen på boken var antiklimaktisk.',
    soundLink: '',
    wordId: 113
  },
  {
    nor: 'å erverve',
    eng: 'to acquire',
    pl: 'nabyć',
    ar: 'اكتساب',
    ger: 'erwerben',
    lt: 'įsigyti',
    key: '114',
    norEgz: 'De prøver å erverve en ny eiendom.',
    soundLink: '',
    wordId: 114
  },
  {
    nor: 'å standardisere',
    eng: 'to standardize',
    pl: 'standaryzować',
    ar: 'توحيد المعايير',
    ger: 'standardisieren',
    lt: 'standartizuoti',
    key: '115',
    norEgz: 'Vi må standardisere prosessene våre.',
    soundLink: '',
    wordId: 115
  },
  {
    nor: 'en askese',
    eng: 'asceticism',
    pl: 'ascetyzm',
    ar: 'الزهد',
    ger: 'Askese',
    lt: 'asketizmas',
    key: '116',
    norEgz: 'Mange munke praktiserer askese.',
    soundLink: '',
    wordId: 116
  },
  {
    nor: 'å transformere',
    eng: 'to transform',
    pl: 'przekształcić',
    ar: 'تحويل',
    ger: 'transformieren',
    lt: 'transformuoti',
    key: '117',
    norEgz: 'Hun ønsker å transformere selskapets kultur.',
    soundLink: '',
    wordId: 117
  },
  {
    nor: 'å validere',
    eng: 'to validate',
    pl: 'walidować',
    ar: 'التحقق من صحة',
    ger: 'validieren',
    lt: 'validuoti',
    key: '118',
    norEgz: 'Vi trenger å validere disse resultatene.',
    soundLink: '',
    wordId: 118
  },
  {
    nor: 'en volatilitet',
    eng: 'volatility',
    pl: 'zmienność',
    ar: 'تقلب',
    ger: 'Volatilität',
    lt: 'volatilumas',
    key: '119',
    norEgz: 'Markedet har vist stor volatilitet denne uken.',
    soundLink: '',
    wordId: 119
  },
  {
    nor: 'veltalende',
    eng: 'eloquent',
    pl: 'elokwentny',
    ar: 'بليغ',
    ger: 'redegewandt',
    lt: 'iškalbingas',
    key: '120',
    norEgz: 'Han er en veltalende talsmann.',
    soundLink: '',
    wordId: 120
  },
  {
    nor: 'viljesterk',
    eng: 'strong-willed',
    pl: 'silnowolny',
    ar: 'عنيد',
    ger: 'willensstark',
    lt: 'valingas',
    key: '121',
    norEgz: 'Hun er en viljesterk person.',
    soundLink: '',
    wordId: 121
  },
  {
    nor: 'virtuell',
    eng: 'virtual',
    pl: 'wirtualny',
    ar: 'افتراضي',
    ger: 'virtuell',
    lt: 'virtualus',
    key: '122',
    norEgz: 'Vi deltok i en virtuell konferanse.',
    soundLink: '',
    wordId: 122
  },
  {
    nor: 'ytterliggående',
    eng: 'extreme',
    pl: 'skrajny',
    ar: 'متطرف',
    ger: 'extrem',
    lt: 'kraštutinis',
    key: '123',
    norEgz: 'Han har ytterliggående synspunkter.',
    soundLink: '',
    wordId: 123
  },
  {
    nor: 'å reevaluere',
    eng: 'to reevaluate',
    pl: 'przeocenić',
    ar: 'إعادة التقييم',
    ger: 'neu bewerten',
    lt: 'pervertinti',
    key: '124',
    norEgz: 'Vi må reevaluere strategien vår.',
    soundLink: '',
    wordId: 124
  },
  {
    nor: 'å rekonstruere',
    eng: 'to reconstruct',
    pl: 'rekonstruować',
    ar: 'إعادة بناء',
    ger: 'rekonstruieren',
    lt: 'rekonstruoti',
    key: '125',
    norEgz: 'De må rekonstruere broen etter ulykken.',
    soundLink: '',
    wordId: 125
  },
  {
    nor: 'kynisk',
    eng: 'cynical',
    pl: 'cyniczny',
    ar: 'ساخر',
    ger: 'zynisch',
    lt: 'ciniškas',
    key: '126',
    norEgz: 'Han hadde et kynisk smil om munnen.',
    soundLink: '',
    wordId: 126
  },
  {
    nor: 'uforutsigbar',
    eng: 'unpredictable',
    pl: 'nieprzewidywalny',
    ar: 'غير قابل للتنبؤ',
    ger: 'unvorhersehbar',
    lt: 'neprognozuojamas',
    key: '127',
    norEgz: 'Været her er ganske uforutsigbart.',
    soundLink: '',
    wordId: 127
  },
  {
    nor: 'uortodoks',
    eng: 'unorthodox',
    pl: 'nieortodoksyjny',
    ar: 'غير تقليدي',
    ger: 'unorthodox',
    lt: 'neortodoksinis',
    key: '128',
    norEgz: 'Hans uortodokse metoder har skapt kontrovers.',
    soundLink: '',
    wordId: 128
  },
  {
    nor: 'å konseptualisere',
    eng: 'to conceptualize',
    pl: 'konceptualizować',
    ar: 'تصور',
    ger: 'konzeptualisieren',
    lt: 'konceptualizuoti',
    key: '129',
    norEgz: 'Vi prøver å konseptualisere en ny forretningsmodell.',
    soundLink: '',
    wordId: 129
  },
  {
    nor: 'å manifestere',
    eng: 'to manifest',
    pl: 'manifestować',
    ar: 'تجلي',
    ger: 'manifestieren',
    lt: 'manifestuoti',
    key: '130',
    norEgz: 'Kunstneren prøver å manifestere sin visjon.',
    soundLink: '',
    wordId: 130
  },
  {
    nor: 'en avholdenhet',
    eng: 'an abstinence',
    pl: 'wstrzemięźliwość',
    ar: 'امتناع',
    ger: 'eine Enthaltsamkeit',
    lt: 'susilaikymas',
    key: '131',
    norEgz: 'Han praktiserer en avholdenhet fra alkohol.',
    soundLink: '',
    wordId: 131
  },
  {
    nor: 'en avskaffelse',
    eng: 'an abolition',
    pl: 'zniesienie',
    ar: 'إلغاء',
    ger: 'eine Abschaffung',
    lt: 'panaikinimas',
    key: '132',
    norEgz: 'Avskaffelsen av slaveri var et viktig skritt.',
    soundLink: '',
    wordId: 132
  },
  {
    nor: 'en antakelse',
    eng: 'an assumption',
    pl: 'założenie',
    ar: 'افتراض',
    ger: 'eine Annahme',
    lt: 'prielaida',
    key: '133',
    norEgz: 'Vi baserer dette på en antakelse om økonomisk vekst.',
    soundLink: '',
    wordId: 133
  },
  {
    nor: 'en bevilling',
    eng: 'an allocation',
    pl: 'przydział',
    ar: 'تخصيص',
    ger: 'eine Zuteilung',
    lt: 'skirtis',
    key: '134',
    norEgz: 'Kommunen fikk en bevilling til nytt utstyr.',
    soundLink: '',
    wordId: 134
  },
  {
    nor: 'futuristisk',
    eng: 'futuristic',
    pl: 'futurystyczny',
    ar: 'مستقبلي',
    ger: 'futuristisch',
    lt: 'futuristiškas',
    key: '135',
    norEgz: 'Arkitekturen på bygningen er svært futuristisk.',
    soundLink: '',
    wordId: 135
  },
  {
    nor: 'hierarkisk',
    eng: 'hierarchical',
    pl: 'hierarchiczny',
    ar: 'هرمي',
    ger: 'hierarchisch',
    lt: 'hierarchinis',
    key: '136',
    norEgz: 'Bedriften har en hierarkisk struktur.',
    soundLink: '',
    wordId: 136
  },
  {
    nor: 'inkonsekvent',
    eng: 'inconsistent',
    pl: 'niespójny',
    ar: 'غير متسق',
    ger: 'inkonsistent',
    lt: 'nenuoseklus',
    key: '137',
    norEgz: 'Hans historie virker inkonsekvent og usammenhengende.',
    soundLink: '',
    wordId: 137
  }




]