export default dataObj = [
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description',
    level: 'A1',
    link: 'Exc1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Sceond thing',
    description: 'here is some description 2',
    level: 'A1',
    link: 'Exc1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Third thing',
    description: 'here is some description 3',
    level: 'A1',
    link: 'Exc1x3x1',
    key: 3,
    showPro: false,
   },
    {
    title: 'Fourth thing',
    description: 'here is some description 4',
    level: 'A1',
    link: 'Exc1x4x1',
    key: 4,
    showPro: true,
   },
    {
    title: 'Fifth thing',
    description: 'here is some description 5',
    level: 'A1',
    link: 'Exc1x5x1',
    key: 5,
    showPro: true,
   },
   {
    title: '6 thing',
    description: 'here is some description',
    level: 'A1',
    link: 'Exc1x6x1',
    key: 6,
    showPro: true,
   },
    {
    title: '7 thing',
    description: 'here is some description 2',
    level: 'A1',
    link: 'Exc1x7x1',
    key: 7,
    showPro: true,
   },
    {
    title: '8 thing',
    description: 'here is some description 3',
    level: 'A1',
    link: 'Exc1x8x1',
    key: 8,
    showPro: true,
   },
    {
    title: '9 thing',
    description: 'here is some description 4',
    level: 'A1',
    link: 'Exc1x9x1',
    key: 9,
    showPro: true,
   },
    {
    title: 'Fifth thing',
    description: 'here is some description 5',
    level: 'A1',
    link: '',
    key: 10,
    showPro: true,
   },
];