export default dataObj = [
    {
    title: 'First thing',
    description: 'here is some description',
    level: 'A1',
    link: 'Exc1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Sceond thing',
    description: 'here is some description 2',
    level: 'A1',
    link: 'Exc1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Third thing',
    description: 'here is some description 3',
    level: 'A1',
    link: '',
    key: 3,
    showPro: false,
   },
    {
    title: 'Fourth thing',
    description: 'here is some description 4',
    level: 'A1',
    link: '',
    key: 4,
    showPro: true,
   },
    {
    title: 'Fifth thing',
    description: 'here is some description 5',
    level: 'A1',
    link: '',
    key: 5,
    showPro: true,
   },
   {
    title: 'First thing',
    description: 'here is some description',
    level: 'A1',
    link: '',
    key: 6,
    showPro: true,
   },
    {
    title: 'Sceond thing',
    description: 'here is some description 2',
    level: 'A1',
    link: '',
    key: 7,
    showPro: true,
   },
    {
    title: 'Third thing',
    description: 'here is some description 3',
    level: 'A1',
    link: '',
    key: 8,
    showPro: true,
   },
    {
    title: 'Fourth thing',
    description: 'here is some description 4',
    level: 'A1',
    link: '',
    key: 9,
    showPro: true,
   },
    {
    title: 'Fifth thing',
    description: 'here is some description 5',
    level: 'A1',
    link: '',
    key: 10,
    showPro: true,
   },
];