[
    {
        nor: 'Hei!',
        eng: 'Hello!',
        pl: 'Cześć!',
        ar: 'مرحبًا!',
        ger: 'Hallo!',
        lt: 'Labas!',
        ua: 'Привіт!',
        sp: '¡Hola!',
        key: '0',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhei.mp3?alt=media&token=3f211e07-a57a-439e-98fd-9ef3a608d6fa',
        wordId: 0
    },
    {
        nor: 'God morgen',
        eng: 'Good morning',
        pl: 'Dzień dobry',
        ar: 'صباح الخير',
        ger: 'Guten Morgen',
        lt: 'Labas rytas',
        ua: 'Доброго ранку',
        sp: 'Buenos días',
        key: '1',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgodmorgen.mp3?alt=media&token=85b734d1-7269-49bb-83fa-99d17e0596ed',
        wordId: 1
    },
    {
        nor: 'God ettermiddag',
        eng: 'Good afternoon',
        pl: 'Dzień dobry',
        ar: 'مساء الخير',
        ger: 'Guten Tag',
        lt: 'Labą dieną',
        ua: 'Доброго дня',
        sp: 'Buenas tardes',
        key: '2',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgodettermiddag.mp3?alt=media&token=c0bb179f-cdaa-41d7-9d54-5cbce08b48e7',
        wordId: 2
    },
    {
        nor: 'God kveld',
        eng: 'Good evening',
        pl: 'Dobry wieczór',
        ar: 'مساء الخير',
        ger: 'Guten Abend',
        lt: 'Labas vakaras',
        ua: 'Добрий вечір',
        sp: 'Buenas noches',
        key: '3',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgodkveld.mp3?alt=media&token=6577d734-b9dd-4019-98b2-b3898add8b6a',
        wordId: 3
    },
    {
        nor: 'God natt',
        eng: 'Good night',
        pl: 'Dobranoc',
        ar: 'تصبح على خير',
        ger: 'Gute Nacht',
        lt: 'Labos nakties',
        ua: 'Добраніч',
        sp: 'Buenas noches',
        key: '4',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgodnatt.mp3?alt=media&token=7d57ba64-41af-4c11-a983-6e9044bc0810',
        wordId: 4
    },
    {
        nor: 'Ha det bra',
        eng: 'Goodbye',
        pl: 'Do widzenia',
        ar: 'وداعًا',
        ger: 'Auf Wiedersehen',
        lt: 'Viso gero',
        ua: 'До побачення',
        sp: 'Adiós',
        key: '5',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhadetbra.mp3?alt=media&token=ccb2e7be-a23e-41dd-9f55-6106f86b512a',
        wordId: 5
    },
    {
        nor: 'Takk',
        eng: 'Thank you',
        pl: 'Dziękuję',
        ar: 'شكرا',
        ger: 'Danke',
        lt: 'Ačiū',
        ua: 'Дякую',
        sp: 'Gracias',
        key: '6',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fextakk.mp3?alt=media&token=33dae24a-013b-48aa-9d5b-7039dcda3788',
        wordId: 6
    },
    {
        nor: 'Vær så snill',
        eng: 'Please',
        pl: 'Proszę',
        ar: 'من فضلك',
        ger: 'Bitte',
        lt: 'Prašau',
        ua: 'Будь ласка',
        sp: 'Por favor',
        key: '7',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexveersaasnill.mp3?alt=media&token=8ea486dd-aa11-4d5d-8442-38a88e2cd719',
        wordId: 7
    },
    {
        nor: 'Unnskyld',
        eng: 'Sorry',
        pl: 'Przepraszam',
        ar: 'آسف',
        ger: 'Entschuldigung',
        lt: 'Atsiprašau',
        ua: 'Вибачте',
        sp: 'Lo siento',
        key: '8',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexunnskyld.mp3?alt=media&token=d99d184f-3de5-4c75-9893-296aa3d81eb0',
        wordId: 8
    },
    {
        nor: 'Ingen årsak',
        eng: 'You are welcome',
        pl: 'Nie ma za co',
        ar: 'عفوًا',
        ger: 'Gern geschehen',
        lt: 'Prašau',
        ua: 'Будь ласка',
        sp: 'De nada',
        key: '9',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexingenaarsak.mp3?alt=media&token=46dd1124-c224-4b18-a1e5-ae4af6526233',
        wordId: 9
    },
    {
        nor: 'Hva heter du?',
        eng: 'What is your name?',
        pl: 'Jak masz na imię?',
        ar: 'ما اسمك؟',
        ger: 'Wie heißt du?',
        lt: 'Kuo tu vardu?',
        ua: 'Як тебе звати?',
        sp: '¿Cómo te llamas?',
        key: '10',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvaheterdu.mp3?alt=media&token=ea0e520d-40f3-441d-86ba-2a55365bfcfd',
        wordId: 10
    },
    {
        nor: 'Jeg heter ...',
        eng: 'My name is ...',
        pl: 'Nazywam się ...',
        ar: 'اسمي هو ...',
        ger: 'Ich heiße ...',
        lt: 'Mano vardas yra ...',
        ua: 'Мене звуть ...',
        sp: 'Mi nombre es ...',
        key: '11',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjjegheter.mp3?alt=media&token=7425e3ce-f1bf-4ec6-ade5-486f9f8163cf',
        wordId: 11
    },
    {
        nor: 'Hvordan går det?',
        eng: 'How are you?',
        pl: 'Jak się masz?',
        ar: 'كيف حالك؟',
        ger: 'Wie geht es dir?',
        lt: 'Kaip sekasi?',
        ua: 'Як справи?',
        sp: '¿Cómo estás?',
        key: '12',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvordangaardet.mp3?alt=media&token=2ed0740e-23d4-463d-a6aa-0ec8b5c6cfc8',
        wordId: 12
    },
    {
        nor: 'Det går bra',
        eng: 'It is going well',
        pl: 'Wszystko idzie dobrze',
        ar: 'الأمور تسير جيدًا',
        ger: 'Es geht gut',
        lt: 'Viskas gerai',
        ua: 'Все йде добре',
        sp: 'Va bien',
        key: '13',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexdetgaarbra.mp3?alt=media&token=a09f2384-8f07-4cd3-bf2c-2e680693b888',
        wordId: 13
    },
    {
        nor: 'Det går dårlig',
        eng: 'It is going poorly',
        pl: 'Idzie źle',
        ar: 'الأمور لا تسير على ما يُرام',
        ger: 'Es geht schlecht',
        lt: 'Viskas blogai',
        ua: 'Все йде погано',
        sp: 'Va mal',
        key: '14',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexdetgaardaarlig.mp3?alt=media&token=02dd648c-288b-4611-ae89-8b2bb2092d32',
        wordId: 14
    },
    {
        nor: 'Hvor er ...?',
        eng: 'Where is ...?',
        pl: 'Gdzie jest ...?',
        ar: 'أين هو ...؟',
        ger: 'Wo ist ...?',
        lt: 'Kur yra ...?',
        ua: 'Де ...?',
        sp: '¿Dónde está ...?',
        key: '15',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorer.mp3?alt=media&token=3b05707d-63bc-43db-9b77-d9a75a7b3c73',
        wordId: 15
    },
    {
        nor: 'Hvor gammel er du?',
        eng: 'How old are you?',
        pl: 'Ile masz lat?',
        ar: 'كم عمرك؟',
        ger: 'Wie alt bist du?',
        lt: 'Kiek tau metų?',
        ua: 'Скільки тобі років?',
        sp: '¿Cuántos años tienes?',
        key: '16',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorgammelerdu.mp3?alt=media&token=2d62c9ae-717d-44ee-bcff-083f0fdad172',
        wordId: 16
    },
    {
        nor: 'Jeg er tretti år gammel',
        eng: 'I am thirty years old',
        pl: 'Mam trzydzieści lat',
        ar: 'عمري ثلاثون عامًا',
        ger: 'Ich bin dreißig Jahre alt',
        lt: 'Man trisdešimt metų',
        ua: 'Мені тридцять років',
        sp: 'Tengo treinta años',
        key: '17',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegeraargamme.mp3?alt=media&token=c3086ba1-1f4c-4fde-99c3-5bf3185cc5fe',
        wordId: 17
    },
    {
        nor: 'Hva er klokka?',
        eng: 'What time is it?',
        pl: 'Która jest godzina?',
        ar: 'كم الساعة؟',
        ger: 'Wie spät ist es?',
        lt: 'Kiek valandų?',
        ua: 'Скільки година?',
        sp: '¿Qué hora es?',
        key: '18',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvaerklokka.mp3?alt=media&token=0a1e5a50-0fcc-4778-bb22-f8f82c31b0ba',
        wordId: 18
    },
    {
        nor: 'Hvor mye koster det?',
        eng: 'How much does it cost?',
        pl: 'Ile to kosztuje?',
        ar: 'بكم هذا؟',
        ger: 'Wie viel kostet das?',
        lt: 'Kiek tai kainuoja?',
        ua: 'Скільки це коштує?',
        sp: '¿Cuánto cuesta?',
        key: '19',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvormyekosterdet.mp3?alt=media&token=34dfdf22-f0a2-464d-9ff2-cb3200d2f8e5',
        wordId: 19
    },
    {
        nor: 'Jeg vil gjerne ha ...',
        eng: 'I would like ...',
        pl: 'Chciałbym ...',
        ar: 'أود ...',
        ger: 'Ich möchte ...',
        lt: 'Aš norėčiau ...',
        ua: 'Я б хотів ...',
        sp: 'Me gustaría ...',
        key: '20',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegvilgjerneha.mp3?alt=media&token=860dc4ee-bf41-4e14-864c-3d323f1cc1e0',
        wordId: 20
    },
    {
        nor: 'Kan du hjelpe meg?',
        eng: 'Can you help me?',
        pl: 'Czy możesz mi pomóc?',
        ar: 'هل يمكنك مساعدتي؟',
        ger: 'Können Sie mir helfen?',
        lt: 'Ar galite man padėti?',
        ua: 'Ви можете мені допомогти?',
        sp: '¿Puedes ayudarme?',
        key: '21',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexkanduhjelpemeg.mp3?alt=media&token=c4334e7b-020f-4ed2-abca-b30d5b506ef1',
        wordId: 21
    },
    {
        nor: 'Snakker du engelsk?',
        eng: 'Do you speak English?',
        pl: 'Czy mówisz po angielsku?',
        ar: 'هل تتحدث الإنجليزية؟',
        ger: 'Sprichst du Englisch?',
        lt: 'Ar kalbate angliškai?',
        ua: 'Ви розмовляєте англійською?',
        sp: '¿Hablas inglés?',
        key: '22',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexsnakkerduengelsk.mp3?alt=media&token=febda677-b74d-47a4-896c-5bde429a3ca6',
        wordId: 22
    },
    {
        nor: 'Jeg forstår ikke',
        eng: 'I don’t understand',
        pl: 'Nie rozumiem',
        ar: 'لا أفهم',
        ger: 'Ich verstehe nicht',
        lt: 'Aš nesuprantu',
        ua: 'Я не розумію',
        sp: 'No entiendo',
        key: '23',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegforstaarikke.mp3?alt=media&token=38955284-c820-4857-8948-ee7b316d8db5',
        wordId: 23
    },
    {
        nor: 'Kan du snakke saktere?',
        eng: 'Can you speak slower?',
        pl: 'Czy możesz mówić wolniej?',
        ar: 'هل يمكنك التحدث ببطء أكثر؟',
        ger: 'Können Sie langsamer sprechen?',
        lt: 'Ar galite kalbėti lėčiau?',
        ua: 'Ви можете говорити повільніше?',
        sp: '¿Puedes hablar más despacio?',
        key: '24',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexkandusnakkesaktere.mp3?alt=media&token=95b137ac-30b3-4abb-8986-a07bee23cb66',
        wordId: 24
    },
    {
        nor: 'Venstre',
        eng: 'Left',
        pl: 'Lewo',
        ar: 'يسار',
        ger: 'Links',
        lt: 'Kairė',
        ua: 'Ліворуч',
        sp: 'Izquierda',
        key: '25',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexvenstre.mp3?alt=media&token=5891c7c3-02c2-47a0-bd28-229fa3542eb6',
        wordId: 25
    },
    {
        nor: 'Høyre',
        eng: 'Right',
        pl: 'Prawo',
        ar: 'يمين',
        ger: 'Rechts',
        lt: 'Dešinė',
        ua: 'Праворуч',
        sp: 'Derecha',
        key: '26',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhooyre.mp3?alt=media&token=46e8b028-7808-48f9-8cd9-b18077c3f07d',
        wordId: 26
    },
    {
        nor: 'Rett fram',
        eng: 'Straight ahead',
        pl: 'Prosto',
        ar: 'مستقيم',
        ger: 'Geradeaus',
        lt: 'Tiesiai',
        ua: 'Прямо',
        sp: 'Recto',
        key: '27',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexrettfram.mp3?alt=media&token=258836af-95aa-436a-ae7e-191c90b4d1b4',
        wordId: 27
    },
    {
        nor: 'Hjelp!',
        eng: 'Help!',
        pl: 'Pomocy!',
        ar: 'مساعدة!',
        ger: 'Hilfe!',
        lt: 'Pagalba!',
        ua: 'Допоможіть!',
        sp: '¡Ayuda!',
        key: '28',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhjelp.mp3?alt=media&token=f077dcbc-0c96-4d2a-a088-0616160b2c98',
        wordId: 28
    },
    {
        nor: 'Takk for maten',
        eng: 'Thanks for the food',
        pl: 'Dziękuję za jedzenie',
        ar: 'شكرًا على الطعام',
        ger: 'Danke für das Essen',
        lt: 'Ačiū už maistą',
        ua: 'Дякую за їжу',
        sp: 'Gracias por la comida',
        key: '29',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fextakkformaten.mp3?alt=media&token=d5e36f4a-b7e2-4939-afde-b1c816947a7c',
        wordId: 29
    },
    {
        nor: 'Skål!',
        eng: 'Cheers!',
        pl: 'Na zdrowie!',
        ar: 'في صحتك!',
        ger: 'Prost!',
        lt: 'Į sveikatą!',
        ua: 'Будьмо!',
        sp: '¡Salud!',
        key: '30',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexskaal.mp3?alt=media&token=19d4aa95-f90d-4684-9c91-9ea49dff3460',
        wordId: 30
    },
    {
        nor: 'Gratulerer med dagen!',
        eng: 'Happy birthday!',
        pl: 'Wszystkiego najlepszego!',
        ar: 'عيد ميلاد سعيد!',
        ger: 'Alles Gute zum Geburtstag!',
        lt: 'Sveikinu su gimtadieniu!',
        ua: 'З днем народження!',
        sp: '¡Feliz cumpleaños!',
        key: '31',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgratulerer.mp3?alt=media&token=fbac4d0f-687c-44f7-80dd-aa98caa75821',
        wordId: 31
    },
    {
        nor: 'God jul!',
        eng: 'Merry Christmas!',
        pl: 'Wesołych Świąt!',
        ar: 'عيد ميلاد مجيد!',
        ger: 'Frohe Weihnachten!',
        lt: 'Linksmų Kalėdų!',
        ua: 'Веселих Різдвяних свят!',
        sp: '¡Feliz Navidad!',
        key: '32',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgodjul.mp3?alt=media&token=4cee46b9-ece4-4c56-8bf9-2428332ac88f',
        wordId: 32
    },
    {
        nor: 'Godt nyttår!',
        eng: 'Happy New Year!',
        pl: 'Szczęśliwego Nowego Roku!',
        ar: 'كل عام وأنتم بخير!',
        ger: 'Frohes neues Jahr!',
        lt: 'Laimingų Naujųjų Metų!',
        ua: 'З Новим роком!',
        sp: '¡Feliz Año Nuevo!',
        key: '33',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexgodtnyttaar.mp3?alt=media&token=736e8131-b329-47b4-a106-aaa731b8e39c',
        wordId: 33
    },
    {
        nor: 'Hvordan sier man det på norsk?',
        eng: 'How do you say that in Norwegian?',
        pl: 'Jak to się mówi po norwesku?',
        ar: 'كيف تقول ذلك بالنرويجية؟',
        ger: 'Wie sagt man das auf Norwegisch?',
        lt: 'Kaip tai pasakyti norvegiškai?',
        ua: 'Як це кажуть норвезькою?',
        sp: '¿Cómo se dice eso en noruego?',
        key: '34',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvordansierman.mp3?alt=media&token=4b428fa7-1167-4faf-b3ad-4767e3889a3b',
        wordId: 34
    },
    {
        nor: 'Hva betyr ...?',
        eng: 'What does ... mean?',
        pl: 'Co oznacza ...?',
        ar: 'ماذا يعني ...؟',
        ger: 'Was bedeutet ...?',
        lt: 'Ką reiškia ...?',
        ua: 'Що означає ...?',
        sp: '¿Qué significa ...?',
        key: '35',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvabetyr.mp3?alt=media&token=ca4e76f0-9d9b-4ef2-9670-fd37524df531',
        wordId: 35
    },
    {
        nor: 'Hvor kommer du fra?',
        eng: 'Where are you from?',
        pl: 'Skąd jesteś?',
        ar: 'من أين أنت؟',
        ger: 'Woher kommst du?',
        lt: 'Iš kur tu?',
        ua: 'Звідки ви?',
        sp: '¿De dónde eres?',
        key: '36',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorkommerdufra.mp3?alt=media&token=5b91ae72-021a-4602-9b13-6177cd61939a',
        wordId: 36
    },
    {
        nor: 'Jeg kommer fra ...',
        eng: 'I come from ...',
        pl: 'Pochodzę z ...',
        ar: 'أنا من ...',
        ger: 'Ich komme aus ...',
        lt: 'Aš esu iš ...',
        ua: 'Я з ...',
        sp: 'Vengo de ...',
        key: '37',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegkommerfra.mp3?alt=media&token=6f1353b9-b3e8-4cbb-98f9-3eede79dd60e',
        wordId: 37
    },
    {
        nor: 'Jeg bor i ...',
        eng: 'I live in ...',
        pl: 'Mieszkam w ...',
        ar: 'أعيش في ...',
        ger: 'Ich wohne in ...',
        lt: 'Aš gyvenu ...',
        ua: 'Я живу в ...',
        sp: 'Vivo en ...',
        key: '38',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegbori.mp3?alt=media&token=ff57de21-5cc4-4c16-8694-02923cb36c9d',
        wordId: 38
    },
    {
        nor: 'Jeg liker ...',
        eng: 'I like ...',
        pl: 'Lubię ...',
        ar: 'أنا أحب ...',
        ger: 'Ich mag ...',
        lt: 'Man patinka ...',
        ua: 'Мені подобається ...',
        sp: 'Me gusta ...',
        key: '39',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegliker.mp3?alt=media&token=9d5718bd-163d-4fef-a9ed-8d96ebd7fe75',
        wordId: 39
    },
    {
        nor: 'Jeg elsker deg',
        eng: 'I love you',
        pl: 'Kocham cię',
        ar: 'أنا أحبك',
        ger: 'Ich liebe dich',
        lt: 'Aš tave myliu',
        ua: 'Я тебе кохаю',
        sp: 'Te amo',
        key: '40',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegelskerdeg.mp3?alt=media&token=81e906d7-e05a-418b-995a-f6daf2fb6bae',
        wordId: 40
    },
    {
        nor: 'Når går toget?',
        eng: 'When does the train leave?',
        pl: 'Kiedy odjeżdża pociąg?',
        ar: 'متى يغادر القطار؟',
        ger: 'Wann fährt der Zug ab?',
        lt: 'Kada išvyksta traukinys?',
        ua: 'Коли відходить поїзд?',
        sp: '¿Cuándo sale el tren?',
        key: '41',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexnaargaartoget.mp3?alt=media&token=af414833-13dc-4808-b6de-0b80ee8afb37',
        wordId: 41
    },
    {
        nor: 'Hvor langt er det?',
        eng: 'How far is it?',
        pl: 'Jak to jest daleko?',
        ar: 'كم هو البعد؟',
        ger: 'Wie weit ist es?',
        lt: 'Kiek tai toli?',
        ua: 'Як це далеко?',
        sp: '¿Qué tan lejos está?',
        key: '42',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorlangerdet.mp3?alt=media&token=384ad0fb-1930-4d86-b2e9-b53f6d884e4a',
        wordId: 42
    },
    {
        nor: 'Hvordan kommer jeg dit?',
        eng: 'How do I get there?',
        pl: 'Jak tam dojdę?',
        ar: 'كيف أصل إلى هناك؟',
        ger: 'Wie komme ich dorthin?',
        lt: 'Kaip ten nuvykti?',
        ua: 'Як я можу туди дістатися?',
        sp: '¿Cómo llego allí?',
        key: '43',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvordankommer.mp3?alt=media&token=326784a3-805d-4675-85f0-bf7d05de3a64',
        wordId: 43
    },
    {
        nor: 'Er det ledig her?',
        eng: 'Is it available here?',
        pl: 'Czy to jest dostępne tutaj?',
        ar: 'هل هو متاح هنا؟',
        ger: 'Ist es hier verfügbar?',
        lt: 'Ar čia yra laisvų vietų?',
        ua: 'Це доступно тут?',
        sp: '¿Está disponible aquí?',
        key: '44',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexerdetledig.mp3?alt=media&token=2c53a62d-4066-40e2-8d2f-3a6fcea835af',
        wordId: 44
    },
    {
        nor: 'Hvor mye tid tar det?',
        eng: 'How much time does it take?',
        pl: 'Ile to zajmuje czasu?',
        ar: 'كم من الوقت يستغرق؟',
        ger: 'Wie lange dauert das?',
        lt: 'Kiek tai užtrunka?',
        ua: 'Скільки часу це займає?',
        sp: '¿Cuánto tiempo lleva?',
        key: '45',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvormyetidtar.mp3?alt=media&token=ab6e8a1f-4828-4994-a30b-c70a28392ecb',
        wordId: 45
    },
    {
        nor: 'Hvor ofte går bussen?',
        eng: 'How often does the bus run?',
        pl: 'Jak często jeździ autobus?',
        ar: 'كم مرة يمر الحافلة؟',
        ger: 'Wie oft fährt der Bus?',
        lt: 'Kaip dažnai važiuoja autobusas?',
        ua: 'Як часто їздить автобус?',
        sp: '¿Con qué frecuencia pasa el autobús?',
        key: '46',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorofte.mp3?alt=media&token=beb219b3-7396-4030-b86b-82a27b60b983',
        wordId: 46
    },
    {
        nor: 'Hvordan er været?',
        eng: 'How is the weather?',
        pl: 'Jaka jest pogoda?',
        ar: 'كيف الطقس؟',
        ger: 'Wie ist das Wetter?',
        lt: 'Koks oras?',
        ua: 'Яка погода?',
        sp: '¿Cómo está el clima?',
        key: '47',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvordanerveere.mp3?alt=media&token=1ea7efd4-1c19-47cb-a1e0-ec73f93d7663',
        wordId: 47
    },
    {
        nor: 'Hva skal vi gjøre i dag?',
        eng: 'What are we doing today?',
        pl: 'Co robimy dzisiaj?',
        ar: 'ماذا سنفعل اليوم؟',
        ger: 'Was machen wir heute?',
        lt: 'Ką darysime šiandien?',
        ua: 'Що ми будемо робити сьогодні?',
        sp: '¿Qué hacemos hoy?',
        key: '48',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvaskalvigjoore.mp3?alt=media&token=b031e284-05a4-4edb-908f-3c630912b4b9',
        wordId: 48
    },
    {
        nor: 'Hvor er toalettet?',
        eng: 'Where is the toilet?',
        pl: 'Gdzie jest toaleta?',
        ar: 'أين الحمام؟',
        ger: 'Wo ist die Toilette?',
        lt: 'Kur yra tualetas?',
        ua: 'Де туалет?',
        sp: '¿Dónde está el baño?',
        key: '49',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorertoalettet.mp3?alt=media&token=a82c93ba-6e51-45ae-8231-0939ae24b6d6',
        wordId: 49
    },
    {
        nor: 'Hva studerer du?',
        eng: 'What do you study?',
        pl: 'Co studiujesz?',
        ar: 'ماذا تدرس؟',
        ger: 'Was studierst du?',
        lt: 'Ką tu studijuoji?',
        ua: 'Що ви вчите?',
        sp: '¿Qué estudias?',
        key: '50',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvastudererdu.mp3?alt=media&token=b3a956ba-99ab-4180-befe-3ab10a783ce0',
        wordId: 50
    },
    {
        nor: 'Hva jobber du med?',
        eng: 'What do you do for a living?',
        pl: 'Czym się zajmujesz?',
        ar: 'ما هو عملك؟',
        ger: 'Was machst du beruflich?',
        lt: 'Kuo tu užsiimi?',
        ua: 'Де ви працюєте?',
        sp: '¿A qué te dedicas?',
        key: '51',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvajobberdu.mp3?alt=media&token=56a68f87-07d2-4546-a5ce-34022fd0d60b',
        wordId: 51
    },
    {
        nor: 'Hvor lenge har du bodd her?',
        eng: 'How long have you lived here?',
        pl: 'Jak długo tu mieszkasz?',
        ar: 'منذ متى عشت هنا؟',
        ger: 'Wie lange wohnst du schon hier?',
        lt: 'Kiek laiko čia gyveni?',
        ua: 'Як довго ви тут живете?',
        sp: '¿Cuánto tiempo llevas viviendo aquí?',
        key: '52',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorlengebodd.mp3?alt=media&token=16062955-39a0-42e2-9875-6c344e558a3f',
        wordId: 52
    },
    {
        nor: 'Jeg vil gjerne bestille ...',
        eng: 'I would like to order ...',
        pl: 'Chciałbym zamówić ...',
        ar: 'أود طلب ...',
        ger: 'Ich möchte bestellen ...',
        lt: 'Norėčiau užsisakyti ...',
        ua: 'Я б хотів замовити ...',
        sp: 'Me gustaría pedir ...',
        key: '53',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexjegvilgjernebestile.mp3?alt=media&token=552b8ca6-5d19-4c3a-b082-c91d96110322',
        wordId: 53
    },
    {
        nor: 'Hvordan smaker maten?',
        eng: 'How does the food taste?',
        pl: 'Jak smakuje jedzenie?',
        ar: 'كيف طعم الطعام؟',
        ger: 'Wie schmeckt das Essen?',
        lt: 'Kaip skonis maistas?',
        ua: 'Як смакує їжа?',
        sp: '¿Cómo sabe la comida?',
        key: '54',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvordansmakermaten.mp3?alt=media&token=43baa15e-52a7-4c93-a02c-0ccdc8f4797c',
        wordId: 54
    },
    {
        nor: 'Hva er din favoritt ...?',
        eng: 'What is your favorite ...?',
        pl: 'Jakie jest twoje ulubione ...?',
        ar: 'ما هو المفضل لديك ...؟',
        ger: 'Was ist dein Lieblings ...?',
        lt: 'Koks tavo mėgstamiausias ...?',
        ua: 'Який твій улюблений ...?',
        sp: '¿Cuál es tu favorito ...?',
        key: '55',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvaerdinfavoritt.mp3?alt=media&token=6365347f-a0a5-437b-88c4-32183d283eee',
        wordId: 55
    },
    {
        nor: 'Hva anbefaler du?',
        eng: 'What do you recommend?',
        pl: 'Co polecasz?',
        ar: 'ماذا توصي به؟',
        ger: 'Was empfehlen Sie?',
        lt: 'Ką rekomenduojate?',
        ua: 'Що ви рекомендуєте?',
        sp: '¿Qué recomiendas?',
        key: '56',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvaanbefalerdu.mp3?alt=media&token=934938a0-c6f5-44fc-8f76-924556c28108',
        wordId: 56
    },
    {
        nor: 'Hvordan kommer jeg til ...?',
        eng: 'How do I get to ...?',
        pl: 'Jak dotrzeć do ...?',
        ar: 'كيف أصل إلى ...؟',
        ger: 'Wie komme ich zu ...?',
        lt: 'Kaip nuvykti į ...?',
        ua: 'Як я можу дістатися до ...?',
        sp: '¿Cómo llego a ...?',
        key: '57',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvordankommerjegtil.mp3?alt=media&token=98f73a86-f4d7-49b9-93b4-70442e14a0a5',
        wordId: 57
    },
    {
        nor: 'Hva er telefonnummeret ditt?',
        eng: 'What is your phone number?',
        pl: 'Jaki jest twój numer telefonu?',
        ar: 'ما رقم هاتفك؟',
        ger: 'Was ist deine Telefonnummer?',
        lt: 'Koks tavo telefonas?',
        ua: 'Який у вас номер телефону?',
        sp: '¿Cuál es tu número de teléfono?',
        key: '58',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvaertelefon.mp3?alt=media&token=ddb6fa2c-658d-47a1-852b-3013d8563eff',
        wordId: 58
    },
    {
        nor: 'Hvor ligger nærmeste ...?',
        eng: 'Where is the nearest ...?',
        pl: 'Gdzie jest najbliższy ...?',
        ar: 'أين هو الأقرب ...؟',
        ger: 'Wo ist der nächste ...?',
        lt: 'Kur yra artimiausias ...?',
        ua: 'Де найближчий ...?',
        sp: '¿Dónde está el más cercano ...?',
        key: '59',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhvorliggerneermeste.mp3?alt=media&token=40693e9d-541c-4b2f-9509-b1dfddb9be04',
        wordId: 59
    },
    {
        nor: 'Ha en fin dag!',
        eng: 'Have a nice day!',
        pl: 'Miłego dnia!',
        ar: 'أتمنى لك يوماً طيباً!',
        ger: 'Schönen Tag noch!',
        lt: 'Geros dienos!',
        ua: 'Гарного дня!',
        sp: '¡Que tengas un buen día!',
        key: '60',
        norexp: true,
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fexhaenfindag.mp3?alt=media&token=f0622cf6-d58b-4162-9fbe-a6e1e2e8a654',
        wordId: 60
    }
];