[
    {
      nor: 'å burde',
      eng: 'should',
      pl: 'powinien',
      ar: 'يجب',
      ger: 'sollte',
      lt: 'turėtų',
      ua: 'повинен',
      sp: 'deber',
      norEgz: 'bør, burde, har burdet',
      key: '0',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firboor.mp3?alt=media&token=74862211-1898-479a-b938-3e383d52e407',
      wordId: 0
    },
    {
      nor: 'å ha',
      eng: 'have',
      pl: 'mieć',
      ar: 'لدي',
      ger: 'haben',
      lt: 'turėti',
      ua: 'мати',
      sp: 'tener',
      norEgz: 'har, hadde, har hatt',
      key: '1',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firhar.mp3?alt=media&token=562c6c5a-5781-4f49-a99a-d1d2abd1e4ab',
      wordId: 1
    },
    {
      nor: 'å kunne',
      eng: 'can',
      pl: 'móc',
      ar: 'يمكن',
      ger: 'können',
      lt: 'gali',
      ua: 'могти',
      sp: 'poder',
      norEgz: 'kan, kunne, har kunnet',
      key: '2',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkan.mp3?alt=media&token=3f159107-d490-4bdc-8f31-1ef172ba0cf9',
      wordId: 2
    },
    {
      nor: 'å måtte',
      eng: 'must',
      pl: 'musieć',
      ar: 'يجب',
      ger: 'müssen',
      lt: 'privalėti',
      ua: 'мусити',
      sp: 'deber',
      norEgz: 'må, måtte, har måttet',
      key: '3',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firmaa.mp3?alt=media&token=0a79f197-c53c-4f41-91eb-09100f7ec677',
      wordId: 3
    },
    {
      nor: 'å skulle',
      eng: 'shall',
      pl: 'powinien',
      ar: 'سوف',
      ger: 'sollte',
      lt: 'turėtų',
      ua: 'повинен',
      sp: 'deber',
      norEgz: 'skal, skulle, har skullet',
      key: '4',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskal.mp3?alt=media&token=b7501814-13bf-4837-a2ba-7e18d968ac44',
      wordId: 4
    },
    {
      nor: 'å ville',
      eng: 'want',
      pl: 'chcieć',
      ar: 'يريد',
      ger: 'wollen',
      lt: 'nori',
      ua: 'хотіти',
      sp: 'querer',
      norEgz: 'vil, ville, har villet',
      key: '5',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firvil.mp3?alt=media&token=c53eff48-8e91-40c6-ac74-a52785d8743c',
      wordId: 5
    },
    {
      nor: 'å være',
      eng: 'be',
      pl: 'być',
      ar: 'كان',
      ger: 'sein',
      lt: 'būti',
      ua: 'бути',
      sp: 'ser',
      norEgz: 'er, var, har vært',
      key: '6',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firer.mp3?alt=media&token=26a3359b-ee20-4012-aa21-6066ffc633c0',
      wordId: 6
    },
    {
      nor: 'å arbeide',
      eng: 'work',
      pl: 'pracować',
      ar: 'عمل',
      ger: 'arbeiten',
      lt: 'dirbti',
      ua: 'працювати',
      sp: 'trabajar',
      norEgz: 'arbeider, arbeidet, har arbeidet',
      key: '7',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firarbeider.mp3?alt=media&token=526495a8-1f93-4780-80d1-bdb8090327a0',
      wordId: 7
    },
    {
      nor: 'å bade',
      eng: 'bathe',
      pl: 'kąpać się',
      ar: 'الاستحمام',
      ger: 'baden',
      lt: 'maudytis',
      ua: 'купатися',
      sp: 'bañarse',
      norEgz: 'bader, badet, har badet',
      key: '8',
      irr: true,
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbader.mp3?alt=media&token=9b378b55-137d-4f0a-ae46-1ecb481d4e3b',
      wordId: 8
    },
    {
    nor: 'å be',
    eng: 'ask',
    pl: 'prosić',
    ar: 'طلب',
    ger: 'bitten',
    lt: 'prašyti',
    ua: 'просити',
    sp: 'pedir',
    norEgz: 'ber, bad, har bedt',
    key: '9',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firber.mp3?alt=media&token=72518676-39ae-491b-9b2b-47caee74e819',
    wordId: 9
    },
    {
    nor: 'å bedra',
    eng: 'deceive',
    pl: 'oszukiwać',
    ar: 'خدع',
    ger: 'betrügen',
    lt: 'apgaudinėti',
    ua: 'обманювати',
    sp: 'engañar',
    norEgz: 'bedrar, bedro, har bedratt',
    key: '10',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbedrar.mp3?alt=media&token=d61b1ca8-39dc-4e5a-ae62-78f98c9c1599',
    wordId: 10
    },
    {
    nor: 'å begynne',
    eng: 'begin',
    pl: 'zaczynać',
    ar: 'يبدأ',
    ger: 'beginnen',
    lt: 'pradėti',
    ua: 'починати',
    sp: 'comenzar',
    norEgz: 'begynner, begynte, har begynt',
    key: '11',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbegynner.mp3?alt=media&token=71d305d6-9632-49a1-a6e1-7b6bba21bab3',
    wordId: 11
    },
    {
    nor: 'å beskrive',
    eng: 'describe',
    pl: 'opisywać',
    ar: 'وصف',
    ger: 'beschreiben',
    lt: 'aprašyti',
    ua: 'описувати',
    sp: 'describir',
    norEgz: 'beskriver, beskrev, har beskrevet',
    key: '12',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbeskriver.mp3?alt=media&token=e7be01d6-38b0-4a20-a9ac-ce3ebed847d0',
    wordId: 12
    },
    {
    nor: 'å bestemme',
    eng: 'decide',
    pl: 'decydować',
    ar: 'قرر',
    ger: 'entscheiden',
    lt: 'nuspręsti',
    ua: 'вирішити',
    sp: 'decidir',
    norEgz: 'bestemmer, bestemte, har bestemt',
    key: '13',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbestemmer.mp3?alt=media&token=a2409e77-bebf-4b1e-99fd-b91cd2b6f0aa',
    wordId: 13
    },
    {
    nor: 'å bestille',
    eng: 'order',
    pl: 'zamawiać',
    ar: 'طلب',
    ger: 'bestellen',
    lt: 'užsakyti',
    ua: 'замовляти',
    sp: 'ordenar',
    norEgz: 'bestiller, bestilte, har bestilt',
    key: '14',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbestiller.mp3?alt=media&token=a679121f-834f-46c7-ae18-2b14778d255a',
    wordId: 14
    },
    {
    nor: 'å bety',
    eng: 'mean',
    pl: 'znaczyć',
    ar: 'يعني',
    ger: 'bedeuten',
    lt: 'reikšti',
    ua: 'значити',
    sp: 'significar',
    norEgz: 'betyr, betydde, har betydd',
    key: '15',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbetyr.mp3?alt=media&token=ec44e8a4-7e6c-4324-98b3-d1c567ce124d',
    wordId: 15
    },
    {
    nor: 'å binde',
    eng: 'tie',
    pl: 'wiązać',
    ar: 'ربط',
    ger: 'binden',
    lt: 'rišti',
    ua: 'зв’язувати',
    sp: 'atar',
    norEgz: 'binder, bandt, har bundet',
    key: '16',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbinder.mp3?alt=media&token=4994652b-71df-4b6c-9315-07cc7dc92637',
    wordId: 16
    },
    {
    nor: 'å bite',
    eng: 'bite',
    pl: 'gryźć',
    ar: 'عض',
    ger: 'beißen',
    lt: 'kąsti',
    ua: 'гризти',
    sp: 'morder',
    norEgz: 'biter, beit, har bitt',
    key: '17',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbiter.mp3?alt=media&token=304ffe61-a55a-45a1-bb39-c646140a2888',
    wordId: 17
    },
    {
    nor: 'å bli',
    eng: 'become',
    pl: 'stać się',
    ar: 'تصبح',
    ger: 'werden',
    lt: 'tapti',
    ua: 'ставати',
    sp: 'convertirse',
    norEgz: 'blir, ble, har blitt',
    key: '18',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firblir.mp3?alt=media&token=15b8e909-9c9d-4385-a2a9-1c99930a3b4c',
    wordId: 18
    },
    {
    nor: 'å bo',
    eng: 'live',
    pl: 'mieszkać',
    ar: 'عاش',
    ger: 'wohnen',
    lt: 'gyventi',
    ua: 'жити',
    sp: 'vivir',
    norEgz: 'bor, bodde, har bodd',
    key: '19',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbor.mp3?alt=media&token=f481903e-226d-4b30-a0b3-9086061466a6',
    wordId: 19
    },
    {
    nor: 'å brekke',
    eng: 'break',
    pl: 'łamać',
    ar: 'كسر',
    ger: 'brechen',
    lt: 'laužti',
    ua: 'ламати',
    sp: 'romper',
    norEgz: 'brekker, brakk, har brukket',
    key: '20',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbrekker.mp3?alt=media&token=6773f7d0-ef6e-4bd6-924a-264ac934e75b',
    wordId: 20
    },
    {
    nor: 'å brenne',
    eng: 'burn',
    pl: 'palić',
    ar: 'احترق',
    ger: 'brennen',
    lt: 'degti',
    ua: 'горіти',
    sp: 'quemar',
    norEgz: 'brenner, brant, har brent',
    key: '21',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbrenner.mp3?alt=media&token=dc14e8d9-8a1a-42af-bc54-98bfde684c01',
    wordId: 21
    },
    {
    nor: 'å bryte',
    eng: 'break',
    pl: 'łamać',
    ar: 'كسر',
    ger: 'brechen',
    lt: 'laužti',
    ua: 'ламати',
    sp: 'romper',
    norEgz: 'bryter, brøt, har brutt',
    key: '22',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbryter.mp3?alt=media&token=e26fb802-aaf7-4db3-924b-a217950c51de',
    wordId: 22
    },
    {
    nor: 'å by',
    eng: 'offer',
    pl: 'oferować',
    ar: 'عرض',
    ger: 'anbieten',
    lt: 'pasiūlyti',
    ua: 'пропонувати',
    sp: 'ofrecer',
    norEgz: 'byr, bød, har budt',
    key: '23',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbyr.mp3?alt=media&token=4e99780b-b98c-42a8-a341-094c17196f89',
    wordId: 23
    },
    {
    nor: 'å bære',
    eng: 'carry',
    pl: 'nosić',
    ar: 'حمل',
    ger: 'tragen',
    lt: 'nešti',
    ua: 'носити',
    sp: 'llevar',
    norEgz: 'bærer, bar, har båret',
    key: '24',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firbeerer.mp3?alt=media&token=72f6911b-5cf0-40a4-987d-020ef380e7f2',
    wordId: 24
    },
    {
    nor: 'å dette',
    eng: 'fall',
    pl: 'upaść',
    ar: 'سقط',
    ger: 'fallen',
    lt: 'kristi',
    ua: 'падати',
    sp: 'caer',
    norEgz: 'detter, datt, har dettet',
    key: '25',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firdetter.mp3?alt=media&token=566cbd94-4b2c-4446-b300-e396f057291a',
    wordId: 25
    },
    {
    nor: 'å dra',
    eng: 'go',
    pl: 'iść',
    ar: 'ذهب',
    ger: 'gehen',
    lt: 'eiti',
    ua: 'йти',
    sp: 'ir',
    norEgz: 'drar, dro, har dratt',
    key: '26',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firdrar.mp3?alt=media&token=6884ca95-e54f-46ed-ad32-bedf1ffedbeb',
    wordId: 26
    },
    {
    nor: 'å drikke',
    eng: 'drink',
    pl: 'pić',
    ar: 'شرب',
    ger: 'trinken',
    lt: 'gerti',
    ua: 'пити',
    sp: 'beber',
    norEgz: 'drikker, drakk, har drukket',
    key: '27',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firdrikker.mp3?alt=media&token=27680619-b48c-463a-b3ab-b86cad4eff88',
    wordId: 27
    },
    {
    nor: 'å drive',
    eng: 'drive',
    pl: 'prowadzić',
    ar: 'قاد',
    ger: 'treiben',
    lt: 'vesti',
    ua: 'проводити',
    sp: 'conducir',
    norEgz: 'driver, dreiv, har drevet',
    key: '28',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firdriver.mp3?alt=media&token=39532687-f9d0-42c1-9bda-f75df32528fd',
    wordId: 28
    },
    {
    nor: 'å drømme',
    eng: 'dream',
    pl: 'marzyć',
    ar: 'حلم',
    ger: 'träumen',
    lt: 'svajoti',
    ua: 'мріяти',
    sp: 'soñar',
    norEgz: 'drømmer, drømte, har drømt',
    key: '29',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firdroommer.mp3?alt=media&token=0419cec6-9739-4139-b748-1e05e4ac1b0c',
    wordId: 29
    },
    {
    nor: 'å falle',
    eng: 'fall',
    pl: 'upadać',
    ar: 'وقع',
    ger: 'fallen',
    lt: 'kristi',
    ua: 'падати',
    sp: 'caer',
    norEgz: 'faller, falt, har falt',
    key: '30',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfaller.mp3?alt=media&token=e10496a0-83cd-4e5f-a7f7-6a331bf08eba',
    wordId: 30
    },
    {
    nor: 'å finne',
    eng: 'find',
    pl: 'znaleźć',
    ar: 'وجد',
    ger: 'finden',
    lt: 'rasti',
    ua: 'знайти',
    sp: 'encontrar',
    norEgz: 'finner, fant, har funnet',
    key: '31',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfinner.mp3?alt=media&token=01e5d824-9360-4eac-ab79-7cb2aa984a25',
    wordId: 31
    },
    {
    nor: 'å finnes',
    eng: 'exist',
    pl: 'istnieć',
    ar: 'وجد',
    ger: 'existieren',
    lt: 'egzistuoti',
    ua: 'існувати',
    sp: 'existir',
    norEgz: 'finnes, fantes, har funnes',
    key: '32',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfinnes.mp3?alt=media&token=e8bb13e8-8953-40d4-9c3d-f9fcef69624a',
    wordId: 32
    },
    {
    nor: 'å fly',
    eng: 'fly',
    pl: 'lecieć',
    ar: 'طار',
    ger: 'fliegen',
    lt: 'skristi',
    ua: 'летіти',
    sp: 'volar',
    norEgz: 'flyr, fløy, har fløyet',
    key: '33',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firflyr.mp3?alt=media&token=2dde5cfd-5a6b-4b0a-8468-d827b6d9990f',
    wordId: 33
    },
    {
    nor: 'å flyte',
    eng: 'float',
    pl: 'płynąć',
    ar: 'طفو',
    ger: 'schwimmen',
    lt: 'plaukti',
    ua: 'плавати',
    sp: 'flotar',
    norEgz: 'flyter, fløt, har flytt',
    key: '34',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firflyter.mp3?alt=media&token=64e57783-7a1f-4fd1-9f56-ae7dace76013',
    wordId: 34
    },
    {
    nor: 'å forby',
    eng: 'prohibit',
    pl: 'zakazywać',
    ar: 'منع',
    ger: 'verbieten',
    lt: 'drausti',
    ua: 'забороняти',
    sp: 'prohibir',
    norEgz: 'forbyr, forbød, har forbudt',
    key: '35',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforbyr.mp3?alt=media&token=7aa55107-50a9-4805-b8d3-90072fc5f60f',
    wordId: 35
    },
    {
    nor: 'å foreslå',
    eng: 'suggest',
    pl: 'proponować',
    ar: 'اقترح',
    ger: 'vorschlagen',
    lt: 'pasiūlyti',
    ua: 'пропонувати',
    sp: 'sugerir',
    norEgz: 'foreslår, foreslo, har foreslått',
    key: '36',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforeslaar.mp3?alt=media&token=338e4dab-f19a-4cb2-a01e-b7b5b314b888',
    wordId: 36
    },
    {
    nor: 'å foretrekke',
    eng: 'prefer',
    pl: 'preferować',
    ar: 'يفضل',
    ger: 'bevorzugen',
    lt: 'teikti pirmenybę',
    ua: 'надавати перевагу',
    sp: 'preferir',
    norEgz: 'foretrekker, foretrakk, har foretrukket',
    key: '37',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforetrekker.mp3?alt=media&token=4ca01475-bb86-44ff-9715-95a8bcc69ee5',
    wordId: 37
    },
    {
    nor: 'å forlate',
    eng: 'leave',
    pl: 'opuszczać',
    ar: 'ترك',
    ger: 'verlassen',
    lt: 'palikti',
    ua: 'залишати',
    sp: 'abandonar',
    norEgz: 'forlater, forlot, har forlatt',
    key: '38',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforlater.mp3?alt=media&token=0b6aaab8-9a7c-4b44-9cd7-86dabca8a8fb',
    wordId: 38
    },
    {
    nor: 'å forstå',
    eng: 'understand',
    pl: 'rozumieć',
    ar: 'فهم',
    ger: 'verstehen',
    lt: 'suprasti',
    ua: 'розуміти',
    sp: 'entender',
    norEgz: 'forstår, forsto, har forstått',
    key: '39',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforstaar.mp3?alt=media&token=2a9d4b2c-0508-4286-86b8-e6074f73bd72',
    wordId: 39
    },
    {
    nor: 'å forsvinne',
    eng: 'disappear',
    pl: 'znikać',
    ar: 'اختفى',
    ger: 'verschwinden',
    lt: 'dingti',
    ua: 'зникати',
    sp: 'desaparecer',
    norEgz: 'forsvinner, forsvant, har forsvunnet',
    key: '40',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforsvinner.mp3?alt=media&token=92cfdadd-50ea-4b03-bc54-947f57598c3e',
    wordId: 40
    },
    {
    nor: 'å fortelle',
    eng: 'tell',
    pl: 'opowiadać',
    ar: 'قال',
    ger: 'erzählen',
    lt: 'pasakoti',
    ua: 'розповідати',
    sp: 'contar',
    norEgz: 'forteller, fortalte, har fortalt',
    key: '41',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firforteller.mp3?alt=media&token=b00e5197-3b6a-49ea-b76a-53dbc3a54b65',
    wordId: 41
    },
    {
    nor: 'å fryse',
    eng: 'freeze',
    pl: 'zamrażać',
    ar: 'تجمد',
    ger: 'frieren',
    lt: 'šalti',
    ua: 'заморожувати',
    sp: 'congelar',
    norEgz: 'fryser, frøs, har frosset',
    key: '42',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfryser.mp3?alt=media&token=2f6840e0-6425-4018-a67d-20d329779209',
    wordId: 42
    },
    {
    nor: 'å fyke',
    eng: 'whiz',
    pl: 'śmigać',
    ar: 'تهب',
    ger: 'sausen',
    lt: 'švilpti',
    ua: 'летіти',
    sp: 'silbar',
    norEgz: 'fyker, føk, har føket',
    key: '43',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfyker.mp3?alt=media&token=f2485904-9d4b-4985-a49f-08e622d0c3b2',
    wordId: 43
    },
    {
    nor: 'å fylle',
    eng: 'fill',
    pl: 'napełniać',
    ar: 'يملأ',
    ger: 'füllen',
    lt: 'užpildyti',
    ua: 'заповнювати',
    sp: 'llenar',
    norEgz: 'fyller, fylte, har fylt',
    key: '44',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfyller.mp3?alt=media&token=bc862896-e984-48bf-8d91-2a63f47b7eda',
    wordId: 44
    },
    {
    nor: 'å få',
    eng: 'get',
    pl: 'dostać',
    ar: 'حصل على',
    ger: 'bekommen',
    lt: 'gauti',
    ua: 'отримувати',
    sp: 'obtener',
    norEgz: 'får, fikk, har fått',
    key: '45',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firfaar.mp3?alt=media&token=68a30deb-ba67-474a-9011-c70a53dbc8ae',
    wordId: 45
    },
    {
    nor: 'å gi',
    eng: 'give',
    pl: 'dać',
    ar: 'أعطى',
    ger: 'geben',
    lt: 'duoti',
    ua: 'давати',
    sp: 'dar',
    norEgz: 'gir, ga, har gitt',
    key: '46',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgir.mp3?alt=media&token=9bc768bb-7540-4fe3-a0cd-367add13128c',
    wordId: 46
    },
    {
    nor: 'å gidde',
    eng: 'bother',
    pl: 'chcieć',
    ar: 'يزعج',
    ger: 'sich bemühen',
    lt: 'vaivuotis',
    ua: 'турбуватися',
    sp: 'molestar',
    norEgz: 'gidder, gadd, har giddet',
    key: '47',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgidder.mp3?alt=media&token=5b582536-5c8c-4278-b8e3-fd01e7591b12',
    wordId: 47
    },
    {
    nor: 'å gjelde',
    eng: 'apply',
    pl: 'dotyczyć',
    ar: 'تنطبق',
    ger: 'gelten',
    lt: 'taikyti',
    ua: 'стосуватися',
    sp: 'aplicar',
    norEgz: 'gjelder, gjaldt, har gjeldt',
    key: '48',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgjelder.mp3?alt=media&token=9788fd8b-6e2e-4730-ae11-9dbe99c7ee1c',
    wordId: 48
    },
    {
    nor: 'å gjemme',
    eng: 'hide',
    pl: 'chować',
    ar: 'أخفى',
    ger: 'verstecken',
    lt: 'slėpti',
    ua: 'ховати',
    sp: 'esconder',
    norEgz: 'gjemmer, gjemte, har gjemt',
    key: '49',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgjemmer.mp3?alt=media&token=9db9e2e4-3f6e-4e12-b516-b9bfeb0131ba',
    wordId: 49
    },
    {
    nor: 'å gjøre',
    eng: 'do',
    pl: 'robić',
    ar: 'فعل',
    ger: 'tun',
    lt: 'daryti',
    ua: 'робити',
    sp: 'hacer',
    norEgz: 'gjør, gjorde, har gjort',
    key: '50',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgjoor.mp3?alt=media&token=ec7da98e-0f6c-4b4e-82ac-6aae8a841726',
    wordId: 50
    },
    {
    nor: 'å glede seg',
    eng: 'to look forward to',
    pl: 'cieszyć się',
    ar: 'تتطلع الى',
    ger: 'sich freuen',
    lt: 'džiaugtis',
    ua: 'радіти',
    sp: 'alegrarse',
    norEgz: 'gleder seg, gledet seg, har gledet seg',
    key: '51',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgleder.mp3?alt=media&token=0b371ca9-9953-49c4-b031-e4f645737966',
    wordId: 51
    },
    {
    nor: 'å glemme',
    eng: 'forget',
    pl: 'zapomnieć',
    ar: 'نسى',
    ger: 'vergessen',
    lt: 'pamiršti',
    ua: 'забути',
    sp: 'olvidar',
    norEgz: 'glemmer, glemte, har glemt',
    key: '52',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firglemmer.mp3?alt=media&token=6edf27b1-b00d-497c-853b-cdf8b207b14d',
    wordId: 52
    },
    {
    nor: 'å gli',
    eng: 'slide',
    pl: 'ślizgać się',
    ar: 'ينزلق',
    ger: 'gleiten',
    lt: 'slinkti',
    ua: 'ковзати',
    sp: 'deslizar',
    norEgz: 'glir, gled, har glidd',
    key: '53',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firglir.mp3?alt=media&token=b7e5d458-7bf7-4855-b59f-febff55b7d46',
    wordId: 53
    },
    {
    nor: 'å glippe',
    eng: 'slip',
    pl: 'umknąć',
    ar: 'يفلت',
    ger: 'entgleiten',
    lt: 'praleisti',
    ua: 'ускользнуть',
    sp: 'escapar',
    norEgz: 'glipper, glapp, har glippet',
    key: '54',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firglipper.mp3?alt=media&token=a3ab0fb2-9418-4f4f-b7aa-02e0e65dcfa5',
    wordId: 54
    },
    {
    nor: 'å gni',
    eng: 'rub',
    pl: 'trzeć',
    ar: 'يفرك',
    ger: 'reiben',
    lt: 'trinti',
    ua: 'терти',
    sp: 'frotar',
    norEgz: 'gnir, gned, har gnidd',
    key: '55',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgnir.mp3?alt=media&token=b578af96-6401-4877-95d7-1de2c9fa4a9e',
    wordId: 55
    },
    {
    nor: 'å grine',
    eng: 'cry',
    pl: 'płakać',
    ar: 'بكى',
    ger: 'weinen',
    lt: 'verkti',
    ua: 'плакати',
    sp: 'llorar',
    norEgz: 'griner, grein, har grint',
    key: '56',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgriner.mp3?alt=media&token=81e376d6-52c7-4cd8-9dd7-63aaddb7f4a9',
    wordId: 56
    },
    {
    nor: 'å gripe',
    eng: 'grasp',
    pl: 'chwycić',
    ar: 'أمسك',
    ger: 'ergreifen',
    lt: 'pagauti',
    ua: 'хапати',
    sp: 'agarrar',
    norEgz: 'griper, greip, har grepet',
    key: '57',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgriper.mp3?alt=media&token=02740587-b297-458a-9a7e-9b33cdd6c33e',
    wordId: 57
    },
    {
    nor: 'å gråte',
    eng: 'cry',
    pl: 'płakać',
    ar: 'بكى',
    ger: 'weinen',
    lt: 'verkti',
    ua: 'плакати',
    sp: 'llorar',
    norEgz: 'gråter, gråt, har grått',
    key: '58',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgraater.mp3?alt=media&token=01049157-02c9-470a-befc-12b791a44994',
    wordId: 58
    },
    {
    nor: 'å gå',
    eng: 'to walk',
    pl: 'iść',
    ar: 'يمشي',
    ger: 'gehen',
    lt: 'eiti',
    ua: 'йти',
    sp: 'caminar',
    norEgz: 'går, gikk, har gått',
    key: '59',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firgaar.mp3?alt=media&token=e704ecc8-e208-45a9-b82f-413a3b8bdc2f',
    wordId: 59
    },
    {
    nor: 'å hende',
    eng: 'to happen',
    pl: 'wydarzyć się',
    ar: 'حدث',
    ger: 'geschehen',
    lt: 'atsitikti',
    ua: 'траплятися',
    sp: 'ocurrir',
    norEgz: 'hender, hendte, har hendt',
    key: '60',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firhender.mp3?alt=media&token=4943d7a1-1629-4d69-8b2c-6f00a0f15aae',
    wordId: 60
    },
    {
    nor: 'å henge',
    eng: 'to hang',
    pl: 'wisieć',
    ar: 'يعلق',
    ger: 'hängen',
    lt: 'kaboti',
    ua: 'вішати',
    sp: 'colgar',
    norEgz: 'henger, hengte, har hengt',
    key: '61',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firhenger.mp3?alt=media&token=04099aad-b307-4a3b-ac26-632bc92630a2',
    wordId: 61
    },
    {
    nor: 'å hete',
    eng: 'to be named',
    pl: 'nazywać się',
    ar: 'كان اسمه',
    ger: 'heißen',
    lt: 'vadintis',
    ua: 'називатися',
    sp: 'llamarse',
    norEgz: 'heter, het, har hett',
    key: '62',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firheter.mp3?alt=media&token=a8d80a16-09fa-4caf-8924-e78fd1c54d48',
    wordId: 62
    },
    {
    nor: 'å hilse',
    eng: 'to greet',
    pl: 'witać',
    ar: 'يرحب',
    ger: 'grüßen',
    lt: 'sveikinti',
    ua: 'вітати',
    sp: 'saludar',
    norEgz: 'hilser, hilste, har hilst',
    key: '63',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firhilser.mp3?alt=media&token=ec91113e-6a52-4c80-baaa-f54a240c6918',
    wordId: 63
    },
    {
    nor: 'å hjelpe',
    eng: 'to help',
    pl: 'pomóc',
    ar: 'يساعد',
    ger: 'helfen',
    lt: 'padėti',
    ua: 'допомагати',
    sp: 'ayudar',
    norEgz: 'hjelper, hjalp, har hjulpet',
    key: '64',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firhjelper.mp3?alt=media&token=656c92c6-093f-4252-8ae8-5558358f806f',
    wordId: 64
    },
    {
    nor: 'å holde',
    eng: 'to hold',
    pl: 'trzymać',
    ar: 'يحمل',
    ger: 'halten',
    lt: 'laikyti',
    ua: 'тримати',
    sp: 'sostener',
    norEgz: 'holder, holdt, har holdt',
    key: '65',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firholder.mp3?alt=media&token=bd944fee-2944-4569-9336-a394d5410469',
    wordId: 65
    },
    {
    nor: 'å håpe',
    eng: 'to hope',
    pl: 'mieć nadzieję',
    ar: 'أمل',
    ger: 'hoffen',
    lt: 'tikėtis',
    ua: 'сподіватися',
    sp: 'esperar',
    norEgz: 'håper, håpet, har håpet',
    key: '66',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firhaaper.mp3?alt=media&token=31c937e8-6215-4dbc-94e5-89950088f7b5',
    wordId: 66
    },
    {
    nor: 'å kjenne',
    eng: 'to know',
    pl: 'znać',
    ar: 'يعرف',
    ger: 'kennen',
    lt: 'žinoti',
    ua: 'знати',
    sp: 'conocer',
    norEgz: 'kjenner, kjente, har kjent',
    key: '67',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkjenner.mp3?alt=media&token=dab9687a-bcb2-4490-8120-60ce3f80aa67',
    wordId: 67
    },
    {
    nor: 'å kle',
    eng: 'to dress',
    pl: 'ubierać',
    ar: 'يلبس',
    ger: 'kleiden',
    lt: 'rengtis',
    ua: 'одягатися',
    sp: 'vestir',
    norEgz: 'kler, kledde, har kledd',
    key: '68',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkler.mp3?alt=media&token=9c3301e4-f066-4322-a137-02d06efaedd0',
    wordId: 68
    },
    {
    nor: 'å klippe',
    eng: 'to cut',
    pl: 'ciąć',
    ar: 'يقطع',
    ger: 'schneiden',
    lt: 'pjauti',
    ua: 'різати',
    sp: 'cortar',
    norEgz: 'klipper, klippet, har klipt',
    key: '69',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firklipper.mp3?alt=media&token=e900969b-d98e-48eb-ba92-15d3733b0b6f',
    wordId: 69
    },
    {
    nor: 'å klype',
    eng: 'to pinch',
    pl: 'szczypać',
    ar: 'يقرص',
    ger: 'kneifen',
    lt: 'žniurioti',
    ua: 'щипати',
    sp: 'pellizcar',
    norEgz: 'klyper, kløp, har kløpet',
    key: '70',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firklyper.mp3?alt=media&token=7bd71bca-e9a9-45de-8bc4-285b3b7c5e0c',
    wordId: 70
    },
    {
    nor: 'å knekke',
    eng: 'to crack',
    pl: 'pękać',
    ar: 'يكسر',
    ger: 'knacken',
    lt: 'trūktelėti',
    ua: 'тріскати',
    sp: 'romper',
    norEgz: 'knekker, knakk, har knekt',
    key: '71',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firknekker.mp3?alt=media&token=2125ee4a-bc72-46d9-81e1-dadc390150d7',
    wordId: 71
    },
    {
    nor: 'å knipe',
    eng: 'to pinch',
    pl: 'szczypać',
    ar: 'يقرص',
    ger: 'kneifen',
    lt: 'žniurioti',
    ua: 'щипати',
    sp: 'pellizcar',
    norEgz: 'kniper, kneip, har knepet',
    key: '72',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkniper.mp3?alt=media&token=a3a25b81-6ba9-4622-8677-a1ef681d3ac7',
    wordId: 72
    },
    {
    nor: 'å komme',
    eng: 'to come',
    pl: 'przychodzić',
    ar: 'يأتي',
    ger: 'kommen',
    lt: 'ateiti',
    ua: 'приходити',
    sp: 'venir',
    norEgz: 'kommer, kom, har kommet',
    key: '73',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkommer.mp3?alt=media&token=5354f628-7d9a-483f-9594-b0e9b163ec3d',
    wordId: 73
    },
    {
    nor: 'å kose seg',
    eng: 'to enjoy oneself',
    pl: 'bawić się',
    ar: 'يستمتع',
    ger: 'sich vergnügen',
    lt: 'smagiai leisti laiką',
    ua: 'гарно проводити час',
    sp: 'disfrutar',
    norEgz: 'koser seg, koste seg, har kost seg',
    key: '74',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkoser.mp3?alt=media&token=d5ea3e7d-a0b0-450b-a937-f6c4190a6613',
    wordId: 74
    },
    {
    nor: 'å krype',
    eng: 'to crawl',
    pl: 'pełzać',
    ar: 'يزحف',
    ger: 'kriechen',
    lt: 'roplioti',
    ua: 'повзти',
    sp: 'reptar',
    norEgz: 'kryper, krøp, har krøpet',
    key: '75',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firkryper.mp3?alt=media&token=e0e276fc-4148-48c3-a4ff-1d69d8d8d86c',
    wordId: 75
    },
    {
    nor: 'å la',
    eng: 'to let',
    pl: 'pozwolić',
    ar: 'يترك',
    ger: 'lassen',
    lt: 'leisti',
    ua: 'дозволити',
    sp: 'dejar',
    norEgz: 'lar, lot, har latt',
    key: '76',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firlar.mp3?alt=media&token=bd865fa1-cc8a-4e28-96ac-74520425bf09',
    wordId: 76
    },
    {
    nor: 'å lage',
    eng: 'to make',
    pl: 'robić',
    ar: 'يصنع',
    ger: 'machen',
    lt: 'daryti',
    ua: 'робити',
    sp: 'hacer',
    norEgz: 'lager, laget, har laget',
    key: '77',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firlager.mp3?alt=media&token=5af478ce-8b94-423f-9b6c-18694cc1d33b',
    wordId: 77
    },
    {
    nor: 'å late som',
    eng: 'to pretend',
    pl: 'udawać',
    ar: 'يتظاهر',
    ger: 'so tun als ob',
    lt: 'apsimesti',
    ua: 'удавати',
    sp: 'fingir',
    norEgz: 'later som, lot som, har latt som',
    key: '78',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firlater.mp3?alt=media&token=8551bd66-7552-42ac-9b39-37990407d185',
    wordId: 78
    },
    {
    nor: 'å le',
    eng: 'to laugh',
    pl: 'śmiać się',
    ar: 'يضحك',
    ger: 'lachen',
    lt: 'juoktis',
    ua: 'сміятися',
    sp: 'reír',
    norEgz: 'ler, lo, har ledd',
    key: '79',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firler.mp3?alt=media&token=fc649360-36f9-4c1b-9629-1682f257f2fb',
    wordId: 79
    },
    {
    nor: 'å legge',
    eng: 'to lay',
    pl: 'kłaść',
    ar: 'وضع',
    ger: 'legen',
    lt: 'tiesti',
    ua: 'класти',
    sp: 'poner',
    norEgz: 'legger, la, har lagt',
    key: '80',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firlegger.mp3?alt=media&token=a8cdc86a-f6f1-430b-a0e0-eed1cd28eaf4',
    wordId: 80
    },
    {
    nor: 'å lete',
    eng: 'to search',
    pl: 'szukać',
    ar: 'يبحث',
    ger: 'suchen',
    lt: 'ieškoti',
    ua: 'шукати',
    sp: 'buscar',
    norEgz: 'leter, lette, har lett',
    key: '81',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firleter.mp3?alt=media&token=aab1b421-5dab-4870-bc26-a33c65a2e975',
    wordId: 81
    },
    {
    nor: 'å lide',
    eng: 'to suffer',
    pl: 'cierpieć',
    ar: 'يعاني',
    ger: 'leiden',
    lt: 'kenčia',
    ua: 'страждати',
    sp: 'sufrir',
    norEgz: 'lider, led, har lidd',
    key: '82',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firlider.mp3?alt=media&token=52785d20-00ca-421b-a503-8a1e100dcf87',
    wordId: 82
    },
    {
    nor: 'å ligge',
    eng: 'to lie (position)',
    pl: 'leżeć',
    ar: 'يكمن',
    ger: 'liegen',
    lt: 'gulėti',
    ua: 'лежати',
    sp: 'yacer',
    norEgz: 'ligger, lå, har ligget',
    key: '83',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firligger.mp3?alt=media&token=3ae1eb1e-478b-46ee-8d96-10048d156f96',
    wordId: 83
    },
    {
    nor: 'å lyve',
    eng: 'to lie (untruth)',
    pl: 'kłamać',
    ar: 'يكذب',
    ger: 'lügen',
    lt: 'meluoti',
    ua: 'брехати',
    sp: 'mentir',
    norEgz: 'lyver, løy, har løyet',
    key: '84',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firlyver.mp3?alt=media&token=dc036476-a62a-4536-8c7c-60abfadbad72',
    wordId: 84
    },
    {
    nor: 'å møte',
    eng: 'to meet',
    pl: 'spotykać',
    ar: 'يلتقي',
    ger: 'treffen',
    lt: 'susitikti',
    ua: 'зустрічати',
    sp: 'encontrar',
    norEgz: 'møter, møtte, har møtt',
    key: '85',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firmooter.mp3?alt=media&token=5a6319d1-38d9-41d1-aff9-921f00ab6880',
    wordId: 85
    },
    {
    nor: 'å nyse',
    eng: 'to sneeze',
    pl: 'kichnąć',
    ar: 'يعطس',
    ger: 'niesen',
    lt: 'čiaudėti',
    ua: 'чхати',
    sp: 'estornudar',
    norEgz: 'nyser, nøs, har nøset',
    key: '86',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firnyser.mp3?alt=media&token=92ccabba-22b1-4912-8c7b-cbfa3edc07d3',
    wordId: 86
    },
    {
    nor: 'å nyte',
    eng: 'to enjoy',
    pl: 'cieszyć się',
    ar: 'يستمتع',
    ger: 'genießen',
    lt: 'mėgautis',
    ua: 'насолоджуватися',
    sp: 'disfrutar',
    norEgz: 'nyter, nøt, har nytt',
    key: '87',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firnyter.mp3?alt=media&token=b0721cfc-d91c-446b-82f8-6b3ff1093065',
    wordId: 87
    },
    {
    nor: 'å overdrive',
    eng: 'to exaggerate',
    pl: 'przesadzać',
    ar: 'يبالغ',
    ger: 'übertreiben',
    lt: 'perdėti',
    ua: 'перебільшувати',
    sp: 'exagerar',
    norEgz: 'overdriver, overdreiv, har overdrevet',
    key: '88',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firoverdriver.mp3?alt=media&token=f1c460c8-0af5-475c-a250-056e17ec6e80',
    wordId: 88
    },
    {
    nor: 'å passe',
    eng: 'to fit, to take care of',
    pl: 'pasować, opiekować się',
    ar: 'يناسب، يعتني',
    ger: 'passen, aufpassen',
    lt: 'tikti, rūpintis',
    ua: 'підходити, доглядати',
    sp: 'quedar, cuidar',
    norEgz: 'passer, passet, har passet',
    key: '89',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firpasser.mp3?alt=media&token=4848e534-8e16-475a-b2fb-dc62b9894792',
    wordId: 89
    },
    {
    nor: 'å pipe',
    eng: 'to whistle',
    pl: 'gwizdać',
    ar: 'يصفر',
    ger: 'pfeifen',
    lt: 'švilpti',
    ua: 'свистіти',
    sp: 'silbar',
    norEgz: 'piper, peip, har pepet',
    key: '90',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firpiper.mp3?alt=media&token=90da6f7b-2ffa-46d0-872d-182cbd9f1ac4',
    wordId: 90
    },
    {
    nor: 'å pleie',
    eng: 'to tend, to care for',
    pl: 'pielęgnować',
    ar: 'يرعى',
    ger: 'pflegen',
    lt: 'slaugyti',
    ua: 'доглядати',
    sp: 'cuidar',
    norEgz: 'pleier, pleide, har pleid',
    key: '91',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firpleier.mp3?alt=media&token=cac62143-a967-4a41-ab04-302c377eed88',
    wordId: 91
    },
    {
    nor: 'å rekke',
    eng: 'to reach',
    pl: 'zdążyć',
    ar: 'وصل',
    ger: 'erreichen',
    lt: 'pasiekti',
    ua: 'досягти',
    sp: 'alcanzar',
    norEgz: 'rekker, rakk, har rukket',
    key: '92',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firrekker.mp3?alt=media&token=9d42e562-ccbe-427a-bd4b-59efe07fcfb7',
    wordId: 92
    },
    {
    nor: 'å renne',
    eng: 'to run (liquid)',
    pl: 'ciec',
    ar: 'تدفق',
    ger: 'laufen (Flüssigkeit)',
    lt: 'tekėti',
    ua: 'течія',
    sp: 'correr (líquido)',
    norEgz: 'renner, rant, har runnet',
    key: '93',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firrenner.mp3?alt=media&token=d6521495-e5c8-4a05-b926-d4fc269babae',
    wordId: 93
    },
    {
    nor: 'å ri',
    eng: 'to ride',
    pl: 'jeździć',
    ar: 'ركوب',
    ger: 'reiten',
    lt: 'jojimas',
    ua: 'їздити верхи',
    sp: 'montar',
    norEgz: 'rir, reid, har ridd',
    key: '94',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firrir.mp3?alt=media&token=105d6988-3e43-4c09-b05b-8aacec7920e7',
    wordId: 94
    },
    {
    nor: 'å rive',
    eng: 'to tear',
    pl: 'drzeć',
    ar: 'يمزق',
    ger: 'reißen',
    lt: 'plėšti',
    ua: 'рвати',
    sp: 'rasgar',
    norEgz: 'river, reiv, har revet',
    key: '95',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firriver.mp3?alt=media&token=10afea8c-3ffa-4942-a416-72d3d8f2e311',
    wordId: 95
    },
    {
    nor: 'å rope',
    eng: 'to shout',
    pl: 'krzyczeć',
    ar: 'يصرخ',
    ger: 'rufen',
    lt: 'šaukti',
    ua: 'кричати',
    sp: 'gritar',
    norEgz: 'roper, ropte, har ropt',
    key: '96',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firroper.mp3?alt=media&token=6a9678bf-5518-4da2-baba-fd3636032463',
    wordId: 96
    },
    {
    nor: 'å ryke',
    eng: 'to smoke',
    pl: 'palić',
    ar: 'يدخن',
    ger: 'rauchen',
    lt: 'rūkyti',
    ua: 'курити',
    sp: 'fumar',
    norEgz: 'ryker, røk, har røket',
    key: '97',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firryker.mp3?alt=media&token=7056ed2c-1c74-44bd-a5a3-97fd4dead672',
    wordId: 97
    },
    {
    nor: 'å se',
    eng: 'to see',
    pl: 'widzieć',
    ar: 'يرى',
    ger: 'sehen',
    lt: 'matyti',
    ua: 'бачити',
    sp: 'ver',
    norEgz: 'ser, så, har sett',
    key: '98',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firser.mp3?alt=media&token=92a39f96-6cc4-4bd3-a80a-67795337abca',
    wordId: 98
    },
    {
    nor: 'å selge',
    eng: 'to sell',
    pl: 'sprzedawać',
    ar: 'يبيع',
    ger: 'verkaufen',
    lt: 'parduoti',
    ua: 'продавати',
    sp: 'vender',
    norEgz: 'selger, solgte, har solgt',
    key: '99',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firselger.mp3?alt=media&token=bd9a15ba-01bd-490d-9a22-d6a48740c5d3',
    wordId: 99
    },
    {
    nor: 'å sende',
    eng: 'to send',
    pl: 'wysyłać',
    ar: 'يرسل',
    ger: 'senden',
    lt: 'siųsti',
    ua: 'надсилати',
    sp: 'enviar',
    norEgz: 'sender, sendte, har sendt',
    key: '100',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsender.mp3?alt=media&token=b86155c2-31e4-4b1d-86a7-a1c086d1c54f',
    wordId: 100
    },
    {
    nor: 'å sette',
    eng: 'to put, set',
    pl: 'stawiać, kłaść',
    ar: 'وضع',
    ger: 'setzen, stellen',
    lt: 'dėti, nustatyti',
    ua: 'ставити, кладити',
    sp: 'poner, establecer',
    norEgz: 'setter, satte, har satt',
    key: '101',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsetter.mp3?alt=media&token=aa0a4b5b-259f-4c8e-bd32-c46bab627400',
    wordId: 101
    },
    {
    nor: 'å si',
    eng: 'to say',
    pl: 'mówić',
    ar: 'يقول',
    ger: 'sagen',
    lt: 'sakyti',
    ua: 'казати',
    sp: 'decir',
    norEgz: 'sier, sa, har sagt',
    key: '102',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsier.mp3?alt=media&token=be3921bb-acfa-4ea2-83df-8c9f878a87f7',
    wordId: 102
    },
    {
    nor: 'å sitte',
    eng: 'to sit',
    pl: 'siedzieć',
    ar: 'يجلس',
    ger: 'sitzen',
    lt: 'sėdėti',
    ua: 'сидіти',
    sp: 'sentarse',
    norEgz: 'sitter, satt, har sittet',
    key: '103',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsitter.mp3?alt=media&token=e6ebddb7-ab6c-44ab-a895-180cf86b1a8f',
    wordId: 103
    },
    {
    nor: 'å skinne',
    eng: 'to shine',
    pl: 'świecić',
    ar: 'يشرق',
    ger: 'scheinen',
    lt: 'šviesti',
    ua: 'світити',
    sp: 'brillar',
    norEgz: 'skinner, skinte, har skint',
    key: '104',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskinner.mp3?alt=media&token=6d45dc50-f57b-48ee-b1ed-fe81d20310ee',
    wordId: 104
    },
    {
    nor: 'å skjelve',
    eng: 'to tremble, shake',
    pl: 'drżeć',
    ar: 'يرتجف',
    ger: 'zittern, beben',
    lt: 'drebulys, purtyti',
    ua: 'тремтіти',
    sp: 'temblar',
    norEgz: 'skjelver, skalv, har skjelvet',
    key: '105',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskjelver.mp3?alt=media&token=2101f3fd-ed70-43c0-9cfc-3fe307d1c4d4',
    wordId: 105
    },
    {
    nor: 'å skjære',
    eng: 'to cut',
    pl: 'ciąć',
    ar: 'يقطع',
    ger: 'schneiden',
    lt: 'pjauti',
    ua: 'різати',
    sp: 'cortar',
    norEgz: 'skjærer, skar, har skåret',
    key: '106',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskjeerer.mp3?alt=media&token=e7e65163-215d-43a0-9b88-9bd401a42bf2',
    wordId: 106
    },
    {
    nor: 'å skjønne',
    eng: 'to understand',
    pl: 'rozumieć',
    ar: 'فهم',
    ger: 'verstehen',
    lt: 'suprasti',
    ua: 'розуміти',
    sp: 'entender',
    norEgz: 'skjønner, skjønte, har skjønt',
    key: '107',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskjoonner.mp3?alt=media&token=1df32061-0bd5-4640-a3d9-22471e6e5b28',
    wordId: 107
    },
    {
    nor: 'å skrike',
    eng: 'to scream',
    pl: 'krzyczeć',
    ar: 'صرخ',
    ger: 'schreien',
    lt: 'šaukti',
    ua: 'кричати',
    sp: 'gritar',
    norEgz: 'skriker, skreik, har skreket',
    key: '108',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskriker.mp3?alt=media&token=a2618572-876c-44f7-be62-364b3246dbf7',
    wordId: 108
    },
    {
    nor: 'å skrive',
    eng: 'to write',
    pl: 'pisać',
    ar: 'كتب',
    ger: 'schreiben',
    lt: 'rašyti',
    ua: 'писати',
    sp: 'escribir',
    norEgz: 'skriver, skrev, har skrevet',
    key: '109',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskriver.mp3?alt=media&token=0a65f8b2-16a3-4237-9809-2fd64439fbd4',
    wordId: 109
    },
    {
    nor: 'å skryte',
    eng: 'to boast',
    pl: 'chwalić się',
    ar: 'تفاخر',
    ger: 'prahlen',
    lt: 'girtis',
    ua: 'хвастатися',
    sp: 'presumir',
    norEgz: 'skryter, skrøt, har skrytt',
    key: '110',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskryter.mp3?alt=media&token=2604932e-b4d9-4944-a4f2-dde981238f51',
    wordId: 110
    },
    {
    nor: 'å skyldes',
    eng: 'to be due to',
    pl: 'być spowodowanym przez',
    ar: 'يرجع إلى',
    ger: 'zurückzuführen sein auf',
    lt: 'būti dėl',
    ua: 'завдяки',
    sp: 'ser debido a',
    norEgz: 'skyldes, skyldtes, har skyldtes',
    key: '111',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskyldes.mp3?alt=media&token=a4929c65-3c1f-48e7-98c5-491047c0a5d6',
    wordId: 111
    },
    {
    nor: 'å skylle',
    eng: 'to rinse',
    pl: 'płukać',
    ar: 'شطف',
    ger: 'spülen',
    lt: 'plauti',
    ua: 'промивати',
    sp: 'enjuagar',
    norEgz: 'skyller, skylte, har skylt',
    key: '112',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskyller.mp3?alt=media&token=f787c219-04d2-48a8-95cc-17bc5389f3b2',
    wordId: 112
    },
    {
    nor: 'å skynde',
    eng: 'to hurry',
    pl: 'śpieszyć się',
    ar: 'عجل',
    ger: 'eilen',
    lt: 'skubėti',
    ua: 'поспішати',
    sp: 'apresurarse',
    norEgz: 'skynder, skyndte, har skyndt',
    key: '113',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskynder.mp3?alt=media&token=3abd3ced-2100-435c-93dc-3a91953db358',
    wordId: 113
    },
    {
    nor: 'å skyte',
    eng: 'to shoot',
    pl: 'strzelać',
    ar: 'أطلق النار',
    ger: 'schießen',
    lt: 'šauti',
    ua: 'стріляти',
    sp: 'disparar',
    norEgz: 'skyter, skjøt, har skutt',
    key: '114',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskyter.mp3?alt=media&token=5024ae22-5f36-478e-969f-3d5711d74c7b',
    wordId: 114
    },
    {
    nor: 'å skyve',
    eng: 'to push',
    pl: 'pchać',
    ar: 'دفع',
    ger: 'schieben',
    lt: 'stumti',
    ua: 'штовхати',
    sp: 'empujar',
    norEgz: 'skyver, skjøv, har skjøvet',
    key: '115',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firskyver.mp3?alt=media&token=54469bf0-79bc-4d55-ac0c-834c1d7b390e',
    wordId: 115
    },
    {
    nor: 'å slippe',
    eng: 'to release',
    pl: 'puszczać',
    ar: 'أطلق',
    ger: 'loslassen',
    lt: 'paleisti',
    ua: 'відпускати',
    sp: 'soltar',
    norEgz: 'slipper, slapp, har sluppet',
    key: '116',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firslipper.mp3?alt=media&token=654ba6e3-39a1-4b35-b56e-5ee1f12de33f',
    wordId: 116
    },
    {
    nor: 'å slite',
    eng: 'to wear out',
    pl: 'zużywać się',
    ar: 'استهلك',
    ger: 'verschleißen',
    lt: 'susidėvėti',
    ua: 'зношуватися',
    sp: 'desgastarse',
    norEgz: 'sliter, sleit, har slitt',
    key: '117',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsliter.mp3?alt=media&token=0b0e8991-9e49-4800-bd3c-d1dfa4abfcb6',
    wordId: 117
    },
    {
    nor: 'å slå',
    eng: 'to hit',
    pl: 'uderzyć',
    ar: 'ضرب',
    ger: 'schlagen',
    lt: 'mušti',
    ua: 'ударити',
    sp: 'golpear',
    norEgz: 'slår, slo, har slått',
    key: '118',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firslaar.mp3?alt=media&token=205d012f-5067-4bec-96b8-6d5ffcd2363a',
    wordId: 118
    },
    {
    nor: 'å slåss',
    eng: 'to fight',
    pl: 'walczyć',
    ar: 'قاتل',
    ger: 'kämpfen',
    lt: 'kautis',
    ua: 'битися',
    sp: 'pelear',
    norEgz: 'slåss, sloss, har slåss',
    key: '119',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firslaass.mp3?alt=media&token=3895bc6a-6253-4078-9e45-fea809388dfc',
    wordId: 119
    },
    {
    nor: 'å smelle',
    eng: 'to bang',
    pl: 'huknąć',
    ar: 'انفجر',
    ger: 'knallen',
    lt: 'skambėti',
    ua: 'гупати',
    sp: 'chasquear',
    norEgz: 'smeller, smalt, har smelt',
    key: '120',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsmeller.mp3?alt=media&token=dea2822c-698a-4963-adc8-6c5c19f9b78a',
    wordId: 120
    },
    {
    nor: 'å snike',
    eng: 'to sneak',
    pl: 'skradać się',
    ar: 'تسلل',
    ger: 'schleichen',
    lt: 'šliuoti',
    ua: 'крастися',
    sp: 'deslizarse',
    norEgz: 'sniker, snek, har sneket',
    key: '121',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsniker.mp3?alt=media&token=ad317de2-4042-49d7-9d1a-2a8e7d1faf74',
    wordId: 121
    },
    {
    nor: 'å sove',
    eng: 'to sleep',
    pl: 'spać',
    ar: 'نام',
    ger: 'schlafen',
    lt: 'miegoti',
    ua: 'спати',
    sp: 'dormir',
    norEgz: 'sover, sov, har sovet',
    key: '122',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsover.mp3?alt=media&token=106fbcb0-aabf-41df-8e34-2d31f289363c',
    wordId: 122
    },
    {
    nor: 'å spille',
    eng: 'to play',
    pl: 'grać',
    ar: 'لعب',
    ger: 'spielen',
    lt: 'žaisti',
    ua: 'грати',
    sp: 'jugar',
    norEgz: 'spiller, spilte, har spilt',
    key: '123',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firspiller.mp3?alt=media&token=179679cb-7cf6-486b-bdb9-6ac9a8a46c0f',
    wordId: 123
    },
    {
    nor: 'å spinne',
    eng: 'to spin',
    pl: 'przędź',
    ar: 'دوران',
    ger: 'spinnen',
    lt: 'verpti',
    ua: 'прядіння',
    sp: 'girar',
    norEgz: 'spinner, spant, har spunnet',
    key: '124',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firspinner.mp3?alt=media&token=e3cc49e6-87d9-476d-bfc7-4a48a8b41a15',
    wordId: 124
    },
    {
    nor: 'å sprekke',
    eng: 'to burst',
    pl: 'pękać',
    ar: 'انفجار',
    ger: 'platzen',
    lt: 'sprogti',
    ua: 'розриватися',
    sp: 'reventar',
    norEgz: 'sprekker, sprakk, har sprukket',
    key: '125',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsprekker.mp3?alt=media&token=7190d905-ec20-4308-a52b-d1a3910b774e',
    wordId: 125
    },
    {
    nor: 'å sprette',
    eng: 'to bounce',
    pl: 'odbijać się',
    ar: 'ارتداد',
    ger: 'hüpfen',
    lt: 'šoktelėti',
    ua: 'підскакувати',
    sp: 'rebotar',
    norEgz: 'spretter, spratt, har sprettet',
    key: '126',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firspretter.mp3?alt=media&token=5c4c2cf8-9703-46e0-9ddb-64ac9abc7fa4',
    wordId: 126
    },
    {
    nor: 'å springe',
    eng: 'to run',
    pl: 'biegać',
    ar: 'ركض',
    ger: 'laufen',
    lt: 'bėgti',
    ua: 'бігти',
    sp: 'correr',
    norEgz: 'springer, sprang, har sprunget',
    key: '127',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firspringer.mp3?alt=media&token=f41d9c7d-cccb-4c35-b145-f32744847ae7',
    wordId: 127
    },
    {
    nor: 'å spørre',
    eng: 'to ask',
    pl: 'pytać',
    ar: 'سأل',
    ger: 'fragen',
    lt: 'klausti',
    ua: 'питати',
    sp: 'preguntar',
    norEgz: 'spør, spurte, har spurt',
    key: '128',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firspoor.mp3?alt=media&token=48bd042e-4d92-43f5-affe-8777f1823fbe',
    wordId: 128
    },
    {
    nor: 'å stave',
    eng: 'to spell',
    pl: 'literować',
    ar: 'تهجئة',
    ger: 'buchstabieren',
    lt: 'rašyti',
    ua: 'грамотно писати',
    sp: 'deletrear',
    norEgz: 'staver, stavet, har stavet',
    key: '129',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstaver.mp3?alt=media&token=8b7ebdf7-536c-4c08-b5c3-4bba9077ad05',
    wordId: 129
    },
    {
    nor: 'å stelle',
    eng: 'to care',
    pl: 'opiekować się',
    ar: 'رعاية',
    ger: 'pflegen',
    lt: 'rūpintis',
    ua: 'доглядати',
    sp: 'cuidar',
    norEgz: 'steller, stelte, har stelt',
    key: '130',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsteller.mp3?alt=media&token=1327d48a-aa55-4f40-a23b-8a86512b37d0',
    wordId: 130
    },
    {
    nor: 'å stemme',
    eng: 'to vote',
    pl: 'głosować',
    ar: 'تصويت',
    ger: 'abstimmen',
    lt: 'balsuoti',
    ua: 'голосувати',
    sp: 'votar',
    norEgz: 'stemmer, stemte, har stemt',
    key: '131',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstemmer.mp3?alt=media&token=37eb36a0-9780-4d04-aafe-4df2bfe0cae5',
    wordId: 131
    },
    {
    nor: 'å stenge',
    eng: 'to close',
    pl: 'zamykać',
    ar: 'أغلق',
    ger: 'schließen',
    lt: 'uždaryti',
    ua: 'закривати',
    sp: 'cerrar',
    norEgz: 'stenger, stengte, har stengt',
    key: '132',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstenger.mp3?alt=media&token=38934191-d950-4f8c-8b2e-d13561862169',
    wordId: 132
    },
    {
    nor: 'å stige',
    eng: 'to rise',
    pl: 'rosnąć',
    ar: 'ارتفع',
    ger: 'steigen',
    lt: 'kilti',
    ua: 'підніматися',
    sp: 'ascender',
    norEgz: 'stiger, steig, har steget',
    key: '133',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstiger.mp3?alt=media&token=3c3f9e3c-43a5-451a-8b0c-c71a2cb49a66',
    wordId: 133
    },
    {
    nor: 'å stikke',
    eng: 'to stick',
    pl: 'kłuć',
    ar: 'طعن',
    ger: 'stechen',
    lt: 'durti',
    ua: 'колоти',
    sp: 'pinchar',
    norEgz: 'stikker, stakk, har stukket',
    key: '134',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstikker.mp3?alt=media&token=66242d31-41f5-4f0e-9bb3-4d0ca1cbf4d5',
    wordId: 134
    },
    {
    nor: 'å stille',
    eng: 'to set',
    pl: 'ustawiać',
    ar: 'ضبط',
    ger: 'einstellen',
    lt: 'nustatyti',
    ua: 'встановлювати',
    sp: 'ajustar',
    norEgz: 'stiller, stilte, har stilt',
    key: '135',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstiller.mp3?alt=media&token=c7a394e5-aa6a-49d5-b2bf-ea58eee17198',
    wordId: 135
    },
    {
    nor: 'å stjele',
    eng: 'to steal',
    pl: 'kraść',
    ar: 'سرق',
    ger: 'stehlen',
    lt: 'vogti',
    ua: 'красти',
    sp: 'robar',
    norEgz: 'stjeler, stjal, har stjålet',
    key: '136',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstjeler.mp3?alt=media&token=3d72be52-d2f3-4562-9291-abf0f8b5ae0c',
    wordId: 136
    },
    {
    nor: 'å strekke',
    eng: 'to stretch',
    pl: 'rozciągać się',
    ar: 'تمتد',
    ger: 'strecken',
    lt: 'tempti',
    ua: 'розтягувати',
    sp: 'estirar',
    norEgz: 'strekker, strakk, har strukket',
    key: '137',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstrekker.mp3?alt=media&token=9ec498e2-c98e-44fb-aa55-aa53010f8e76',
    wordId: 137
    },
    {
    nor: 'å stryke',
    eng: 'to iron',
    pl: 'prasować',
    ar: 'كوى',
    ger: 'bügeln',
    lt: 'lyginti',
    ua: 'прасувати',
    sp: 'planchar',
    norEgz: 'stryker, strøk, har strøket',
    key: '138',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstryker.mp3?alt=media&token=52b24e7f-e709-4d7f-94f3-a69181f18c14',
    wordId: 138
    },
    {
    nor: 'å stå',
    eng: 'to stand',
    pl: 'stać',
    ar: 'وقف',
    ger: 'stehen',
    lt: 'stovėti',
    ua: 'стояти',
    sp: 'estar de pie',
    norEgz: 'står, sto, har stått',
    key: '139',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firstaar.mp3?alt=media&token=6ff47f9c-1df3-4acd-9888-92cc06ab85b6',
    wordId: 139
    },
    {
    nor: 'å svike',
    eng: 'to betray',
    pl: 'zdradzić',
    ar: 'خان',
    ger: 'verraten',
    lt: 'išduoti',
    ua: 'зрадити',
    sp: 'traicionar',
    norEgz: 'sviker, sveik, har sveket',
    key: '140',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsviker.mp3?alt=media&token=5558b32a-3e78-48f9-a868-d3a776a79146',
    wordId: 140
    },
    {
    nor: 'å svømme',
    eng: 'to swim',
    pl: 'pływać',
    ar: 'سبح',
    ger: 'schwimmen',
    lt: 'plaukti',
    ua: 'плавати',
    sp: 'nadar',
    norEgz: 'svømmer, svømte, har svømt',
    key: '141',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsvoommer.mp3?alt=media&token=8e12d51c-8525-40a3-923c-19f5ef48240f',
    wordId: 141
    },
    {
    nor: 'å sy',
    eng: 'to sew',
    pl: 'szyć',
    ar: 'خيط',
    ger: 'nähen',
    lt: 'siūti',
    ua: 'шити',
    sp: 'coser',
    norEgz: 'syr, sydde, har sydd',
    key: '142',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsyr.mp3?alt=media&token=de88cff4-9a32-41ea-a8ab-27d72fe6f9fc',
    wordId: 142
    },
    {
    nor: 'å synes',
    eng: 'to think (opinion)',
    pl: 'myśleć',
    ar: 'اعتقد',
    ger: 'meinen',
    lt: 'manyti',
    ua: 'думати',
    sp: 'parecer',
    norEgz: 'synes, syntes, har syntes',
    key: '143',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsynes.mp3?alt=media&token=5edd4111-d450-469f-8ccd-5e874d064568',
    wordId: 143
    },
    {
    nor: 'å synge',
    eng: 'to sing',
    pl: 'śpiewać',
    ar: 'غنى',
    ger: 'singen',
    lt: 'dainuoti',
    ua: 'співати',
    sp: 'cantar',
    norEgz: 'synger, sang, har sunget',
    key: '144',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsynger.mp3?alt=media&token=f463ffb6-12f0-47e7-bf74-2bd4abbdba27',
    wordId: 144
    },
    {
    nor: 'å synke',
    eng: 'to sink',
    pl: 'tonąć',
    ar: 'غرق',
    ger: 'sinken',
    lt: 'skęsti',
    ua: 'тонути',
    sp: 'hundir',
    norEgz: 'synker, sank, har sunket',
    key: '145',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firsynker.mp3?alt=media&token=aadc4503-2739-4731-9fb0-30b706f6f13a',
    wordId: 145
    },
    {
    nor: 'å ta',
    eng: 'to take',
    pl: 'brać',
    ar: 'أخذ',
    ger: 'nehmen',
    lt: 'imti',
    ua: 'брати',
    sp: 'tomar',
    norEgz: 'tar, tok, har tatt',
    key: '146',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtar.mp3?alt=media&token=f725ea8f-46e0-43e8-8175-ccc2c3897db9',
    wordId: 146
    },
    {
    nor: 'å tenke',
    eng: 'to think',
    pl: 'myśleć',
    ar: 'فكر',
    ger: 'denken',
    lt: 'galvoti',
    ua: 'думати',
    sp: 'pensar',
    norEgz: 'tenker, tenkte, har tenkt',
    key: '147',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtenker.mp3?alt=media&token=bf1ca656-6c9f-43dc-b689-bdf5188b6c93',
    wordId: 147
    },
    {
    nor: 'å tilby',
    eng: 'to offer',
    pl: 'oferować',
    ar: 'عرض',
    ger: 'anbieten',
    lt: 'siūlyti',
    ua: 'пропонувати',
    sp: 'ofrecer',
    norEgz: 'tilbyr, tilbød, har tilbudt',
    key: '148',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtilbyr.mp3?alt=media&token=f6122d09-f70a-483a-9178-a93768b20965',
    wordId: 148
    },
    {
    nor: 'å tillate',
    eng: 'to allow',
    pl: 'pozwalać',
    ar: 'سمح',
    ger: 'erlauben',
    lt: 'leisti',
    ua: 'дозволяти',
    sp: 'permitir',
    norEgz: 'tillater, tillot, har tillatt',
    key: '149',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtillater.mp3?alt=media&token=128b6c45-d16b-48e8-a671-96e7a80b65fc',
    wordId: 149
    },
    {
    nor: 'å treffe',
    eng: 'to meet',
    pl: 'spotykać',
    ar: 'التقى',
    ger: 'treffen',
    lt: 'susitikti',
    ua: 'зустрічати',
    sp: 'encontrar',
    norEgz: 'treffer, traff, har truffet',
    key: '150',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtreffer.mp3?alt=media&token=d3811543-dd58-4502-899d-23174e1bdbbd',
    wordId: 150
    },
    {
    nor: 'å treffes',
    eng: 'to meet (reflexive)',
    pl: 'spotykać się',
    ar: 'التقى',
    ger: 'sich treffen',
    lt: 'susitikti',
    ua: 'зустрічатися',
    sp: 'encontrarse',
    norEgz: 'treffes, treftes, har treftes',
    key: '151',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtreffes.mp3?alt=media&token=8cf327f3-76d7-494d-9e82-91d8279229b7',
    wordId: 151
    },
    {
    nor: 'å trekke',
    eng: 'to pull',
    pl: 'ciągnąć',
    ar: 'سحب',
    ger: 'ziehen',
    lt: 'traukti',
    ua: 'тягти',
    sp: 'tirar',
    norEgz: 'trekker, trakk, har trukket',
    key: '152',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtrekker.mp3?alt=media&token=74bafcfd-26e8-4ecd-8c27-16284df50c63',
    wordId: 152
    },
    {
    nor: 'å trenge',
    eng: 'to need',
    pl: 'potrzebować',
    ar: 'احتاج',
    ger: 'brauchen',
    lt: 'reikėti',
    ua: 'потребувати',
    sp: 'necesitar',
    norEgz: 'trenger, trengte, har trengt',
    key: '153',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtrenger.mp3?alt=media&token=9c8b0924-8a8e-4f26-be62-ced66143f598',
    wordId: 153
    },
    {
    nor: 'å trives',
    eng: 'to thrive',
    pl: 'dobrze się czuć',
    ar: 'ازدهر',
    ger: 'sich wohlfühlen',
    lt: 'klestėti',
    ua: 'процвітати',
    sp: 'prosperar',
    norEgz: 'trives, trivdes, har trivdes',
    key: '154',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtrives.mp3?alt=media&token=94880e8b-e889-4f46-8bb3-e2a1c2eac7ae',
    wordId: 154
    },
    {
    nor: 'å tvinge',
    eng: 'to force',
    pl: 'zmuszać',
    ar: 'أجبر',
    ger: 'zwingen',
    lt: 'priversti',
    ua: 'примушувати',
    sp: 'forzar',
    norEgz: 'tvinger, tvang, har tvunget',
    key: '155',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtvinger.mp3?alt=media&token=0c57a80c-6150-49d9-bb85-b76396a63ef8',
    wordId: 155
    },
    {
    nor: 'å tørke',
    eng: 'to dry',
    pl: 'suszyć',
    ar: 'جفف',
    ger: 'trocknen',
    lt: 'džiovinti',
    ua: 'сушити',
    sp: 'secar',
    norEgz: 'tørker, tørket, har tørket',
    key: '156',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtoorker.mp3?alt=media&token=e01b1843-4381-4ae4-8320-ae158bc1ea29',
    wordId: 156
    },
    {
    nor: 'å tørre',
    eng: 'to dare',
    pl: 'odważyć się',
    ar: 'جرؤ',
    ger: 'wagen',
    lt: 'drįsti',
    ua: 'наважитися',
    sp: 'atreverse',
    norEgz: 'tør, turte, har turt',
    key: '157',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firtoor.mp3?alt=media&token=fcca3aa8-cb0e-4228-a208-ccea0e6f032c',
    wordId: 157
    },
    {
    nor: 'å unngå',
    eng: 'to avoid',
    pl: 'unikać',
    ar: 'تجنب',
    ger: 'vermeiden',
    lt: 'vengti',
    ua: 'уникати',
    sp: 'evitar',
    norEgz: 'unngår, unngikk, har unngått',
    key: '158',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firunngaar.mp3?alt=media&token=60368d3c-48c7-439e-a883-e1cad77ee21d',
    wordId: 158
    },
    {
    nor: 'å velge',
    eng: 'to choose',
    pl: 'wybierać',
    ar: 'اختار',
    ger: 'wählen',
    lt: 'rinktis',
    ua: 'вибирати',
    sp: 'elegir',
    norEgz: 'velger, valgte, har valgt',
    key: '159',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firvelger.mp3?alt=media&token=17ec27d2-1046-4f48-a2f3-f841824d99f6',
    wordId: 159
    },
    {
    nor: 'å vinne',
    eng: 'to win',
    pl: 'wygrywać',
    ar: 'فاز',
    ger: 'gewinnen',
    lt: 'laimėti',
    ua: 'вигравати',
    sp: 'ganar',
    norEgz: 'vinner, vant, har vunnet',
    key: '160',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firvinner.mp3?alt=media&token=38ef634b-59fc-460c-94ee-1703ed90db0b',
    wordId: 160
    },
    {
    nor: 'å vite',
    eng: 'to know',
    pl: 'wiedzieć',
    ar: 'عرف',
    ger: 'wissen',
    lt: 'žinoti',
    ua: 'знати',
    sp: 'saber',
    norEgz: 'vet, visste, har visst',
    key: '161',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firvet.mp3?alt=media&token=3366ca8f-d567-4099-81ef-5275872df273',
    wordId: 161
    },
    {
    nor: 'å vokse',
    eng: 'to grow',
    pl: 'rosnąć',
    ar: 'نمى',
    ger: 'wachsen',
    lt: 'augti',
    ua: 'рости',
    sp: 'crecer',
    norEgz: 'vokser, vokste, har vokst',
    key: '162',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firvokser.mp3?alt=media&token=e363ebed-a8a3-4074-bd03-fb4ea659babe',
    wordId: 162
    },
    {
    nor: 'å vri',
    eng: 'to twist',
    pl: 'kręcić',
    ar: 'لف',
    ger: 'verdrehen',
    lt: 'pasukti',
    ua: 'крутити',
    sp: 'retorcer',
    norEgz: 'vrir, vrei, har vridd',
    key: '163',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firvrir.mp3?alt=media&token=1a85d1c4-b01f-4aeb-834f-d651c858d37d',
    wordId: 163
    },
    {
    nor: 'å ødelegge',
    eng: 'to destroy',
    pl: 'zniszczyć',
    ar: 'دمر',
    ger: 'zerstören',
    lt: 'sunaikinti',
    ua: 'знищувати',
    sp: 'destruir',
    norEgz: 'ødelegger, ødela, har ødelagt',
    key: '164',
    irr: true,
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Firoodelegger.mp3?alt=media&token=6de1f999-c6e2-4e6e-b36c-4ca3bb8add34',
    wordId: 164
    }

  ]