export default dataObj = [
    {
    title: 'Personal pronouns',
    description: 'Personlige pronomen',
    level: 'A1',
    link: 'Class6x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Possessive pronouns',
    description: 'Possessiver',
    level: 'A1',
    link: 'Class6x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Demonstrative pronouns',
    description: 'Demonstrativer',
    level: 'A1',
    link: 'Class6x3x1',
    key: 3,
    showPro: false,
   },
    {
    title: 'Quantifiers',
    description: 'Kvantorer',
    level: 'A1',
    link: 'Class6x4x1',
    key: 4,
    showPro: false,
   },
   {
    title: 'Indefinite pronouns',
    description: 'Ubestemt pronomen',
    level: 'A1',
    link: 'Class6x5x1',
    key: 5,
    showPro: false,
   },
   {
    title: 'Reflexive pronouns',
    description: 'Refleksive pronomen',
    level: 'A1',
    link: 'Class6x6x1',
    key: 6,
    showPro: false,
   }
];