export default dataObj = [
    {
    title: 'Artikler',
    description: 'articles',
    level: 'A1',
    link: 'Class1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Bøyning av substantiv',
    description: 'here is some description 2',
    level: 'A1',
    link: 'Class1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Uregelmessig bøyning',
    description: 'here is some description 3',
    level: 'A1',
    link: '',
    key: 3,
    showPro: false,
   },
    {
    title: 'Bestemt eller ubestemt',
    description: 'here is some description 4',
    level: 'A1',
    link: '',
    key: 4,
    showPro: true,
   },
    {
    title: 'Substaniv som ikke telles',
    description: 'here is some description 5',
    level: 'A1',
    link: '',
    key: 5,
    showPro: true,
   },
   {
    title: 'Genitiv',
    description: 'here is some description',
    level: 'A1',
    link: '',
    key: 6,
    showPro: true,
   },
    {
    title: 'Substantivfraser',
    description: 'here is some description 2',
    level: 'A1',
    link: '',
    key: 7,
    showPro: true,
   },
    {
    title: 'Samskriving',
    description: 'here is some description 3',
    level: 'A1',
    link: '',
    key: 8,
    showPro: true,
   }
];