export default dataObj = [
    {
    title: 'Kongruens',
    description: 'present time - introduction',
    level: 'A1',
    link: 'Class1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Uregelmessig bøyning av adjektiv',
    description: 'here is some description 2',
    level: 'A1',
    link: 'Class1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Gradbøyning',
    description: 'here is some description 3',
    level: 'A1',
    link: '',
    key: 3,
    showPro: false,
   },
    {
    title: 'Uregelmessig gradbøyning',
    description: 'here is some description 4',
    level: 'A1',
    link: '',
    key: 4,
    showPro: true,
   },
    {
    title: 'Mer og mest, mindre og minst',
    description: 'here is some description 5',
    level: 'A1',
    link: '',
    key: 5,
    showPro: true,
   },
   {
    title: 'Perfektum partisipp',
    description: 'here is some description',
    level: 'A1',
    link: '',
    key: 6,
    showPro: true,
   },
    {
    title: 'Presens partisipp',
    description: 'here is some description 2',
    level: 'A1',
    link: '',
    key: 7,
    showPro: true,
   },
    {
    title: 'Adverb',
    description: 'here is some description 3',
    level: 'A1',
    link: '',
    key: 8,
    showPro: true,
   }
];