export default dataObj = [
    {
    title: 'Setning',
    description: 'sentence',
    level: 'A1',
    link: 'Class1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Spørsmål',
    description: 'questions',
    level: 'A1',
    link: 'Class1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Hovedsetning',
    description: 'main sentence',
    level: 'A1',
    link: '',
    key: 3,
    showPro: false,
   },
    {
    title: 'Leddsetning',
    description: 'joint sentence',
    level: 'A1',
    link: '',
    key: 4,
    showPro: true,
   },
    {
    title: 'Indirekte tale',
    description: 'indirect speech',
    level: 'A1',
    link: '',
    key: 5,
    showPro: true,
   },
   {
    title: 'Vilkårsetning',
    description: 'conditional statement',
    level: 'A1',
    link: '',
    key: 6,
    showPro: true,
   },
    {
    title: 'Subjekt',
    description: 'subject',
    level: 'A1',
    link: '',
    key: 7,
    showPro: true,
   },
    {
    title: 'Adverbial',
    description: 'adverbial',
    level: 'A1',
    link: '',
    key: 8,
    showPro: true,
   }
];