export default dataObj = [
    {
    title: 'Presens',
    description: 'present time - introduction',
    level: 'A1',
    link: 'Class1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Presens futurum',
    description: 'future time',
    level: 'A1',
    link: 'Class1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Preteritum',
    description: 'past time',
    level: 'A1',
    link: 'Class1x3x1',
    key: 3,
    showPro: false,
   },
    {
    title: 'Presens perfektum',
    description: 'past participle',
    level: 'A1',
    link: 'Class1x4x1',
    key: 4,
    showPro: true,
   },
    {
    title: 'Preteritum perfektum',
    description: 'past perfect',
    level: 'A1',
    link: 'Class1x5x1',
    key: 5,
    showPro: true,
   },
   {
    title: 'Andre konstruksjoner',
    description: 'other constructions',
    level: 'A1',
    link: 'Class1x6x1',
    key: 6,
    showPro: true,
   }
];