export default dataObj = [
    {
    title: 'Verbbøyning',
    description: 'verb inflection',
    level: 'A1',
    link: 'Class1x1x1',
    key: 1,
    showPro: false,
   },
    {
    title: 'Modalverb',
    description: 'modal verbs',
    level: 'A1',
    link: 'Class1x2x1',
    key: 2,
    showPro: false,
   },
    {
    title: 'Modalverb - preteritum',
    description: 'modal verbs - past time',
    level: 'A1',
    link: '',
    key: 3,
    showPro: false,
   },
    {
    title: 'Modalverb - perfektum',
    description: 'modal verbs - past participle',
    level: 'A1',
    link: '',
    key: 4,
    showPro: true,
   },
    {
    title: 'Imperativ',
    description: 'imperativ verbs',
    level: 'A1',
    link: '',
    key: 5,
    showPro: true,
   },
   {
    title: 'Passiv',
    description: 'passive voice',
    level: 'A1',
    link: '',
    key: 6,
    showPro: true,
   },
    {
    title: 'S-verb',
    description: 's-verb',
    level: 'A1',
    link: '',
    key: 7,
    showPro: true,
   },
    {
    title: 'Verbfraser',
    description: 'verb phrases',
    level: 'A1',
    link: '',
    key: 8,
    showPro: true,
   },
    {
    title: 'Verbal sammensetning',
    description: 'verbal composition',
    level: 'A1',
    link: '',
    key: 9,
    showPro: true,
   }
];

